/* ============================================================================
 * AccountsPayableExtraModals.tsx — modals ported from the original page 3.6.html.
 * ----------------------------------------------------------------------------
 * AUTO-GENERATED by port_missing_modals.py — regenerate rather than hand-edit.
 *
 * These dialogs exist in the legacy HTML and were reachable there via
 * onclick="openModal('…')", but were never carried into the React port, so the
 * buttons that target them did nothing. Markup, titles, sizes, tables and
 * footer actions are ported from the source.
 *
 * Legacy bridges applied:
 *   openModal('x')        -> onOpen('x')
 *   data-bs-dismiss       -> onClose
 *   processAction(...)    -> doAction(...)  (spinner -> receipt)
 * ========================================================================== */
import type { ReactNode } from "react";
import { useEffect, useRef, useState } from "react";
import styles from "../styles/accounts-payable.module.css";

const s = styles as Record<string, string>;
const cx = (...c: (string | false | undefined)[]) =>
	c.filter(Boolean).join(" ");

interface Props {
	active: string | null;
	onClose: () => void;
	onOpen: (id: string) => void;
}

interface Result {
	msg: string;
	ref?: string;
}

/* Modal shell — mirrors the shared kit used by the hand-written modals so
 * these dialogs look and behave identically. */
function MBox({
	id,
	active,
	title,
	size = "md",
	onClose,
	children,
	footer,
}: {
	id: string;
	active: string | null;
	title: ReactNode;
	size?: "md" | "lg" | "xl";
	onClose: () => void;
	children: ReactNode;
	footer?: ReactNode;
}) {
	if (active !== id) return null;
	return (
		<>
			<div className={s.backdrop} onClick={onClose} />
			<div className={s.modalWrap} role="dialog" aria-modal="true">
				<div
					className={cx(
						s.modalBox,
						size === "lg" && s.modalBoxLg,
						size === "xl" && s.modalBoxXl,
					)}
				>
					<div className={s.modalHeader}>
						<h5 className={s.modalTitle}>{title}</h5>
						<button
							type="button"
							className="btn-close"
							aria-label="Close"
							onClick={onClose}
						/>
					</div>
					<div className={s.modalBody}>{children}</div>
					{footer && <div className={s.modalFooter}>{footer}</div>}
				</div>
			</div>
		</>
	);
}

function Busy() {
	return (
		<div className={s.loadingOv}>
			<div className={s.spinner} />
			<p className={s.loadingLabel}>Processing...</p>
		</div>
	);
}

export default function AccountsPayableExtraModals({
	active,
	onClose,
	onOpen,
}: Props) {
	const [results, setResults] = useState<Record<string, Result>>({});
	const [busy, setBusy] = useState<string | null>(null);
	const [flows, setFlows] = useState<Record<string, number>>({});
	const timer = useRef<number | undefined>(undefined);

	/* LEGACY BRIDGE: cacheResettable() — clear state when the modal closes. */
	useEffect(() => {
		if (active === null) {
			setResults({});
			setBusy(null);
			setFlows({});
		}
	}, [active]);
	useEffect(() => () => window.clearTimeout(timer.current), []);

	/* LEGACY BRIDGE: processAction() — 1.2s spinner, then a receipt. */
	const doAction = (id: string, msg: string, ref?: string) => {
		setBusy(id);
		timer.current = window.setTimeout(() => {
			setResults((p) => ({ ...p, [id]: { msg, ref } }));
			setBusy(null);
		}, 1200);
	};

	const nextFlow = (key: string, total: number) => {
		const cur = flows[key] ?? 1;
		if (cur >= total) {
			onClose();
			return;
		}
		setFlows((p) => ({ ...p, [key]: cur + 1 }));
	};
	void nextFlow;

	const bodyFor = (id: string, content: ReactNode) => {
		if (busy === id) return <Busy />;
		const r = results[id];
		if (r)
			return (
				<div className={s.receipt}>
					<div className={s.receiptIcon}>
						<i className="bi bi-check-lg" />
					</div>
					<h5 style={{ fontWeight: 700, color: "var(--pm-accent)" }}>
						{r.msg}
					</h5>
					{r.ref && (
						<p style={{ fontSize: 12, color: "var(--pm-muted)" }}>
							Ref: {r.ref}
						</p>
					)}
				</div>
			);
		return content;
	};

	return (
		<>
			<MBox
				id="approveExpenseModal"
				active={active}
				onClose={onClose}
				title={
					<>
						<i className="bi bi-check2-square text-primary me-2" /> Review
						Expense Claim
					</>
				}
				footer={
					<>
						<button
							type="button"
							className={cx(s.btnPm, s.btnPmD)}
							onClick={onClose}
						>
							Reject
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnPmP)}
							onClick={() =>
								doAction(
									"approveExpenseModal",
									"Expense approved. Added to next payroll/reimbursement run.",
								)
							}
						>
							Approve&Reimburse
						</button>
					</>
				}
			>
				{bodyFor(
					"approveExpenseModal",
					<>
						<div
							className="p-3 rounded mb-3"
							style={{ background: "var(--pm-surface-2)" }}
						>
							<div className="d-flex align-items-center gap-3 mb-3">
								<div
									className={s.avatar}
									style={{ background: "var(--pm-gradient-blue)" }}
								>
									DN
								</div>
								<div>
									<strong>David N. (Sales)</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										Submitted: Today
									</div>
								</div>
							</div>
							<div className="d-flex justify-content-between mb-1">
								<span className="text-muted">Category</span>
								<strong>Meals&Entertainment</strong>
							</div>
							<div className="d-flex justify-content-between mb-1">
								<span className="text-muted">Amount</span>
								<strong style={{ color: "var(--pm-danger)" }}>
									KES 14,500
								</strong>
							</div>
							<div className="d-flex justify-content-between">
								<span className="text-muted">Receipt</span>
								<a href="#">
									View Attachment<i className="bi bi-box-arrow-up-right"></i>
								</a>
							</div>
						</div>
						<div className="mb-3">
							<label className={s.formLabel}>Manager Notes (Optional)</label>
							<textarea className={s.formControl} rows={2}></textarea>
						</div>
					</>,
				)}
			</MBox>
			<MBox
				id="attentionActionModal"
				active={active}
				onClose={onClose}
				title={
					<>
						<i className="bi bi-exclamation-circle text-danger me-2" /> Action
						Items (4)
					</>
				}
				footer={
					<>
						<button type="button" className={s.btnPm} onClick={onClose}>
							Close
						</button>
					</>
				}
			>
				{bodyFor(
					"attentionActionModal",
					<>
						<div className={s.statusRow}>
							<div>
								<strong>3-Way Match Failed</strong>
								<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
									INV-1004 Qty Mismatch
								</div>
							</div>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm, s.btnPmD)}
								onClick={() => onOpen("invoiceDetailsModal")}
							>
								Review
							</button>
						</div>
						<div className={s.statusRow}>
							<div>
								<strong>Pending Dept Approvals</strong>
								<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
									4 invoices awaiting sign-off
								</div>
							</div>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								onClick={() => onOpen("departmentApprovalModal")}
							>
								Nudge
							</button>
						</div>
						<div className={s.statusRow}>
							<div>
								<strong>Supplier KYB Pending</strong>
								<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
									Global Logistics missing KRA
								</div>
							</div>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								onClick={() => onOpen("kybVerificationModal")}
							>
								Verify
							</button>
						</div>
						<div className={s.statusRow}>
							<div>
								<strong>Unprocessed Expense Claims</strong>
								<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
									Sales Team KES 112k
								</div>
							</div>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								onClick={() => onOpen("approveExpenseModal")}
							>
								Approve
							</button>
						</div>
					</>,
				)}
			</MBox>
			<MBox
				id="createPoModal"
				active={active}
				size="lg"
				onClose={onClose}
				title={
					<>
						<i className="bi bi-file-earmark-plus text-info me-2" /> Create
						Purchase Order
					</>
				}
				footer={
					<>
						<button type="button" className={s.btnPm} onClick={onClose}>
							Cancel
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnPmP)}
							onClick={() =>
								doAction(
									"createPoModal",
									"Purchase Order created and routed for internal approval.",
									"PO-998",
								)
							}
						>
							Create PO
						</button>
					</>
				}
			>
				{bodyFor(
					"createPoModal",
					<>
						<div className="row g-3">
							<div className="col-md-6">
								<label className={s.formLabel}>Supplier</label>
								<select className={s.formControl}>
									<option>OfficeMart Stationers</option>
									<option>TechCorp Solutions</option>
								</select>
							</div>
							<div className="col-md-6">
								<label className={s.formLabel}>Department / Cost Center</label>
								<select className={s.formControl}>
									<option>HR&Admin</option>
									<option>IT</option>
									<option>Marketing</option>
								</select>
							</div>
							<div className="col-12">
								<label className={s.formLabel}>Items</label>
								<div className="d-flex gap-2 mb-2">
									<input
										className={s.formControl}
										placeholder="Description"
										style={{ flex: 2 }}
									/>
									<input
										className={s.formControl}
										placeholder="Qty"
										style={{ flex: 1 }}
									/>
									<input
										className={s.formControl}
										placeholder="Unit Price"
										style={{ flex: 1 }}
									/>
								</div>
								<button
									type="button"
									className={cx(s.btnPm, s.btnSm, "pm-btn-outline")}
									onClick={onClose}
								>
									<i className="bi bi-plus"></i>Add Line Item
								</button>
							</div>
							<div className="col-12">
								<div
									className="p-3 rounded"
									style={{ background: "var(--pm-surface-2)" }}
								>
									<div className="d-flex justify-content-between">
										<span style={{ fontWeight: 700 }}>Estimated Total</span>
										<strong
											style={{ color: "var(--pm-primary)", fontSize: 18 }}
										>
											KES 0.00
										</strong>
									</div>
								</div>
							</div>
						</div>
					</>,
				)}
			</MBox>
			<MBox
				id="departmentApprovalModal"
				active={active}
				onClose={onClose}
				title={
					<>
						<i className="bi bi-person-check me-2" /> Request Department
						Approval
					</>
				}
				footer={
					<>
						<button type="button" className={s.btnPm} onClick={onClose}>
							Cancel
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnPmP)}
							onClick={() =>
								doAction(
									"departmentApprovalModal",
									"Approval request sent to Sarah K.",
								)
							}
						>
							Send Nudge
						</button>
					</>
				}
			>
				{bodyFor(
					"departmentApprovalModal",
					<>
						<p style={{ fontSize: 13, color: "var(--pm-ink-soft)" }}>
							Invoice INV-4419 (OfficeMart) requires HR Department approval
							before payment can be executed.
						</p>
						<div className="mb-3">
							<label className={s.formLabel}>Route to Approver</label>
							<select className={s.formControl}>
								<option>Sarah K. (HR Manager)</option>
								<option>David N. (Sales Head)</option>
							</select>
						</div>
						<div className="mb-3">
							<label className={s.formLabel}>Add Note</label>
							<textarea className={s.formControl} rows={2}>
								Hi Sarah, please approve the latest stationery invoice so we can
								clear it this Friday.
							</textarea>
						</div>
						<div className="form-check">
							<input
								type="checkbox"
								className="form-check-input"
								defaultChecked
							/>
							<label className="form-check-label" style={{ fontSize: 13 }}>
								Send email and push notification immediately
							</label>
						</div>
					</>,
				)}
			</MBox>
			<MBox
				id="disputeInvoiceModal"
				active={active}
				onClose={onClose}
				title={
					<>
						<i className="bi bi-exclamation-triangle text-danger me-2" />{" "}
						Dispute Invoice (INV-1004)
					</>
				}
				footer={
					<>
						<button type="button" className={s.btnPm} onClick={onClose}>
							Cancel
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnPmD)}
							onClick={() =>
								doAction(
									"disputeInvoiceModal",
									"Invoice flagged as disputed. Supplier notified.",
								)
							}
						>
							Submit Dispute
						</button>
					</>
				}
			>
				{bodyFor(
					"disputeInvoiceModal",
					<>
						<div className="mb-3">
							<label className={s.formLabel}>Reason for Dispute</label>
							<select className={s.formControl}>
								<option>Quantity mismatch vs Goods Receipt</option>
								<option>Price differs from PO</option>
								<option>Duplicate invoice</option>
								<option>Defective goods / services</option>
							</select>
						</div>
						<div className="mb-3">
							<label className={s.formLabel}>Details</label>
							<textarea className={s.formControl} rows={3}>
								We ordered 50 items but GRN-442 confirms only 40 were delivered.
								Please issue a credit note for the missing 10 units.
							</textarea>
						</div>
						<div
							className="p-3 rounded"
							style={{ background: "var(--pm-warning-soft)", fontSize: 12 }}
						>
							This will freeze the invoice in the AP pipeline and send an
							automated notification to the supplier via their portal/email.
						</div>
					</>,
				)}
			</MBox>
			<MBox
				id="dpoAnalyticsModal"
				active={active}
				size="lg"
				onClose={onClose}
				title={
					<>
						<i className="bi bi-pie-chart text-danger me-2" /> DPO & Cash Flow
						Analytics
					</>
				}
				footer={
					<>
						<button type="button" className={s.btnPm} onClick={onClose}>
							Close
						</button>
					</>
				}
			>
				{bodyFor(
					"dpoAnalyticsModal",
					<>
						<div className="row g-3">
							<div className="col-md-4">
								<div
									className="p-3 rounded text-center"
									style={{ background: "var(--pm-info-soft)" }}
								>
									<div
										style={{ fontSize: 11, fontWeight: 700, color: "#1D4ED8" }}
									>
										AVG DPO
									</div>
									<div
										style={{
											fontSize: 28,
											fontWeight: 700,
											color: "var(--pm-info)",
										}}
									>
										42 Days
									</div>
								</div>
							</div>
							<div className="col-md-8">
								<h6 style={{ fontSize: 13, fontWeight: 700 }}>
									6-Month Outflow Trend
								</h6>
								<div className={s.chartBars}>
									<div
										className={s.chartBar}
										style={{ height: "50%", background: "var(--pm-warning)" }}
									>
										<span className={s.barLabel}>Jan</span>
									</div>
									<div
										className={s.chartBar}
										style={{ height: "60%", background: "var(--pm-warning)" }}
									>
										<span className={s.barLabel}>Feb</span>
									</div>
									<div
										className={s.chartBar}
										style={{ height: "45%", background: "var(--pm-warning)" }}
									>
										<span className={s.barLabel}>Mar</span>
									</div>
									<div
										className={s.chartBar}
										style={{ height: "70%", background: "var(--pm-danger)" }}
									>
										<span className={s.barLabel}>Apr</span>
									</div>
									<div
										className={s.chartBar}
										style={{ height: "55%", background: "var(--pm-warning)" }}
									>
										<span className={s.barLabel}>May</span>
									</div>
									<div
										className={s.chartBar}
										style={{ height: "80%", background: "var(--pm-primary)" }}
									>
										<span className={s.barLabel}>Jun</span>
									</div>
								</div>
							</div>
						</div>
						<div
							className="p-3 rounded mt-3"
							style={{ background: "var(--pm-surface-2)", fontSize: 12 }}
						>
							<i className="bi bi-stars text-purple me-1"></i>AI Insight:
							Extending payment terms for non-critical suppliers from Net 15 to
							Net 30 could free up KES 1.2M in monthly working capital.
						</div>
					</>,
				)}
			</MBox>
			<MBox
				id="earlyPaymentDiscountModal"
				active={active}
				onClose={onClose}
				title={
					<>
						<i className="bi bi-window" /> Capture Early Payment Discount
					</>
				}
				footer={
					<>
						<button type="button" className={s.btnPm} onClick={onClose}>
							Ignore
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnPmA)}
							onClick={() =>
								doAction(
									"earlyPaymentDiscountModal",
									"Discount captured! Payment of KES 416,500 queued for today.",
								)
							}
						>
							Pay Now&Save KES 8,500
						</button>
					</>
				}
			>
				{bodyFor(
					"earlyPaymentDiscountModal",
					<>
						<div
							className="p-3 rounded mb-3"
							style={{
								background: "var(--pm-accent-soft)",
								textAlign: "center",
							}}
						>
							<div style={{ fontSize: 11, fontWeight: 700, color: "#047857" }}>
								SAVINGS OPPORTUNITY
							</div>
							<div
								style={{
									fontSize: 28,
									fontWeight: 700,
									color: "var(--pm-accent)",
								}}
							>
								KES 8,500
							</div>
						</div>
						<div className="table-responsive">
							<table className={s.tbl}>
								<tbody>
									<tr>
										<td>Invoice</td>
										<td>INV-2210 (OfficeMart)</td>
									</tr>
									<tr>
										<td>Original Amount</td>
										<td>KES 425,000</td>
									</tr>
									<tr>
										<td>Discount Terms</td>
										<td>2% 10 Net 30</td>
									</tr>
									<tr>
										<td>Discount Expiry</td>
										<td style={{ color: "var(--pm-danger)" }}>
											Tomorrow, 5:00 PM
										</td>
									</tr>
									<tr>
										<td>
											<strong style={{ color: "var(--pm-primary)" }}>
												New Total
											</strong>
										</td>
										<td>
											<strong style={{ color: "var(--pm-primary)" }}>
												KES 416,500
											</strong>
										</td>
									</tr>
								</tbody>
							</table>
						</div>
					</>,
				)}
			</MBox>
			<MBox
				id="expenseClaimModal"
				active={active}
				onClose={onClose}
				title={
					<>
						<i className="bi bi-receipt text-warning me-2" /> File Expense Claim
					</>
				}
				footer={
					<>
						<button type="button" className={s.btnPm} onClick={onClose}>
							Cancel
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnPmP)}
							onClick={() =>
								doAction(
									"expenseClaimModal",
									"Expense claim submitted for manager review.",
									"EX-5541",
								)
							}
						>
							Submit Claim
						</button>
					</>
				}
			>
				{bodyFor(
					"expenseClaimModal",
					<>
						<div className="mb-3">
							<label className={s.formLabel}>Category</label>
							<select className={s.formControl}>
								<option>Travel&Mileage</option>
								<option>Meals&Entertainment</option>
								<option>Office Supplies</option>
								<option>Software/Subscriptions</option>
							</select>
						</div>
						<div className="mb-3">
							<label className={s.formLabel}>Amount (KES)</label>
							<input className={s.formControl} placeholder="0.00" />
						</div>
						<div className="mb-3">
							<label className={s.formLabel}>Description / Purpose</label>
							<textarea
								className={s.formControl}
								rows={2}
								placeholder="Client lunch with Acme corp..."
							></textarea>
						</div>
						<div className="mb-3">
							<label className={s.formLabel}>Attach Receipt</label>
							<input type="file" className={s.formControl} />
						</div>
					</>,
				)}
			</MBox>
			<MBox
				id="exportApReportModal"
				active={active}
				onClose={onClose}
				title={
					<>
						<i className="bi bi-download me-2" /> Export Accounts Payable Data
					</>
				}
				footer={
					<>
						<button type="button" className={s.btnPm} onClick={onClose}>
							Cancel
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnPmP)}
							onClick={() =>
								doAction(
									"exportApReportModal",
									"Report generated and downloaded successfully.",
								)
							}
						>
							<i className="bi bi-download"></i>Generate Data
						</button>
					</>
				}
			>
				{bodyFor(
					"exportApReportModal",
					<>
						<div className="mb-3">
							<label className={s.formLabel}>Report Type</label>
							<select className={s.formControl}>
								<option>AP Aging Summary</option>
								<option>Invoice Register</option>
								<option>Payment History</option>
								<option>Supplier Master List</option>
							</select>
						</div>
						<div className="row g-3 mb-3">
							<div className="col-6">
								<label className={s.formLabel}>Start Date</label>
								<input
									type="date"
									className={s.formControl}
									defaultValue="2025-01-01"
								/>
							</div>
							<div className="col-6">
								<label className={s.formLabel}>End Date</label>
								<input
									type="date"
									className={s.formControl}
									defaultValue="2025-06-30"
								/>
							</div>
						</div>
						<div className="mb-3">
							<label className={s.formLabel}>Format</label>
							<select className={s.formControl}>
								<option>Excel (.xlsx)</option>
								<option>CSV</option>
								<option>PDF</option>
								<option>ERP Sync (JSON)</option>
							</select>
						</div>
					</>,
				)}
			</MBox>
			<MBox
				id="kybVerificationModal"
				active={active}
				onClose={onClose}
				title={
					<>
						<i className="bi bi-shield-check text-info me-2" /> Supplier KYB
						Verification
					</>
				}
				footer={
					<>
						<button type="button" className={s.btnPm} onClick={onClose}>
							Close
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnPmP)}
							onClick={() =>
								doAction(
									"kybVerificationModal",
									"Supplier KYB verified successfully. Account is now Active.",
								)
							}
						>
							Mark as Verified
						</button>
					</>
				}
			>
				{bodyFor(
					"kybVerificationModal",
					<>
						<div
							className="p-3 rounded mb-3"
							style={{ background: "var(--pm-surface-2)" }}
						>
							<strong>Global Logistics Hub</strong>
							<br />
							<span style={{ fontSize: 11, color: "var(--pm-muted)" }}>
								Status: Pending compliance
							</span>
						</div>
						<div className="mb-3">
							<label className={s.formLabel}>KRA PIN Verification</label>
							<div className="d-flex gap-2">
								<input
									className={s.formControl}
									placeholder="Enter PIN (e.g. P05...)"
								/>
								<button
									type="button"
									className={cx(s.btnPm, s.btnPmP)}
									onClick={onClose}
								>
									iTax Lookup
								</button>
							</div>
						</div>
						<div className="mb-3">
							<label className={s.formLabel}>Company Registry (CR12)</label>
							<input type="file" className={s.formControl} />
						</div>
						<div className="form-check">
							<input type="checkbox" className="form-check-input" />
							<label className="form-check-label" style={{ fontSize: 13 }}>
								Manually override and approve (Requires Admin)
							</label>
						</div>
					</>,
				)}
			</MBox>
			<MBox
				id="paySupplierModal"
				active={active}
				onClose={onClose}
				title={
					<>
						<i className="bi bi-send text-success me-2" /> Pay Supplier
					</>
				}
				footer={
					<>
						<button type="button" className={s.btnPm} onClick={onClose}>
							Cancel
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnPmP)}
							onClick={() =>
								doAction(
									"paySupplierModal",
									"Payment of KES 85,200 to Global Logistics initiated. Pending final director approval.",
									"PMT-2025-992",
								)
							}
						>
							Initiate Payment
						</button>
					</>
				}
			>
				{bodyFor(
					"paySupplierModal",
					<>
						<div className="mb-3">
							<label className={s.formLabel}>Invoice to Pay</label>
							<select className={s.formControl}>
								<option>INV-0092 (Global Logistics) - KES 85,200</option>
								<option>INV-881A (CleanCo) - KES 24,000</option>
							</select>
						</div>
						<div className="mb-3">
							<label className={s.formLabel}>Payment Amount</label>
							<input className={s.formControl} defaultValue="85200" />
						</div>
						<div className="mb-3">
							<label className={s.formLabel}>Source Account</label>
							<select className={s.formControl}>
								<option>Main Ops Account (Equity) - KES 4.2M</option>
								<option>PayMo Wallet - KES 800K</option>
							</select>
						</div>
						<div className="mb-3">
							<label className={s.formLabel}>Remittance Method</label>
							<div
								className="p-3 border rounded mb-2 d-flex align-items-center gap-3"
								style={{
									borderColor: "var(--pm-primary)!important",
									background: "rgba(79,70,229,.04)",
								}}
							>
								<input type="radio" name="spay" defaultChecked />
								<i
									className="bi bi-bank"
									style={{ fontSize: 20, color: "var(--pm-info)" }}
								></i>
								<div>
									<strong>RTGS / Bank</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										To KCB Account
									</div>
								</div>
							</div>
							<div className="p-3 border rounded d-flex align-items-center gap-3">
								<input type="radio" name="spay" />
								<i
									className="bi bi-phone"
									style={{ fontSize: 20, color: "var(--pm-accent)" }}
								></i>
								<div>
									<strong>M-Pesa B2B</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										Instant
									</div>
								</div>
							</div>
						</div>
					</>,
				)}
			</MBox>
			<MBox
				id="payableAgingModal"
				active={active}
				size="lg"
				onClose={onClose}
				title={
					<>
						<i className="bi bi-bar-chart text-info me-2" /> Accounts Payable
						Aging Detail
					</>
				}
				footer={
					<>
						<button type="button" className={s.btnPm} onClick={onClose}>
							Close
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnPmP)}
							onClick={() => onOpen("exportApReportModal")}
						>
							Export CSV
						</button>
					</>
				}
			>
				{bodyFor(
					"payableAgingModal",
					<>
						<div className="table-responsive">
							<table className={s.tbl}>
								<thead>
									<tr>
										<th>Supplier</th>
										<th>Current</th>
										<th>1-30 Days</th>
										<th>31-60 Days</th>
										<th>60+ Days</th>
										<th>Total Balance</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>TechCorp Solutions</td>
										<td>KES 0</td>
										<td>KES 450,000</td>
										<td>KES 0</td>
										<td>KES 0</td>
										<td>
											<strong>KES 450,000</strong>
										</td>
									</tr>
									<tr>
										<td>Global Logistics</td>
										<td>KES 85,200</td>
										<td>KES 0</td>
										<td>KES 0</td>
										<td>KES 0</td>
										<td>
											<strong>KES 85,200</strong>
										</td>
									</tr>
									<tr>
										<td>DesignWorks Agency</td>
										<td>KES 0</td>
										<td>KES 0</td>
										<td>KES 210,000</td>
										<td>KES 0</td>
										<td>
											<strong>KES 210,000</strong>
										</td>
									</tr>
									<tr>
										<td>Alpha Supplies</td>
										<td>KES 0</td>
										<td>KES 0</td>
										<td>KES 0</td>
										<td>KES 145,000</td>
										<td style={{ color: "var(--pm-danger)" }}>
											<strong>KES 145,000</strong>
										</td>
									</tr>
								</tbody>
								<tfoot>
									<tr>
										<th>Total</th>
										<th>KES 1,250,000</th>
										<th>KES 845,000</th>
										<th>KES 210,000</th>
										<th>KES 145,000</th>
										<th style={{ color: "var(--pm-primary)" }}>
											KES 2,450,000
										</th>
									</tr>
								</tfoot>
							</table>
						</div>
					</>,
				)}
			</MBox>
			<MBox
				id="paymentReceiptModal"
				active={active}
				onClose={onClose}
				title={
					<>
						<i className="bi bi-receipt me-2" /> Remittance Advice
					</>
				}
				footer={
					<>
						<button type="button" className={s.btnPm} onClick={onClose}>
							Close
						</button>
					</>
				}
			>
				{bodyFor(
					"paymentReceiptModal",
					<>
						<div className={s.receipt}>
							<div className="receipt-icon">
								<i className="bi bi-check-lg"></i>
							</div>
							<h5 style={{ fontWeight: 700, color: "var(--pm-accent)" }}>
								Settlement Completed
							</h5>
							<div
								className="p-3 rounded text-start mt-3"
								style={{ background: "#fff", fontSize: 13 }}
							>
								<div className="d-flex justify-content-between mb-2">
									<span className="text-muted">Batch ID</span>
									<strong>BATCH-20250625-C</strong>
								</div>
								<div className="d-flex justify-content-between mb-2">
									<span className="text-muted">Method</span>
									<strong>M-Pesa B2B</strong>
								</div>
								<div className="d-flex justify-content-between mb-2">
									<span className="text-muted">Invoices Cleared</span>
									<strong>8 Invoices</strong>
								</div>
								<div className="d-flex justify-content-between">
									<span className="text-muted">Total Paid</span>
									<strong style={{ color: "var(--pm-primary)" }}>
										KES 412,500
									</strong>
								</div>
							</div>
							<div
								className="d-flex justify-content-center mt-3"
								style={{ gap: 8 }}
							>
								<button
									type="button"
									className={cx(s.btnPm, s.btnSm)}
									onClick={onClose}
								>
									<i className="bi bi-envelope"></i>Resend to Suppliers
								</button>
								<button
									type="button"
									className={cx(s.btnPm, s.btnSm)}
									onClick={onClose}
								>
									<i className="bi bi-download"></i>PDF
								</button>
							</div>
						</div>
					</>,
				)}
			</MBox>
			<MBox
				id="supplierProfileModal"
				active={active}
				size="lg"
				onClose={onClose}
				title={
					<>
						<i className="bi bi-building me-2" /> TechCorp Solutions Ltd
					</>
				}
				footer={
					<>
						<button type="button" className={s.btnPm} onClick={onClose}>
							Close
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnPmP)}
							onClick={() => onOpen("uploadInvoiceModal")}
						>
							New Invoice
						</button>
					</>
				}
			>
				{bodyFor(
					"supplierProfileModal",
					<>
						<div className={cx(s.pills, "mb-3")}>
							<button
								type="button"
								className={cx(s.pill, "active")}
								onClick={onClose}
							>
								Info&Terms
							</button>
							<button type="button" className={s.pill} onClick={onClose}>
								Invoices&Payments
							</button>
						</div>
						<div id="suppProf-info" className="tab-panel active">
							<div className="row g-3">
								<div className="col-md-6">
									<div
										className="p-3 rounded"
										style={{ background: "var(--pm-surface-2)" }}
									>
										<span className="text-muted" style={{ fontSize: 11 }}>
											KRA PIN
										</span>
										<br />
										<strong>P051283944L</strong>
									</div>
								</div>
								<div className="col-md-6">
									<div
										className="p-3 rounded"
										style={{ background: "var(--pm-surface-2)" }}
									>
										<span className="text-muted" style={{ fontSize: 11 }}>
											Payment Bank
										</span>
										<br />
										<strong>NCBA (Acc: ***8821)</strong>
									</div>
								</div>
								<div className="col-md-6">
									<div
										className="p-3 rounded"
										style={{ background: "var(--pm-surface-2)" }}
									>
										<span className="text-muted" style={{ fontSize: 11 }}>
											Payment Terms
										</span>
										<br />
										<strong>Net 30</strong>
									</div>
								</div>
								<div className="col-md-6">
									<div
										className="p-3 rounded"
										style={{ background: "var(--pm-surface-2)" }}
									>
										<span className="text-muted" style={{ fontSize: 11 }}>
											Total Spend (YTD)
										</span>
										<br />
										<strong>KES 2,450,000</strong>
									</div>
								</div>
							</div>
							<div className="d-flex gap-2 mt-3">
								<button
									type="button"
									className={cx(s.btnPm, s.btnSm)}
									onClick={onClose}
								>
									<i className="bi bi-pencil"></i>Edit Details
								</button>
								<button
									type="button"
									className={cx(s.btnPm, s.btnSm)}
									onClick={() => onOpen("vendorPerformanceModal")}
								>
									<i className="bi bi-star"></i>Performance Rating
								</button>
							</div>
						</div>
						<div id="suppProf-history" className="tab-panel">
							<div className="table-responsive">
								<table className={s.tbl}>
									<thead>
										<tr>
											<th>Inv #</th>
											<th>Date</th>
											<th>Amount</th>
											<th>Status</th>
										</tr>
									</thead>
									<tbody>
										<tr>
											<td>INV-1004</td>
											<td>24 Jun</td>
											<td>KES 450,000</td>
											<td>
												<span className={cx(s.badge, s.badgeW)}>Disputed</span>
											</td>
										</tr>
										<tr>
											<td>INV-0992</td>
											<td>12 May</td>
											<td>KES 1,200,000</td>
											<td>
												<span className={cx(s.badge, s.badgeS)}>Paid</span>
											</td>
										</tr>
										<tr>
											<td>INV-0881</td>
											<td>10 Apr</td>
											<td>KES 800,000</td>
											<td>
												<span className={cx(s.badge, s.badgeS)}>Paid</span>
											</td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
					</>,
				)}
			</MBox>
			<MBox
				id="supplierStatementModal"
				active={active}
				onClose={onClose}
				title={
					<>
						<i className="bi bi-file-text me-2" /> Generate Supplier Statement
					</>
				}
				footer={
					<>
						<button type="button" className={s.btnPm} onClick={onClose}>
							Cancel
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnPmP)}
							onClick={() =>
								doAction(
									"supplierStatementModal",
									"Statement generated successfully. PDF downloaded.",
								)
							}
						>
							<i className="bi bi-download"></i>Generate PDF
						</button>
					</>
				}
			>
				{bodyFor(
					"supplierStatementModal",
					<>
						<div className="mb-3">
							<label className={s.formLabel}>Supplier</label>
							<select className={s.formControl}>
								<option>TechCorp Solutions</option>
								<option>OfficeMart Stationers</option>
							</select>
						</div>
						<div className="row g-3 mb-3">
							<div className="col-6">
								<label className={s.formLabel}>Start Date</label>
								<input
									type="date"
									className={s.formControl}
									defaultValue="2025-01-01"
								/>
							</div>
							<div className="col-6">
								<label className={s.formLabel}>End Date</label>
								<input
									type="date"
									className={s.formControl}
									defaultValue="2025-06-30"
								/>
							</div>
						</div>
						<div className="mb-3">
							<label className={s.formLabel}>Include</label>
							<div className="form-check">
								<input
									type="checkbox"
									className="form-check-input"
									defaultChecked
								/>
								<label className="form-check-label">Invoices</label>
							</div>
							<div className="form-check">
								<input
									type="checkbox"
									className="form-check-input"
									defaultChecked
								/>
								<label className="form-check-label">Payments made</label>
							</div>
							<div className="form-check">
								<input
									type="checkbox"
									className="form-check-input"
									defaultChecked
								/>
								<label className="form-check-label">Credit notes</label>
							</div>
						</div>
					</>,
				)}
			</MBox>
			<MBox
				id="uploadInvoiceModal"
				active={active}
				onClose={onClose}
				title={
					<>
						<i className="bi bi-cloud-arrow-up text-primary me-2" /> Upload &
						Scan Invoice
					</>
				}
				footer={
					<>
						<button type="button" className={s.btnPm} onClick={onClose}>
							Cancel
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnPmP)}
							onClick={() =>
								doAction(
									"uploadInvoiceModal",
									"Invoice scanned successfully! Extracted KES 45,000 from Alpha Suppliers.",
									"INV-SCAN-01",
								)
							}
						>
							Process via OCR
						</button>
					</>
				}
			>
				{bodyFor(
					"uploadInvoiceModal",
					<>
						<div className="file-upload-zone mb-3">
							<i
								className="bi bi-file-earmark-pdf"
								style={{ fontSize: 32, color: "var(--pm-primary)" }}
							></i>
							<div style={{ fontWeight: 600, marginTop: 8 }}>
								Drag&drop invoice PDF or image here
							</div>
							<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
								PayMo OCR will automatically extract details
							</div>
						</div>
						<div
							className="p-3 rounded"
							style={{ background: "var(--pm-surface-2)" }}
						>
							<h6 style={{ fontWeight: 700, fontSize: 12, marginBottom: 8 }}>
								OR FORWARD VIA EMAIL
							</h6>
							<p
								style={{ fontSize: 11, color: "var(--pm-ink-soft)", margin: 0 }}
							>
								Suppliers can email invoices directly to:
								<br />
								<strong style={{ color: "var(--pm-primary)" }}>
									ap-invoices@yourbusiness.paymo.co.ke
								</strong>
							</p>
						</div>
					</>,
				)}
			</MBox>
			<MBox
				id="vendorPerformanceModal"
				active={active}
				onClose={onClose}
				title={
					<>
						<i className="bi bi-star-half text-warning me-2" /> Vendor
						Performance: TechCorp
					</>
				}
				footer={
					<>
						<button type="button" className={s.btnPm} onClick={onClose}>
							Close
						</button>
					</>
				}
			>
				{bodyFor(
					"vendorPerformanceModal",
					<>
						<div className="d-flex align-items-center justify-content-between mb-4">
							<div>
								<div
									style={{
										fontSize: 32,
										fontWeight: 700,
										color: "var(--pm-warning)",
									}}
								>
									4.8
									<span style={{ fontSize: 16, color: "var(--pm-muted)" }}>
										/5
									</span>
								</div>
								<div
									style={{
										fontSize: 11,
										fontWeight: 700,
										color: "var(--pm-muted)",
									}}
								>
									OVERALL SCORE
								</div>
							</div>
							<div style={{ fontSize: 24, color: "var(--pm-warning)" }}>
								<i className="bi bi-star-fill"></i>
								<i className="bi bi-star-fill"></i>
								<i className="bi bi-star-fill"></i>
								<i className="bi bi-star-fill"></i>
								<i className="bi bi-star-half"></i>
							</div>
						</div>
						<div className="mb-3">
							<div
								className="d-flex justify-content-between mb-1"
								style={{ fontSize: 12 }}
							>
								<span>On-Time Delivery</span>
								<span>98%</span>
							</div>
							<div className={s.progress}>
								<div
									className={s.progressBar}
									style={{ width: "98%", background: "var(--pm-accent)" }}
								></div>
							</div>
						</div>
						<div className="mb-3">
							<div
								className="d-flex justify-content-between mb-1"
								style={{ fontSize: 12 }}
							>
								<span>Invoice Accuracy (vs PO)</span>
								<span>92%</span>
							</div>
							<div className={s.progress}>
								<div
									className={s.progressBar}
									style={{ width: "92%", background: "var(--pm-info)" }}
								></div>
							</div>
						</div>
						<div className="mb-3">
							<div
								className="d-flex justify-content-between mb-1"
								style={{ fontSize: 12 }}
							>
								<span>Dispute Rate</span>
								<span>4%</span>
							</div>
							<div className={s.progress}>
								<div
									className={s.progressBar}
									style={{ width: "4%", background: "var(--pm-warning)" }}
								></div>
							</div>
						</div>
					</>,
				)}
			</MBox>
		</>
	);
}
