/* ============================================================================
 * AccountsPayableBody.tsx — the page body, ported verbatim from 3.6.html.
 * ----------------------------------------------------------------------------
 * AUTO-GENERATED by port_page_bodies.py — regenerate rather than hand-edit.
 *
 * WHY THIS EXISTS
 * The first React port of this page paraphrased the original instead of
 * converting it: cards and whole numbered sections were absent and the tables
 * carried invented columns and rows. This file is a faithful conversion of the
 * source `<div class="pm-content">` of 3.6.html, so every card, table row
 * and figure matches the original layout.
 *
 * BRIDGES APPLIED
 *   class=            -> className=
 *   style="a:b"       -> style={{ a: "b" }}
 *   openModal('x')    -> onOpen('x')   (the page's setActiveModal)
 *   other onclick=    -> onAction()    (toast / no-op, never a dead button)
 *   every <td>        -> gains data-label from its column header, which the
 *                        responsive CSS uses to render tables as cards <=768px
 * ========================================================================== */
import styles from "../styles/accounts-payable.module.css";

const s = styles as Record<string, string>;
const cx = (...c: (string | false | undefined)[]) =>
	c.filter(Boolean).join(" ");

interface Props {
	/** Opens a modal by id — the page's setActiveModal. */
	onOpen: (id: string) => void;
	/** Fallback for legacy buttons that only fired a toast. */
	onAction?: () => void;
}

export default function AccountsPayableBody({ onOpen, onAction }: Props) {
	const act = onAction ?? (() => undefined);
	return (
		<>
			<div className="row g-3">
				<div className="col-lg-3 col-md-6">
					<div className={cx(s.card, s.cardAccent)} style={{ minHeight: 170 }}>
						<p
							style={{
								margin: 0,
								fontSize: 12,
								color: "rgba(255,255,255,.78)",
							}}
						>
							AP Engine is active <span style={{ color: "#86efac" }}>●</span>
						</p>
						<div
							className={s.sv}
							style={{ margin: "8px 0", color: "#fff", fontSize: 24 }}
						>
							KES 2.45M
						</div>
						<p
							style={{
								margin: 0,
								fontSize: 11,
								color: "rgba(255,255,255,.78)",
								textTransform: "uppercase",
								letterSpacing: "0.05em",
							}}
						>
							Total Outstanding Payables
						</p>
						<div className="d-flex flex-wrap mt-3" style={{ gap: 8 }}>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								style={{
									background: "rgba(255,255,255,.12)",
									borderColor: "rgba(255,255,255,.22)",
									color: "#fff",
								}}
								onClick={() => onOpen("payableAgingModal")}
							>
								Aging Report
							</button>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								style={{
									background: "rgba(255,255,255,.12)",
									borderColor: "rgba(255,255,255,.22)",
									color: "#fff",
								}}
								onClick={() => onOpen("uploadInvoiceModal")}
							>
								Process
							</button>
						</div>
					</div>
				</div>
				<div className="col-lg-3 col-md-6">
					<div className={s.card} style={{ minHeight: 170 }}>
						<p className={s.sl} style={{ color: "var(--pm-danger)" }}>
							DUE IN 7 DAYS
						</p>
						<div className={s.sv} style={{ margin: "6px 0" }}>
							KES 845,000
						</div>
						<span className={cx(s.badge, s.badgeD)}>
							<i className="bi bi-exclamation-circle"></i>12 invoices due
						</span>
						<div className="mt-3">
							<div
								className="d-flex justify-content-between"
								style={{ fontSize: 11, color: "var(--pm-muted)" }}
							>
								<span>Cash readiness</span>
								<span>92%</span>
							</div>
							<div className={cx(s.progress, "mt-1")}>
								<div
									className={s.progressBar}
									style={{ width: "92%", background: "var(--pm-danger)" }}
								></div>
							</div>
						</div>
					</div>
				</div>
				<div className="col-lg-3 col-md-6">
					<div className={s.card} style={{ minHeight: 170 }}>
						<p className={s.sl} style={{ color: "var(--pm-info)" }}>
							DPO (DAYS PAYABLE OUTSTANDING)
						</p>
						<div className={s.sv} style={{ margin: "6px 0" }}>
							42 Days
						</div>
						<span className={cx(s.badge, s.badgeS)}>
							<i className="bi bi-arrow-up-right"></i>+4 days vs last month
						</span>
						<div
							className="mt-2"
							style={{ fontSize: 12, color: "var(--pm-ink-soft)" }}
						>
							<div>
								Standard term: <strong>30 Days</strong>
							</div>
							<div>
								Liquidity optimized: <strong>High</strong>
							</div>
						</div>
					</div>
				</div>
				<div className="col-lg-3 col-md-6">
					<div
						className={s.card}
						style={{ minHeight: 170, borderLeft: "3px solid var(--pm-accent)" }}
					>
						<p className={s.sl} style={{ color: "var(--pm-accent)" }}>
							DISCOUNTS CAPTURED
						</p>
						<div className={s.sv} style={{ margin: "6px 0" }}>
							KES 45,200
						</div>
						<span className={cx(s.badge, s.badgeS)}>
							<i className="bi bi-piggy-bank"></i>Early payments
						</span>
						<div
							className="mt-2"
							style={{ fontSize: 12, color: "var(--pm-ink-soft)" }}
						>
							<div>
								Available to capture:{" "}
								<strong style={{ color: "var(--pm-accent)" }}>
									KES 12,500
								</strong>
							</div>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm, "mt-1 w-100")}
								onClick={() => onOpen("earlyPaymentDiscountModal")}
							>
								Capture now
							</button>
						</div>
					</div>
				</div>
			</div>
			<div className="row g-3">
				<div className="col-lg-4">
					<div className={s.card}>
						<div className="d-flex justify-content-between align-items-center mb-3">
							<h3 className={s.st}>Attention Required</h3>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								onClick={() => onOpen("attentionActionModal")}
							>
								View all
							</button>
						</div>
						<div className={s.feedItem}>
							<div
								className={s.iconCircle}
								style={{
									background: "var(--pm-danger-soft)",
									color: "var(--pm-danger)",
									fontSize: 12,
								}}
							>
								PO
							</div>
							<div style={{ flex: 1 }}>
								<div style={{ fontWeight: 600, fontSize: 13 }}>
									3-Way Match Failed
								</div>
								<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
									Inv #1004 (TechCorp) quantity mismatch
								</div>
							</div>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm, s.btnPmD)}
								onClick={() => onOpen("invoiceDetailModal")}
							>
								Review
							</button>
						</div>
						<div className={s.feedItem}>
							<div
								className={s.iconCircle}
								style={{
									background: "var(--pm-warning-soft)",
									color: "var(--pm-warning)",
									fontSize: 12,
								}}
							>
								AP
							</div>
							<div style={{ flex: 1 }}>
								<div style={{ fontWeight: 600, fontSize: 13 }}>
									Pending Dept Approvals
								</div>
								<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
									4 invoices awaiting IT sign-off
								</div>
							</div>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								onClick={() => onOpen("departmentApprovalModal")}
							>
								Nudge
							</button>
						</div>
						<div className={s.feedItem}>
							<div
								className={s.iconCircle}
								style={{
									background: "var(--pm-info-soft)",
									color: "var(--pm-info)",
									fontSize: 12,
								}}
							>
								KYC
							</div>
							<div style={{ flex: 1 }}>
								<div style={{ fontWeight: 600, fontSize: 13 }}>
									Supplier KYB Pending
								</div>
								<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
									Global Logistics Ltd missing KRA PIN
								</div>
							</div>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								onClick={() => onOpen("kybVerificationModal")}
							>
								Verify
							</button>
						</div>
						<div className={s.feedItem}>
							<div
								className={s.iconCircle}
								style={{
									background: "var(--pm-purple-soft)",
									color: "var(--pm-purple)",
									fontSize: 12,
								}}
							>
								EX
							</div>
							<div style={{ flex: 1 }}>
								<div style={{ fontWeight: 600, fontSize: 13 }}>
									Unprocessed Expense Claims
								</div>
								<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
									KES 112,000 from Sales Team
								</div>
							</div>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								onClick={() => onOpen("approveExpenseModal")}
							>
								Approve
							</button>
						</div>
					</div>
				</div>
				<div className="col-lg-4">
					<div className={s.card}>
						<div className="d-flex justify-content-between align-items-center mb-3">
							<h3 className={s.st}>Smart Suggestions</h3>
							<span className={cx(s.badge, s.badgeP)}>
								<i className="bi bi-stars"></i>AI
							</span>
						</div>
						<div className={s.feedItem}>
							<div
								className={s.iconCircle}
								style={{
									background: "var(--pm-accent-soft)",
									color: "var(--pm-accent)",
									fontSize: 12,
								}}
							>
								EP
							</div>
							<div style={{ flex: 1 }}>
								<div style={{ fontWeight: 600, fontSize: 13 }}>
									Early Payment Discount
								</div>
								<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
									Pay OfficeMart by Fri to save KES 8,500
								</div>
							</div>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								onClick={() => onOpen("earlyPaymentDiscountModal")}
							>
								Execute
							</button>
						</div>
						<div className={s.feedItem}>
							<div
								className={s.iconCircle}
								style={{
									background: "var(--pm-primary-light)",
									color: "#fff",
									fontSize: 12,
								}}
							>
								BP
							</div>
							<div style={{ flex: 1 }}>
								<div style={{ fontWeight: 600, fontSize: 13 }}>
									Batch 15 PesaLink Transfers
								</div>
								<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
									Combine payments to reduce bank fees by 40%
								</div>
							</div>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								onClick={() => onOpen("bulkPaySuppliersModal")}
							>
								Batch
							</button>
						</div>
						<div className={s.feedItem}>
							<div
								className={s.iconCircle}
								style={{
									background: "var(--pm-warning-soft)",
									color: "var(--pm-warning)",
									fontSize: 12,
								}}
							>
								DP
							</div>
							<div style={{ flex: 1 }}>
								<div style={{ fontWeight: 600, fontSize: 13 }}>
									Possible Duplicate Invoice
								</div>
								<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
									Inv #441 (CleanCo) matches last month
								</div>
							</div>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								onClick={() => onOpen("disputeInvoiceModal")}
							>
								Flag
							</button>
						</div>
						<div className={s.feedItem}>
							<div
								className={s.iconCircle}
								style={{
									background: "var(--pm-info-soft)",
									color: "var(--pm-info)",
									fontSize: 12,
								}}
							>
								VD
							</div>
							<div style={{ flex: 1 }}>
								<div style={{ fontWeight: 600, fontSize: 13 }}>
									Invite Suppliers to Portal
								</div>
								<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
									4 top suppliers still using email invoices
								</div>
							</div>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								onClick={() => onOpen("onboardSupplierInviteModal")}
							>
								Invite
							</button>
						</div>
					</div>
				</div>
				<div className="col-lg-4">
					<div className={s.card}>
						<div className="mb-3">
							<h3 className={s.st}>Quick Actions</h3>
							<p className={s.ss}>Accounts payable workflows</p>
						</div>
						<div className={s.quickGrid}>
							<button
								type="button"
								className={s.quickBtn}
								onClick={() => onOpen("uploadInvoiceModal")}
							>
								<i className="bi bi-cloud-arrow-up text-primary me-1"></i>Scan
								Invoice
							</button>
							<button
								type="button"
								className={s.quickBtn}
								onClick={() => onOpen("createPoModal")}
							>
								<i className="bi bi-file-earmark-plus text-info me-1"></i>Create
								PO
							</button>
							<button
								type="button"
								className={s.quickBtn}
								onClick={() => onOpen("paySupplierModal")}
							>
								<i className="bi bi-send text-success me-1"></i>Pay Supplier
							</button>
							<button
								type="button"
								className={s.quickBtn}
								onClick={() => onOpen("bulkPaySuppliersModal")}
							>
								<i
									className="bi bi-collection-play me-1"
									style={{ color: "var(--pm-purple)" }}
								></i>
								Bulk Run
							</button>
							<button
								type="button"
								className={s.quickBtn}
								onClick={() => onOpen("expenseClaimModal")}
							>
								<i className="bi bi-receipt text-warning me-1"></i>File Expense
							</button>
							<button
								type="button"
								className={s.quickBtn}
								onClick={() => onOpen("schedulePaymentModal")}
							>
								<i className="bi bi-calendar-event text-danger me-1"></i>
								Schedule
							</button>
							<button
								type="button"
								className={s.quickBtn}
								onClick={() => onOpen("supplierStatementModal")}
							>
								<i
									className="bi bi-file-text me-1"
									style={{ color: "var(--pm-ink-soft)" }}
								></i>
								Statements
							</button>
							<button
								type="button"
								className={s.quickBtn}
								onClick={() => onOpen("exportApReportModal")}
							>
								<i
									className="bi bi-download me-1"
									style={{ color: "var(--pm-accent)" }}
								></i>
								Export Data
							</button>
						</div>
					</div>
				</div>
			</div>
			<div className={s.card}>
				<div
					className="d-flex justify-content-between align-items-center mb-3 flex-wrap"
					style={{ gap: 8 }}
				>
					<div>
						<h3 className={s.st}>
							<i
								className="bi bi-journal-richtext"
								style={{ color: "var(--pm-primary)" }}
							></i>
							Supplier Directory & Master Data
						</h3>
						<p className={s.ss}>
							Manage vendor onboarding, KYC/KYB compliance, credit terms, and
							performance ratings.
						</p>
					</div>
					<div className="d-flex" style={{ gap: 8 }}>
						<button
							type="button"
							className={cx(s.btnPm, s.btnSm)}
							onClick={() => onOpen("onboardSupplierInviteModal")}
						>
							<i className="bi bi-envelope"></i>Invite to Portal
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnSm, s.btnPmP)}
							onClick={() => onOpen("addSupplierModal")}
						>
							<i className="bi bi-plus-lg"></i>Add Supplier
						</button>
					</div>
				</div>
				<div className="table-responsive">
					<table className={s.tbl}>
						<thead>
							<tr>
								<th>Supplier Name</th>
								<th>Category</th>
								<th>Primary Pay Method</th>
								<th>Credit Terms</th>
								<th>Status</th>
								<th>Rating</th>
								<th>Actions</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td data-label="Supplier Name">
									<strong>TechCorp Solutions Ltd</strong>
									<br />
									<span style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										KRA: P051283944L
									</span>
								</td>
								<td data-label="Category">IT Services</td>
								<td data-label="Primary Pay Method">Bank (NCBA)</td>
								<td data-label="Credit Terms">Net 30</td>
								<td data-label="Status">
									<span className={cx(s.badge, s.badgeS)}>Active</span>
								</td>
								<td data-label="Rating">4.8 ⭐</td>
								<td data-label="Actions">
									<div className="d-flex gap-1">
										<button
											type="button"
											className={cx(s.btnPm, s.btnSm)}
											onClick={() => onOpen("supplierProfileModal")}
										>
											Profile
										</button>
										<button
											type="button"
											className={cx(s.btnPm, s.btnSm)}
											onClick={() => onOpen("vendorPerformanceModal")}
										>
											<i className="bi bi-star"></i>
										</button>
									</div>
								</td>
							</tr>
							<tr>
								<td data-label="Supplier Name">
									<strong>OfficeMart Stationers</strong>
									<br />
									<span style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										KRA: P002239401G
									</span>
								</td>
								<td data-label="Category">Supplies</td>
								<td data-label="Primary Pay Method">M-Pesa Till 445100</td>
								<td data-label="Credit Terms">Net 15</td>
								<td data-label="Status">
									<span className={cx(s.badge, s.badgeS)}>Active</span>
								</td>
								<td data-label="Rating">4.5 ⭐</td>
								<td data-label="Actions">
									<div className="d-flex gap-1">
										<button
											type="button"
											className={cx(s.btnPm, s.btnSm)}
											onClick={() => onOpen("supplierProfileModal")}
										>
											Profile
										</button>
										<button
											type="button"
											className={cx(s.btnPm, s.btnSm)}
											onClick={() => onOpen("vendorPerformanceModal")}
										>
											<i className="bi bi-star"></i>
										</button>
									</div>
								</td>
							</tr>
							<tr>
								<td data-label="Supplier Name">
									<strong>Global Logistics Hub</strong>
									<br />
									<span style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										Missing KRA PIN
									</span>
								</td>
								<td data-label="Category">Transport</td>
								<td data-label="Primary Pay Method">Bank (KCB)</td>
								<td data-label="Credit Terms">Net 45</td>
								<td data-label="Status">
									<span className={cx(s.badge, s.badgeW)}>KYB Pending</span>
								</td>
								<td data-label="Rating">New</td>
								<td data-label="Actions">
									<div className="d-flex gap-1">
										<button
											type="button"
											className={cx(s.btnPm, s.btnSm)}
											onClick={() => onOpen("kybVerificationModal")}
										>
											Verify
										</button>
									</div>
								</td>
							</tr>
							<tr>
								<td data-label="Supplier Name">
									<strong>CleanCo Janitorial</strong>
									<br />
									<span style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										KRA: P089122304K
									</span>
								</td>
								<td data-label="Category">Facilities</td>
								<td data-label="Primary Pay Method">M-Pesa PayBill</td>
								<td data-label="Credit Terms">COD</td>
								<td data-label="Status">
									<span className={cx(s.badge, s.badgeS)}>Active</span>
								</td>
								<td data-label="Rating">3.9 ⭐</td>
								<td data-label="Actions">
									<div className="d-flex gap-1">
										<button
											type="button"
											className={cx(s.btnPm, s.btnSm)}
											onClick={() => onOpen("supplierProfileModal")}
										>
											Profile
										</button>
										<button
											type="button"
											className={cx(s.btnPm, s.btnSm)}
											onClick={() => onOpen("vendorPerformanceModal")}
										>
											<i className="bi bi-star"></i>
										</button>
									</div>
								</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div className={s.card}>
				<div
					className="d-flex justify-content-between align-items-center mb-3 flex-wrap"
					style={{ gap: 8 }}
				>
					<div>
						<h3 className={s.st}>
							<i
								className="bi bi-cpu"
								style={{ color: "var(--pm-purple)" }}
							></i>
							Invoice Processing & Three-Way Matching
						</h3>
						<p className={s.ss}>
							OCR data extraction, PO matching, routing to departments, and
							approval workflows.
						</p>
					</div>
					<div className="d-flex" style={{ gap: 8 }}>
						<button
							type="button"
							className={cx(s.btnPm, s.btnSm)}
							onClick={() => onOpen("createPoModal")}
						>
							<i className="bi bi-file-earmark-plus"></i>New PO
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnSm, s.btnPmP)}
							onClick={() => onOpen("uploadInvoiceModal")}
						>
							<i className="bi bi-upc-scan"></i>Scan Invoice
						</button>
					</div>
				</div>
				<div className="row g-3">
					<div className="col-lg-3">
						<div className={cx(s.utilityBlock, "text-center")}>
							<div
								style={{
									fontSize: 11,
									fontWeight: 700,
									color: "var(--pm-muted)",
									marginBottom: 12,
								}}
							>
								INVOICE PIPELINE
							</div>
							<div className="d-flex justify-content-around mb-3">
								<div>
									<div
										style={{
											fontSize: 20,
											fontWeight: 700,
											color: "var(--pm-info)",
										}}
									>
										14
									</div>
									<div style={{ fontSize: 10 }}>NEW (OCR)</div>
								</div>
								<div>
									<div
										style={{
											fontSize: 20,
											fontWeight: 700,
											color: "var(--pm-warning)",
										}}
									>
										8
									</div>
									<div style={{ fontSize: 10 }}>PENDING APPR.</div>
								</div>
								<div>
									<div
										style={{
											fontSize: 20,
											fontWeight: 700,
											color: "var(--pm-accent)",
										}}
									>
										45
									</div>
									<div style={{ fontSize: 10 }}>READY TO PAY</div>
								</div>
							</div>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm, "w-100")}
								onClick={() => onOpen("approvalQueueModal")}
							>
								View Approval Queue
							</button>
						</div>
					</div>
					<div className="col-lg-9">
						<div className="table-responsive">
							<table className={s.tbl}>
								<thead>
									<tr>
										<th>Inv #</th>
										<th>Supplier</th>
										<th>Amount</th>
										<th>3-Way Match</th>
										<th>Department Auth</th>
										<th>Status</th>
										<th>Action</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td data-label="Inv #">INV-1004</td>
										<td data-label="Supplier">TechCorp Solutions</td>
										<td data-label="Amount">KES 450,000</td>
										<td data-label="3-Way Match">
											<span className={cx(s.badge, s.badgeD)}>Failed: Qty</span>
										</td>
										<td data-label="Department Auth">
											<span className={cx(s.badge, s.badgeS)}>
												IT Dept (Approved)
											</span>
										</td>
										<td data-label="Status">
											<span className={cx(s.badge, s.badgeW)}>Exception</span>
										</td>
										<td data-label="Action">
											<button
												type="button"
												className={cx(s.btnPm, s.btnSm)}
												onClick={() => onOpen("invoiceDetailModal")}
											>
												Review
											</button>
										</td>
									</tr>
									<tr>
										<td data-label="Inv #">INV-4419</td>
										<td data-label="Supplier">OfficeMart Stationers</td>
										<td data-label="Amount">KES 12,500</td>
										<td data-label="3-Way Match">
											<span className={cx(s.badge, s.badgeS)}>
												Matched (PO-992)
											</span>
										</td>
										<td data-label="Department Auth">
											<span className={cx(s.badge, s.badgeW)}>
												HR Dept (Pending)
											</span>
										</td>
										<td data-label="Status">
											<span className={cx(s.badge, s.badgeI)}>Routing</span>
										</td>
										<td data-label="Action">
											<button
												type="button"
												className={cx(s.btnPm, s.btnSm)}
												onClick={() => onOpen("departmentApprovalModal")}
											>
												Nudge
											</button>
										</td>
									</tr>
									<tr>
										<td data-label="Inv #">INV-0092</td>
										<td data-label="Supplier">Global Logistics</td>
										<td data-label="Amount">KES 85,200</td>
										<td data-label="3-Way Match">
											<span className={cx(s.badge, s.badgeDark)}>No PO</span>
										</td>
										<td data-label="Department Auth">
											<span className={cx(s.badge, s.badgeS)}>
												Ops (Approved)
											</span>
										</td>
										<td data-label="Status">
											<span className={cx(s.badge, s.badgeS)}>Ready</span>
										</td>
										<td data-label="Action">
											<button
												type="button"
												className={cx(s.btnPm, s.btnSm)}
												onClick={() => onOpen("paySupplierModal")}
											>
												Pay
											</button>
										</td>
									</tr>
									<tr>
										<td data-label="Inv #">INV-881A</td>
										<td data-label="Supplier">CleanCo Janitorial</td>
										<td data-label="Amount">KES 24,000</td>
										<td data-label="3-Way Match">
											<span className={cx(s.badge, s.badgeS)}>
												Matched (PO-995)
											</span>
										</td>
										<td data-label="Department Auth">
											<span className={cx(s.badge, s.badgeS)}>
												Facilities (Approved)
											</span>
										</td>
										<td data-label="Status">
											<span className={cx(s.badge, s.badgeS)}>Ready</span>
										</td>
										<td data-label="Action">
											<button
												type="button"
												className={cx(s.btnPm, s.btnSm)}
												onClick={() => onOpen("paySupplierModal")}
											>
												Pay
											</button>
										</td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
			<div className={s.card}>
				<div
					className="d-flex justify-content-between align-items-center mb-3 flex-wrap"
					style={{ gap: 8 }}
				>
					<div>
						<h3 className={s.st}>
							<i
								className="bi bi-bank"
								style={{ color: "var(--pm-accent)" }}
							></i>
							Supplier Payments & Treasury Settlement
						</h3>
						<p className={s.ss}>
							Batch disbursements, manage early payments, and execute transfers
							via M-Pesa, PesaLink, or RTGS.
						</p>
					</div>
					<div className="d-flex" style={{ gap: 8 }}>
						<button
							type="button"
							className={cx(s.btnPm, s.btnSm)}
							onClick={() => onOpen("schedulePaymentModal")}
						>
							<i className="bi bi-calendar"></i>Schedule
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnSm, s.btnPmA)}
							onClick={() => onOpen("bulkPaySuppliersModal")}
						>
							<i className="bi bi-play-circle"></i>Execute Batch
						</button>
					</div>
				</div>
				<div className="table-responsive">
					<table className={s.tbl}>
						<thead>
							<tr>
								<th>Payment Batch / Ref</th>
								<th>Date Scheduled</th>
								<th>Invoices Included</th>
								<th>Total Value</th>
								<th>Method</th>
								<th>Status</th>
								<th>Action</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td data-label="Payment Batch / Ref">BATCH-20250628-A</td>
								<td data-label="Date Scheduled">Tomorrow, 10:00 AM</td>
								<td data-label="Invoices Included">15 invoices</td>
								<td data-label="Total Value">KES 1,240,000</td>
								<td data-label="Method">PesaLink (Mixed)</td>
								<td data-label="Status">
									<span className={cx(s.badge, s.badgeI)}>Scheduled</span>
								</td>
								<td data-label="Action">
									<button
										type="button"
										className={cx(s.btnPm, s.btnSm)}
										onClick={() => onOpen("bulkPaySuppliersModal")}
									>
										Edit Batch
									</button>
								</td>
							</tr>
							<tr>
								<td data-label="Payment Batch / Ref">PMT-TC-1003</td>
								<td data-label="Date Scheduled">Today, 2:00 PM</td>
								<td data-label="Invoices Included">1 invoice (TechCorp)</td>
								<td data-label="Total Value">KES 200,000</td>
								<td data-label="Method">RTGS</td>
								<td data-label="Status">
									<span className={cx(s.badge, s.badgeW)}>
										Pending Final Auth
									</span>
								</td>
								<td data-label="Action">
									<button
										type="button"
										className={cx(s.btnPm, s.btnSm)}
										onClick={() => onOpen("paySupplierModal")}
									>
										Authorize
									</button>
								</td>
							</tr>
							<tr>
								<td data-label="Payment Batch / Ref">BATCH-20250625-C</td>
								<td data-label="Date Scheduled">25 Jun 2025</td>
								<td data-label="Invoices Included">8 invoices</td>
								<td data-label="Total Value">KES 412,500</td>
								<td data-label="Method">M-Pesa B2B</td>
								<td data-label="Status">
									<span className={cx(s.badge, s.badgeS)}>Completed</span>
								</td>
								<td data-label="Action">
									<button
										type="button"
										className={cx(s.btnPm, s.btnSm)}
										onClick={() => onOpen("paymentReceiptModal")}
									>
										Receipts
									</button>
								</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div className="row g-3">
				<div className="col-lg-6">
					<div className={cx(s.card, "h-100")}>
						<div className="d-flex justify-content-between align-items-center mb-3">
							<div>
								<h3 className={s.st}>
									<i
										className="bi bi-receipt"
										style={{ color: "var(--pm-warning)" }}
									></i>
									Expense Claims
								</h3>
								<p className={s.ss}>Employee reimbursement & petty cash</p>
							</div>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								onClick={() => onOpen("expenseClaimModal")}
							>
								File Claim
							</button>
						</div>
						<div className={s.feedItem}>
							<div
								className={s.avatar}
								style={{
									background: "var(--pm-gradient-blue)",
									width: 32,
									height: 32,
									fontSize: 12,
								}}
							>
								DN
							</div>
							<div style={{ flex: 1 }}>
								<div style={{ fontWeight: 600, fontSize: 13 }}>
									David N. (Sales)
								</div>
								<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
									Client dinner + Taxi · KES 14,500
								</div>
							</div>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm, s.btnPmP)}
								onClick={() => onOpen("approveExpenseModal")}
							>
								Review
							</button>
						</div>
						<div className={s.feedItem}>
							<div
								className={s.avatar}
								style={{
									background: "var(--pm-gradient-rose)",
									width: 32,
									height: 32,
									fontSize: 12,
								}}
							>
								MK
							</div>
							<div style={{ flex: 1 }}>
								<div style={{ fontWeight: 600, fontSize: 13 }}>
									Mercy K. (Ops)
								</div>
								<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
									Office supplies · KES 8,200
								</div>
							</div>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm, s.btnPmP)}
								onClick={() => onOpen("approveExpenseModal")}
							>
								Review
							</button>
						</div>
						<div className={s.feedItem}>
							<div
								className={s.iconCircle}
								style={{
									background: "var(--pm-info-soft)",
									color: "var(--pm-info)",
									fontSize: 14,
									width: 32,
									height: 32,
								}}
							>
								<i className="bi bi-cash"></i>
							</div>
							<div style={{ flex: 1 }}>
								<div style={{ fontWeight: 600, fontSize: 13 }}>
									Petty Cash Replenishment
								</div>
								<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
									Branch 2 · KES 50,000
								</div>
							</div>
							<span className={cx(s.badge, s.badgeS)}>Approved</span>
						</div>
					</div>
				</div>
				<div className="col-lg-6">
					<div className={cx(s.card, "h-100")}>
						<div className="d-flex justify-content-between align-items-center mb-3">
							<div>
								<h3 className={s.st}>
									<i
										className="bi bi-pie-chart"
										style={{ color: "var(--pm-danger)" }}
									></i>
									Payable Analytics
								</h3>
								<p className={s.ss}>Aging, DPO, and cash outflow forecasting</p>
							</div>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								onClick={() => onOpen("dpoAnalyticsModal")}
							>
								Dashboards
							</button>
						</div>
						<div className={s.utilityBlock} style={{ padding: 12 }}>
							<h4
								style={{
									fontSize: 12,
									fontWeight: 700,
									color: "var(--pm-muted)",
									marginBottom: 8,
								}}
							>
								AGING SUMMARY (KES)
							</h4>
							<div
								className="d-flex justify-content-between mb-1"
								style={{ fontSize: 13 }}
							>
								<span>Current (Not Due)</span>
								<strong>1,250,000</strong>
							</div>
							<div className={cx(s.progress, "mb-2")}>
								<div
									className={s.progressBar}
									style={{ width: "50%", background: "var(--pm-accent)" }}
								></div>
							</div>
							<div
								className="d-flex justify-content-between mb-1"
								style={{ fontSize: 13 }}
							>
								<span>1-30 Days Past Due</span>
								<strong>845,000</strong>
							</div>
							<div className={cx(s.progress, "mb-2")}>
								<div
									className={s.progressBar}
									style={{ width: "35%", background: "var(--pm-warning)" }}
								></div>
							</div>
							<div
								className="d-flex justify-content-between mb-1"
								style={{ fontSize: 13 }}
							>
								<span>31-60 Days Past Due</span>
								<strong>210,000</strong>
							</div>
							<div className={cx(s.progress, "mb-2")}>
								<div
									className={s.progressBar}
									style={{ width: "10%", background: "var(--pm-danger)" }}
								></div>
							</div>
							<div
								className="d-flex justify-content-between mb-1"
								style={{ fontSize: 13 }}
							>
								<span>60+ Days (Disputed)</span>
								<strong>145,000</strong>
							</div>
							<div className={s.progress}>
								<div
									className={s.progressBar}
									style={{ width: "5%", background: "var(--pm-ink)" }}
								></div>
							</div>
						</div>
						<div className="d-flex gap-2 mt-3">
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm, "w-100")}
								onClick={() => onOpen("payableAgingModal")}
							>
								Full Aging Report
							</button>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm, "w-100")}
								onClick={() => onOpen("exportApReportModal")}
							>
								<i className="bi bi-download"></i>Export
							</button>
						</div>
					</div>
				</div>
			</div>
		</>
	);
}
