/* ============================================================================
 * OpenBankingBody.tsx — the page body, ported verbatim from 3.10.html.
 * ----------------------------------------------------------------------------
 * AUTO-GENERATED by port_page_bodies.py — regenerate rather than hand-edit.
 *
 * WHY THIS EXISTS
 * The first React port of this page paraphrased the original instead of
 * converting it: cards and whole numbered sections were absent and the tables
 * carried invented columns and rows. This file is a faithful conversion of the
 * source `<div class="pm-content">` of 3.10.html, so every card, table row
 * and figure matches the original layout.
 *
 * BRIDGES APPLIED
 *   class=            -> className=
 *   style="a:b"       -> style={{ a: "b" }}
 *   openModal('x')    -> onOpen('x')   (the page's setActiveModal)
 *   other onclick=    -> onAction()    (toast / no-op, never a dead button)
 *   every <td>        -> gains data-label from its column header, which the
 *                        responsive CSS uses to render tables as cards <=768px
 * ========================================================================== */
import styles from "../styles/open-banking.module.css";

const s = styles as Record<string, string>;
const cx = (...c: (string | false | undefined)[]) =>
	c.filter(Boolean).join(" ");

interface Props {
	/** Opens a modal by id — the page's setActiveModal. */
	onOpen: (id: string) => void;
	/** Fallback for legacy buttons that only fired a toast. */
	onAction?: () => void;
}

export default function OpenBankingBody({ onOpen, onAction }: Props) {
	const act = onAction ?? (() => undefined);
	return (
		<>
			<div className="row g-3">
				<div className="col-lg-4">
					<div className={cx(s.card, s.cardAccent)} style={{ minHeight: 170 }}>
						<p
							style={{
								margin: 0,
								fontSize: 12,
								color: "rgba(255,255,255,.78)",
							}}
						>
							Open banking hub live <span style={{ color: "#86efac" }}>●</span>
						</p>
						<div className={s.sv} style={{ margin: "8px 0", color: "#fff" }}>
							7 bank accounts connected
						</div>
						<p
							style={{
								margin: 0,
								fontSize: 12,
								color: "rgba(255,255,255,.78)",
							}}
						>
							Equity, KCB, Co-op, Stanbic, Family, NCBA, I&M — consolidated view
							across all business and personal accounts.
						</p>
						<div className="d-flex flex-wrap mt-3" style={{ gap: 8 }}>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								style={{
									background: "rgba(255,255,255,.12)",
									borderColor: "rgba(255,255,255,.22)",
									color: "#fff",
								}}
								onClick={() => onOpen("connectBankModal")}
							>
								Connect
							</button>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								style={{
									background: "rgba(255,255,255,.12)",
									borderColor: "rgba(255,255,255,.22)",
									color: "#fff",
								}}
								onClick={() => onOpen("transferModal")}
							>
								Transfer
							</button>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								style={{
									background: "rgba(255,255,255,.12)",
									borderColor: "rgba(255,255,255,.22)",
									color: "#fff",
								}}
								onClick={() => onOpen("reconcileModal")}
							>
								Reconcile
							</button>
						</div>
					</div>
				</div>
				<div className="col-lg-2 col-md-4 col-6">
					<div className={s.card} style={{ minHeight: 170 }}>
						<p className={s.sl} style={{ color: "var(--pm-accent)" }}>
							TOTAL CASH POSITION
						</p>
						<div className={s.sv} style={{ margin: "6px 0" }}>
							KES 18.7M
						</div>
						<span className={cx(s.badge, s.badgeS)}>
							<i className="bi bi-graph-up"></i>+12.4% MoM
						</span>
						<div
							className="mt-2"
							style={{ fontSize: 12, color: "var(--pm-ink-soft)" }}
						>
							Available: KES 14.2M
							<br />
							Pending: KES 4.5M
						</div>
					</div>
				</div>
				<div className="col-lg-3 col-md-4 col-6">
					<div className={s.card} style={{ minHeight: 170 }}>
						<p className={s.sl} style={{ color: "var(--pm-info)" }}>
							INSTANT TRANSFERS (MTD)
						</p>
						<div className={s.sv} style={{ margin: "6px 0" }}>
							KES 41.2M
						</div>
						<span className={cx(s.badge, s.badgeI)}>
							<i className="bi bi-lightning-charge"></i>186 transfers
						</span>
						<div
							className="mt-2"
							style={{ fontSize: 12, color: "var(--pm-ink-soft)" }}
						>
							Avg settlement: 12 seconds
							<br />
							Success rate: 99.7%
						</div>
					</div>
				</div>
				<div className="col-lg-3 col-md-4">
					<div
						className={s.card}
						style={{
							minHeight: 170,
							borderLeft: "3px solid var(--pm-warning)",
						}}
					>
						<p className={s.sl} style={{ color: "var(--pm-warning)" }}>
							RECONCILIATION STATUS
						</p>
						<div className={s.sv} style={{ margin: "6px 0" }}>
							94.8%
						</div>
						<span className={cx(s.badge, s.badgeW)}>
							<i className="bi bi-exclamation-triangle"></i>14 exceptions
						</span>
						<div
							className="mt-2"
							style={{ fontSize: 12, color: "var(--pm-ink-soft)" }}
						>
							Auto-matched: 412
							<br />
							Manual review: 14
						</div>
					</div>
				</div>
			</div>
			<div className="row g-3">
				<div className="col-lg-4">
					<div className={s.card}>
						<div className="d-flex justify-content-between align-items-center mb-3">
							<h3 className={s.st}>Attention Required</h3>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								onClick={() => onOpen("attentionModal")}
							>
								View all
							</button>
						</div>
						<div className={s.statusRow}>
							<div className="d-flex align-items-center gap-3">
								<div
									style={{
										width: 36,
										height: 36,
										borderRadius: "50%",
										background: "var(--pm-danger-soft)",
										color: "var(--pm-danger)",
										display: "flex",
										alignItems: "center",
										justifyContent: "center",
										fontSize: 14,
										flexShrink: 0,
									}}
								>
									<i className="bi bi-bank"></i>
								</div>
								<div>
									<div style={{ fontWeight: 600, fontSize: 13 }}>
										KCB account balance below minimum{" "}
									</div>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										KES 42,100 · minimum KES 50,000
									</div>
								</div>
							</div>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								onClick={() => onOpen("transferModal")}
							>
								Top-up
							</button>
						</div>
						<div className={s.statusRow}>
							<div className="d-flex align-items-center gap-3">
								<div
									style={{
										width: 36,
										height: 36,
										borderRadius: "50%",
										background: "var(--pm-warning-soft)",
										color: "var(--pm-warning)",
										display: "flex",
										alignItems: "center",
										justifyContent: "center",
										fontSize: 14,
										flexShrink: 0,
									}}
								>
									<i className="bi bi-list-check"></i>
								</div>
								<div>
									<div style={{ fontWeight: 600, fontSize: 13 }}>
										14 unreconciled transactions
									</div>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										Equity & Stanbic accounts{" "}
									</div>
								</div>
							</div>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								onClick={() => onOpen("reconcileModal")}
							>
								Review
							</button>
						</div>
						<div className={s.statusRow}>
							<div className="d-flex align-items-center gap-3">
								<div
									style={{
										width: 36,
										height: 36,
										borderRadius: "50%",
										background: "var(--pm-info-soft)",
										color: "var(--pm-info)",
										display: "flex",
										alignItems: "center",
										justifyContent: "center",
										fontSize: 14,
										flexShrink: 0,
									}}
								>
									<i className="bi bi-clock"></i>
								</div>
								<div>
									<div style={{ fontWeight: 600, fontSize: 13 }}>
										Co-op account link expires in 7 days{" "}
									</div>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										Re-authenticate consent
									</div>
								</div>
							</div>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								onClick={() => onOpen("reauthModal")}
							>
								Re-auth
							</button>
						</div>
					</div>
				</div>
				<div className="col-lg-4">
					<div className={s.card}>
						<div className="d-flex justify-content-between align-items-center mb-3">
							<h3 className={s.st}>Smart Suggestions</h3>
							<span className={cx(s.badge, s.badgeP)}>
								<i className="bi bi-stars"></i>AI
							</span>
						</div>
						<div className={s.statusRow}>
							<div className="d-flex align-items-center gap-3">
								<div
									style={{
										width: 36,
										height: 36,
										borderRadius: "50%",
										background: "var(--pm-accent-soft)",
										color: "var(--pm-accent)",
										display: "flex",
										alignItems: "center",
										justifyContent: "center",
										fontSize: 14,
										flexShrink: 0,
									}}
								>
									<i className="bi bi-graph-up"></i>
								</div>
								<div>
									<div style={{ fontWeight: 600, fontSize: 13 }}>
										Consolidate 3 low-activity accounts{" "}
									</div>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										Potential fee savings: KES 18,200/year
									</div>
								</div>
							</div>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								onClick={() => onOpen("optimizeModal")}
							>
								Analyse
							</button>
						</div>
						<div className={s.statusRow}>
							<div className="d-flex align-items-center gap-3">
								<div
									style={{
										width: 36,
										height: 36,
										borderRadius: "50%",
										background: "var(--pm-warning-soft)",
										color: "var(--pm-warning)",
										display: "flex",
										alignItems: "center",
										justifyContent: "center",
										fontSize: 14,
										flexShrink: 0,
									}}
								>
									<i className="bi bi-clock-history"></i>
								</div>
								<div>
									<div style={{ fontWeight: 600, fontSize: 13 }}>
										Schedule recurring transfers to payroll account
									</div>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										Reduce manual effort by 92%{" "}
									</div>
								</div>
							</div>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								onClick={() => onOpen("scheduleTransferModal")}
							>
								Setup
							</button>
						</div>
						<div className={s.statusRow}>
							<div className="d-flex align-items-center gap-3">
								<div
									style={{
										width: 36,
										height: 36,
										borderRadius: "50%",
										background: "var(--pm-purple-soft)",
										color: "var(--pm-purple)",
										display: "flex",
										alignItems: "center",
										justifyContent: "center",
										fontSize: 14,
										flexShrink: 0,
									}}
								>
									<i className="bi bi-shield-check"></i>
								</div>
								<div>
									<div style={{ fontWeight: 600, fontSize: 13 }}>
										Enable real-time fraud alerts on I&M{" "}
									</div>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										High-value transfers detected{" "}
									</div>
								</div>
							</div>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								onClick={() => onOpen("fraudSettingsModal")}
							>
								Enable
							</button>
						</div>
					</div>
				</div>
				<div className="col-lg-4">
					<div className={s.card}>
						<div className="mb-3">
							<h3 className={s.st}>Quick Actions</h3>
							<p className={s.ss}>Frequent open banking workflows</p>
						</div>
						<div className={s.quickGrid}>
							<button
								type="button"
								className={s.quickBtn}
								onClick={() => onOpen("transferModal")}
							>
								<i className="bi bi-arrow-left-right text-primary me-1"></i>
								Instant Transfer
							</button>
							<button
								type="button"
								className={s.quickBtn}
								onClick={() => onOpen("connectBankModal")}
							>
								<i className="bi bi-plus-circle text-success me-1"></i>Link
								Account
							</button>
							<button
								type="button"
								className={s.quickBtn}
								onClick={() => onOpen("reconcileModal")}
							>
								<i className="bi bi-list-check text-info me-1"></i>Reconcile
							</button>
							<button
								type="button"
								className={s.quickBtn}
								onClick={() => onOpen("cashFlowModal")}
							>
								<i
									className="bi bi-graph-up me-1"
									style={{ color: "var(--pm-purple)" }}
								></i>
								Cash Flow
							</button>
							<button
								type="button"
								className={s.quickBtn}
								onClick={() => onOpen("exportStatementModal")}
							>
								<i className="bi bi-download text-muted me-1"></i>Export
							</button>
							<button
								type="button"
								className={s.quickBtn}
								onClick={() => onOpen("scheduleTransferModal")}
							>
								<i
									className="bi bi-calendar-event me-1"
									style={{ color: "var(--pm-accent)" }}
								></i>
								Schedule
							</button>
							<button
								type="button"
								className={s.quickBtn}
								onClick={() => onOpen("fraudSettingsModal")}
							>
								<i className="bi bi-shield-exclamation text-danger me-1"></i>
								Fraud Alerts
							</button>
							<button
								type="button"
								className={s.quickBtn}
								onClick={() => onOpen("manageLinksModal")}
							>
								<i className="bi bi-link-45deg text-warning me-1"></i>Manage
								Links
							</button>
						</div>
					</div>
				</div>
			</div>
			<div className={s.card}>
				<div
					className="d-flex justify-content-between align-items-center mb-3 flex-wrap"
					style={{ gap: 8 }}
				>
					<div>
						<h3 className={s.st}>
							<i
								className="bi bi-bank2"
								style={{ color: "var(--pm-primary)" }}
							></i>
							Connected Bank Accounts & Consolidated Cash Position
						</h3>
						<p className={s.ss}>
							All linked bank accounts with real-time balances, consolidated
							view, and instant PesaLink transfer capability.
						</p>
					</div>
					<div className="d-flex" style={{ gap: 8 }}>
						<button
							type="button"
							className={cx(s.btnPm, s.btnSm)}
							onClick={() => onOpen("connectBankModal")}
						>
							<i className="bi bi-plus-lg"></i>Link Bank
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnSm)}
							onClick={() => onOpen("manageLinksModal")}
						>
							<i className="bi bi-gear"></i>Manage
						</button>
					</div>
				</div>
				<div className="row g-3">
					<div className="col-lg-8">
						<div className={s.utilityBlock}>
							<h4 style={{ fontSize: 14, fontWeight: 700, margin: "0 0 16px" }}>
								Linked Bank Accounts
							</h4>
							<div className="table-responsive">
								<table className={s.tbl}>
									<thead>
										<tr>
											<th>Bank</th>
											<th>Account</th>
											<th>Nickname</th>
											<th>Balance</th>
											<th>Last Sync</th>
											<th>Status</th>
											<th>Actions</th>
										</tr>
									</thead>
									<tbody>
										<tr>
											<td data-label="Bank">
												<strong>Equity Bank</strong>
											</td>
											<td data-label="Account">***4521</td>
											<td data-label="Nickname">Operating Account</td>
											<td data-label="Balance">
												<strong>KES 6,842,100</strong>
											</td>
											<td data-label="Last Sync">Just now</td>
											<td data-label="Status">
												<span className={cx(s.badge, s.badgeS)}>Live</span>
											</td>
											<td data-label="Actions">
												<div className="d-flex" style={{ gap: 4 }}>
													<button
														type="button"
														className={cx(s.btnPm, s.btnSm)}
														onClick={() => onOpen("transferModal")}
													>
														Transfer
													</button>
													<button
														type="button"
														className={cx(s.btnPm, s.btnSm)}
														onClick={() => onOpen("accountDetailModal")}
													>
														View
													</button>
												</div>
											</td>
										</tr>
										<tr>
											<td data-label="Bank">
												<strong>KCB Bank</strong>
											</td>
											<td data-label="Account">***7782</td>
											<td data-label="Nickname">Payroll Account</td>
											<td data-label="Balance">
												<strong>KES 2,104,550</strong>
											</td>
											<td data-label="Last Sync">Just now</td>
											<td data-label="Status">
												<span className={cx(s.badge, s.badgeS)}>Live</span>
											</td>
											<td data-label="Actions">
												<div className="d-flex" style={{ gap: 4 }}>
													<button
														type="button"
														className={cx(s.btnPm, s.btnSm)}
														onClick={() => onOpen("transferModal")}
													>
														Transfer
													</button>
													<button
														type="button"
														className={cx(s.btnPm, s.btnSm)}
														onClick={() => onOpen("accountDetailModal")}
													>
														View
													</button>
												</div>
											</td>
										</tr>
										<tr>
											<td data-label="Bank">
												<strong>Co-op Bank</strong>
											</td>
											<td data-label="Account">***3390</td>
											<td data-label="Nickname">Collections Account</td>
											<td data-label="Balance">
												<strong>KES 4,892,300</strong>
											</td>
											<td data-label="Last Sync">2 min ago</td>
											<td data-label="Status">
												<span className={cx(s.badge, s.badgeS)}>Live</span>
											</td>
											<td data-label="Actions">
												<div className="d-flex" style={{ gap: 4 }}>
													<button
														type="button"
														className={cx(s.btnPm, s.btnSm)}
														onClick={() => onOpen("transferModal")}
													>
														Transfer
													</button>
													<button
														type="button"
														className={cx(s.btnPm, s.btnSm)}
														onClick={() => onOpen("accountDetailModal")}
													>
														View
													</button>
												</div>
											</td>
										</tr>
										<tr>
											<td data-label="Bank">
												<strong>Stanbic Bank</strong>
											</td>
											<td data-label="Account">***9912</td>
											<td data-label="Nickname">Project Account</td>
											<td data-label="Balance">
												<strong>KES 1,204,750</strong>
											</td>
											<td data-label="Last Sync">5 min ago</td>
											<td data-label="Status">
												<span className={cx(s.badge, s.badgeS)}>Live</span>
											</td>
											<td data-label="Actions">
												<div className="d-flex" style={{ gap: 4 }}>
													<button
														type="button"
														className={cx(s.btnPm, s.btnSm)}
														onClick={() => onOpen("transferModal")}
													>
														Transfer
													</button>
													<button
														type="button"
														className={cx(s.btnPm, s.btnSm)}
														onClick={() => onOpen("accountDetailModal")}
													>
														View
													</button>
												</div>
											</td>
										</tr>
										<tr>
											<td data-label="Bank">
												<strong>Family Bank</strong>
											</td>
											<td data-label="Account">***5543</td>
											<td data-label="Nickname">Reserve Fund</td>
											<td data-label="Balance">
												<strong>KES 3,200,000</strong>
											</td>
											<td data-label="Last Sync">12 min ago</td>
											<td data-label="Status">
												<span className={cx(s.badge, s.badgeW)}>Syncing</span>
											</td>
											<td data-label="Actions">
												<div className="d-flex" style={{ gap: 4 }}>
													<button
														type="button"
														className={cx(s.btnPm, s.btnSm)}
														onClick={() => onOpen("reauthModal")}
													>
														Re-auth
													</button>
													<button
														type="button"
														className={cx(s.btnPm, s.btnSm)}
														onClick={() => onOpen("accountDetailModal")}
													>
														View
													</button>
												</div>
											</td>
										</tr>
										<tr>
											<td data-label="Bank">
												<strong>NCBA Bank</strong>
											</td>
											<td data-label="Account">***1128</td>
											<td data-label="Nickname">Client Escrow</td>
											<td data-label="Balance">
												<strong>KES 420,180</strong>
											</td>
											<td data-label="Last Sync">1 hr ago</td>
											<td data-label="Status">
												<span className={cx(s.badge, s.badgeS)}>Live</span>
											</td>
											<td data-label="Actions">
												<div className="d-flex" style={{ gap: 4 }}>
													<button
														type="button"
														className={cx(s.btnPm, s.btnSm)}
														onClick={() => onOpen("transferModal")}
													>
														Transfer
													</button>
													<button
														type="button"
														className={cx(s.btnPm, s.btnSm)}
														onClick={() => onOpen("accountDetailModal")}
													>
														View
													</button>
												</div>
											</td>
										</tr>
										<tr>
											<td data-label="Bank">
												<strong>I&M Bank</strong>
											</td>
											<td data-label="Account">***6674</td>
											<td data-label="Nickname">Investment Account</td>
											<td data-label="Balance">
												<strong>KES 89,450</strong>
											</td>
											<td data-label="Last Sync">3 hr ago</td>
											<td data-label="Status">
												<span className={cx(s.badge, s.badgeS)}>Live</span>
											</td>
											<td data-label="Actions">
												<div className="d-flex" style={{ gap: 4 }}>
													<button
														type="button"
														className={cx(s.btnPm, s.btnSm)}
														onClick={() => onOpen("transferModal")}
													>
														Transfer
													</button>
													<button
														type="button"
														className={cx(s.btnPm, s.btnSm)}
														onClick={() => onOpen("accountDetailModal")}
													>
														View
													</button>
												</div>
											</td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
					</div>
					<div className="col-lg-4">
						<div className={s.utilityBlock}>
							<h4 style={{ fontSize: 14, fontWeight: 700, margin: "0 0 16px" }}>
								Consolidated Position
							</h4>
							<div
								className="p-3 rounded mb-3"
								style={{ background: "var(--pm-accent-soft)" }}
							>
								<div
									style={{ fontSize: 11, color: "#047857", fontWeight: 700 }}
								>
									TOTAL AVAILABLE CASH
								</div>
								<div
									style={{
										fontSize: 28,
										fontWeight: 700,
										color: "var(--pm-accent)",
									}}
								>
									KES 14.2M
								</div>
							</div>
							<div
								className="p-3 rounded mb-3"
								style={{ background: "var(--pm-info-soft)" }}
							>
								<div
									style={{ fontSize: 11, color: "#1D4ED8", fontWeight: 700 }}
								>
									PENDING SETTLEMENTS
								</div>
								<div
									style={{
										fontSize: 28,
										fontWeight: 700,
										color: "var(--pm-info)",
									}}
								>
									KES 4.5M
								</div>
							</div>
							<div
								className="p-3 rounded"
								style={{ background: "var(--pm-surface)" }}
							>
								<div
									style={{
										fontSize: 11,
										color: "var(--pm-muted)",
										fontWeight: 700,
									}}
								>
									7-DAY FORECAST{" "}
								</div>
								<div
									style={{
										fontSize: 22,
										fontWeight: 700,
										color: "var(--pm-primary)",
									}}
								>
									KES 22.1M
								</div>
								<div style={{ fontSize: 12, color: "var(--pm-ink-soft)" }}>
									Expected inflows: KES 8.3M{" "}
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div className={s.card}>
				<div
					className="d-flex justify-content-between align-items-center mb-3 flex-wrap"
					style={{ gap: 8 }}
				>
					<div>
						<h3 className={s.st}>
							<i
								className="bi bi-arrow-left-right"
								style={{ color: "var(--pm-accent)" }}
							></i>
							Instant Transfers, Standing Orders & Scheduled Payments
						</h3>
						<p className={s.ss}>
							Execute real-time PesaLink transfers, create recurring payment
							schedules, and manage standing orders across all linked banks.
						</p>
					</div>
					<div className="d-flex" style={{ gap: 8 }}>
						<button
							type="button"
							className={cx(s.btnPm, s.btnSm)}
							onClick={() => onOpen("transferModal")}
						>
							<i className="bi bi-send"></i>New Transfer
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnSm)}
							onClick={() => onOpen("scheduleTransferModal")}
						>
							<i className="bi bi-clock"></i>Schedule
						</button>
					</div>
				</div>
				<div className="row g-3">
					<div className="col-lg-5">
						<div className={s.utilityBlock}>
							<h4 style={{ fontSize: 14, fontWeight: 700, margin: "0 0 16px" }}>
								Recent Transfers
							</h4>
							<div className="table-responsive">
								<table className={s.tbl}>
									<thead>
										<tr>
											<th>Date</th>
											<th>From → To</th>
											<th>Amount</th>
											<th>Status</th>
											<th>Ref</th>
										</tr>
									</thead>
									<tbody>
										<tr>
											<td data-label="Date">27 Jun 14:32</td>
											<td data-label="From → To">Equity → KCB</td>
											<td data-label="Amount">
												<strong>KES 850,000</strong>
											</td>
											<td data-label="Status">
												<span className={cx(s.badge, s.badgeS)}>Instant</span>
											</td>
											<td data-label="Ref">PL-442189</td>
										</tr>
										<tr>
											<td data-label="Date">27 Jun 11:04</td>
											<td data-label="From → To">Co-op → Equity</td>
											<td data-label="Amount">
												<strong>KES 1,200,000</strong>
											</td>
											<td data-label="Status">
												<span className={cx(s.badge, s.badgeS)}>Instant</span>
											</td>
											<td data-label="Ref">PL-442155</td>
										</tr>
										<tr>
											<td data-label="Date">26 Jun 16:55</td>
											<td data-label="From → To">Stanbic → NCBA</td>
											<td data-label="Amount">
												<strong>KES 320,000</strong>
											</td>
											<td data-label="Status">
												<span className={cx(s.badge, s.badgeS)}>Instant</span>
											</td>
											<td data-label="Ref">PL-441902</td>
										</tr>
										<tr>
											<td data-label="Date">26 Jun 09:12</td>
											<td data-label="From → To">Equity → Family</td>
											<td data-label="Amount">
												<strong>KES 500,000</strong>
											</td>
											<td data-label="Status">
												<span className={cx(s.badge, s.badgeI)}>Pending</span>
											</td>
											<td data-label="Ref">PL-441784</td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
					</div>
					<div className="col-lg-4">
						<div className={s.utilityBlock}>
							<h4 style={{ fontSize: 14, fontWeight: 700, margin: "0 0 16px" }}>
								Standing Orders
							</h4>
							<div className={s.statusRow}>
								<div>
									<strong>Payroll to KCB</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										KES 2.4M • Every 25th
									</div>
								</div>
								<button
									type="button"
									className={cx(s.btnPm, s.btnSm)}
									onClick={() => onOpen("scheduleTransferModal")}
								>
									Edit
								</button>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Rent to NCBA</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										KES 185K • Monthly 1st
									</div>
								</div>
								<button
									type="button"
									className={cx(s.btnPm, s.btnSm)}
									onClick={() => onOpen("scheduleTransferModal")}
								>
									Edit
								</button>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Utilities to Equity</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										KES 320K • Auto
									</div>
								</div>
								<button
									type="button"
									className={cx(s.btnPm, s.btnSm)}
									onClick={() => onOpen("scheduleTransferModal")}
								>
									Edit
								</button>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Insurance to Stanbic</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										KES 92K • Quarterly
									</div>
								</div>
								<button
									type="button"
									className={cx(s.btnPm, s.btnSm)}
									onClick={() => onOpen("scheduleTransferModal")}
								>
									Edit
								</button>
							</div>
						</div>
					</div>
					<div className="col-lg-3">
						<div className={s.utilityBlock}>
							<h4 style={{ fontSize: 14, fontWeight: 700, margin: "0 0 16px" }}>
								Quick Transfer
							</h4>
							<div className="mb-3">
								<label className={s.formLabel}>From</label>
								<select className={s.formControl}>
									<option>Equity ****4521</option>
									<option>Co-op ****3390</option>
									<option>Stanbic ****9912</option>
								</select>
							</div>
							<div className="mb-3">
								<label className={s.formLabel}>To</label>
								<select className={s.formControl}>
									<option>KCB ****7782</option>
									<option>NCBA ****1128</option>
									<option>Family ****5543</option>
								</select>
							</div>
							<div className="mb-3">
								<label className={s.formLabel}>Amount (KES)</label>
								<input className={s.formControl} defaultValue="500000" />
							</div>
							<button
								type="button"
								className={cx(s.btnPm, s.btnPmP, "w-100")}
								onClick={() => onOpen("transferModal")}
							>
								Send Now
							</button>
						</div>
					</div>
				</div>
			</div>
			<div className={s.card}>
				<div
					className="d-flex justify-content-between align-items-center mb-3 flex-wrap"
					style={{ gap: 8 }}
				>
					<div>
						<h3 className={s.st}>
							<i
								className="bi bi-list-check"
								style={{ color: "var(--pm-info)" }}
							></i>
							Transaction History, Reconciliation & Matching Engine
						</h3>
						<p className={s.ss}>
							Multi-bank transaction feed, auto-reconciliation engine, exception
							handling, and audit-ready reports.
						</p>
					</div>
					<div className="d-flex" style={{ gap: 8 }}>
						<button
							type="button"
							className={cx(s.btnPm, s.btnSm)}
							onClick={() => onOpen("reconcileModal")}
						>
							<i className="bi bi-list-check"></i>Reconcile
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnSm)}
							onClick={() => onOpen("exportStatementModal")}
						>
							<i className="bi bi-download"></i>Export
						</button>
					</div>
				</div>
				<div className="row g-3">
					<div className="col-lg-8">
						<div className={s.utilityBlock}>
							<h4 style={{ fontSize: 14, fontWeight: 700, margin: "0 0 16px" }}>
								Multi-Bank Transaction Feed{" "}
							</h4>
							<div className="table-responsive">
								<table className={s.tbl}>
									<thead>
										<tr>
											<th>Date</th>
											<th>Bank</th>
											<th>Description</th>
											<th>Amount</th>
											<th>Match Status</th>
											<th>Action</th>
										</tr>
									</thead>
									<tbody>
										<tr>
											<td data-label="Date">27 Jun</td>
											<td data-label="Bank">Equity</td>
											<td data-label="Description">Client payment - ABC Ltd</td>
											<td data-label="Amount">
												<strong>+KES 1,850,000</strong>
											</td>
											<td data-label="Match Status">
												<span className={cx(s.badge, s.badgeS)}>Matched</span>
											</td>
											<td data-label="Action">
												<button
													type="button"
													className={cx(s.btnPm, s.btnSm)}
													onClick={() => onOpen("matchDetailModal")}
												>
													View
												</button>
											</td>
										</tr>
										<tr>
											<td data-label="Date">27 Jun</td>
											<td data-label="Bank">Co-op</td>
											<td data-label="Description">
												Supplier payment - XYZ Traders
											</td>
											<td data-label="Amount">
												<strong>-KES 420,000</strong>
											</td>
											<td data-label="Match Status">
												<span className={cx(s.badge, s.badgeS)}>Matched</span>
											</td>
											<td data-label="Action">
												<button
													type="button"
													className={cx(s.btnPm, s.btnSm)}
													onClick={() => onOpen("matchDetailModal")}
												>
													View
												</button>
											</td>
										</tr>
										<tr>
											<td data-label="Date">26 Jun</td>
											<td data-label="Bank">Stanbic</td>
											<td data-label="Description">Unknown credit</td>
											<td data-label="Amount">
												<strong>+KES 85,000</strong>
											</td>
											<td data-label="Match Status">
												<span className={cx(s.badge, s.badgeW)}>Unmatched</span>
											</td>
											<td data-label="Action">
												<button
													type="button"
													className={cx(s.btnPm, s.btnSm)}
													onClick={() => onOpen("reconcileModal")}
												>
													Match
												</button>
											</td>
										</tr>
										<tr>
											<td data-label="Date">26 Jun</td>
											<td data-label="Bank">KCB</td>
											<td data-label="Description">Payroll transfer</td>
											<td data-label="Amount">
												<strong>-KES 2,400,000</strong>
											</td>
											<td data-label="Match Status">
												<span className={cx(s.badge, s.badgeS)}>Matched</span>
											</td>
											<td data-label="Action">
												<button
													type="button"
													className={cx(s.btnPm, s.btnSm)}
													onClick={() => onOpen("matchDetailModal")}
												>
													View
												</button>
											</td>
										</tr>
										<tr>
											<td data-label="Date">25 Jun</td>
											<td data-label="Bank">Family</td>
											<td data-label="Description">Duplicate entry</td>
											<td data-label="Amount">
												<strong>+KES 150,000</strong>
											</td>
											<td data-label="Match Status">
												<span className={cx(s.badge, s.badgeD)}>Exception</span>
											</td>
											<td data-label="Action">
												<button
													type="button"
													className={cx(s.btnPm, s.btnSm)}
													onClick={() => onOpen("exceptionModal")}
												>
													Resolve
												</button>
											</td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
					</div>
					<div className="col-lg-4">
						<div className={s.utilityBlock}>
							<h4 style={{ fontSize: 14, fontWeight: 700, margin: "0 0 16px" }}>
								Reconciliation Summary
							</h4>
							<div
								className="p-3 rounded mb-3"
								style={{ background: "var(--pm-accent-soft)" }}
							>
								<div
									style={{ fontSize: 11, color: "#047857", fontWeight: 700 }}
								>
									AUTO-MATCHED
								</div>
								<div
									style={{
										fontSize: 24,
										fontWeight: 700,
										color: "var(--pm-accent)",
									}}
								>
									412 txns
								</div>
								<div style={{ fontSize: 12, color: "#065F46" }}>KES 38.4M</div>
							</div>
							<div
								className="p-3 rounded mb-3"
								style={{ background: "var(--pm-warning-soft)" }}
							>
								<div
									style={{ fontSize: 11, color: "#B45309", fontWeight: 700 }}
								>
									UNMATCHED
								</div>
								<div
									style={{
										fontSize: 24,
										fontWeight: 700,
										color: "var(--pm-warning)",
									}}
								>
									14 txns
								</div>
								<div style={{ fontSize: 12, color: "#92400E" }}>
									KES 235,000
								</div>
							</div>
							<div
								className="p-3 rounded"
								style={{ background: "var(--pm-info-soft)" }}
							>
								<div
									style={{ fontSize: 11, color: "#1D4ED8", fontWeight: 700 }}
								>
									EXCEPTIONS
								</div>
								<div
									style={{
										fontSize: 24,
										fontWeight: 700,
										color: "var(--pm-info)",
									}}
								>
									3 txns
								</div>
								<div style={{ fontSize: 12, color: "#1E40AF" }}>
									KES 150,000
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div className={s.card}>
				<div
					className="d-flex justify-content-between align-items-center mb-3 flex-wrap"
					style={{ gap: 8 }}
				>
					<div>
						<h3 className={s.st}>
							<i
								className="bi bi-graph-up-arrow"
								style={{ color: "var(--pm-purple)" }}
							></i>
							Cash Flow Analytics, Forecasting & Bank Performance
						</h3>
						<p className={s.ss}>
							Multi-bank cash flow trends, 90-day forecasts, bank performance
							benchmarking, and liquidity risk indicators.
						</p>
					</div>
					<div className="d-flex" style={{ gap: 8 }}>
						<button
							type="button"
							className={cx(s.btnPm, s.btnSm)}
							onClick={() => onOpen("cashFlowModal")}
						>
							<i className="bi bi-graph-up"></i>Forecast
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnSm)}
							onClick={() => onOpen("bankBenchmarkModal")}
						>
							<i className="bi bi-bar-chart"></i>Benchmark
						</button>
					</div>
				</div>
				<div className="row g-3">
					<div className="col-lg-5">
						<div className={s.utilityBlock}>
							<h4 style={{ fontSize: 14, fontWeight: 700, margin: "0 0 16px" }}>
								90-Day Cash Flow Forecast{" "}
							</h4>
							<div className={s.chartBars}>
								<div
									className={s.chartBar}
									style={{ height: "55%", background: "var(--pm-info)" }}
								>
									<span className={s.barLabel}>W1</span>
								</div>
								<div
									className={s.chartBar}
									style={{ height: "68%", background: "var(--pm-info)" }}
								>
									<span className={s.barLabel}>W2</span>
								</div>
								<div
									className={s.chartBar}
									style={{ height: "82%", background: "var(--pm-warning)" }}
								>
									<span className={s.barLabel}>W3</span>
								</div>
								<div
									className={s.chartBar}
									style={{ height: "74%", background: "var(--pm-info)" }}
								>
									<span className={s.barLabel}>W4</span>
								</div>
								<div
									className={s.chartBar}
									style={{ height: "90%", background: "var(--pm-primary)" }}
								>
									<span className={s.barLabel}>W5</span>
								</div>
								<div
									className={s.chartBar}
									style={{ height: "65%", background: "var(--pm-accent)" }}
								>
									<span className={s.barLabel}>W6</span>
								</div>
								<div
									className={s.chartBar}
									style={{ height: "78%", background: "var(--pm-primary)" }}
								>
									<span className={s.barLabel}>W7</span>
								</div>
								<div
									className={s.chartBar}
									style={{ height: "85%", background: "var(--pm-info)" }}
								>
									<span className={s.barLabel}>W8</span>
								</div>
								<div
									className={s.chartBar}
									style={{ height: "72%", background: "var(--pm-accent)" }}
								>
									<span className={s.barLabel}>W9</span>
								</div>
								<div
									className={s.chartBar}
									style={{ height: "95%", background: "var(--pm-primary)" }}
								>
									<span className={s.barLabel}>W10</span>
								</div>
								<div
									className={s.chartBar}
									style={{ height: "60%", background: "var(--pm-info)" }}
								>
									<span className={s.barLabel}>W11</span>
								</div>
								<div
									className={s.chartBar}
									style={{ height: "88%", background: "var(--pm-accent)" }}
								>
									<span className={s.barLabel}>W12</span>
								</div>
							</div>
							<div
								className="d-flex flex-wrap mt-3"
								style={{ gap: 12, fontSize: 11 }}
							>
								<span>
									<span
										style={{
											display: "inline-block",
											width: 8,
											height: 8,
											borderRadius: "50%",
											background: "var(--pm-primary)",
											marginRight: 4,
										}}
									></span>
									Inflows
								</span>
								<span>
									<span
										style={{
											display: "inline-block",
											width: 8,
											height: 8,
											borderRadius: "50%",
											background: "var(--pm-accent)",
											marginRight: 4,
										}}
									></span>
									Outflows
								</span>
								<span>
									<span
										style={{
											display: "inline-block",
											width: 8,
											height: 8,
											borderRadius: "50%",
											background: "var(--pm-warning)",
											marginRight: 4,
										}}
									></span>
									Peak
								</span>
							</div>
						</div>
					</div>
					<div className="col-lg-4">
						<div className={s.utilityBlock}>
							<h4 style={{ fontSize: 14, fontWeight: 700, margin: "0 0 16px" }}>
								Bank Performance
							</h4>
							<div className={s.statusRow}>
								<div>
									<strong>Equity Bank</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										Fastest settlement • 8s avg{" "}
									</div>
								</div>
								<span className={cx(s.badge, s.badgeS)}>Best</span>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Co-op Bank</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										Highest volume • KES 18.2M{" "}
									</div>
								</div>
								<span className={cx(s.badge, s.badgeS)}>Top</span>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>KCB Bank</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										Lowest fee • KES 0
									</div>
								</div>
								<span className={cx(s.badge, s.badgeI)}>Good</span>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Stanbic Bank</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										Slowest sync • 15 min
									</div>
								</div>
								<span className={cx(s.badge, s.badgeW)}>Review</span>
							</div>
						</div>
					</div>
					<div className="col-lg-3">
						<div className={s.utilityBlock}>
							<h4 style={{ fontSize: 14, fontWeight: 700, margin: "0 0 16px" }}>
								Liquidity Risk
							</h4>
							<div
								className="p-3 rounded mb-3"
								style={{ background: "var(--pm-accent-soft)" }}
							>
								<div
									style={{ fontSize: 11, color: "#047857", fontWeight: 700 }}
								>
									MINIMUM BALANCE ALERT{" "}
								</div>
								<div
									style={{
										fontSize: 20,
										fontWeight: 700,
										color: "var(--pm-accent)",
									}}
								>
									2 accounts
								</div>
							</div>
							<div
								className="p-3 rounded mb-3"
								style={{ background: "var(--pm-warning-soft)" }}
							>
								<div
									style={{ fontSize: 11, color: "#B45309", fontWeight: 700 }}
								>
									OVERDRAFT UTILISATION{" "}
								</div>
								<div
									style={{
										fontSize: 20,
										fontWeight: 700,
										color: "var(--pm-warning)",
									}}
								>
									12%
								</div>
							</div>
							<div
								className="p-3 rounded"
								style={{ background: "var(--pm-info-soft)" }}
							>
								<div
									style={{ fontSize: 11, color: "#1D4ED8", fontWeight: 700 }}
								>
									FORECASTED LOW
								</div>
								<div
									style={{
										fontSize: 20,
										fontWeight: 700,
										color: "var(--pm-info)",
									}}
								>
									Week 8
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div className={s.card}>
				<div
					className="d-flex justify-content-between align-items-center mb-3 flex-wrap"
					style={{ gap: 8 }}
				>
					<div>
						<h3 className={s.st}>
							<i
								className="bi bi-shield-check"
								style={{ color: "var(--pm-danger)" }}
							></i>
							Security, Consent Management & Fraud Controls
						</h3>
						<p className={s.ss}>
							Consent lifecycle, fraud detection, transaction limits, and
							security audit logs across all linked banks.
						</p>
					</div>
					<div className="d-flex" style={{ gap: 8 }}>
						<button
							type="button"
							className={cx(s.btnPm, s.btnSm)}
							onClick={() => onOpen("fraudSettingsModal")}
						>
							<i className="bi bi-shield"></i>Fraud
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnSm)}
							onClick={() => onOpen("consentModal")}
						>
							<i className="bi bi-key"></i>Consents
						</button>
					</div>
				</div>
				<div className="row g-3">
					<div className="col-lg-4">
						<div className={s.utilityBlock}>
							<h4 style={{ fontSize: 14, fontWeight: 700, margin: "0 0 16px" }}>
								Active Consents
							</h4>
							<div className={s.statusRow}>
								<div>
									<strong>Equity Bank</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										View + Transfer • Expires 15 Aug
									</div>
								</div>
								<span className={cx(s.badge, s.badgeS)}>Valid</span>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>KCB Bank</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										View + Transfer • Expires 12 Sep
									</div>
								</div>
								<span className={cx(s.badge, s.badgeS)}>Valid</span>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Co-op Bank</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										View only • Expires 20 Jul{" "}
									</div>
								</div>
								<span className={cx(s.badge, s.badgeW)}>Expiring</span>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Family Bank</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										Expired • Re-auth required{" "}
									</div>
								</div>
								<span className={cx(s.badge, s.badgeD)}>Expired</span>
							</div>
						</div>
					</div>
					<div className="col-lg-4">
						<div className={s.utilityBlock}>
							<h4 style={{ fontSize: 14, fontWeight: 700, margin: "0 0 16px" }}>
								Fraud Controls
							</h4>
							<div className="form-check form-switch mb-2">
								<input
									className="form-check-input"
									type="checkbox"
									defaultChecked
								/>
								<label className="form-check-label">
									Real-time fraud alerts
								</label>
							</div>
							<div className="form-check form-switch mb-2">
								<input
									className="form-check-input"
									type="checkbox"
									defaultChecked
								/>
								<label className="form-check-label">
									Large transfer verification
								</label>
							</div>
							<div className="form-check form-switch mb-2">
								<input className="form-check-input" type="checkbox" />
								<label className="form-check-label">
									New beneficiary approval
								</label>
							</div>
							<div className="form-check form-switch">
								<input
									className="form-check-input"
									type="checkbox"
									defaultChecked
								/>
								<label className="form-check-label">
									Daily transfer limit (KES 5M)
								</label>
							</div>
							<div className="mt-3">
								<label className={s.formLabel}>High-value threshold</label>
								<input className={s.formControl} defaultValue="1,000,000" />
							</div>
						</div>
					</div>
					<div className="col-lg-4">
						<div className={s.utilityBlock}>
							<h4 style={{ fontSize: 14, fontWeight: 700, margin: "0 0 16px" }}>
								Security Log (Last 7 Days){" "}
							</h4>
							<div className={s.statusRow}>
								<div>
									<strong>New device login</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										Equity — 24 Jun
									</div>
								</div>
								<span className={cx(s.badge, s.badgeS)}>Approved</span>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Consent revoked</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										Family Bank — 22 Jun
									</div>
								</div>
								<span className={cx(s.badge, s.badgeD)}>Action</span>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Transfer limit changed</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										KCB — 20 Jun
									</div>
								</div>
								<span className={cx(s.badge, s.badgeS)}>Approved</span>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div className={s.card}>
				<div
					className="d-flex justify-content-between align-items-center mb-3 flex-wrap"
					style={{ gap: 8 }}
				>
					<div>
						<h3 className={s.st}>
							<i
								className="bi bi-gear-fill"
								style={{ color: "var(--pm-muted)" }}
							></i>
							Open Banking Settings, Preferences & Support
						</h3>
						<p className={s.ss}>
							Notification preferences, reconciliation rules, bank connection
							health, and dedicated open banking support.
						</p>
					</div>
					<div className="d-flex" style={{ gap: 8 }}>
						<button
							type="button"
							className={cx(s.btnPm, s.btnSm)}
							onClick={() => onOpen("obSettingsModal")}
						>
							<i className="bi bi-gear"></i>Settings
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnSm)}
							onClick={() => onOpen("obSupportModal")}
						>
							<i className="bi bi-headset"></i>Support
						</button>
					</div>
				</div>
				<div className="row g-3">
					<div className="col-lg-4">
						<div className={s.utilityBlock}>
							<h4 style={{ fontSize: 14, fontWeight: 700, margin: "0 0 16px" }}>
								Notification Preferences
							</h4>
							<div className={s.statusRow}>
								<div>
									<strong>Transfer completed</strong>
								</div>
								<div className="form-check form-switch">
									<input
										className="form-check-input"
										type="checkbox"
										defaultChecked
									/>
								</div>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Reconciliation exception</strong>
								</div>
								<div className="form-check form-switch">
									<input
										className="form-check-input"
										type="checkbox"
										defaultChecked
									/>
								</div>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Consent expiring</strong>
								</div>
								<div className="form-check form-switch">
									<input
										className="form-check-input"
										type="checkbox"
										defaultChecked
									/>
								</div>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Fraud alert</strong>
								</div>
								<div className="form-check form-switch">
									<input
										className="form-check-input"
										type="checkbox"
										defaultChecked
									/>
								</div>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Bank link failure</strong>
								</div>
								<div className="form-check form-switch">
									<input
										className="form-check-input"
										type="checkbox"
										defaultChecked
									/>
								</div>
							</div>
						</div>
					</div>
					<div className="col-lg-4">
						<div className={s.utilityBlock}>
							<h4 style={{ fontSize: 14, fontWeight: 700, margin: "0 0 16px" }}>
								Reconciliation Rules
							</h4>
							<div className="form-check mb-2">
								<input
									className="form-check-input"
									type="checkbox"
									defaultChecked
								/>
								<label className="form-check-label" style={{ fontSize: 13 }}>
									Auto-match by exact amount + reference
								</label>
							</div>
							<div className="form-check mb-2">
								<input
									className="form-check-input"
									type="checkbox"
									defaultChecked
								/>
								<label className="form-check-label" style={{ fontSize: 13 }}>
									Auto-match by amount within ±KES 100
								</label>
							</div>
							<div className="form-check mb-2">
								<input className="form-check-input" type="checkbox" />
								<label className="form-check-label" style={{ fontSize: 13 }}>
									Flag duplicates across banks
								</label>
							</div>
							<div className="form-check">
								<input
									className="form-check-input"
									type="checkbox"
									defaultChecked
								/>
								<label className="form-check-label" style={{ fontSize: 13 }}>
									Auto-create exceptions for unmatched
								</label>
							</div>
							<div className="mt-3">
								<label className={s.formLabel}>Auto-reconcile window</label>
								<select className={s.formControl}>
									<option>7 days</option>
									<option>14 days</option>
									<option>30 days</option>
								</select>
							</div>
						</div>
					</div>
					<div className="col-lg-4">
						<div className={s.utilityBlock}>
							<h4 style={{ fontSize: 14, fontWeight: 700, margin: "0 0 16px" }}>
								Connection Health
							</h4>
							<div className={s.statusRow}>
								<div>
									<strong>Equity Bank</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										Uptime 99.9% • Last sync: Now{" "}
									</div>
								</div>
								<span className={cx(s.badge, s.badgeS)}>Healthy</span>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>KCB Bank</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										Uptime 99.8% • Last sync: Now{" "}
									</div>
								</div>
								<span className={cx(s.badge, s.badgeS)}>Healthy</span>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Family Bank</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										Connection issue • 3 hr ago{" "}
									</div>
								</div>
								<span className={cx(s.badge, s.badgeW)}>Issue</span>
							</div>
							<div className="mt-3">
								<button
									type="button"
									className={cx(s.btnPm, s.btnSm, "w-100")}
									onClick={() => onOpen("obSupportModal")}
								>
									Contact Open Banking Support
								</button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</>
	);
}
