/* ============================================================================
 * OpenBankingExtraModals.tsx — modals ported from the original page 3.10.html.
 * ----------------------------------------------------------------------------
 * AUTO-GENERATED by port_missing_modals.py — regenerate rather than hand-edit.
 *
 * These dialogs exist in the legacy HTML and were reachable there via
 * onclick="openModal('…')", but were never carried into the React port, so the
 * buttons that target them did nothing. Markup, titles, sizes, tables and
 * footer actions are ported from the source.
 *
 * Legacy bridges applied:
 *   openModal('x')        -> onOpen('x')
 *   data-bs-dismiss       -> onClose
 *   processAction(...)    -> doAction(...)  (spinner -> receipt)
 * ========================================================================== */
import type { ReactNode } from "react";
import { useEffect, useRef, useState } from "react";
import styles from "../styles/open-banking.module.css";

const s = styles as Record<string, string>;
const cx = (...c: (string | false | undefined)[]) =>
	c.filter(Boolean).join(" ");

interface Props {
	active: string | null;
	onClose: () => void;
	onOpen: (id: string) => void;
}

interface Result {
	msg: string;
	ref?: string;
}

/* Modal shell — mirrors the shared kit used by the hand-written modals so
 * these dialogs look and behave identically. */
function MBox({
	id,
	active,
	title,
	size = "md",
	onClose,
	children,
	footer,
}: {
	id: string;
	active: string | null;
	title: ReactNode;
	size?: "md" | "lg" | "xl";
	onClose: () => void;
	children: ReactNode;
	footer?: ReactNode;
}) {
	if (active !== id) return null;
	return (
		<>
			<div className={s.backdrop} onClick={onClose} />
			<div className={s.modalWrap} role="dialog" aria-modal="true">
				<div
					className={cx(
						s.modalBox,
						size === "lg" && s.modalBoxLg,
						size === "xl" && s.modalBoxXl,
					)}
				>
					<div className={s.modalHeader}>
						<h5 className={s.modalTitle}>{title}</h5>
						<button
							type="button"
							className="btn-close"
							aria-label="Close"
							onClick={onClose}
						/>
					</div>
					<div className={s.modalBody}>{children}</div>
					{footer && <div className={s.modalFooter}>{footer}</div>}
				</div>
			</div>
		</>
	);
}

function Busy() {
	return (
		<div className={s.loadingOv}>
			<div className={s.spinner} />
			<p className={s.loadingLabel}>Processing...</p>
		</div>
	);
}

export default function OpenBankingExtraModals({
	active,
	onClose,
	onOpen: _onOpen,
}: Props) {
	const [results, setResults] = useState<Record<string, Result>>({});
	const [busy, setBusy] = useState<string | null>(null);
	const [flows, setFlows] = useState<Record<string, number>>({});
	const timer = useRef<number | undefined>(undefined);

	/* LEGACY BRIDGE: cacheResettable() — clear state when the modal closes. */
	useEffect(() => {
		if (active === null) {
			setResults({});
			setBusy(null);
			setFlows({});
		}
	}, [active]);
	useEffect(() => () => window.clearTimeout(timer.current), []);

	/* LEGACY BRIDGE: processAction() — 1.2s spinner, then a receipt. */
	const doAction = (id: string, msg: string, ref?: string) => {
		setBusy(id);
		timer.current = window.setTimeout(() => {
			setResults((p) => ({ ...p, [id]: { msg, ref } }));
			setBusy(null);
		}, 1200);
	};
	void doAction;

	const nextFlow = (key: string, total: number) => {
		const cur = flows[key] ?? 1;
		if (cur >= total) {
			onClose();
			return;
		}
		setFlows((p) => ({ ...p, [key]: cur + 1 }));
	};
	void nextFlow;

	const bodyFor = (id: string, content: ReactNode) => {
		if (busy === id) return <Busy />;
		const r = results[id];
		if (r)
			return (
				<div className={s.receipt}>
					<div className={s.receiptIcon}>
						<i className="bi bi-check-lg" />
					</div>
					<h5 style={{ fontWeight: 700, color: "var(--pm-accent)" }}>
						{r.msg}
					</h5>
					{r.ref && (
						<p style={{ fontSize: 12, color: "var(--pm-muted)" }}>
							Ref: {r.ref}
						</p>
					)}
				</div>
			);
		return content;
	};

	return (
		<>
			<MBox
				id="cashFlowModal"
				active={active}
				size="xl"
				onClose={onClose}
				title={
					<>
						<i className="bi bi-graph-up-arrow text-purple me-2" /> 90-Day Cash
						Flow Forecast
					</>
				}
				footer={
					<>
						<button type="button" className={s.btnPm} onClick={onClose}>
							Close
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnPmP)}
							onClick={onClose}
						>
							Schedule Transfers
						</button>
					</>
				}
			>
				{bodyFor(
					"cashFlowModal",
					<>
						<div className="row g-3">
							<div className="col-md-8">
								<div className={s.chartBars} style={{ height: 140 }}>
									<div
										className={s.chartBar}
										style={{ height: "55%", background: "var(--pm-info)" }}
									>
										<span className={s.barLabel}>W1</span>
									</div>
									<div
										className={s.chartBar}
										style={{ height: "68%", background: "var(--pm-info)" }}
									>
										<span className={s.barLabel}>W2</span>
									</div>
									<div
										className={s.chartBar}
										style={{ height: "82%", background: "var(--pm-warning)" }}
									>
										<span className={s.barLabel}>W3</span>
									</div>
									<div
										className={s.chartBar}
										style={{ height: "74%", background: "var(--pm-info)" }}
									>
										<span className={s.barLabel}>W4</span>
									</div>
									<div
										className={s.chartBar}
										style={{ height: "90%", background: "var(--pm-primary)" }}
									>
										<span className={s.barLabel}>W5</span>
									</div>
									<div
										className={s.chartBar}
										style={{ height: "65%", background: "var(--pm-accent)" }}
									>
										<span className={s.barLabel}>W6</span>
									</div>
									<div
										className={s.chartBar}
										style={{ height: "78%", background: "var(--pm-primary)" }}
									>
										<span className={s.barLabel}>W7</span>
									</div>
									<div
										className={s.chartBar}
										style={{ height: "85%", background: "var(--pm-info)" }}
									>
										<span className={s.barLabel}>W8</span>
									</div>
									<div
										className={s.chartBar}
										style={{ height: "72%", background: "var(--pm-accent)" }}
									>
										<span className={s.barLabel}>W9</span>
									</div>
									<div
										className={s.chartBar}
										style={{ height: "95%", background: "var(--pm-primary)" }}
									>
										<span className={s.barLabel}>W10</span>
									</div>
									<div
										className={s.chartBar}
										style={{ height: "60%", background: "var(--pm-info)" }}
									>
										<span className={s.barLabel}>W11</span>
									</div>
									<div
										className={s.chartBar}
										style={{ height: "88%", background: "var(--pm-accent)" }}
									>
										<span className={s.barLabel}>W12</span>
									</div>
								</div>
							</div>
							<div className="col-md-4">
								<div
									className="p-3 rounded mb-2"
									style={{ background: "var(--pm-accent-soft)" }}
								>
									<div
										style={{ fontSize: 11, color: "#047857", fontWeight: 700 }}
									>
										PEAK CASH
									</div>
									<div
										style={{
											fontSize: 22,
											fontWeight: 700,
											color: "var(--pm-accent)",
										}}
									>
										Week 10
									</div>
									<div style={{ fontSize: 14, color: "#065F46" }}>
										KES 22.1M
									</div>
								</div>
								<div
									className="p-3 rounded mb-2"
									style={{ background: "var(--pm-warning-soft)" }}
								>
									<div
										style={{ fontSize: 11, color: "#B45309", fontWeight: 700 }}
									>
										LOWEST POINT
									</div>
									<div
										style={{
											fontSize: 22,
											fontWeight: 700,
											color: "var(--pm-warning)",
										}}
									>
										Week 8
									</div>
									<div style={{ fontSize: 14, color: "#92400E" }}>
										KES 11.4M
									</div>
								</div>
								<div
									className="p-3 rounded"
									style={{ background: "var(--pm-info-soft)" }}
								>
									<div
										style={{ fontSize: 11, color: "#1D4ED8", fontWeight: 700 }}
									>
										NET CHANGE
									</div>
									<div
										style={{
											fontSize: 22,
											fontWeight: 700,
											color: "var(--pm-info)",
										}}
									>
										+KES 3.4M
									</div>
								</div>
							</div>
						</div>
					</>,
				)}
			</MBox>
			<MBox
				id="consentModal"
				active={active}
				size="lg"
				onClose={onClose}
				title={
					<>
						<i className="bi bi-key text-primary me-2" /> Consent Management
					</>
				}
				footer={
					<>
						<button type="button" className={s.btnPm} onClick={onClose}>
							Close
						</button>
					</>
				}
			>
				{bodyFor(
					"consentModal",
					<>
						<div className="table-responsive">
							<table className={s.tbl}>
								<thead>
									<tr>
										<th>Bank</th>
										<th>Consent</th>
										<th>Expires</th>
										<th>Status</th>
										<th>Action</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>Equity Bank</td>
										<td>View + Transfer</td>
										<td>15 Aug 2025</td>
										<td>
											<span className={cx(s.badge, s.badgeS)}>Valid</span>
										</td>
										<td>
											<button
												type="button"
												className={cx(s.btnPm, s.btnSm)}
												onClick={onClose}
											>
												Revoke
											</button>
										</td>
									</tr>
									<tr>
										<td>KCB Bank</td>
										<td>View + Transfer</td>
										<td>12 Sep 2025</td>
										<td>
											<span className={cx(s.badge, s.badgeS)}>Valid</span>
										</td>
										<td>
											<button
												type="button"
												className={cx(s.btnPm, s.btnSm)}
												onClick={onClose}
											>
												Revoke
											</button>
										</td>
									</tr>
									<tr>
										<td>Co-op Bank</td>
										<td>View only</td>
										<td>20 Jul 2025</td>
										<td>
											<span className={cx(s.badge, s.badgeW)}>Expiring</span>
										</td>
										<td>
											<button
												type="button"
												className={cx(s.btnPm, s.btnSm)}
												onClick={onClose}
											>
												Re-auth
											</button>
										</td>
									</tr>
									<tr>
										<td>Family Bank</td>
										<td>View + Transfer</td>
										<td>Expired</td>
										<td>
											<span className={cx(s.badge, s.badgeD)}>Expired</span>
										</td>
										<td>
											<button
												type="button"
												className={cx(s.btnPm, s.btnSm)}
												onClick={onClose}
											>
												Re-auth
											</button>
										</td>
									</tr>
								</tbody>
							</table>
						</div>
					</>,
				)}
			</MBox>
			<MBox
				id="exceptionModal"
				active={active}
				onClose={onClose}
				title={
					<>
						<i className="bi bi-exclamation-triangle text-warning me-2" />{" "}
						Resolve Exception
					</>
				}
				footer={
					<>
						<button type="button" className={s.btnPm} onClick={onClose}>
							Cancel
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnPmP)}
							onClick={onClose}
						>
							Resolve Exception
						</button>
					</>
				}
			>
				{bodyFor(
					"exceptionModal",
					<>
						<div className="mb-3">
							<label className={s.formLabel}>Transaction</label>
							<div
								className="p-3 rounded"
								style={{ background: "var(--pm-surface-2)", fontSize: 13 }}
							>
								26 Jun • Stanbic • Unknown credit • KES 85,000
							</div>
						</div>
						<div className="mb-3">
							<label className={s.formLabel}>Match To</label>
							<select className={s.formControl}>
								<option>Invoice INV-4428 (KES 85,000)</option>
								<option>Invoice INV-4431 (KES 85,000)</option>
								<option>Create new invoice</option>
							</select>
						</div>
						<div className="mb-3">
							<label className={s.formLabel}>Notes</label>
							<textarea className={s.formControl} rows={3}>
								Amount matches invoice exactly. Reference slightly different due
								to bank truncation.
							</textarea>
						</div>
					</>,
				)}
			</MBox>
			<MBox
				id="fraudSettingsModal"
				active={active}
				onClose={onClose}
				title={
					<>
						<i className="bi bi-shield-exclamation text-danger me-2" /> Fraud &
						Security Settings
					</>
				}
				footer={
					<>
						<button type="button" className={s.btnPm} onClick={onClose}>
							Cancel
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnPmP)}
							onClick={onClose}
						>
							Save Settings
						</button>
					</>
				}
			>
				{bodyFor(
					"fraudSettingsModal",
					<>
						<div className="form-check form-switch mb-3">
							<input
								className="form-check-input"
								type="checkbox"
								defaultChecked
							/>
							<label className="form-check-label">
								Real-time fraud detection on all banks
							</label>
						</div>
						<div className="form-check form-switch mb-3">
							<input
								className="form-check-input"
								type="checkbox"
								defaultChecked
							/>
							<label className="form-check-label">
								Large transfer verification (KES 1M+)
							</label>
						</div>
						<div className="form-check form-switch mb-3">
							<input className="form-check-input" type="checkbox" />
							<label className="form-check-label">
								New beneficiary approval workflow
							</label>
						</div>
						<div className="mb-3">
							<label className={s.formLabel}>Daily transfer limit (KES)</label>
							<input className={s.formControl} defaultValue="5000000" />
						</div>
						<div className="mb-3">
							<label className={s.formLabel}>Single transfer limit (KES)</label>
							<input className={s.formControl} defaultValue="2000000" />
						</div>
						<div
							className="p-3 rounded"
							style={{ background: "var(--pm-info-soft)", fontSize: 12 }}
						>
							<i className="bi bi-info-circle me-1"></i>All changes require 2FA
							confirmation and are logged in the security audit trail.
						</div>
					</>,
				)}
			</MBox>
			<MBox
				id="obSupportModal"
				active={active}
				onClose={onClose}
				title={
					<>
						<i className="bi bi-headset me-2" /> Open Banking Support
					</>
				}
				footer={
					<>
						<button type="button" className={s.btnPm} onClick={onClose}>
							Cancel
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnPmP)}
							onClick={onClose}
						>
							Submit Ticket
						</button>
					</>
				}
			>
				{bodyFor(
					"obSupportModal",
					<>
						<div className="mb-3">
							<label className={s.formLabel}>Issue Type</label>
							<select className={s.formControl}>
								<option>Bank connection issue</option>
								<option>Reconciliation problem</option>
								<option>Transfer failure</option>
								<option>Consent / Security</option>
								<option>Other</option>
							</select>
						</div>
						<div className="mb-3">
							<label className={s.formLabel}>Bank (if applicable)</label>
							<select className={s.formControl}>
								<option>Any / All</option>
								<option>Equity Bank</option>
								<option>KCB Bank</option>
								<option>Family Bank</option>
							</select>
						</div>
						<div className="mb-3">
							<label className={s.formLabel}>Description</label>
							<textarea className={s.formControl} rows={4}>
								Describe the issue in detail...
							</textarea>
						</div>
					</>,
				)}
			</MBox>
			<MBox
				id="testModal"
				active={active}
				onClose={onClose}
				title={
					<>
						<i className="bi bi-eye me-2" /> Test Modal
					</>
				}
				footer={
					<>
						<button type="button" className={s.btnPm} onClick={onClose}>
							Close
						</button>
					</>
				}
			>
				{bodyFor(
					"testModal",
					<>
						<p style={{ fontSize: 13, color: "var(--pm-ink-soft)" }}>
							This is a placeholder modal used for testing. All production
							modals are fully functional.
						</p>
					</>,
				)}
			</MBox>
		</>
	);
}
