/* ============================================================================
 * TreasuryCashExtraModals.tsx — modals ported from the original page 3.7.html.
 * ----------------------------------------------------------------------------
 * AUTO-GENERATED by port_missing_modals.py — regenerate rather than hand-edit.
 *
 * These dialogs exist in the legacy HTML and were reachable there via
 * onclick="openModal('…')", but were never carried into the React port, so the
 * buttons that target them did nothing. Markup, titles, sizes, tables and
 * footer actions are ported from the source.
 *
 * Legacy bridges applied:
 *   openModal('x')        -> onOpen('x')
 *   data-bs-dismiss       -> onClose
 *   processAction(...)    -> doAction(...)  (spinner -> receipt)
 * ========================================================================== */
import type { ReactNode } from "react";
import { useEffect, useRef, useState } from "react";
import styles from "../styles/treasury-cash.module.css";

const s = styles as Record<string, string>;
const cx = (...c: (string | false | undefined)[]) =>
	c.filter(Boolean).join(" ");

interface Props {
	active: string | null;
	onClose: () => void;
	onOpen: (id: string) => void;
}

interface Result {
	msg: string;
	ref?: string;
}

/* Modal shell — mirrors the shared kit used by the hand-written modals so
 * these dialogs look and behave identically. */
function MBox({
	id,
	active,
	title,
	size = "md",
	onClose,
	children,
	footer,
}: {
	id: string;
	active: string | null;
	title: ReactNode;
	size?: "md" | "lg" | "xl";
	onClose: () => void;
	children: ReactNode;
	footer?: ReactNode;
}) {
	if (active !== id) return null;
	return (
		<>
			<div className={s.backdrop} onClick={onClose} />
			<div className={s.modalWrap} role="dialog" aria-modal="true">
				<div
					className={cx(
						s.modalBox,
						size === "lg" && s.modalBoxLg,
						size === "xl" && s.modalBoxXl,
					)}
				>
					<div className={s.modalHeader}>
						<h5 className={s.modalTitle}>{title}</h5>
						<button
							type="button"
							className="btn-close"
							aria-label="Close"
							onClick={onClose}
						/>
					</div>
					<div className={s.modalBody}>{children}</div>
					{footer && <div className={s.modalFooter}>{footer}</div>}
				</div>
			</div>
		</>
	);
}

function Busy() {
	return (
		<div className={s.loadingOv}>
			<div className={s.spinner} />
			<p className={s.loadingLabel}>Processing...</p>
		</div>
	);
}

export default function TreasuryCashExtraModals({
	active,
	onClose,
	onOpen,
}: Props) {
	const [results, setResults] = useState<Record<string, Result>>({});
	const [busy, setBusy] = useState<string | null>(null);
	const [flows, setFlows] = useState<Record<string, number>>({});
	const timer = useRef<number | undefined>(undefined);

	/* LEGACY BRIDGE: cacheResettable() — clear state when the modal closes. */
	useEffect(() => {
		if (active === null) {
			setResults({});
			setBusy(null);
			setFlows({});
		}
	}, [active]);
	useEffect(() => () => window.clearTimeout(timer.current), []);

	/* LEGACY BRIDGE: processAction() — 1.2s spinner, then a receipt. */
	const doAction = (id: string, msg: string, ref?: string) => {
		setBusy(id);
		timer.current = window.setTimeout(() => {
			setResults((p) => ({ ...p, [id]: { msg, ref } }));
			setBusy(null);
		}, 1200);
	};

	const nextFlow = (key: string, total: number) => {
		const cur = flows[key] ?? 1;
		if (cur >= total) {
			onClose();
			return;
		}
		setFlows((p) => ({ ...p, [key]: cur + 1 }));
	};
	void nextFlow;

	const bodyFor = (id: string, content: ReactNode) => {
		if (busy === id) return <Busy />;
		const r = results[id];
		if (r)
			return (
				<div className={s.receipt}>
					<div className={s.receiptIcon}>
						<i className="bi bi-check-lg" />
					</div>
					<h5 style={{ fontWeight: 700, color: "var(--pm-accent)" }}>
						{r.msg}
					</h5>
					{r.ref && (
						<p style={{ fontSize: 12, color: "var(--pm-muted)" }}>
							Ref: {r.ref}
						</p>
					)}
				</div>
			);
		return content;
	};

	return (
		<>
			<MBox
				id="attentionModal"
				active={active}
				size="lg"
				onClose={onClose}
				title={
					<>
						<i className="bi bi-exclamation-circle text-warning me-2" />{" "}
						Treasury Action Items
					</>
				}
				footer={
					<>
						<button type="button" className={s.btnPm} onClick={onClose}>
							Close
						</button>
					</>
				}
			>
				{bodyFor(
					"attentionModal",
					<>
						<div className={s.statusRow}>
							<div>
								<strong>3 Sweeps require approval</strong>
								<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
									KES 4.2M target balancing transfers
								</div>
							</div>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm, s.btnPmP)}
								onClick={() => onOpen("approvalQueueModal")}
							>
								Review
							</button>
						</div>
						<div className={s.statusRow}>
							<div>
								<strong>USD/KES dropped to 129.10</strong>
								<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
									Hit target alert for vendor payment
								</div>
							</div>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								onClick={() => onOpen("bookFXModal")}
							>
								Trade
							</button>
						</div>
						<div className={s.statusRow}>
							<div>
								<strong>T-Bill maturity tomorrow</strong>
								<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
									KES 5.0M principal + interest
								</div>
							</div>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								onClick={() => onOpen("investmentPortfolioModal")}
							>
								Action
							</button>
						</div>
						<div className={s.statusRow}>
							<div>
								<strong>Unreconciled bank statement</strong>
								<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
									Equity Bank main op account
								</div>
							</div>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								onClick={() => onOpen("reconciliationModal")}
							>
								Fix
							</button>
						</div>
					</>,
				)}
			</MBox>
			<MBox
				id="bankStatementsModal"
				active={active}
				size="lg"
				onClose={onClose}
				title={
					<>
						<i className="bi bi-journal-text me-2" /> Bank Statements (API
						Pulled)
					</>
				}
				footer={
					<>
						<button type="button" className={s.btnPm} onClick={onClose}>
							Close
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnPmP)}
							onClick={() => onOpen("exportTreasuryModal")}
						>
							Export PDF/CSV
						</button>
					</>
				}
			>
				{bodyFor(
					"bankStatementsModal",
					<>
						<div className="d-flex justify-content-between mb-3">
							<select className={s.formControl} style={{ width: 250 }}>
								<option>Equity Bank Main</option>
								<option>KCB Payroll</option>
							</select>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								onClick={onClose}
							>
								<i className="bi bi-arrow-clockwise"></i>Sync Now
							</button>
						</div>
						<div className="table-responsive">
							<table className={s.tbl}>
								<thead>
									<tr>
										<th>Date</th>
										<th>Description</th>
										<th>Ref</th>
										<th>In</th>
										<th>Out</th>
										<th>Balance</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>28 Jun</td>
										<td>PayMo SWEEP IN</td>
										<td>TRF-001</td>
										<td>1,450,200</td>
										<td>-</td>
										<td>14,250,000</td>
									</tr>
									<tr>
										<td>27 Jun</td>
										<td>VENDOR PAY - ALIBABA</td>
										<td>SWIFT-88</td>
										<td>-</td>
										<td>582,300</td>
										<td>12,799,800</td>
									</tr>
									<tr>
										<td>25 Jun</td>
										<td>PAYROLL FUNDING</td>
										<td>TRF-002</td>
										<td>-</td>
										<td>4,000,000</td>
										<td>13,382,100</td>
									</tr>
								</tbody>
							</table>
						</div>
					</>,
				)}
			</MBox>
			<MBox
				id="exportTreasuryModal"
				active={active}
				onClose={onClose}
				title={
					<>
						<i className="bi bi-file-earmark-pdf text-danger me-2" /> Export
						Treasury Reports
					</>
				}
				footer={
					<>
						<button type="button" className={s.btnPm} onClick={onClose}>
							Cancel
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnPmP)}
							onClick={() =>
								doAction(
									"exportTreasuryModal",
									"Report generated and downloading...",
								)
							}
						>
							<i className="bi bi-download"></i>Generate Report
						</button>
					</>
				}
			>
				{bodyFor(
					"exportTreasuryModal",
					<>
						<div className="mb-3">
							<label className={s.formLabel}>Report Type</label>
							<select className={s.formControl}>
								<option>Consolidated Cash Position</option>
								<option>FX Exposure&Hedging</option>
								<option>Investment Yield Summary</option>
								<option>Sweep&Auto-transfer Log</option>
								<option>Cash Flow Forecast (30D)</option>
							</select>
						</div>
						<div className="row g-3 mb-3">
							<div className="col-6">
								<label className={s.formLabel}>From</label>
								<input
									type="date"
									className={s.formControl}
									defaultValue="2025-06-01"
								/>
							</div>
							<div className="col-6">
								<label className={s.formLabel}>To</label>
								<input
									type="date"
									className={s.formControl}
									defaultValue="2025-06-28"
								/>
							</div>
						</div>
						<div className="mb-3">
							<label className={s.formLabel}>Format</label>
							<select className={s.formControl}>
								<option>PDF</option>
								<option>Excel (XLSX)</option>
								<option>CSV</option>
							</select>
						</div>
					</>,
				)}
			</MBox>
			<MBox
				id="fxAlertModal"
				active={active}
				onClose={onClose}
				title={
					<>
						<i className="bi bi-bell text-accent me-2" /> Set FX Target Alert
					</>
				}
				footer={
					<>
						<button type="button" className={s.btnPm} onClick={onClose}>
							Cancel
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnPmP)}
							onClick={() =>
								doAction(
									"fxAlertModal",
									"Alert configured for USD/KES at 128.50.",
								)
							}
						>
							Save Alert
						</button>
					</>
				}
			>
				{bodyFor(
					"fxAlertModal",
					<>
						<div className="mb-3">
							<label className={s.formLabel}>Currency Pair</label>
							<select className={s.formControl}>
								<option>USD/KES</option>
								<option>EUR/KES</option>
								<option>GBP/KES</option>
							</select>
						</div>
						<div className="mb-3">
							<label className={s.formLabel}>Alert Me When Rate Is</label>
							<select className={s.formControl}>
								<option>Less than or equal to (&lt;=)</option>
								<option>Greater than or equal to (&gt;=)</option>
							</select>
						</div>
						<div className="mb-3">
							<label className={s.formLabel}>Target Rate</label>
							<input
								type="number"
								className={s.formControl}
								defaultValue="128.50"
								step="0.01"
							/>
						</div>
						<div className="mb-3">
							<label className={s.formLabel}>Notification Channel</label>
							<div className="form-check">
								<input
									className="form-check-input"
									type="checkbox"
									defaultChecked
								/>
								<label className="form-check-label">SMS / Push</label>
							</div>
							<div className="form-check">
								<input
									className="form-check-input"
									type="checkbox"
									defaultChecked
								/>
								<label className="form-check-label">Email</label>
							</div>
						</div>
					</>,
				)}
			</MBox>
			<MBox
				id="fxRatesModal"
				active={active}
				size="lg"
				onClose={onClose}
				title={
					<>
						<i className="bi bi-graph-up-arrow text-info me-2" /> Live Interbank
						FX Rates
					</>
				}
				footer={
					<>
						<button type="button" className={s.btnPm} onClick={onClose}>
							Close
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnPmP)}
							onClick={() => onOpen("fxAlertModal")}
						>
							Set Rate Alerts
						</button>
					</>
				}
			>
				{bodyFor(
					"fxRatesModal",
					<>
						<div className="table-responsive">
							<table className={s.tbl}>
								<thead>
									<tr>
										<th>Pair</th>
										<th>Bid</th>
										<th>Ask</th>
										<th>Spread</th>
										<th>Trend (24h)</th>
										<th>Action</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>USD/KES</td>
										<td>129.10</td>
										<td>129.40</td>
										<td>0.30</td>
										<td>
											<span style={{ color: "var(--pm-accent)" }}>
												<i className="bi bi-arrow-down"></i>-0.12%
											</span>
										</td>
										<td>
											<button
												type="button"
												className={cx(s.btnPm, s.btnSm)}
												onClick={() => onOpen("bookFXModal")}
											>
												Trade
											</button>
										</td>
									</tr>
									<tr>
										<td>EUR/KES</td>
										<td>140.20</td>
										<td>140.85</td>
										<td>0.65</td>
										<td>
											<span style={{ color: "var(--pm-danger)" }}>
												<i className="bi bi-arrow-up"></i>+0.32%
											</span>
										</td>
										<td>
											<button
												type="button"
												className={cx(s.btnPm, s.btnSm)}
												onClick={() => onOpen("bookFXModal")}
											>
												Trade
											</button>
										</td>
									</tr>
									<tr>
										<td>GBP/KES</td>
										<td>165.40</td>
										<td>166.10</td>
										<td>0.70</td>
										<td>
											<span style={{ color: "var(--pm-accent)" }}>
												<i className="bi bi-arrow-down"></i>-0.05%
											</span>
										</td>
										<td>
											<button
												type="button"
												className={cx(s.btnPm, s.btnSm)}
												onClick={() => onOpen("bookFXModal")}
											>
												Trade
											</button>
										</td>
									</tr>
									<tr>
										<td>UGX/KES</td>
										<td>0.034</td>
										<td>0.035</td>
										<td>0.001</td>
										<td>
											<span style={{ color: "var(--pm-muted)" }}>
												<i className="bi bi-dash"></i>0.00%
											</span>
										</td>
										<td>
											<button
												type="button"
												className={cx(s.btnPm, s.btnSm)}
												onClick={() => onOpen("bookFXModal")}
											>
												Trade
											</button>
										</td>
									</tr>
								</tbody>
							</table>
						</div>
						<div
							className="p-3 rounded mt-3"
							style={{ background: "var(--pm-surface-2)", fontSize: 12 }}
						>
							<i className="bi bi-info-circle me-1"></i>Rates shown are
							indicative interbank rates. Final executable rates are provided on
							the trade booking screen.
						</div>
					</>,
				)}
			</MBox>
			<MBox
				id="fxRiskModal"
				active={active}
				size="lg"
				onClose={onClose}
				title={
					<>
						<i className="bi bi-shield-exclamation text-warning me-2" /> FX
						Exposure & Hedging
					</>
				}
				footer={
					<>
						<button type="button" className={s.btnPm} onClick={onClose}>
							Close
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnPmP)}
							onClick={() => onOpen("bookFXModal")}
						>
							Book Forward Contract
						</button>
					</>
				}
			>
				{bodyFor(
					"fxRiskModal",
					<>
						<div className="row g-3 mb-3">
							<div className="col-md-6">
								<div
									className="p-3 rounded"
									style={{ background: "var(--pm-warning-soft)" }}
								>
									<div
										style={{
											fontSize: 11,
											fontWeight: 700,
											color: "var(--pm-warning)",
										}}
									>
										USD PAYABLES (30D)
									</div>
									<div
										style={{
											fontSize: 24,
											fontWeight: 700,
											color: "var(--pm-ink)",
										}}
									>
										$ 42,500
									</div>
								</div>
							</div>
							<div className="col-md-6">
								<div
									className="p-3 rounded"
									style={{ background: "var(--pm-success-soft)" }}
								>
									<div
										style={{
											fontSize: 11,
											fontWeight: 700,
											color: "var(--pm-accent)",
										}}
									>
										USD RECEIVABLES (30D)
									</div>
									<div
										style={{
											fontSize: 24,
											fontWeight: 700,
											color: "var(--pm-ink)",
										}}
									>
										$ 12,000
									</div>
								</div>
							</div>
						</div>
						<div
							className="p-3 rounded mb-3"
							style={{ background: "var(--pm-surface-2)", fontSize: 13 }}
						>
							<div className="d-flex justify-content-between mb-1">
								<span>Net Short Exposure</span>
								<strong style={{ color: "var(--pm-danger)" }}>$ 30,500</strong>
							</div>
							<div className="d-flex justify-content-between mb-1">
								<span>Current Hedged Position</span>
								<strong>$ 18,200 (Forward @ 130.10)</strong>
							</div>
							<div className="d-flex justify-content-between">
								<span>Unhedged Risk</span>
								<strong style={{ color: "var(--pm-warning)" }}>$ 12,300</strong>
							</div>
						</div>
						<h6 style={{ fontWeight: 700 }}>Recommendation</h6>
						<p style={{ fontSize: 12, color: "var(--pm-muted)" }}>
							Consider booking a forward contract for the remaining $ 12,300 to
							lock in current rates before expected KES depreciation next month.
						</p>
					</>,
				)}
			</MBox>
			<MBox
				id="liquidateInvestModal"
				active={active}
				onClose={onClose}
				title={
					<>
						<i className="bi bi-box-arrow-right text-danger me-2" /> Withdraw /
						Liquidate Investment
					</>
				}
				footer={
					<>
						<button type="button" className={s.btnPm} onClick={onClose}>
							Cancel
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnPmD)}
							onClick={() =>
								doAction(
									"liquidateInvestModal",
									"Withdrawal initiated. Funds will settle within 24 hours.",
									"WTD-9921",
								)
							}
						>
							Withdraw Funds
						</button>
					</>
				}
			>
				{bodyFor(
					"liquidateInvestModal",
					<>
						<div
							className="p-3 rounded mb-3"
							style={{ background: "var(--pm-surface-2)" }}
						>
							<div className="d-flex justify-content-between mb-1">
								<span className="text-muted">Investment</span>
								<strong>PayMo Corporate MMF</strong>
							</div>
							<div className="d-flex justify-content-between">
								<span className="text-muted">Available Balance</span>
								<strong style={{ color: "var(--pm-primary)" }}>
									KES 8,500,000
								</strong>
							</div>
						</div>
						<div className="mb-3">
							<label className={s.formLabel}>Withdrawal Amount (KES)</label>
							<input
								type="number"
								className={s.formControl}
								defaultValue="1000000"
							/>
						</div>
						<div className="mb-3">
							<label className={s.formLabel}>Destination Account</label>
							<select className={s.formControl}>
								<option>Equity Bank Main</option>
								<option>PayMo Wallet</option>
							</select>
						</div>
						<div style={{ fontSize: 12, color: "var(--pm-muted)" }}>
							Withdrawals from MMF reflect in your target account within 24
							hours. Early withdrawal from locked deposits may incur penalty
							fees.
						</div>
					</>,
				)}
			</MBox>
			<MBox
				id="multiAccountModal"
				active={active}
				size="lg"
				onClose={onClose}
				title={
					<>
						<i className="bi bi-bank me-2" /> Corporate Accounts Dashboard
					</>
				}
				footer={
					<>
						<button type="button" className={s.btnPm} onClick={onClose}>
							Close
						</button>
					</>
				}
			>
				{bodyFor(
					"multiAccountModal",
					<>
						<div className="d-flex justify-content-end mb-3">
							<button
								type="button"
								className={cx(s.btnPm, s.btnPmP, s.btnSm)}
								onClick={() => onOpen("addAccountModal")}
							>
								<i className="bi bi-plus"></i>Add Account
							</button>
						</div>
						<div className="table-responsive">
							<table className={s.tbl}>
								<thead>
									<tr>
										<th>Bank / Wallet</th>
										<th>Account No</th>
										<th>Currency</th>
										<th>Balance</th>
										<th>Last Sync</th>
										<th>Action</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>Equity Bank Main</td>
										<td>018***4521</td>
										<td>KES</td>
										<td>14,250,000</td>
										<td>Just now</td>
										<td>
											<button
												type="button"
												className={cx(s.btnPm, s.btnSm)}
												onClick={() => onOpen("bankStatementsModal")}
											>
												Stmt
											</button>
										</td>
									</tr>
									<tr>
										<td>KCB Payroll</td>
										<td>110***8832</td>
										<td>KES</td>
										<td>3,800,000</td>
										<td>10m ago</td>
										<td>
											<button
												type="button"
												className={cx(s.btnPm, s.btnSm)}
												onClick={() => onOpen("bankStatementsModal")}
											>
												Stmt
											</button>
										</td>
									</tr>
									<tr>
										<td>StanChart USD</td>
										<td>870***9911</td>
										<td>USD</td>
										<td>$45,200</td>
										<td>1h ago</td>
										<td>
											<button
												type="button"
												className={cx(s.btnPm, s.btnSm)}
												onClick={() => onOpen("bankStatementsModal")}
											>
												Stmt
											</button>
										</td>
									</tr>
									<tr>
										<td>Safaricom Till</td>
										<td>Till 88291</td>
										<td>KES</td>
										<td>1,450,200</td>
										<td>Live</td>
										<td>
											<button
												type="button"
												className={cx(s.btnPm, s.btnSm)}
												onClick={() => onOpen("transferFundsModal")}
											>
												Sweep
											</button>
										</td>
									</tr>
									<tr>
										<td>PayMo Wallet</td>
										<td>PM-00192</td>
										<td>KES</td>
										<td>4,200,000</td>
										<td>Live</td>
										<td>
											<button
												type="button"
												className={cx(s.btnPm, s.btnSm)}
												onClick={() => onOpen("transferFundsModal")}
											>
												Move
											</button>
										</td>
									</tr>
								</tbody>
							</table>
						</div>
					</>,
				)}
			</MBox>
			<MBox
				id="scenarioBuilderModal"
				active={active}
				onClose={onClose}
				title={
					<>
						<i className="bi bi-sliders text-primary me-2" /> "What-If" Scenario
						Builder
					</>
				}
				footer={
					<>
						<button type="button" className={s.btnPm} onClick={onClose}>
							Cancel
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnPmP)}
							onClick={() =>
								doAction(
									"scenarioBuilderModal",
									"Scenario saved and applied to forecast view.",
								)
							}
						>
							Apply Scenario
						</button>
					</>
				}
			>
				{bodyFor(
					"scenarioBuilderModal",
					<>
						<div className="mb-3">
							<label className={s.formLabel}>Scenario Name</label>
							<input
								type="text"
								className={s.formControl}
								defaultValue="Late Client Payments"
							/>
						</div>
						<div className="mb-3">
							<label className={s.formLabel}>Receivables Delay</label>
							<select className={s.formControl}>
								<option>Push all inflows by 7 days</option>
								<option>Push 30% of inflows by 14 days</option>
								<option>Push all inflows by 30 days</option>
							</select>
						</div>
						<div className="mb-3">
							<label className={s.formLabel}>Payables Strategy</label>
							<select className={s.formControl}>
								<option>Pay on time (Normal)</option>
								<option>Delay supplier payments by 7 days</option>
							</select>
						</div>
						<div className="mb-3">
							<label className={s.formLabel}>FX Shock</label>
							<select className={s.formControl}>
								<option>None</option>
								<option>KES depreciation by 5%</option>
							</select>
						</div>
						<div
							className="p-3 rounded mt-3"
							style={{ background: "var(--pm-warning-soft)", fontSize: 12 }}
						>
							<i className="bi bi-exclamation-triangle me-1"></i>Under this
							scenario, you will face a liquidity shortfall of
							<strong>KES 1.2M</strong>on Jul 25 (Payroll date). Recommended
							mitigation: Liquidate KES 1.5M from MMF on Jul 23.
						</div>
					</>,
				)}
			</MBox>
			<MBox
				id="sweepHistoryModal"
				active={active}
				size="lg"
				onClose={onClose}
				title={
					<>
						<i className="bi bi-clock-history me-2" /> Automated Sweep Logs
					</>
				}
				footer={
					<>
						<button type="button" className={s.btnPm} onClick={onClose}>
							Close
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnPmP)}
							onClick={() => onOpen("exportTreasuryModal")}
						>
							Export Logs
						</button>
					</>
				}
			>
				{bodyFor(
					"sweepHistoryModal",
					<>
						<div className="table-responsive">
							<table className={s.tbl}>
								<thead>
									<tr>
										<th>Date&Time</th>
										<th>Rule</th>
										<th>Amount Swept</th>
										<th>Status</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>27 Jun, 23:00</td>
										<td>Till to Equity (EOD)</td>
										<td>KES 840,500</td>
										<td>
											<span className={cx(s.badge, s.badgeS)}>Success</span>
										</td>
									</tr>
									<tr>
										<td>26 Jun, 23:00</td>
										<td>Till to Equity (EOD)</td>
										<td>KES 790,200</td>
										<td>
											<span className={cx(s.badge, s.badgeS)}>Success</span>
										</td>
									</tr>
									<tr>
										<td>25 Jun, 09:00</td>
										<td>Equity to KCB (Target)</td>
										<td>KES 4,000,000</td>
										<td>
											<span className={cx(s.badge, s.badgeS)}>Success</span>
										</td>
									</tr>
									<tr>
										<td>24 Jun, 23:00</td>
										<td>Till to Equity (EOD)</td>
										<td>KES 920,000</td>
										<td>
											<span className={cx(s.badge, s.badgeS)}>Success</span>
										</td>
									</tr>
								</tbody>
							</table>
						</div>
					</>,
				)}
			</MBox>
			<MBox
				id="sweepRuleModal"
				active={active}
				onClose={onClose}
				title={
					<>
						<i className="bi bi-arrow-repeat text-secondary me-2" /> Configure
						Automated Sweep
					</>
				}
				footer={
					<>
						<button type="button" className={s.btnPm} onClick={onClose}>
							Cancel
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnPmP)}
							onClick={() =>
								doAction(
									"sweepRuleModal",
									"Sweep rule configured successfully.",
									"SWP-CFG-102",
								)
							}
						>
							Save Rule
						</button>
					</>
				}
			>
				{bodyFor(
					"sweepRuleModal",
					<>
						<div className="mb-3">
							<label className={s.formLabel}>Source Account</label>
							<select className={s.formControl}>
								<option>Safaricom Till</option>
								<option>Equity Bank Main</option>
							</select>
						</div>
						<div className="mb-3">
							<label className={s.formLabel}>Destination Account</label>
							<select className={s.formControl}>
								<option>Equity Bank Main</option>
								<option>KCB Payroll Acct</option>
								<option>PayMo Yield (MMF)</option>
							</select>
						</div>
						<div className="mb-3">
							<label className={s.formLabel}>Sweep Type</label>
							<select className={s.formControl}>
								<option>Zero Balance (Sweep everything)</option>
								<option>Target Balance (Keep minimum amount)</option>
								<option>Threshold Sweep (Sweep amounts above X)</option>
							</select>
						</div>
						<div className="mb-3">
							<label className={s.formLabel}>
								Threshold / Target Amount (KES)
							</label>
							<input
								type="number"
								className={s.formControl}
								defaultValue="500000"
							/>
						</div>
						<div className="mb-3">
							<label className={s.formLabel}>Frequency</label>
							<select className={s.formControl}>
								<option>End of Day (11:00 PM)</option>
								<option>Real-time (Instantly above threshold)</option>
								<option>Weekly (Friday 5 PM)</option>
							</select>
						</div>
					</>,
				)}
			</MBox>
			<MBox
				id="yieldAnalyticsModal"
				active={active}
				size="lg"
				onClose={onClose}
				title={
					<>
						<i className="bi bi-bar-chart-line text-purple me-2" /> Yield
						Analytics
					</>
				}
				footer={
					<>
						<button type="button" className={s.btnPm} onClick={onClose}>
							Close
						</button>
					</>
				}
			>
				{bodyFor(
					"yieldAnalyticsModal",
					<>
						<div className={s.chartBars} style={{ height: 150 }}>
							<div
								className={s.chartBar}
								style={{ height: "30%", background: "var(--pm-purple)" }}
							>
								<span className={s.barLabel}>Jan</span>
							</div>
							<div
								className={s.chartBar}
								style={{ height: "45%", background: "var(--pm-purple)" }}
							>
								<span className={s.barLabel}>Feb</span>
							</div>
							<div
								className={s.chartBar}
								style={{ height: "60%", background: "var(--pm-purple)" }}
							>
								<span className={s.barLabel}>Mar</span>
							</div>
							<div
								className={s.chartBar}
								style={{ height: "55%", background: "var(--pm-purple)" }}
							>
								<span className={s.barLabel}>Apr</span>
							</div>
							<div
								className={s.chartBar}
								style={{ height: "75%", background: "var(--pm-purple)" }}
							>
								<span className={s.barLabel}>May</span>
							</div>
							<div
								className={s.chartBar}
								style={{ height: "85%", background: "var(--pm-purple)" }}
							>
								<span className={s.barLabel}>Jun</span>
							</div>
						</div>
						<div className="table-responsive mt-4">
							<table className={s.tbl}>
								<thead>
									<tr>
										<th>Month</th>
										<th>Avg Principal</th>
										<th>Interest Earned</th>
										<th>Effective Annual Yield</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>June</td>
										<td>KES 18.0M</td>
										<td>KES 185,200</td>
										<td>12.3%</td>
									</tr>
									<tr>
										<td>May</td>
										<td>KES 16.5M</td>
										<td>KES 160,400</td>
										<td>11.6%</td>
									</tr>
									<tr>
										<td>April</td>
										<td>KES 15.0M</td>
										<td>KES 135,000</td>
										<td>10.8%</td>
									</tr>
								</tbody>
							</table>
						</div>
					</>,
				)}
			</MBox>
		</>
	);
}
