/* ============================================================================
 * MultiCurrencyTreasuryExtraSections.tsx — page sections restored from 3.11.html.
 * ----------------------------------------------------------------------------
 * AUTO-GENERATED by port_missing_sections.py — regenerate rather than hand-edit.
 *
 * Sections 3.11.5, 3.11.6 exist in the original page but were dropped by the first
 * React port, so the cards, tables and controls they contain were missing from
 * the app entirely. Markup is ported from the source; `openModal('x')` becomes
 * `onOpen('x')` so the existing modal layer handles the dialogs.
 * ========================================================================== */
import styles from "../styles/multi-currency-treasury.module.css";

const s = styles as Record<string, string>;
const cx = (...c: (string | false | undefined)[]) =>
	c.filter(Boolean).join(" ");

interface Props {
	/** Opens a modal by id — same bridge the rest of the page uses. */
	onOpen: (id: string) => void;
	/** Fallback for legacy buttons that only fired a toast. */
	onToast?: () => void;
}

export default function MultiCurrencyTreasuryExtraSections({
	onOpen,
	onToast,
}: Props) {
	const noop = onToast ?? (() => undefined);
	void noop;
	return (
		<>
			{/* ported from 3.11.html */}
			<div className={s.card}>
				<div>
					<h3 className={s.st}>
						<i
							className="bi bi-file-earmark-check"
							style={{ color: "var(--pm-warning)" }}
						></i>
						Regulatory Compliance & Reporting
					</h3>
					<p className={s.ss}>
						CBK forex reporting, KRA requirements, suspicious transaction
						monitoring, audit trails and filing calendar.
					</p>
				</div>
				<div className="d-flex" style={{ gap: 8 }}>
					<button
						type="button"
						className={cx(s.btnPm, s.btnSm)}
						onClick={() => onOpen("complianceModal")}
					>
						<i className="bi bi-file-earmark-text"></i>File Report
					</button>
				</div>
				<div className="row g-3">
					<div className="col-lg-6">
						<div className={s.utilityBlock}>
							<h4 style={{ fontSize: 14, fontWeight: 700, margin: "0 0 16px" }}>
								Compliance Status
							</h4>
							<div className="sr">
								<div>
									<strong>CBK Forex Returns</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										Monthly Form FX-1
									</div>
								</div>
								<span className={cx(s.badge, s.badgeS)}>Submitted</span>
							</div>
							<div className="sr">
								<div>
									<strong>CBK Large FX Transactions</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										Form FX-2 • 3 reports this month
									</div>
								</div>
								<span className={cx(s.badge, s.badgeS)}>Complete</span>
							</div>
							<div className="sr">
								<div>
									<strong>KRA Withholding Tax</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										FX gains • KES 184K
									</div>
								</div>
								<span className={cx(s.badge, s.badgeS)}>Filed</span>
							</div>
							<div className="sr">
								<div>
									<strong>STR Filing</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										1 pending review
									</div>
								</div>
								<span className={cx(s.badge, s.badgeW)}>Action</span>
							</div>
						</div>
					</div>
					<div className="col-lg-6">
						<div className={s.utilityBlock}>
							<h4 style={{ fontSize: 14, fontWeight: 700, margin: "0 0 16px" }}>
								Upcoming Deadlines
							</h4>
							<div className="sr">
								<div>
									<strong>CBK Monthly Return</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										Due 30 Jun 2025
									</div>
								</div>
								<span className={cx(s.badge, s.badgeI)}>3 days</span>
							</div>
							<div className="sr">
								<div>
									<strong>KRA Quarterly FX Gains</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										Due 15 Jul 2025
									</div>
								</div>
								<span className={cx(s.badge, s.badgeW)}>18 days</span>
							</div>
							<div className="sr">
								<div>
									<strong>Internal Audit</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										Q2 Treasury audit
									</div>
								</div>
								<span className={cx(s.badge, s.badgeP)}>45 days</span>
							</div>
						</div>
					</div>
				</div>
				<div className={s.card}>
					<div
						className="d-flex justify-content-between align-items-center mb-3 flex-wrap"
						style={{ gap: 8 }}
					>
						<div>
							<h3 className={s.st}>
								<i
									className="bi bi-clipboard-data"
									style={{ color: "var(--pm-danger)" }}
								></i>
							</h3>
						</div>
					</div>
				</div>
			</div>
			{/* ported from 3.11.html */}
			<div className={s.card}>
				<div>
					<h3 className={s.st}>
						<i
							className="bi bi-clipboard-data"
							style={{ color: "var(--pm-danger)" }}
						></i>
						Treasury Analytics, Reconciliation & Reporting
					</h3>
					<p className={s.ss}>
						P&Lby currency, exposure reports, reconciliation status, audit logs
						and scheduled exports.
					</p>
				</div>
				<div className="d-flex" style={{ gap: 8 }}>
					<button
						type="button"
						className={cx(s.btnPm, s.btnSm)}
						onClick={() => onOpen("reconcileModal")}
					>
						<i className="bi bi-list-check"></i>Reconcile
					</button>
					<button
						type="button"
						className={cx(s.btnPm, s.btnSm)}
						onClick={() => onOpen("reportExportModal")}
					>
						<i className="bi bi-download"></i>Export
					</button>
				</div>
				<div className="row g-3">
					<div className="col-lg-5">
						<div className={s.utilityBlock}>
							<h4 style={{ fontSize: 14, fontWeight: 700, margin: "0 0 16px" }}>
								P&Lby Currency (MTD)
							</h4>
							<div className="sr">
								<div>
									<strong>USD</strong>
								</div>
								<strong style={{ color: "var(--pm-accent)" }}>
									+KES 142,800
								</strong>
							</div>
							<div className="sr">
								<div>
									<strong>EUR</strong>
								</div>
								<strong style={{ color: "var(--pm-accent)" }}>
									+KES 38,400
								</strong>
							</div>
							<div className="sr">
								<div>
									<strong>GBP</strong>
								</div>
								<strong style={{ color: "var(--pm-danger)" }}>
									-KES 12,600
								</strong>
							</div>
							<div className="sr">
								<div>
									<strong>UGX/TZS</strong>
								</div>
								<strong style={{ color: "var(--pm-accent)" }}>
									+KES 15,600
								</strong>
							</div>
							<div className="sr">
								<div>
									<strong>Overall</strong>
								</div>
								<strong style={{ color: "var(--pm-accent)", fontSize: 16 }}>
									+KES 184,200
								</strong>
							</div>
						</div>
					</div>
					<div className="col-lg-7">
						<div className={s.utilityBlock}>
							<h4 style={{ fontSize: 14, fontWeight: 700, margin: "0 0 16px" }}>
								Reconciliation Status
							</h4>
							<div className="sr">
								<div>
									<strong>USD Nostro Account</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										Bank vs Internal
									</div>
								</div>
								<span className={cx(s.badge, s.badgeS)}>Matched</span>
							</div>
							<div className="sr">
								<div>
									<strong>EUR Nostro Account</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										Bank vs Internal
									</div>
								</div>
								<span className={cx(s.badge, s.badgeS)}>Matched</span>
							</div>
							<div className="sr">
								<div>
									<strong>GBP Nostro Account</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										Bank vs Internal
									</div>
								</div>
								<span className={cx(s.badge, s.badgeW)}>1 exception</span>
							</div>
							<div className="sr">
								<div>
									<strong>Forward Contracts</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										Mark-to-market vs ledger
									</div>
								</div>
								<span className={cx(s.badge, s.badgeS)}>Matched</span>
							</div>
						</div>
					</div>
				</div>
			</div>
		</>
	);
}
