/* ============================================================================
 * BusinessOnboardingBody.tsx — the page body, ported verbatim from 3.12.html.
 * ----------------------------------------------------------------------------
 * AUTO-GENERATED by port_page_bodies.py — regenerate rather than hand-edit.
 *
 * WHY THIS EXISTS
 * The first React port of this page paraphrased the original instead of
 * converting it: cards and whole numbered sections were absent and the tables
 * carried invented columns and rows. This file is a faithful conversion of the
 * source `<div class="pm-content">` of 3.12.html, so every card, table row
 * and figure matches the original layout.
 *
 * BRIDGES APPLIED
 *   class=            -> className=
 *   style="a:b"       -> style={{ a: "b" }}
 *   openModal('x')    -> onOpen('x')   (the page's setActiveModal)
 *   other onclick=    -> onAction()    (toast / no-op, never a dead button)
 *   every <td>        -> gains data-label from its column header, which the
 *                        responsive CSS uses to render tables as cards <=768px
 * ========================================================================== */
import styles from "../styles/business-onboarding.module.css";

const s = styles as Record<string, string>;
const cx = (...c: (string | false | undefined)[]) =>
	c.filter(Boolean).join(" ");

interface Props {
	/** Opens a modal by id — the page's setActiveModal. */
	onOpen: (id: string) => void;
	/** Fallback for legacy buttons that only fired a toast. */
	onAction?: () => void;
}

export default function BusinessOnboardingBody({ onOpen, onAction }: Props) {
	const act = onAction ?? (() => undefined);
	return (
		<>
			<div className="row g-3">
				<div className="col-lg-4">
					<div className={cx(s.card, s.cardAccent)} style={{ minHeight: 170 }}>
						<p
							style={{
								margin: 0,
								fontSize: 12,
								color: "rgba(255,255,255,.78)",
							}}
						>
							Onboarding pipeline live{" "}
							<span style={{ color: "#86efac" }}>●</span>
						</p>
						<div className={s.sv} style={{ margin: "8px 0", color: "#fff" }}>
							84 businesses onboarded
						</div>
						<p
							style={{
								margin: 0,
								fontSize: 12,
								color: "rgba(255,255,255,.78)",
							}}
						>
							Sole props, partnerships, LLCs, SACCOs, NGOs & corporate groups
							with complete KYB/KYC records and audit trails.{" "}
						</p>
						<div className="d-flex flex-wrap mt-3" style={{ gap: 8 }}>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								style={{
									background: "rgba(255,255,255,.12)",
									borderColor: "rgba(255,255,255,.22)",
									color: "#fff",
								}}
								onClick={() => onOpen("onboardNewModal")}
							>
								New Onboarding
							</button>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								style={{
									background: "rgba(255,255,255,.12)",
									borderColor: "rgba(255,255,255,.22)",
									color: "#fff",
								}}
								onClick={() => onOpen("pendingQueueModal")}
							>
								Review Queue
							</button>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								style={{
									background: "rgba(255,255,255,.12)",
									borderColor: "rgba(255,255,255,.22)",
									color: "#fff",
								}}
								onClick={() => onOpen("bulkOnboardModal")}
							>
								Bulk Import
							</button>
						</div>
					</div>
				</div>
				<div className="col-lg-2 col-md-4 col-6">
					<div className={s.card} style={{ minHeight: 170 }}>
						<p className={s.sl} style={{ color: "var(--pm-accent)" }}>
							COMPLIANCE SCORE
						</p>
						<div className={s.sv} style={{ margin: "6px 0" }}>
							87
							<span style={{ fontSize: 14, color: "var(--pm-muted)" }}>
								/100
							</span>
						</div>
						<span className={cx(s.badge, s.badgeS)}>
							<i className="bi bi-check2-circle"></i>Strong
						</span>
						<div
							className="mt-2"
							style={{ fontSize: 12, color: "var(--pm-ink-soft)" }}
						>
							TCC expiry alerts: 9<br />
							Beneficial ownership: 94%
						</div>
					</div>
				</div>
				<div className="col-lg-3 col-md-4 col-6">
					<div className={s.card} style={{ minHeight: 170 }}>
						<p className={s.sl} style={{ color: "var(--pm-info)" }}>
							PENDING VERIFICATION
						</p>
						<div className={s.sv} style={{ margin: "6px 0" }}>
							18
						</div>
						<span className={cx(s.badge, s.badgeW)}>
							<i className="bi bi-clock"></i>7 awaiting director KYC
						</span>
						<div
							className="mt-2"
							style={{ fontSize: 12, color: "var(--pm-ink-soft)" }}
						>
							12 new applications
							<br />6 renewal reviews
						</div>
					</div>
				</div>
				<div className="col-lg-3 col-md-4">
					<div
						className={s.card}
						style={{
							minHeight: 170,
							borderLeft: "3px solid var(--pm-warning)",
						}}
					>
						<p className={s.sl} style={{ color: "var(--pm-warning)" }}>
							EXPIRING DOCUMENTS
						</p>
						<div className={s.sv} style={{ margin: "6px 0" }}>
							11
						</div>
						<span className={cx(s.badge, s.badgeD)}>
							<i className="bi bi-exclamation-triangle"></i>Action required
						</span>
						<div
							className="mt-2"
							style={{ fontSize: 12, color: "var(--pm-ink-soft)" }}
						>
							TCC: 7 | Permits: 3 | ID: 1
						</div>
					</div>
				</div>
			</div>
			<div className="row g-3">
				<div className="col-lg-4">
					<div className={s.card}>
						<div className="d-flex justify-content-between align-items-center mb-3">
							<h3 className={s.st}>Attention Required</h3>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								onClick={() => onOpen("attentionFullModal")}
							>
								View all
							</button>
						</div>
						<div className={s.statusRow}>
							<div className="d-flex align-items-center gap-3">
								<div
									style={{
										width: 36,
										height: 36,
										borderRadius: "50%",
										background: "var(--pm-danger-soft)",
										color: "var(--pm-danger)",
										display: "flex",
										alignItems: "center",
										justifyContent: "center",
										fontSize: 14,
										flexShrink: 0,
									}}
								>
									<i className="bi bi-building"></i>
								</div>
								<div>
									<div style={{ fontWeight: 600, fontSize: 13 }}>
										Nairobi SACCO — TCC expires in 4 days
									</div>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										KRA-TCC-88291 · Renewal required
									</div>
								</div>
							</div>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								onClick={() => onOpen("renewTCCModal")}
							>
								Renew
							</button>
						</div>
						<div className={s.statusRow}>
							<div className="d-flex align-items-center gap-3">
								<div
									style={{
										width: 36,
										height: 36,
										borderRadius: "50%",
										background: "var(--pm-warning-soft)",
										color: "var(--pm-warning)",
										display: "flex",
										alignItems: "center",
										justifyContent: "center",
										fontSize: 14,
										flexShrink: 0,
									}}
								>
									<i className="bi bi-person-badge"></i>
								</div>
								<div>
									<div style={{ fontWeight: 600, fontSize: 13 }}>
										Director KYC pending — 7 days
									</div>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										Peter Ochieng · Huduma ID upload
									</div>
								</div>
							</div>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								onClick={() => onOpen("directorKYCModal")}
							>
								Verify
							</button>
						</div>
						<div className={s.statusRow}>
							<div className="d-flex align-items-center gap-3">
								<div
									style={{
										width: 36,
										height: 36,
										borderRadius: "50%",
										background: "var(--pm-purple-soft)",
										color: "var(--pm-purple)",
										display: "flex",
										alignItems: "center",
										justifyContent: "center",
										fontSize: 14,
										flexShrink: 0,
									}}
								>
									<i className="bi bi-exclamation-triangle"></i>
								</div>
								<div>
									<div style={{ fontWeight: 600, fontSize: 13 }}>
										Beneficial ownership declaration overdue
									</div>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										Greenfield Logistics · 5 shareholders
									</div>
								</div>
							</div>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								onClick={() => onOpen("beneficialOwnerModal")}
							>
								Complete
							</button>
						</div>
					</div>
				</div>
				<div className="col-lg-4">
					<div className={s.card}>
						<div className="d-flex justify-content-between align-items-center mb-3">
							<h3 className={s.st}>Smart Suggestions</h3>
							<span className={cx(s.badge, s.badgeP)}>
								<i className="bi bi-stars"></i>AI
							</span>
						</div>
						<div className={s.statusRow}>
							<div className="d-flex align-items-center gap-3">
								<div
									style={{
										width: 36,
										height: 36,
										borderRadius: "50%",
										background: "var(--pm-accent-soft)",
										color: "var(--pm-accent)",
										display: "flex",
										alignItems: "center",
										justifyContent: "center",
										fontSize: 14,
										flexShrink: 0,
									}}
								>
									<i className="bi bi-lightning"></i>
								</div>
								<div>
									<div style={{ fontWeight: 600, fontSize: 13 }}>
										Auto-renew 4 expiring TCCs
									</div>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										Prevent compliance gaps
									</div>
								</div>
							</div>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								onClick={() => onOpen("bulkRenewalModal")}
							>
								Auto-Renew
							</button>
						</div>
						<div className={s.statusRow}>
							<div className="d-flex align-items-center gap-3">
								<div
									style={{
										width: 36,
										height: 36,
										borderRadius: "50%",
										background: "var(--pm-info-soft)",
										color: "var(--pm-info)",
										display: "flex",
										alignItems: "center",
										justifyContent: "center",
										fontSize: 14,
										flexShrink: 0,
									}}
								>
									<i className="bi bi-file-earmark-check"></i>
								</div>
								<div>
									<div style={{ fontWeight: 600, fontSize: 13 }}>
										Pre-fill 3 new applications from BRS data
									</div>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										CR12 records available
									</div>
								</div>
							</div>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								onClick={() => onOpen("preFillModal")}
							>
								Pre-fill
							</button>
						</div>
						<div className={s.statusRow}>
							<div className="d-flex align-items-center gap-3">
								<div
									style={{
										width: 36,
										height: 36,
										borderRadius: "50%",
										background: "var(--pm-warning-soft)",
										color: "var(--pm-warning)",
										display: "flex",
										alignItems: "center",
										justifyContent: "center",
										fontSize: 14,
										flexShrink: 0,
									}}
								>
									<i className="bi bi-graph-up"></i>
								</div>
								<div>
									<div style={{ fontWeight: 600, fontSize: 13 }}>
										High-risk business flagged
									</div>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										Unusual ownership structure{" "}
									</div>
								</div>
							</div>
							<button
								type="button"
								className={cx(s.btnPm, s.btnSm)}
								onClick={() => onOpen("riskAssessmentModal")}
							>
								Review
							</button>
						</div>
					</div>
				</div>
				<div className="col-lg-4">
					<div className={s.card}>
						<div className="mb-3">
							<h3 className={s.st}>Quick Actions</h3>
							<p className={s.ss}>Frequent KYB/KYC workflows</p>
						</div>
						<div className={s.quickGrid}>
							<button
								type="button"
								className={s.quickBtn}
								onClick={() => onOpen("onboardNewModal")}
							>
								<i className="bi bi-plus-circle text-primary me-1"></i>New
								Business
							</button>
							<button
								type="button"
								className={s.quickBtn}
								onClick={() => onOpen("directorKYCModal")}
							>
								<i className="bi bi-person-badge text-info me-1"></i>Director
								KYC
							</button>
							<button
								type="button"
								className={s.quickBtn}
								onClick={() => onOpen("beneficialOwnerModal")}
							>
								<i className="bi bi-people text-purple me-1"></i>Beneficial
								Owner
							</button>
							<button
								type="button"
								className={s.quickBtn}
								onClick={() => onOpen("uploadDocumentModal")}
							>
								<i className="bi bi-upload text-success me-1"></i>Upload Docs
							</button>
							<button
								type="button"
								className={s.quickBtn}
								onClick={() => onOpen("riskAssessmentModal")}
							>
								<i className="bi bi-shield-exclamation text-warning me-1"></i>
								Risk Assessment
							</button>
							<button
								type="button"
								className={s.quickBtn}
								onClick={() => onOpen("complianceCheckModal")}
							>
								<i className="bi bi-check2-circle text-success me-1"></i>
								Compliance Check
							</button>
							<button
								type="button"
								className={s.quickBtn}
								onClick={() => onOpen("renewTCCModal")}
							>
								<i
									className="bi bi-file-earmark-text me-1"
									style={{ color: "var(--pm-primary)" }}
								></i>
								Renew TCC
							</button>
							<button
								type="button"
								className={s.quickBtn}
								onClick={() => onOpen("auditTrailModal")}
							>
								<i
									className="bi bi-clock-history me-1"
									style={{ color: "var(--pm-accent)" }}
								></i>
								Audit Trail
							</button>
						</div>
					</div>
				</div>
			</div>
			<div className={s.card}>
				<div
					className="d-flex justify-content-between align-items-center mb-3 flex-wrap"
					style={{ gap: 8 }}
				>
					<div>
						<h3 className={s.st}>
							<i
								className="bi bi-building"
								style={{ color: "var(--pm-primary)" }}
							></i>
							3.12.1 — Business Onboarding Application & KYB Intake
						</h3>
						<p className={s.ss}>
							Sole proprietor, partnership, LLC, SACCO, NGO and corporate group
							intake with automated CR12 validation, county permit lookup and
							KRA PIN verification.
						</p>
					</div>
					<div className="d-flex" style={{ gap: 8 }}>
						<button
							type="button"
							className={cx(s.btnPm, s.btnSm)}
							onClick={() => onOpen("onboardNewModal")}
						>
							<i className="bi bi-plus-lg"></i>Start Onboarding
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnSm, s.btnPmP)}
							onClick={() => onOpen("bulkOnboardModal")}
						>
							<i className="bi bi-upload"></i>Bulk Import
						</button>
					</div>
				</div>
				<div className="row g-3">
					<div className="col-lg-5">
						<div className={s.utilityBlock}>
							<h4 style={{ fontSize: 14, fontWeight: 700, margin: "0 0 16px" }}>
								Active Onboarding Pipeline{" "}
							</h4>
							<div className={s.statusRow}>
								<div>
									<strong>Greenfield Logistics Ltd</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										LLC · CR12-88291 · 92% complete
									</div>
								</div>
								<span className={cx(s.badge, s.badgeW)}>Docs Pending</span>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Shalom SACCO</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										Cooperative · CR12-99102 · 78% complete
									</div>
								</div>
								<span className={cx(s.badge, s.badgeI)}>KYC Review</span>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Mama Mboga Traders</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										Sole Prop · CR12-77192 · 45% complete
									</div>
								</div>
								<span className={cx(s.badge, s.badgeD)}>Incomplete</span>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Hope Children NGO</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										NGO · CR12-44821 · 100% complete
									</div>
								</div>
								<span className={cx(s.badge, s.badgeS)}>Approved</span>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>TechNova Solutions</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										LLC · CR12-99128 · 65% complete
									</div>
								</div>
								<span className={cx(s.badge, s.badgeW)}>Director KYC</span>
							</div>
						</div>
					</div>
					<div className="col-lg-4">
						<div className={s.utilityBlock}>
							<h4 style={{ fontSize: 14, fontWeight: 700, margin: "0 0 16px" }}>
								Application Types This Month{" "}
							</h4>
							<div className={s.statusRow}>
								<div>
									<strong>Sole Proprietorship</strong>
								</div>
								<div>
									<strong>28</strong>
								</div>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Limited Liability Company</strong>
								</div>
								<div>
									<strong>19</strong>
								</div>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Partnership</strong>
								</div>
								<div>
									<strong>11</strong>
								</div>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>SACCO / Cooperative</strong>
								</div>
								<div>
									<strong>7</strong>
								</div>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>NGO / Trust</strong>
								</div>
								<div>
									<strong>4</strong>
								</div>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Corporate Group</strong>
								</div>
								<div>
									<strong>3</strong>
								</div>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Foreign Branch</strong>
								</div>
								<div>
									<strong>2</strong>
								</div>
							</div>
						</div>
					</div>
					<div className="col-lg-3">
						<div className={s.utilityBlock}>
							<h4 style={{ fontSize: 14, fontWeight: 700, margin: "0 0 16px" }}>
								Auto-Validation Results
							</h4>
							<div
								className="p-3 rounded mb-2"
								style={{ background: "var(--pm-accent-soft)" }}
							>
								<div
									style={{ fontSize: 11, color: "#047857", fontWeight: 700 }}
								>
									CR12 VERIFIED
								</div>
								<div
									style={{
										fontSize: 22,
										fontWeight: 700,
										color: "var(--pm-accent)",
									}}
								>
									61
								</div>
								<div style={{ fontSize: 12, color: "#065F46" }}>
									Businesses matched with BRS
								</div>
							</div>
							<div
								className="p-3 rounded mb-2"
								style={{ background: "var(--pm-info-soft)" }}
							>
								<div
									style={{ fontSize: 11, color: "#1D4ED8", fontWeight: 700 }}
								>
									KRA PIN VERIFIED
								</div>
								<div
									style={{
										fontSize: 22,
										fontWeight: 700,
										color: "var(--pm-info)",
									}}
								>
									57
								</div>
								<div style={{ fontSize: 12, color: "#1E40AF" }}>
									Active tax status confirmed
								</div>
							</div>
							<div
								className="p-3 rounded"
								style={{ background: "var(--pm-warning-soft)" }}
							>
								<div
									style={{ fontSize: 11, color: "#B45309", fontWeight: 700 }}
								>
									MANUAL REVIEW
								</div>
								<div
									style={{
										fontSize: 22,
										fontWeight: 700,
										color: "var(--pm-warning)",
									}}
								>
									12
								</div>
								<div style={{ fontSize: 12, color: "#92400E" }}>
									Ownership structure complex
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div className={s.card}>
				<div
					className="d-flex justify-content-between align-items-center mb-3 flex-wrap"
					style={{ gap: 8 }}
				>
					<div>
						<h3 className={s.st}>
							<i
								className="bi bi-file-earmark-check"
								style={{ color: "var(--pm-info)" }}
							></i>
							3.12.2 — KYC/KYB Verification & Document Management
						</h3>
						<p className={s.ss}>
							Certificate of incorporation, KRA PIN, TCC, county permits,
							director IDs, beneficial ownership declarations and automated
							compliance scoring.
						</p>
					</div>
					<div className="d-flex" style={{ gap: 8 }}>
						<button
							type="button"
							className={cx(s.btnPm, s.btnSm)}
							onClick={() => onOpen("uploadDocumentModal")}
						>
							<i className="bi bi-upload"></i>Upload
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnSm, s.btnPmP)}
							onClick={() => onOpen("bulkDocumentModal")}
						>
							<i className="bi bi-files"></i>Bulk Upload
						</button>
					</div>
				</div>
				<div className="row g-3">
					<div className="col-lg-8">
						<div className={s.utilityBlock}>
							<h4 style={{ fontSize: 14, fontWeight: 700, margin: "0 0 16px" }}>
								Document Verification Queue{" "}
							</h4>
							<div className="table-responsive">
								<table className={s.tbl}>
									<thead>
										<tr>
											<th>Business</th>
											<th>Document</th>
											<th>Status</th>
											<th>Uploaded</th>
											<th>Expiry</th>
											<th>Action</th>
										</tr>
									</thead>
									<tbody>
										<tr>
											<td data-label="Business">
												<strong>Greenfield Logistics</strong>
											</td>
											<td data-label="Document">TCC (KRA)</td>
											<td data-label="Status">
												<span className={cx(s.badge, s.badgeW)}>
													Pending Review
												</span>
											</td>
											<td data-label="Uploaded">25 Jun 2025</td>
											<td data-label="Expiry">30 Jun 2025</td>
											<td data-label="Action">
												<button
													type="button"
													className={cx(s.btnPm, s.btnSm)}
													onClick={() => onOpen("verifyDocumentModal")}
												>
													Review
												</button>
											</td>
										</tr>
										<tr>
											<td data-label="Business">
												<strong>Shalom SACCO</strong>
											</td>
											<td data-label="Document">Certificate of Registration</td>
											<td data-label="Status">
												<span className={cx(s.badge, s.badgeS)}>Verified</span>
											</td>
											<td data-label="Uploaded">20 Jun 2025</td>
											<td data-label="Expiry">—</td>
											<td data-label="Action">
												<button
													type="button"
													className={cx(s.btnPm, s.btnSm)}
													onClick={() => onOpen("viewDocumentModal")}
												>
													View
												</button>
											</td>
										</tr>
										<tr>
											<td data-label="Business">
												<strong>Mama Mboga Traders</strong>
											</td>
											<td data-label="Document">
												County Single Business Permit
											</td>
											<td data-label="Status">
												<span className={cx(s.badge, s.badgeW)}>
													Pending Review
												</span>
											</td>
											<td data-label="Uploaded">26 Jun 2025</td>
											<td data-label="Expiry">31 Dec 2025</td>
											<td data-label="Action">
												<button
													type="button"
													className={cx(s.btnPm, s.btnSm)}
													onClick={() => onOpen("verifyDocumentModal")}
												>
													Review
												</button>
											</td>
										</tr>
										<tr>
											<td data-label="Business">
												<strong>TechNova Solutions</strong>
											</td>
											<td data-label="Document">Director ID (Huduma)</td>
											<td data-label="Status">
												<span className={cx(s.badge, s.badgeI)}>
													OCR Complete
												</span>
											</td>
											<td data-label="Uploaded">24 Jun 2025</td>
											<td data-label="Expiry">—</td>
											<td data-label="Action">
												<button
													type="button"
													className={cx(s.btnPm, s.btnSm)}
													onClick={() => onOpen("directorKYCModal")}
												>
													Verify
												</button>
											</td>
										</tr>
										<tr>
											<td data-label="Business">
												<strong>Hope Children NGO</strong>
											</td>
											<td data-label="Document">CR12 Extract</td>
											<td data-label="Status">
												<span className={cx(s.badge, s.badgeS)}>Verified</span>
											</td>
											<td data-label="Uploaded">18 Jun 2025</td>
											<td data-label="Expiry">—</td>
											<td data-label="Action">
												<button
													type="button"
													className={cx(s.btnPm, s.btnSm)}
													onClick={() => onOpen("viewDocumentModal")}
												>
													View
												</button>
											</td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
					</div>
					<div className="col-lg-4">
						<div className={s.utilityBlock}>
							<h4 style={{ fontSize: 14, fontWeight: 700, margin: "0 0 16px" }}>
								Document Types Tracked
							</h4>
							<div className={s.statusRow}>
								<div>
									<strong>Certificate of Incorporation</strong>
								</div>
								<div>
									<span className={cx(s.badge, s.badgeS)}>61</span>
								</div>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>KRA PIN Certificate</strong>
								</div>
								<div>
									<span className={cx(s.badge, s.badgeS)}>57</span>
								</div>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Tax Compliance Certificate</strong>
								</div>
								<div>
									<span className={cx(s.badge, s.badgeW)}>38</span>
								</div>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>County Business Permit</strong>
								</div>
								<div>
									<span className={cx(s.badge, s.badgeW)}>29</span>
								</div>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Director IDs (Huduma/Passport)</strong>
								</div>
								<div>
									<span className={cx(s.badge, s.badgeI)}>84</span>
								</div>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Beneficial Ownership Declaration</strong>
								</div>
								<div>
									<span className={cx(s.badge, s.badgeS)}>52</span>
								</div>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>CR12 Extract</strong>
								</div>
								<div>
									<span className={cx(s.badge, s.badgeS)}>61</span>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div className={s.card}>
				<div
					className="d-flex justify-content-between align-items-center mb-3 flex-wrap"
					style={{ gap: 8 }}
				>
					<div>
						<h3 className={s.st}>
							<i
								className="bi bi-people"
								style={{ color: "var(--pm-purple)" }}
							></i>
							3.12.3 — Beneficial Ownership & Director Verification
						</h3>
						<p className={s.ss}>
							Ultimate beneficial owner (UBO) declaration, 25%+ ownership
							threshold tracking, director KYC, PEP screening and automated
							compliance scoring.
						</p>
					</div>
					<div className="d-flex" style={{ gap: 8 }}>
						<button
							type="button"
							className={cx(s.btnPm, s.btnSm)}
							onClick={() => onOpen("beneficialOwnerModal")}
						>
							<i className="bi bi-people"></i>Add UBO
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnSm)}
							onClick={() => onOpen("directorKYCModal")}
						>
							<i className="bi bi-person-badge"></i>Director KYC
						</button>
					</div>
				</div>
				<div className="row g-3">
					<div className="col-lg-6">
						<div className={s.utilityBlock}>
							<h4 style={{ fontSize: 14, fontWeight: 700, margin: "0 0 16px" }}>
								Beneficial Ownership Dashboard
							</h4>
							<div className={s.statusRow}>
								<div>
									<strong>Greenfield Logistics Ltd</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										5 shareholders · 3 UBOs declared
									</div>
								</div>
								<span className={cx(s.badge, s.badgeS)}>Complete</span>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Shalom SACCO</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										12 board members · 2 UBOs{" "}
									</div>
								</div>
								<span className={cx(s.badge, s.badgeW)}>Pending</span>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>TechNova Solutions</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										3 shareholders · 2 UBOs
									</div>
								</div>
								<span className={cx(s.badge, s.badgeS)}>Complete</span>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Hope Children NGO</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										7 trustees · 1 UBO
									</div>
								</div>
								<span className={cx(s.badge, s.badgeS)}>Complete</span>
							</div>
						</div>
					</div>
					<div className="col-lg-6">
						<div className={s.utilityBlock}>
							<h4 style={{ fontSize: 14, fontWeight: 700, margin: "0 0 16px" }}>
								Director Verification Status{" "}
							</h4>
							<div className={s.statusRow}>
								<div>
									<strong>Peter Ochieng — Greenfield</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										Huduma ID uploaded · PEP check passed
									</div>
								</div>
								<span className={cx(s.badge, s.badgeS)}>Verified</span>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Grace Wanjiku — TechNova</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										Passport uploaded · Awaiting selfie
									</div>
								</div>
								<span className={cx(s.badge, s.badgeI)}>OCR Done</span>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>John Kamau — Shalom SACCO</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										No documents received
									</div>
								</div>
								<span className={cx(s.badge, s.badgeD)}>Missing</span>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Fatima Ali — Hope Children</strong>
									<div style={{ fontSize: 11, color: "var(--pm-muted)" }}>
										ID + selfie verified
									</div>
								</div>
								<span className={cx(s.badge, s.badgeS)}>Verified</span>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div className={s.card}>
				<div
					className="d-flex justify-content-between align-items-center mb-3 flex-wrap"
					style={{ gap: 8 }}
				>
					<div>
						<h3 className={s.st}>
							<i
								className="bi bi-clipboard-check"
								style={{ color: "var(--pm-accent)" }}
							></i>
							3.12.4 — Onboarding Status, Approvals & Ongoing Monitoring
						</h3>
						<p className={s.ss}>
							Real-time onboarding status, multi-level approval workflows,
							compliance scoring, expiry monitoring and automated renewal
							triggers.
						</p>
					</div>
					<div className="d-flex" style={{ gap: 8 }}>
						<button
							type="button"
							className={cx(s.btnPm, s.btnSm)}
							onClick={() => onOpen("approvalQueueModal")}
						>
							<i className="bi bi-check2-all"></i>Approvals
						</button>
						<button
							type="button"
							className={cx(s.btnPm, s.btnSm)}
							onClick={() => onOpen("complianceCheckModal")}
						>
							<i className="bi bi-shield-check"></i>Compliance
						</button>
					</div>
				</div>
				<div className="row g-3">
					<div className="col-lg-4">
						<div className={s.utilityBlock}>
							<h4 style={{ fontSize: 14, fontWeight: 700, margin: "0 0 16px" }}>
								Onboarding Status
							</h4>
							<div className={s.statusRow}>
								<div>
									<strong>Completed & Active</strong>
								</div>
								<div>
									<strong>84</strong>
								</div>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Pending Director KYC</strong>
								</div>
								<div>
									<strong>7</strong>
								</div>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Pending Document Review</strong>
								</div>
								<div>
									<strong>11</strong>
								</div>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Under Compliance Review</strong>
								</div>
								<div>
									<strong>4</strong>
								</div>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Rejected / Withdrawn</strong>
								</div>
								<div>
									<strong>3</strong>
								</div>
							</div>
						</div>
					</div>
					<div className="col-lg-4">
						<div className={s.utilityBlock}>
							<h4 style={{ fontSize: 14, fontWeight: 700, margin: "0 0 16px" }}>
								Approval Workflow
							</h4>
							<div className={s.statusRow}>
								<div>
									<strong>Level 1 — Intake Officer</strong>
								</div>
								<div>
									<span className={cx(s.badge, s.badgeS)}>42</span>
								</div>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Level 2 — Compliance Analyst</strong>
								</div>
								<div>
									<span className={cx(s.badge, s.badgeW)}>18</span>
								</div>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Level 3 — Senior Compliance</strong>
								</div>
								<div>
									<span className={cx(s.badge, s.badgeI)}>9</span>
								</div>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Level 4 — Head of Compliance</strong>
								</div>
								<div>
									<span className={cx(s.badge, s.badgeP)}>3</span>
								</div>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Board Approval Required</strong>
								</div>
								<div>
									<span className={cx(s.badge, s.badgeD)}>2</span>
								</div>
							</div>
						</div>
					</div>
					<div className="col-lg-4">
						<div className={s.utilityBlock}>
							<h4 style={{ fontSize: 14, fontWeight: 700, margin: "0 0 16px" }}>
								Compliance Alerts
							</h4>
							<div className={s.statusRow}>
								<div>
									<strong>TCC Expiring (30 days)</strong>
								</div>
								<div>
									<strong>7</strong>
								</div>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>County Permit Expiring</strong>
								</div>
								<div>
									<strong>3</strong>
								</div>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Director ID Expiring</strong>
								</div>
								<div>
									<strong>1</strong>
								</div>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>PEP Flag Review</strong>
								</div>
								<div>
									<strong>2</strong>
								</div>
							</div>
							<div className={s.statusRow}>
								<div>
									<strong>Adverse Media Alert</strong>
								</div>
								<div>
									<strong>1</strong>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div className={s.card}>
				<div className="d-flex justify-content-between align-items-center mb-3">
					<h3 className={s.st}>
						<i
							className="bi bi-clock-history"
							style={{ color: "var(--pm-muted)" }}
						></i>
						Recent Onboarding Activity
					</h3>
					<button
						type="button"
						className={cx(s.btnPm, s.btnSm)}
						onClick={() => onOpen("auditTrailModal")}
					>
						View Full Audit
					</button>
				</div>
				<div className="table-responsive">
					<table className={s.tbl}>
						<thead>
							<tr>
								<th>Date</th>
								<th>Business</th>
								<th>Action</th>
								<th>User</th>
								<th>Status</th>
								<th>Reference</th>
								<th>Action</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td data-label="Date">27 Jun 2025</td>
								<td data-label="Business">Greenfield Logistics</td>
								<td data-label="Action">TCC Upload</td>
								<td data-label="User">Compliance Analyst</td>
								<td data-label="Status">
									<span className={cx(s.badge, s.badgeW)}>Under Review</span>
								</td>
								<td data-label="Reference">DOC-88291</td>
								<td data-label="Action">
									<button
										type="button"
										className={cx(s.btnPm, s.btnSm)}
										onClick={() => onOpen("verifyDocumentModal")}
									>
										Review
									</button>
								</td>
							</tr>
							<tr>
								<td data-label="Date">26 Jun 2025</td>
								<td data-label="Business">Shalom SACCO</td>
								<td data-label="Action">Director KYC Verified</td>
								<td data-label="User">James M.</td>
								<td data-label="Status">
									<span className={cx(s.badge, s.badgeS)}>Verified</span>
								</td>
								<td data-label="Reference">KYC-99102</td>
								<td data-label="Action">
									<button
										type="button"
										className={cx(s.btnPm, s.btnSm)}
										onClick={() => onOpen("directorKYCModal")}
									>
										View
									</button>
								</td>
							</tr>
							<tr>
								<td data-label="Date">26 Jun 2025</td>
								<td data-label="Business">TechNova Solutions</td>
								<td data-label="Action">Beneficial Owner Added</td>
								<td data-label="User">Compliance Analyst</td>
								<td data-label="Status">
									<span className={cx(s.badge, s.badgeS)}>Complete</span>
								</td>
								<td data-label="Reference">UBO-99128</td>
								<td data-label="Action">
									<button
										type="button"
										className={cx(s.btnPm, s.btnSm)}
										onClick={() => onOpen("beneficialOwnerModal")}
									>
										View
									</button>
								</td>
							</tr>
							<tr>
								<td data-label="Date">25 Jun 2025</td>
								<td data-label="Business">Mama Mboga Traders</td>
								<td data-label="Action">Application Submitted</td>
								<td data-label="User">Self-Service</td>
								<td data-label="Status">
									<span className={cx(s.badge, s.badgeD)}>Incomplete</span>
								</td>
								<td data-label="Reference">APP-77192</td>
								<td data-label="Action">
									<button
										type="button"
										className={cx(s.btnPm, s.btnSm)}
										onClick={() => onOpen("onboardNewModal")}
									>
										Continue
									</button>
								</td>
							</tr>
							<tr>
								<td data-label="Date">24 Jun 2025</td>
								<td data-label="Business">Hope Children NGO</td>
								<td data-label="Action">Approved</td>
								<td data-label="User">Head of Compliance</td>
								<td data-label="Status">
									<span className={cx(s.badge, s.badgeS)}>Active</span>
								</td>
								<td data-label="Reference">APP-44821</td>
								<td data-label="Action">
									<button
										type="button"
										className={cx(s.btnPm, s.btnSm)}
										onClick={() => onOpen("viewBusinessModal")}
									>
										View
									</button>
								</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</>
	);
}
