/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UtilityRouteImport } from './routes/utility'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DevDashboardRouteImport } from './routes/dev-dashboard'
import { Route as DevRouteImport } from './routes/dev'
import { Route as BusinessDashboardRouteImport } from './routes/business-dashboard'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as HomeRouteImport } from './routes/_home'
import { Route as UtilityIndexRouteImport } from './routes/utility/index'
import { Route as DevIndexRouteImport } from './routes/dev/index'
import { Route as DevDashboardIndexRouteImport } from './routes/dev-dashboard/index'
import { Route as BusinessIndexRouteImport } from './routes/business/index'
import { Route as BusinessDashboardIndexRouteImport } from './routes/business-dashboard/index'
import { Route as HomeIndexRouteImport } from './routes/_home/index'
import { Route as UtilityWaterRouteImport } from './routes/utility/water'
import { Route as UtilitySettingsRouteImport } from './routes/utility/settings'
import { Route as UtilityInternetRouteImport } from './routes/utility/internet'
import { Route as UtilityElectricityRouteImport } from './routes/utility/electricity'
import { Route as UtilityAirtimeRouteImport } from './routes/utility/airtime'
import { Route as UtilityModuleRouteImport } from './routes/utility/$module'
import { Route as Transaction_dashboardAppRouteImport } from './routes/transaction_dashboard/app'
import { Route as DevModuleRouteImport } from './routes/dev/$module'
import { Route as DevDashboardWebhooksEventsRouteImport } from './routes/dev-dashboard/webhooks-events'
import { Route as DevDashboardSupportSlasRouteImport } from './routes/dev-dashboard/support-slas'
import { Route as DevDashboardSecurityRouteImport } from './routes/dev-dashboard/security'
import { Route as DevDashboardSdksRouteImport } from './routes/dev-dashboard/sdks'
import { Route as DevDashboardPlaygroundRouteImport } from './routes/dev-dashboard/playground'
import { Route as DevDashboardPartnerMarketplaceRouteImport } from './routes/dev-dashboard/partner-marketplace'
import { Route as DevDashboardMonitoringIncidentsRouteImport } from './routes/dev-dashboard/monitoring-incidents'
import { Route as DevDashboardIntegrationArchitectureRouteImport } from './routes/dev-dashboard/integration-architecture'
import { Route as DevDashboardDeveloperDashboardRouteImport } from './routes/dev-dashboard/developer-dashboard'
import { Route as DevDashboardComplianceAuditRouteImport } from './routes/dev-dashboard/compliance-audit'
import { Route as DevDashboardApiReferenceRouteImport } from './routes/dev-dashboard/api-reference'
import { Route as DevDashboardApiGovernanceRouteImport } from './routes/dev-dashboard/api-governance'
import { Route as CardsAppRouteImport } from './routes/cards/app'
import { Route as BusinessModuleRouteImport } from './routes/business/$module'
import { Route as BusinessDashboardVirtualAccountsRouteImport } from './routes/business-dashboard/virtual-accounts'
import { Route as BusinessDashboardTreasuryCashRouteImport } from './routes/business-dashboard/treasury-cash'
import { Route as BusinessDashboardSupportDisputesRouteImport } from './routes/business-dashboard/support-disputes'
import { Route as BusinessDashboardSettingsAdministrationRouteImport } from './routes/business-dashboard/settings-administration'
import { Route as BusinessDashboardPayrollHrRouteImport } from './routes/business-dashboard/payroll-hr'
import { Route as BusinessDashboardOpenBankingRouteImport } from './routes/business-dashboard/open-banking'
import { Route as BusinessDashboardMultiCurrencyTreasuryRouteImport } from './routes/business-dashboard/multi-currency-treasury'
import { Route as BusinessDashboardInvoicingBillingRouteImport } from './routes/business-dashboard/invoicing-billing'
import { Route as BusinessDashboardFinancialReportingRouteImport } from './routes/business-dashboard/financial-reporting'
import { Route as BusinessDashboardCommandCenterRouteImport } from './routes/business-dashboard/command-center'
import { Route as BusinessDashboardCollectionsMerchantRouteImport } from './routes/business-dashboard/collections-merchant'
import { Route as BusinessDashboardBusinessOnboardingRouteImport } from './routes/business-dashboard/business-onboarding'
import { Route as BusinessDashboardBulkDisbursementsRouteImport } from './routes/business-dashboard/bulk-disbursements'
import { Route as BusinessDashboardAccountsPayableRouteImport } from './routes/business-dashboard/accounts-payable'
import { Route as BusinessDashboardModuleRouteImport } from './routes/business-dashboard/$module'
import { Route as AuthSecurityRouteImport } from './routes/auth/security'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthRecoveryRouteImport } from './routes/auth/recovery'
import { Route as AuthPasskeysRouteImport } from './routes/auth/passkeys'
import { Route as AuthMfaRouteImport } from './routes/auth/mfa'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthIdentityRouteImport } from './routes/auth/identity'
import { Route as AuthHubRouteImport } from './routes/auth/hub'
import { Route as AuthAccountStatusRouteImport } from './routes/auth/account-status'
import { Route as HomeBusinessRouteImport } from './routes/_home/business'
import { Route as Transaction_dashboardAppIndexRouteImport } from './routes/transaction_dashboard/app.index'
import { Route as Transaction_dashboardAppTransfersRouteImport } from './routes/transaction_dashboard/app.transfers'
import { Route as Transaction_dashboardAppTransferOverviewRouteImport } from './routes/transaction_dashboard/app.transfer-overview'
import { Route as Transaction_dashboardAppTransferManagementRouteImport } from './routes/transaction_dashboard/app.transfer-management'
import { Route as Transaction_dashboardAppSettlementRouteImport } from './routes/transaction_dashboard/app.settlement'
import { Route as Transaction_dashboardAppSettingsRouteImport } from './routes/transaction_dashboard/app.settings'
import { Route as Transaction_dashboardAppReconciliationRouteImport } from './routes/transaction_dashboard/app.reconciliation'
import { Route as Transaction_dashboardAppPaymentRailsRouteImport } from './routes/transaction_dashboard/app.payment-rails'
import { Route as Transaction_dashboardAppOpsHealthRouteImport } from './routes/transaction_dashboard/app.ops-health'
import { Route as Transaction_dashboardAppMobileMoneyRouteImport } from './routes/transaction_dashboard/app.mobile-money'
import { Route as Transaction_dashboardAppLiquidityRouteImport } from './routes/transaction_dashboard/app.liquidity'
import { Route as Transaction_dashboardAppKraGovernmentRouteImport } from './routes/transaction_dashboard/app.kra-government'
import { Route as Transaction_dashboardAppInitiateTransferRouteImport } from './routes/transaction_dashboard/app.initiate-transfer'
import { Route as Transaction_dashboardAppFxRouteImport } from './routes/transaction_dashboard/app.fx'
import { Route as Transaction_dashboardAppFeesRouteImport } from './routes/transaction_dashboard/app.fees'
import { Route as Transaction_dashboardAppDisputesRouteImport } from './routes/transaction_dashboard/app.disputes'
import { Route as Transaction_dashboardAppCustomersRouteImport } from './routes/transaction_dashboard/app.customers'
import { Route as Transaction_dashboardAppComplianceRouteImport } from './routes/transaction_dashboard/app.compliance'
import { Route as Transaction_dashboardAppAnalyticsRouteImport } from './routes/transaction_dashboard/app.analytics'
import { Route as Transaction_dashboardAppAccountRouteImport } from './routes/transaction_dashboard/app.account'
import { Route as Transaction_dashboardAppSectionRouteImport } from './routes/transaction_dashboard/app.$section'
import { Route as CardsAppVirtualDebitCardsRouteImport } from './routes/cards/app/virtual-debit-cards'
import { Route as CardsAppVirtualCreditCardsRouteImport } from './routes/cards/app/virtual-credit-cards'
import { Route as CardsAppSupportRouteImport } from './routes/cards/app/support'
import { Route as CardsAppPrepaidCardManagementRouteImport } from './routes/cards/app/prepaid-card-management'
import { Route as CardsAppPhysicalDebitCardsRouteImport } from './routes/cards/app/physical-debit-cards'
import { Route as CardsAppCorporateBusinessCardsRouteImport } from './routes/cards/app/corporate-business-cards'
import { Route as CardsAppCardSettingsSupportRouteImport } from './routes/cards/app/card-settings-support'
import { Route as CardsAppCardSecurityFraudPreventionRouteImport } from './routes/cards/app/card-security-fraud-prevention'
import { Route as CardsAppCardProgramAdministrationRouteImport } from './routes/cards/app/card-program-administration'
import { Route as CardsAppCardCommandCenterRouteImport } from './routes/cards/app/card-command-center'
import { Route as CardsAppCardAnalyticsReportingRouteImport } from './routes/cards/app/card-analytics-reporting'
import { Route as CardsAppAccountSettingsRouteImport } from './routes/cards/app/account-settings'

const UtilityRoute = UtilityRouteImport.update({
  id: '/utility',
  path: '/utility',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DevDashboardRoute = DevDashboardRouteImport.update({
  id: '/dev-dashboard',
  path: '/dev-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessDashboardRoute = BusinessDashboardRouteImport.update({
  id: '/business-dashboard',
  path: '/business-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilityIndexRoute = UtilityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UtilityRoute,
} as any)
const DevIndexRoute = DevIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevRoute,
} as any)
const DevDashboardIndexRoute = DevDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevDashboardRoute,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessDashboardIndexRoute = BusinessDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BusinessDashboardRoute,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRoute,
} as any)
const UtilityWaterRoute = UtilityWaterRouteImport.update({
  id: '/water',
  path: '/water',
  getParentRoute: () => UtilityRoute,
} as any)
const UtilitySettingsRoute = UtilitySettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => UtilityRoute,
} as any)
const UtilityInternetRoute = UtilityInternetRouteImport.update({
  id: '/internet',
  path: '/internet',
  getParentRoute: () => UtilityRoute,
} as any)
const UtilityElectricityRoute = UtilityElectricityRouteImport.update({
  id: '/electricity',
  path: '/electricity',
  getParentRoute: () => UtilityRoute,
} as any)
const UtilityAirtimeRoute = UtilityAirtimeRouteImport.update({
  id: '/airtime',
  path: '/airtime',
  getParentRoute: () => UtilityRoute,
} as any)
const UtilityModuleRoute = UtilityModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => UtilityRoute,
} as any)
const Transaction_dashboardAppRoute =
  Transaction_dashboardAppRouteImport.update({
    id: '/transaction_dashboard/app',
    path: '/transaction_dashboard/app',
    getParentRoute: () => rootRouteImport,
  } as any)
const DevModuleRoute = DevModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => DevRoute,
} as any)
const DevDashboardWebhooksEventsRoute =
  DevDashboardWebhooksEventsRouteImport.update({
    id: '/webhooks-events',
    path: '/webhooks-events',
    getParentRoute: () => DevDashboardRoute,
  } as any)
const DevDashboardSupportSlasRoute = DevDashboardSupportSlasRouteImport.update({
  id: '/support-slas',
  path: '/support-slas',
  getParentRoute: () => DevDashboardRoute,
} as any)
const DevDashboardSecurityRoute = DevDashboardSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DevDashboardRoute,
} as any)
const DevDashboardSdksRoute = DevDashboardSdksRouteImport.update({
  id: '/sdks',
  path: '/sdks',
  getParentRoute: () => DevDashboardRoute,
} as any)
const DevDashboardPlaygroundRoute = DevDashboardPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => DevDashboardRoute,
} as any)
const DevDashboardPartnerMarketplaceRoute =
  DevDashboardPartnerMarketplaceRouteImport.update({
    id: '/partner-marketplace',
    path: '/partner-marketplace',
    getParentRoute: () => DevDashboardRoute,
  } as any)
const DevDashboardMonitoringIncidentsRoute =
  DevDashboardMonitoringIncidentsRouteImport.update({
    id: '/monitoring-incidents',
    path: '/monitoring-incidents',
    getParentRoute: () => DevDashboardRoute,
  } as any)
const DevDashboardIntegrationArchitectureRoute =
  DevDashboardIntegrationArchitectureRouteImport.update({
    id: '/integration-architecture',
    path: '/integration-architecture',
    getParentRoute: () => DevDashboardRoute,
  } as any)
const DevDashboardDeveloperDashboardRoute =
  DevDashboardDeveloperDashboardRouteImport.update({
    id: '/developer-dashboard',
    path: '/developer-dashboard',
    getParentRoute: () => DevDashboardRoute,
  } as any)
const DevDashboardComplianceAuditRoute =
  DevDashboardComplianceAuditRouteImport.update({
    id: '/compliance-audit',
    path: '/compliance-audit',
    getParentRoute: () => DevDashboardRoute,
  } as any)
const DevDashboardApiReferenceRoute =
  DevDashboardApiReferenceRouteImport.update({
    id: '/api-reference',
    path: '/api-reference',
    getParentRoute: () => DevDashboardRoute,
  } as any)
const DevDashboardApiGovernanceRoute =
  DevDashboardApiGovernanceRouteImport.update({
    id: '/api-governance',
    path: '/api-governance',
    getParentRoute: () => DevDashboardRoute,
  } as any)
const CardsAppRoute = CardsAppRouteImport.update({
  id: '/cards/app',
  path: '/cards/app',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessModuleRoute = BusinessModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessDashboardVirtualAccountsRoute =
  BusinessDashboardVirtualAccountsRouteImport.update({
    id: '/virtual-accounts',
    path: '/virtual-accounts',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardTreasuryCashRoute =
  BusinessDashboardTreasuryCashRouteImport.update({
    id: '/treasury-cash',
    path: '/treasury-cash',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardSupportDisputesRoute =
  BusinessDashboardSupportDisputesRouteImport.update({
    id: '/support-disputes',
    path: '/support-disputes',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardSettingsAdministrationRoute =
  BusinessDashboardSettingsAdministrationRouteImport.update({
    id: '/settings-administration',
    path: '/settings-administration',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardPayrollHrRoute =
  BusinessDashboardPayrollHrRouteImport.update({
    id: '/payroll-hr',
    path: '/payroll-hr',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardOpenBankingRoute =
  BusinessDashboardOpenBankingRouteImport.update({
    id: '/open-banking',
    path: '/open-banking',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardMultiCurrencyTreasuryRoute =
  BusinessDashboardMultiCurrencyTreasuryRouteImport.update({
    id: '/multi-currency-treasury',
    path: '/multi-currency-treasury',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardInvoicingBillingRoute =
  BusinessDashboardInvoicingBillingRouteImport.update({
    id: '/invoicing-billing',
    path: '/invoicing-billing',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardFinancialReportingRoute =
  BusinessDashboardFinancialReportingRouteImport.update({
    id: '/financial-reporting',
    path: '/financial-reporting',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardCommandCenterRoute =
  BusinessDashboardCommandCenterRouteImport.update({
    id: '/command-center',
    path: '/command-center',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardCollectionsMerchantRoute =
  BusinessDashboardCollectionsMerchantRouteImport.update({
    id: '/collections-merchant',
    path: '/collections-merchant',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardBusinessOnboardingRoute =
  BusinessDashboardBusinessOnboardingRouteImport.update({
    id: '/business-onboarding',
    path: '/business-onboarding',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardBulkDisbursementsRoute =
  BusinessDashboardBulkDisbursementsRouteImport.update({
    id: '/bulk-disbursements',
    path: '/bulk-disbursements',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardAccountsPayableRoute =
  BusinessDashboardAccountsPayableRouteImport.update({
    id: '/accounts-payable',
    path: '/accounts-payable',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardModuleRoute = BusinessDashboardModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => BusinessDashboardRoute,
} as any)
const AuthSecurityRoute = AuthSecurityRouteImport.update({
  id: '/auth/security',
  path: '/auth/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRecoveryRoute = AuthRecoveryRouteImport.update({
  id: '/auth/recovery',
  path: '/auth/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPasskeysRoute = AuthPasskeysRouteImport.update({
  id: '/auth/passkeys',
  path: '/auth/passkeys',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMfaRoute = AuthMfaRouteImport.update({
  id: '/auth/mfa',
  path: '/auth/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIdentityRoute = AuthIdentityRouteImport.update({
  id: '/auth/identity',
  path: '/auth/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthHubRoute = AuthHubRouteImport.update({
  id: '/auth/hub',
  path: '/auth/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAccountStatusRoute = AuthAccountStatusRouteImport.update({
  id: '/auth/account-status',
  path: '/auth/account-status',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeBusinessRoute = HomeBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => HomeRoute,
} as any)
const Transaction_dashboardAppIndexRoute =
  Transaction_dashboardAppIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Transaction_dashboardAppRoute,
  } as any)
const Transaction_dashboardAppTransfersRoute =
  Transaction_dashboardAppTransfersRouteImport.update({
    id: '/transfers',
    path: '/transfers',
    getParentRoute: () => Transaction_dashboardAppRoute,
  } as any)
const Transaction_dashboardAppTransferOverviewRoute =
  Transaction_dashboardAppTransferOverviewRouteImport.update({
    id: '/transfer-overview',
    path: '/transfer-overview',
    getParentRoute: () => Transaction_dashboardAppRoute,
  } as any)
const Transaction_dashboardAppTransferManagementRoute =
  Transaction_dashboardAppTransferManagementRouteImport.update({
    id: '/transfer-management',
    path: '/transfer-management',
    getParentRoute: () => Transaction_dashboardAppRoute,
  } as any)
const Transaction_dashboardAppSettlementRoute =
  Transaction_dashboardAppSettlementRouteImport.update({
    id: '/settlement',
    path: '/settlement',
    getParentRoute: () => Transaction_dashboardAppRoute,
  } as any)
const Transaction_dashboardAppSettingsRoute =
  Transaction_dashboardAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => Transaction_dashboardAppRoute,
  } as any)
const Transaction_dashboardAppReconciliationRoute =
  Transaction_dashboardAppReconciliationRouteImport.update({
    id: '/reconciliation',
    path: '/reconciliation',
    getParentRoute: () => Transaction_dashboardAppRoute,
  } as any)
const Transaction_dashboardAppPaymentRailsRoute =
  Transaction_dashboardAppPaymentRailsRouteImport.update({
    id: '/payment-rails',
    path: '/payment-rails',
    getParentRoute: () => Transaction_dashboardAppRoute,
  } as any)
const Transaction_dashboardAppOpsHealthRoute =
  Transaction_dashboardAppOpsHealthRouteImport.update({
    id: '/ops-health',
    path: '/ops-health',
    getParentRoute: () => Transaction_dashboardAppRoute,
  } as any)
const Transaction_dashboardAppMobileMoneyRoute =
  Transaction_dashboardAppMobileMoneyRouteImport.update({
    id: '/mobile-money',
    path: '/mobile-money',
    getParentRoute: () => Transaction_dashboardAppRoute,
  } as any)
const Transaction_dashboardAppLiquidityRoute =
  Transaction_dashboardAppLiquidityRouteImport.update({
    id: '/liquidity',
    path: '/liquidity',
    getParentRoute: () => Transaction_dashboardAppRoute,
  } as any)
const Transaction_dashboardAppKraGovernmentRoute =
  Transaction_dashboardAppKraGovernmentRouteImport.update({
    id: '/kra-government',
    path: '/kra-government',
    getParentRoute: () => Transaction_dashboardAppRoute,
  } as any)
const Transaction_dashboardAppInitiateTransferRoute =
  Transaction_dashboardAppInitiateTransferRouteImport.update({
    id: '/initiate-transfer',
    path: '/initiate-transfer',
    getParentRoute: () => Transaction_dashboardAppRoute,
  } as any)
const Transaction_dashboardAppFxRoute =
  Transaction_dashboardAppFxRouteImport.update({
    id: '/fx',
    path: '/fx',
    getParentRoute: () => Transaction_dashboardAppRoute,
  } as any)
const Transaction_dashboardAppFeesRoute =
  Transaction_dashboardAppFeesRouteImport.update({
    id: '/fees',
    path: '/fees',
    getParentRoute: () => Transaction_dashboardAppRoute,
  } as any)
const Transaction_dashboardAppDisputesRoute =
  Transaction_dashboardAppDisputesRouteImport.update({
    id: '/disputes',
    path: '/disputes',
    getParentRoute: () => Transaction_dashboardAppRoute,
  } as any)
const Transaction_dashboardAppCustomersRoute =
  Transaction_dashboardAppCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => Transaction_dashboardAppRoute,
  } as any)
const Transaction_dashboardAppComplianceRoute =
  Transaction_dashboardAppComplianceRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => Transaction_dashboardAppRoute,
  } as any)
const Transaction_dashboardAppAnalyticsRoute =
  Transaction_dashboardAppAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => Transaction_dashboardAppRoute,
  } as any)
const Transaction_dashboardAppAccountRoute =
  Transaction_dashboardAppAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => Transaction_dashboardAppRoute,
  } as any)
const Transaction_dashboardAppSectionRoute =
  Transaction_dashboardAppSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => Transaction_dashboardAppRoute,
  } as any)
const CardsAppVirtualDebitCardsRoute =
  CardsAppVirtualDebitCardsRouteImport.update({
    id: '/virtual-debit-cards',
    path: '/virtual-debit-cards',
    getParentRoute: () => CardsAppRoute,
  } as any)
const CardsAppVirtualCreditCardsRoute =
  CardsAppVirtualCreditCardsRouteImport.update({
    id: '/virtual-credit-cards',
    path: '/virtual-credit-cards',
    getParentRoute: () => CardsAppRoute,
  } as any)
const CardsAppSupportRoute = CardsAppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => CardsAppRoute,
} as any)
const CardsAppPrepaidCardManagementRoute =
  CardsAppPrepaidCardManagementRouteImport.update({
    id: '/prepaid-card-management',
    path: '/prepaid-card-management',
    getParentRoute: () => CardsAppRoute,
  } as any)
const CardsAppPhysicalDebitCardsRoute =
  CardsAppPhysicalDebitCardsRouteImport.update({
    id: '/physical-debit-cards',
    path: '/physical-debit-cards',
    getParentRoute: () => CardsAppRoute,
  } as any)
const CardsAppCorporateBusinessCardsRoute =
  CardsAppCorporateBusinessCardsRouteImport.update({
    id: '/corporate-business-cards',
    path: '/corporate-business-cards',
    getParentRoute: () => CardsAppRoute,
  } as any)
const CardsAppCardSettingsSupportRoute =
  CardsAppCardSettingsSupportRouteImport.update({
    id: '/card-settings-support',
    path: '/card-settings-support',
    getParentRoute: () => CardsAppRoute,
  } as any)
const CardsAppCardSecurityFraudPreventionRoute =
  CardsAppCardSecurityFraudPreventionRouteImport.update({
    id: '/card-security-fraud-prevention',
    path: '/card-security-fraud-prevention',
    getParentRoute: () => CardsAppRoute,
  } as any)
const CardsAppCardProgramAdministrationRoute =
  CardsAppCardProgramAdministrationRouteImport.update({
    id: '/card-program-administration',
    path: '/card-program-administration',
    getParentRoute: () => CardsAppRoute,
  } as any)
const CardsAppCardCommandCenterRoute =
  CardsAppCardCommandCenterRouteImport.update({
    id: '/card-command-center',
    path: '/card-command-center',
    getParentRoute: () => CardsAppRoute,
  } as any)
const CardsAppCardAnalyticsReportingRoute =
  CardsAppCardAnalyticsReportingRouteImport.update({
    id: '/card-analytics-reporting',
    path: '/card-analytics-reporting',
    getParentRoute: () => CardsAppRoute,
  } as any)
const CardsAppAccountSettingsRoute = CardsAppAccountSettingsRouteImport.update({
  id: '/account-settings',
  path: '/account-settings',
  getParentRoute: () => CardsAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof HomeIndexRoute
  '/business': typeof HomeBusinessRoute
  '/business-dashboard': typeof BusinessDashboardRouteWithChildren
  '/dev': typeof DevRouteWithChildren
  '/dev-dashboard': typeof DevDashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/utility': typeof UtilityRouteWithChildren
  '/auth/account-status': typeof AuthAccountStatusRoute
  '/auth/hub': typeof AuthHubRoute
  '/auth/identity': typeof AuthIdentityRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/mfa': typeof AuthMfaRoute
  '/auth/passkeys': typeof AuthPasskeysRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/security': typeof AuthSecurityRoute
  '/business-dashboard/$module': typeof BusinessDashboardModuleRoute
  '/business-dashboard/accounts-payable': typeof BusinessDashboardAccountsPayableRoute
  '/business-dashboard/bulk-disbursements': typeof BusinessDashboardBulkDisbursementsRoute
  '/business-dashboard/business-onboarding': typeof BusinessDashboardBusinessOnboardingRoute
  '/business-dashboard/collections-merchant': typeof BusinessDashboardCollectionsMerchantRoute
  '/business-dashboard/command-center': typeof BusinessDashboardCommandCenterRoute
  '/business-dashboard/financial-reporting': typeof BusinessDashboardFinancialReportingRoute
  '/business-dashboard/invoicing-billing': typeof BusinessDashboardInvoicingBillingRoute
  '/business-dashboard/multi-currency-treasury': typeof BusinessDashboardMultiCurrencyTreasuryRoute
  '/business-dashboard/open-banking': typeof BusinessDashboardOpenBankingRoute
  '/business-dashboard/payroll-hr': typeof BusinessDashboardPayrollHrRoute
  '/business-dashboard/settings-administration': typeof BusinessDashboardSettingsAdministrationRoute
  '/business-dashboard/support-disputes': typeof BusinessDashboardSupportDisputesRoute
  '/business-dashboard/treasury-cash': typeof BusinessDashboardTreasuryCashRoute
  '/business-dashboard/virtual-accounts': typeof BusinessDashboardVirtualAccountsRoute
  '/business/$module': typeof BusinessModuleRoute
  '/cards/app': typeof CardsAppRouteWithChildren
  '/dev-dashboard/api-governance': typeof DevDashboardApiGovernanceRoute
  '/dev-dashboard/api-reference': typeof DevDashboardApiReferenceRoute
  '/dev-dashboard/compliance-audit': typeof DevDashboardComplianceAuditRoute
  '/dev-dashboard/developer-dashboard': typeof DevDashboardDeveloperDashboardRoute
  '/dev-dashboard/integration-architecture': typeof DevDashboardIntegrationArchitectureRoute
  '/dev-dashboard/monitoring-incidents': typeof DevDashboardMonitoringIncidentsRoute
  '/dev-dashboard/partner-marketplace': typeof DevDashboardPartnerMarketplaceRoute
  '/dev-dashboard/playground': typeof DevDashboardPlaygroundRoute
  '/dev-dashboard/sdks': typeof DevDashboardSdksRoute
  '/dev-dashboard/security': typeof DevDashboardSecurityRoute
  '/dev-dashboard/support-slas': typeof DevDashboardSupportSlasRoute
  '/dev-dashboard/webhooks-events': typeof DevDashboardWebhooksEventsRoute
  '/dev/$module': typeof DevModuleRoute
  '/transaction_dashboard/app': typeof Transaction_dashboardAppRouteWithChildren
  '/utility/$module': typeof UtilityModuleRoute
  '/utility/airtime': typeof UtilityAirtimeRoute
  '/utility/electricity': typeof UtilityElectricityRoute
  '/utility/internet': typeof UtilityInternetRoute
  '/utility/settings': typeof UtilitySettingsRoute
  '/utility/water': typeof UtilityWaterRoute
  '/business-dashboard/': typeof BusinessDashboardIndexRoute
  '/business/': typeof BusinessIndexRoute
  '/dev-dashboard/': typeof DevDashboardIndexRoute
  '/dev/': typeof DevIndexRoute
  '/utility/': typeof UtilityIndexRoute
  '/cards/app/account-settings': typeof CardsAppAccountSettingsRoute
  '/cards/app/card-analytics-reporting': typeof CardsAppCardAnalyticsReportingRoute
  '/cards/app/card-command-center': typeof CardsAppCardCommandCenterRoute
  '/cards/app/card-program-administration': typeof CardsAppCardProgramAdministrationRoute
  '/cards/app/card-security-fraud-prevention': typeof CardsAppCardSecurityFraudPreventionRoute
  '/cards/app/card-settings-support': typeof CardsAppCardSettingsSupportRoute
  '/cards/app/corporate-business-cards': typeof CardsAppCorporateBusinessCardsRoute
  '/cards/app/physical-debit-cards': typeof CardsAppPhysicalDebitCardsRoute
  '/cards/app/prepaid-card-management': typeof CardsAppPrepaidCardManagementRoute
  '/cards/app/support': typeof CardsAppSupportRoute
  '/cards/app/virtual-credit-cards': typeof CardsAppVirtualCreditCardsRoute
  '/cards/app/virtual-debit-cards': typeof CardsAppVirtualDebitCardsRoute
  '/transaction_dashboard/app/$section': typeof Transaction_dashboardAppSectionRoute
  '/transaction_dashboard/app/account': typeof Transaction_dashboardAppAccountRoute
  '/transaction_dashboard/app/analytics': typeof Transaction_dashboardAppAnalyticsRoute
  '/transaction_dashboard/app/compliance': typeof Transaction_dashboardAppComplianceRoute
  '/transaction_dashboard/app/customers': typeof Transaction_dashboardAppCustomersRoute
  '/transaction_dashboard/app/disputes': typeof Transaction_dashboardAppDisputesRoute
  '/transaction_dashboard/app/fees': typeof Transaction_dashboardAppFeesRoute
  '/transaction_dashboard/app/fx': typeof Transaction_dashboardAppFxRoute
  '/transaction_dashboard/app/initiate-transfer': typeof Transaction_dashboardAppInitiateTransferRoute
  '/transaction_dashboard/app/kra-government': typeof Transaction_dashboardAppKraGovernmentRoute
  '/transaction_dashboard/app/liquidity': typeof Transaction_dashboardAppLiquidityRoute
  '/transaction_dashboard/app/mobile-money': typeof Transaction_dashboardAppMobileMoneyRoute
  '/transaction_dashboard/app/ops-health': typeof Transaction_dashboardAppOpsHealthRoute
  '/transaction_dashboard/app/payment-rails': typeof Transaction_dashboardAppPaymentRailsRoute
  '/transaction_dashboard/app/reconciliation': typeof Transaction_dashboardAppReconciliationRoute
  '/transaction_dashboard/app/settings': typeof Transaction_dashboardAppSettingsRoute
  '/transaction_dashboard/app/settlement': typeof Transaction_dashboardAppSettlementRoute
  '/transaction_dashboard/app/transfer-management': typeof Transaction_dashboardAppTransferManagementRoute
  '/transaction_dashboard/app/transfer-overview': typeof Transaction_dashboardAppTransferOverviewRoute
  '/transaction_dashboard/app/transfers': typeof Transaction_dashboardAppTransfersRoute
  '/transaction_dashboard/app/': typeof Transaction_dashboardAppIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/business': typeof BusinessIndexRoute
  '/auth/account-status': typeof AuthAccountStatusRoute
  '/auth/hub': typeof AuthHubRoute
  '/auth/identity': typeof AuthIdentityRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/mfa': typeof AuthMfaRoute
  '/auth/passkeys': typeof AuthPasskeysRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/security': typeof AuthSecurityRoute
  '/business-dashboard/$module': typeof BusinessDashboardModuleRoute
  '/business-dashboard/accounts-payable': typeof BusinessDashboardAccountsPayableRoute
  '/business-dashboard/bulk-disbursements': typeof BusinessDashboardBulkDisbursementsRoute
  '/business-dashboard/business-onboarding': typeof BusinessDashboardBusinessOnboardingRoute
  '/business-dashboard/collections-merchant': typeof BusinessDashboardCollectionsMerchantRoute
  '/business-dashboard/command-center': typeof BusinessDashboardCommandCenterRoute
  '/business-dashboard/financial-reporting': typeof BusinessDashboardFinancialReportingRoute
  '/business-dashboard/invoicing-billing': typeof BusinessDashboardInvoicingBillingRoute
  '/business-dashboard/multi-currency-treasury': typeof BusinessDashboardMultiCurrencyTreasuryRoute
  '/business-dashboard/open-banking': typeof BusinessDashboardOpenBankingRoute
  '/business-dashboard/payroll-hr': typeof BusinessDashboardPayrollHrRoute
  '/business-dashboard/settings-administration': typeof BusinessDashboardSettingsAdministrationRoute
  '/business-dashboard/support-disputes': typeof BusinessDashboardSupportDisputesRoute
  '/business-dashboard/treasury-cash': typeof BusinessDashboardTreasuryCashRoute
  '/business-dashboard/virtual-accounts': typeof BusinessDashboardVirtualAccountsRoute
  '/business/$module': typeof BusinessModuleRoute
  '/cards/app': typeof CardsAppRouteWithChildren
  '/dev-dashboard/api-governance': typeof DevDashboardApiGovernanceRoute
  '/dev-dashboard/api-reference': typeof DevDashboardApiReferenceRoute
  '/dev-dashboard/compliance-audit': typeof DevDashboardComplianceAuditRoute
  '/dev-dashboard/developer-dashboard': typeof DevDashboardDeveloperDashboardRoute
  '/dev-dashboard/integration-architecture': typeof DevDashboardIntegrationArchitectureRoute
  '/dev-dashboard/monitoring-incidents': typeof DevDashboardMonitoringIncidentsRoute
  '/dev-dashboard/partner-marketplace': typeof DevDashboardPartnerMarketplaceRoute
  '/dev-dashboard/playground': typeof DevDashboardPlaygroundRoute
  '/dev-dashboard/sdks': typeof DevDashboardSdksRoute
  '/dev-dashboard/security': typeof DevDashboardSecurityRoute
  '/dev-dashboard/support-slas': typeof DevDashboardSupportSlasRoute
  '/dev-dashboard/webhooks-events': typeof DevDashboardWebhooksEventsRoute
  '/dev/$module': typeof DevModuleRoute
  '/utility/$module': typeof UtilityModuleRoute
  '/utility/airtime': typeof UtilityAirtimeRoute
  '/utility/electricity': typeof UtilityElectricityRoute
  '/utility/internet': typeof UtilityInternetRoute
  '/utility/settings': typeof UtilitySettingsRoute
  '/utility/water': typeof UtilityWaterRoute
  '/': typeof HomeIndexRoute
  '/business-dashboard': typeof BusinessDashboardIndexRoute
  '/dev-dashboard': typeof DevDashboardIndexRoute
  '/dev': typeof DevIndexRoute
  '/utility': typeof UtilityIndexRoute
  '/cards/app/account-settings': typeof CardsAppAccountSettingsRoute
  '/cards/app/card-analytics-reporting': typeof CardsAppCardAnalyticsReportingRoute
  '/cards/app/card-command-center': typeof CardsAppCardCommandCenterRoute
  '/cards/app/card-program-administration': typeof CardsAppCardProgramAdministrationRoute
  '/cards/app/card-security-fraud-prevention': typeof CardsAppCardSecurityFraudPreventionRoute
  '/cards/app/card-settings-support': typeof CardsAppCardSettingsSupportRoute
  '/cards/app/corporate-business-cards': typeof CardsAppCorporateBusinessCardsRoute
  '/cards/app/physical-debit-cards': typeof CardsAppPhysicalDebitCardsRoute
  '/cards/app/prepaid-card-management': typeof CardsAppPrepaidCardManagementRoute
  '/cards/app/support': typeof CardsAppSupportRoute
  '/cards/app/virtual-credit-cards': typeof CardsAppVirtualCreditCardsRoute
  '/cards/app/virtual-debit-cards': typeof CardsAppVirtualDebitCardsRoute
  '/transaction_dashboard/app/$section': typeof Transaction_dashboardAppSectionRoute
  '/transaction_dashboard/app/account': typeof Transaction_dashboardAppAccountRoute
  '/transaction_dashboard/app/analytics': typeof Transaction_dashboardAppAnalyticsRoute
  '/transaction_dashboard/app/compliance': typeof Transaction_dashboardAppComplianceRoute
  '/transaction_dashboard/app/customers': typeof Transaction_dashboardAppCustomersRoute
  '/transaction_dashboard/app/disputes': typeof Transaction_dashboardAppDisputesRoute
  '/transaction_dashboard/app/fees': typeof Transaction_dashboardAppFeesRoute
  '/transaction_dashboard/app/fx': typeof Transaction_dashboardAppFxRoute
  '/transaction_dashboard/app/initiate-transfer': typeof Transaction_dashboardAppInitiateTransferRoute
  '/transaction_dashboard/app/kra-government': typeof Transaction_dashboardAppKraGovernmentRoute
  '/transaction_dashboard/app/liquidity': typeof Transaction_dashboardAppLiquidityRoute
  '/transaction_dashboard/app/mobile-money': typeof Transaction_dashboardAppMobileMoneyRoute
  '/transaction_dashboard/app/ops-health': typeof Transaction_dashboardAppOpsHealthRoute
  '/transaction_dashboard/app/payment-rails': typeof Transaction_dashboardAppPaymentRailsRoute
  '/transaction_dashboard/app/reconciliation': typeof Transaction_dashboardAppReconciliationRoute
  '/transaction_dashboard/app/settings': typeof Transaction_dashboardAppSettingsRoute
  '/transaction_dashboard/app/settlement': typeof Transaction_dashboardAppSettlementRoute
  '/transaction_dashboard/app/transfer-management': typeof Transaction_dashboardAppTransferManagementRoute
  '/transaction_dashboard/app/transfer-overview': typeof Transaction_dashboardAppTransferOverviewRoute
  '/transaction_dashboard/app/transfers': typeof Transaction_dashboardAppTransfersRoute
  '/transaction_dashboard/app': typeof Transaction_dashboardAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_home': typeof HomeRouteWithChildren
  '/business': typeof BusinessRouteWithChildren
  '/business-dashboard': typeof BusinessDashboardRouteWithChildren
  '/dev': typeof DevRouteWithChildren
  '/dev-dashboard': typeof DevDashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/utility': typeof UtilityRouteWithChildren
  '/_home/business': typeof HomeBusinessRoute
  '/auth/account-status': typeof AuthAccountStatusRoute
  '/auth/hub': typeof AuthHubRoute
  '/auth/identity': typeof AuthIdentityRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/mfa': typeof AuthMfaRoute
  '/auth/passkeys': typeof AuthPasskeysRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/security': typeof AuthSecurityRoute
  '/business-dashboard/$module': typeof BusinessDashboardModuleRoute
  '/business-dashboard/accounts-payable': typeof BusinessDashboardAccountsPayableRoute
  '/business-dashboard/bulk-disbursements': typeof BusinessDashboardBulkDisbursementsRoute
  '/business-dashboard/business-onboarding': typeof BusinessDashboardBusinessOnboardingRoute
  '/business-dashboard/collections-merchant': typeof BusinessDashboardCollectionsMerchantRoute
  '/business-dashboard/command-center': typeof BusinessDashboardCommandCenterRoute
  '/business-dashboard/financial-reporting': typeof BusinessDashboardFinancialReportingRoute
  '/business-dashboard/invoicing-billing': typeof BusinessDashboardInvoicingBillingRoute
  '/business-dashboard/multi-currency-treasury': typeof BusinessDashboardMultiCurrencyTreasuryRoute
  '/business-dashboard/open-banking': typeof BusinessDashboardOpenBankingRoute
  '/business-dashboard/payroll-hr': typeof BusinessDashboardPayrollHrRoute
  '/business-dashboard/settings-administration': typeof BusinessDashboardSettingsAdministrationRoute
  '/business-dashboard/support-disputes': typeof BusinessDashboardSupportDisputesRoute
  '/business-dashboard/treasury-cash': typeof BusinessDashboardTreasuryCashRoute
  '/business-dashboard/virtual-accounts': typeof BusinessDashboardVirtualAccountsRoute
  '/business/$module': typeof BusinessModuleRoute
  '/cards/app': typeof CardsAppRouteWithChildren
  '/dev-dashboard/api-governance': typeof DevDashboardApiGovernanceRoute
  '/dev-dashboard/api-reference': typeof DevDashboardApiReferenceRoute
  '/dev-dashboard/compliance-audit': typeof DevDashboardComplianceAuditRoute
  '/dev-dashboard/developer-dashboard': typeof DevDashboardDeveloperDashboardRoute
  '/dev-dashboard/integration-architecture': typeof DevDashboardIntegrationArchitectureRoute
  '/dev-dashboard/monitoring-incidents': typeof DevDashboardMonitoringIncidentsRoute
  '/dev-dashboard/partner-marketplace': typeof DevDashboardPartnerMarketplaceRoute
  '/dev-dashboard/playground': typeof DevDashboardPlaygroundRoute
  '/dev-dashboard/sdks': typeof DevDashboardSdksRoute
  '/dev-dashboard/security': typeof DevDashboardSecurityRoute
  '/dev-dashboard/support-slas': typeof DevDashboardSupportSlasRoute
  '/dev-dashboard/webhooks-events': typeof DevDashboardWebhooksEventsRoute
  '/dev/$module': typeof DevModuleRoute
  '/transaction_dashboard/app': typeof Transaction_dashboardAppRouteWithChildren
  '/utility/$module': typeof UtilityModuleRoute
  '/utility/airtime': typeof UtilityAirtimeRoute
  '/utility/electricity': typeof UtilityElectricityRoute
  '/utility/internet': typeof UtilityInternetRoute
  '/utility/settings': typeof UtilitySettingsRoute
  '/utility/water': typeof UtilityWaterRoute
  '/_home/': typeof HomeIndexRoute
  '/business-dashboard/': typeof BusinessDashboardIndexRoute
  '/business/': typeof BusinessIndexRoute
  '/dev-dashboard/': typeof DevDashboardIndexRoute
  '/dev/': typeof DevIndexRoute
  '/utility/': typeof UtilityIndexRoute
  '/cards/app/account-settings': typeof CardsAppAccountSettingsRoute
  '/cards/app/card-analytics-reporting': typeof CardsAppCardAnalyticsReportingRoute
  '/cards/app/card-command-center': typeof CardsAppCardCommandCenterRoute
  '/cards/app/card-program-administration': typeof CardsAppCardProgramAdministrationRoute
  '/cards/app/card-security-fraud-prevention': typeof CardsAppCardSecurityFraudPreventionRoute
  '/cards/app/card-settings-support': typeof CardsAppCardSettingsSupportRoute
  '/cards/app/corporate-business-cards': typeof CardsAppCorporateBusinessCardsRoute
  '/cards/app/physical-debit-cards': typeof CardsAppPhysicalDebitCardsRoute
  '/cards/app/prepaid-card-management': typeof CardsAppPrepaidCardManagementRoute
  '/cards/app/support': typeof CardsAppSupportRoute
  '/cards/app/virtual-credit-cards': typeof CardsAppVirtualCreditCardsRoute
  '/cards/app/virtual-debit-cards': typeof CardsAppVirtualDebitCardsRoute
  '/transaction_dashboard/app/$section': typeof Transaction_dashboardAppSectionRoute
  '/transaction_dashboard/app/account': typeof Transaction_dashboardAppAccountRoute
  '/transaction_dashboard/app/analytics': typeof Transaction_dashboardAppAnalyticsRoute
  '/transaction_dashboard/app/compliance': typeof Transaction_dashboardAppComplianceRoute
  '/transaction_dashboard/app/customers': typeof Transaction_dashboardAppCustomersRoute
  '/transaction_dashboard/app/disputes': typeof Transaction_dashboardAppDisputesRoute
  '/transaction_dashboard/app/fees': typeof Transaction_dashboardAppFeesRoute
  '/transaction_dashboard/app/fx': typeof Transaction_dashboardAppFxRoute
  '/transaction_dashboard/app/initiate-transfer': typeof Transaction_dashboardAppInitiateTransferRoute
  '/transaction_dashboard/app/kra-government': typeof Transaction_dashboardAppKraGovernmentRoute
  '/transaction_dashboard/app/liquidity': typeof Transaction_dashboardAppLiquidityRoute
  '/transaction_dashboard/app/mobile-money': typeof Transaction_dashboardAppMobileMoneyRoute
  '/transaction_dashboard/app/ops-health': typeof Transaction_dashboardAppOpsHealthRoute
  '/transaction_dashboard/app/payment-rails': typeof Transaction_dashboardAppPaymentRailsRoute
  '/transaction_dashboard/app/reconciliation': typeof Transaction_dashboardAppReconciliationRoute
  '/transaction_dashboard/app/settings': typeof Transaction_dashboardAppSettingsRoute
  '/transaction_dashboard/app/settlement': typeof Transaction_dashboardAppSettlementRoute
  '/transaction_dashboard/app/transfer-management': typeof Transaction_dashboardAppTransferManagementRoute
  '/transaction_dashboard/app/transfer-overview': typeof Transaction_dashboardAppTransferOverviewRoute
  '/transaction_dashboard/app/transfers': typeof Transaction_dashboardAppTransfersRoute
  '/transaction_dashboard/app/': typeof Transaction_dashboardAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/business'
    | '/business-dashboard'
    | '/dev'
    | '/dev-dashboard'
    | '/login'
    | '/utility'
    | '/auth/account-status'
    | '/auth/hub'
    | '/auth/identity'
    | '/auth/login'
    | '/auth/mfa'
    | '/auth/passkeys'
    | '/auth/recovery'
    | '/auth/register'
    | '/auth/security'
    | '/business-dashboard/$module'
    | '/business-dashboard/accounts-payable'
    | '/business-dashboard/bulk-disbursements'
    | '/business-dashboard/business-onboarding'
    | '/business-dashboard/collections-merchant'
    | '/business-dashboard/command-center'
    | '/business-dashboard/financial-reporting'
    | '/business-dashboard/invoicing-billing'
    | '/business-dashboard/multi-currency-treasury'
    | '/business-dashboard/open-banking'
    | '/business-dashboard/payroll-hr'
    | '/business-dashboard/settings-administration'
    | '/business-dashboard/support-disputes'
    | '/business-dashboard/treasury-cash'
    | '/business-dashboard/virtual-accounts'
    | '/business/$module'
    | '/cards/app'
    | '/dev-dashboard/api-governance'
    | '/dev-dashboard/api-reference'
    | '/dev-dashboard/compliance-audit'
    | '/dev-dashboard/developer-dashboard'
    | '/dev-dashboard/integration-architecture'
    | '/dev-dashboard/monitoring-incidents'
    | '/dev-dashboard/partner-marketplace'
    | '/dev-dashboard/playground'
    | '/dev-dashboard/sdks'
    | '/dev-dashboard/security'
    | '/dev-dashboard/support-slas'
    | '/dev-dashboard/webhooks-events'
    | '/dev/$module'
    | '/transaction_dashboard/app'
    | '/utility/$module'
    | '/utility/airtime'
    | '/utility/electricity'
    | '/utility/internet'
    | '/utility/settings'
    | '/utility/water'
    | '/business-dashboard/'
    | '/business/'
    | '/dev-dashboard/'
    | '/dev/'
    | '/utility/'
    | '/cards/app/account-settings'
    | '/cards/app/card-analytics-reporting'
    | '/cards/app/card-command-center'
    | '/cards/app/card-program-administration'
    | '/cards/app/card-security-fraud-prevention'
    | '/cards/app/card-settings-support'
    | '/cards/app/corporate-business-cards'
    | '/cards/app/physical-debit-cards'
    | '/cards/app/prepaid-card-management'
    | '/cards/app/support'
    | '/cards/app/virtual-credit-cards'
    | '/cards/app/virtual-debit-cards'
    | '/transaction_dashboard/app/$section'
    | '/transaction_dashboard/app/account'
    | '/transaction_dashboard/app/analytics'
    | '/transaction_dashboard/app/compliance'
    | '/transaction_dashboard/app/customers'
    | '/transaction_dashboard/app/disputes'
    | '/transaction_dashboard/app/fees'
    | '/transaction_dashboard/app/fx'
    | '/transaction_dashboard/app/initiate-transfer'
    | '/transaction_dashboard/app/kra-government'
    | '/transaction_dashboard/app/liquidity'
    | '/transaction_dashboard/app/mobile-money'
    | '/transaction_dashboard/app/ops-health'
    | '/transaction_dashboard/app/payment-rails'
    | '/transaction_dashboard/app/reconciliation'
    | '/transaction_dashboard/app/settings'
    | '/transaction_dashboard/app/settlement'
    | '/transaction_dashboard/app/transfer-management'
    | '/transaction_dashboard/app/transfer-overview'
    | '/transaction_dashboard/app/transfers'
    | '/transaction_dashboard/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/business'
    | '/auth/account-status'
    | '/auth/hub'
    | '/auth/identity'
    | '/auth/login'
    | '/auth/mfa'
    | '/auth/passkeys'
    | '/auth/recovery'
    | '/auth/register'
    | '/auth/security'
    | '/business-dashboard/$module'
    | '/business-dashboard/accounts-payable'
    | '/business-dashboard/bulk-disbursements'
    | '/business-dashboard/business-onboarding'
    | '/business-dashboard/collections-merchant'
    | '/business-dashboard/command-center'
    | '/business-dashboard/financial-reporting'
    | '/business-dashboard/invoicing-billing'
    | '/business-dashboard/multi-currency-treasury'
    | '/business-dashboard/open-banking'
    | '/business-dashboard/payroll-hr'
    | '/business-dashboard/settings-administration'
    | '/business-dashboard/support-disputes'
    | '/business-dashboard/treasury-cash'
    | '/business-dashboard/virtual-accounts'
    | '/business/$module'
    | '/cards/app'
    | '/dev-dashboard/api-governance'
    | '/dev-dashboard/api-reference'
    | '/dev-dashboard/compliance-audit'
    | '/dev-dashboard/developer-dashboard'
    | '/dev-dashboard/integration-architecture'
    | '/dev-dashboard/monitoring-incidents'
    | '/dev-dashboard/partner-marketplace'
    | '/dev-dashboard/playground'
    | '/dev-dashboard/sdks'
    | '/dev-dashboard/security'
    | '/dev-dashboard/support-slas'
    | '/dev-dashboard/webhooks-events'
    | '/dev/$module'
    | '/utility/$module'
    | '/utility/airtime'
    | '/utility/electricity'
    | '/utility/internet'
    | '/utility/settings'
    | '/utility/water'
    | '/'
    | '/business-dashboard'
    | '/dev-dashboard'
    | '/dev'
    | '/utility'
    | '/cards/app/account-settings'
    | '/cards/app/card-analytics-reporting'
    | '/cards/app/card-command-center'
    | '/cards/app/card-program-administration'
    | '/cards/app/card-security-fraud-prevention'
    | '/cards/app/card-settings-support'
    | '/cards/app/corporate-business-cards'
    | '/cards/app/physical-debit-cards'
    | '/cards/app/prepaid-card-management'
    | '/cards/app/support'
    | '/cards/app/virtual-credit-cards'
    | '/cards/app/virtual-debit-cards'
    | '/transaction_dashboard/app/$section'
    | '/transaction_dashboard/app/account'
    | '/transaction_dashboard/app/analytics'
    | '/transaction_dashboard/app/compliance'
    | '/transaction_dashboard/app/customers'
    | '/transaction_dashboard/app/disputes'
    | '/transaction_dashboard/app/fees'
    | '/transaction_dashboard/app/fx'
    | '/transaction_dashboard/app/initiate-transfer'
    | '/transaction_dashboard/app/kra-government'
    | '/transaction_dashboard/app/liquidity'
    | '/transaction_dashboard/app/mobile-money'
    | '/transaction_dashboard/app/ops-health'
    | '/transaction_dashboard/app/payment-rails'
    | '/transaction_dashboard/app/reconciliation'
    | '/transaction_dashboard/app/settings'
    | '/transaction_dashboard/app/settlement'
    | '/transaction_dashboard/app/transfer-management'
    | '/transaction_dashboard/app/transfer-overview'
    | '/transaction_dashboard/app/transfers'
    | '/transaction_dashboard/app'
  id:
    | '__root__'
    | '/_home'
    | '/business'
    | '/business-dashboard'
    | '/dev'
    | '/dev-dashboard'
    | '/login'
    | '/utility'
    | '/_home/business'
    | '/auth/account-status'
    | '/auth/hub'
    | '/auth/identity'
    | '/auth/login'
    | '/auth/mfa'
    | '/auth/passkeys'
    | '/auth/recovery'
    | '/auth/register'
    | '/auth/security'
    | '/business-dashboard/$module'
    | '/business-dashboard/accounts-payable'
    | '/business-dashboard/bulk-disbursements'
    | '/business-dashboard/business-onboarding'
    | '/business-dashboard/collections-merchant'
    | '/business-dashboard/command-center'
    | '/business-dashboard/financial-reporting'
    | '/business-dashboard/invoicing-billing'
    | '/business-dashboard/multi-currency-treasury'
    | '/business-dashboard/open-banking'
    | '/business-dashboard/payroll-hr'
    | '/business-dashboard/settings-administration'
    | '/business-dashboard/support-disputes'
    | '/business-dashboard/treasury-cash'
    | '/business-dashboard/virtual-accounts'
    | '/business/$module'
    | '/cards/app'
    | '/dev-dashboard/api-governance'
    | '/dev-dashboard/api-reference'
    | '/dev-dashboard/compliance-audit'
    | '/dev-dashboard/developer-dashboard'
    | '/dev-dashboard/integration-architecture'
    | '/dev-dashboard/monitoring-incidents'
    | '/dev-dashboard/partner-marketplace'
    | '/dev-dashboard/playground'
    | '/dev-dashboard/sdks'
    | '/dev-dashboard/security'
    | '/dev-dashboard/support-slas'
    | '/dev-dashboard/webhooks-events'
    | '/dev/$module'
    | '/transaction_dashboard/app'
    | '/utility/$module'
    | '/utility/airtime'
    | '/utility/electricity'
    | '/utility/internet'
    | '/utility/settings'
    | '/utility/water'
    | '/_home/'
    | '/business-dashboard/'
    | '/business/'
    | '/dev-dashboard/'
    | '/dev/'
    | '/utility/'
    | '/cards/app/account-settings'
    | '/cards/app/card-analytics-reporting'
    | '/cards/app/card-command-center'
    | '/cards/app/card-program-administration'
    | '/cards/app/card-security-fraud-prevention'
    | '/cards/app/card-settings-support'
    | '/cards/app/corporate-business-cards'
    | '/cards/app/physical-debit-cards'
    | '/cards/app/prepaid-card-management'
    | '/cards/app/support'
    | '/cards/app/virtual-credit-cards'
    | '/cards/app/virtual-debit-cards'
    | '/transaction_dashboard/app/$section'
    | '/transaction_dashboard/app/account'
    | '/transaction_dashboard/app/analytics'
    | '/transaction_dashboard/app/compliance'
    | '/transaction_dashboard/app/customers'
    | '/transaction_dashboard/app/disputes'
    | '/transaction_dashboard/app/fees'
    | '/transaction_dashboard/app/fx'
    | '/transaction_dashboard/app/initiate-transfer'
    | '/transaction_dashboard/app/kra-government'
    | '/transaction_dashboard/app/liquidity'
    | '/transaction_dashboard/app/mobile-money'
    | '/transaction_dashboard/app/ops-health'
    | '/transaction_dashboard/app/payment-rails'
    | '/transaction_dashboard/app/reconciliation'
    | '/transaction_dashboard/app/settings'
    | '/transaction_dashboard/app/settlement'
    | '/transaction_dashboard/app/transfer-management'
    | '/transaction_dashboard/app/transfer-overview'
    | '/transaction_dashboard/app/transfers'
    | '/transaction_dashboard/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeRoute: typeof HomeRouteWithChildren
  BusinessRoute: typeof BusinessRouteWithChildren
  BusinessDashboardRoute: typeof BusinessDashboardRouteWithChildren
  DevRoute: typeof DevRouteWithChildren
  DevDashboardRoute: typeof DevDashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  UtilityRoute: typeof UtilityRouteWithChildren
  AuthAccountStatusRoute: typeof AuthAccountStatusRoute
  AuthHubRoute: typeof AuthHubRoute
  AuthIdentityRoute: typeof AuthIdentityRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthMfaRoute: typeof AuthMfaRoute
  AuthPasskeysRoute: typeof AuthPasskeysRoute
  AuthRecoveryRoute: typeof AuthRecoveryRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthSecurityRoute: typeof AuthSecurityRoute
  CardsAppRoute: typeof CardsAppRouteWithChildren
  Transaction_dashboardAppRoute: typeof Transaction_dashboardAppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/utility': {
      id: '/utility'
      path: '/utility'
      fullPath: '/utility'
      preLoaderRoute: typeof UtilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-dashboard': {
      id: '/dev-dashboard'
      path: '/dev-dashboard'
      fullPath: '/dev-dashboard'
      preLoaderRoute: typeof DevDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-dashboard': {
      id: '/business-dashboard'
      path: '/business-dashboard'
      fullPath: '/business-dashboard'
      preLoaderRoute: typeof BusinessDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utility/': {
      id: '/utility/'
      path: '/'
      fullPath: '/utility/'
      preLoaderRoute: typeof UtilityIndexRouteImport
      parentRoute: typeof UtilityRoute
    }
    '/dev/': {
      id: '/dev/'
      path: '/'
      fullPath: '/dev/'
      preLoaderRoute: typeof DevIndexRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev-dashboard/': {
      id: '/dev-dashboard/'
      path: '/'
      fullPath: '/dev-dashboard/'
      preLoaderRoute: typeof DevDashboardIndexRouteImport
      parentRoute: typeof DevDashboardRoute
    }
    '/business/': {
      id: '/business/'
      path: '/'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business-dashboard/': {
      id: '/business-dashboard/'
      path: '/'
      fullPath: '/business-dashboard/'
      preLoaderRoute: typeof BusinessDashboardIndexRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/utility/water': {
      id: '/utility/water'
      path: '/water'
      fullPath: '/utility/water'
      preLoaderRoute: typeof UtilityWaterRouteImport
      parentRoute: typeof UtilityRoute
    }
    '/utility/settings': {
      id: '/utility/settings'
      path: '/settings'
      fullPath: '/utility/settings'
      preLoaderRoute: typeof UtilitySettingsRouteImport
      parentRoute: typeof UtilityRoute
    }
    '/utility/internet': {
      id: '/utility/internet'
      path: '/internet'
      fullPath: '/utility/internet'
      preLoaderRoute: typeof UtilityInternetRouteImport
      parentRoute: typeof UtilityRoute
    }
    '/utility/electricity': {
      id: '/utility/electricity'
      path: '/electricity'
      fullPath: '/utility/electricity'
      preLoaderRoute: typeof UtilityElectricityRouteImport
      parentRoute: typeof UtilityRoute
    }
    '/utility/airtime': {
      id: '/utility/airtime'
      path: '/airtime'
      fullPath: '/utility/airtime'
      preLoaderRoute: typeof UtilityAirtimeRouteImport
      parentRoute: typeof UtilityRoute
    }
    '/utility/$module': {
      id: '/utility/$module'
      path: '/$module'
      fullPath: '/utility/$module'
      preLoaderRoute: typeof UtilityModuleRouteImport
      parentRoute: typeof UtilityRoute
    }
    '/transaction_dashboard/app': {
      id: '/transaction_dashboard/app'
      path: '/transaction_dashboard/app'
      fullPath: '/transaction_dashboard/app'
      preLoaderRoute: typeof Transaction_dashboardAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/$module': {
      id: '/dev/$module'
      path: '/$module'
      fullPath: '/dev/$module'
      preLoaderRoute: typeof DevModuleRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev-dashboard/webhooks-events': {
      id: '/dev-dashboard/webhooks-events'
      path: '/webhooks-events'
      fullPath: '/dev-dashboard/webhooks-events'
      preLoaderRoute: typeof DevDashboardWebhooksEventsRouteImport
      parentRoute: typeof DevDashboardRoute
    }
    '/dev-dashboard/support-slas': {
      id: '/dev-dashboard/support-slas'
      path: '/support-slas'
      fullPath: '/dev-dashboard/support-slas'
      preLoaderRoute: typeof DevDashboardSupportSlasRouteImport
      parentRoute: typeof DevDashboardRoute
    }
    '/dev-dashboard/security': {
      id: '/dev-dashboard/security'
      path: '/security'
      fullPath: '/dev-dashboard/security'
      preLoaderRoute: typeof DevDashboardSecurityRouteImport
      parentRoute: typeof DevDashboardRoute
    }
    '/dev-dashboard/sdks': {
      id: '/dev-dashboard/sdks'
      path: '/sdks'
      fullPath: '/dev-dashboard/sdks'
      preLoaderRoute: typeof DevDashboardSdksRouteImport
      parentRoute: typeof DevDashboardRoute
    }
    '/dev-dashboard/playground': {
      id: '/dev-dashboard/playground'
      path: '/playground'
      fullPath: '/dev-dashboard/playground'
      preLoaderRoute: typeof DevDashboardPlaygroundRouteImport
      parentRoute: typeof DevDashboardRoute
    }
    '/dev-dashboard/partner-marketplace': {
      id: '/dev-dashboard/partner-marketplace'
      path: '/partner-marketplace'
      fullPath: '/dev-dashboard/partner-marketplace'
      preLoaderRoute: typeof DevDashboardPartnerMarketplaceRouteImport
      parentRoute: typeof DevDashboardRoute
    }
    '/dev-dashboard/monitoring-incidents': {
      id: '/dev-dashboard/monitoring-incidents'
      path: '/monitoring-incidents'
      fullPath: '/dev-dashboard/monitoring-incidents'
      preLoaderRoute: typeof DevDashboardMonitoringIncidentsRouteImport
      parentRoute: typeof DevDashboardRoute
    }
    '/dev-dashboard/integration-architecture': {
      id: '/dev-dashboard/integration-architecture'
      path: '/integration-architecture'
      fullPath: '/dev-dashboard/integration-architecture'
      preLoaderRoute: typeof DevDashboardIntegrationArchitectureRouteImport
      parentRoute: typeof DevDashboardRoute
    }
    '/dev-dashboard/developer-dashboard': {
      id: '/dev-dashboard/developer-dashboard'
      path: '/developer-dashboard'
      fullPath: '/dev-dashboard/developer-dashboard'
      preLoaderRoute: typeof DevDashboardDeveloperDashboardRouteImport
      parentRoute: typeof DevDashboardRoute
    }
    '/dev-dashboard/compliance-audit': {
      id: '/dev-dashboard/compliance-audit'
      path: '/compliance-audit'
      fullPath: '/dev-dashboard/compliance-audit'
      preLoaderRoute: typeof DevDashboardComplianceAuditRouteImport
      parentRoute: typeof DevDashboardRoute
    }
    '/dev-dashboard/api-reference': {
      id: '/dev-dashboard/api-reference'
      path: '/api-reference'
      fullPath: '/dev-dashboard/api-reference'
      preLoaderRoute: typeof DevDashboardApiReferenceRouteImport
      parentRoute: typeof DevDashboardRoute
    }
    '/dev-dashboard/api-governance': {
      id: '/dev-dashboard/api-governance'
      path: '/api-governance'
      fullPath: '/dev-dashboard/api-governance'
      preLoaderRoute: typeof DevDashboardApiGovernanceRouteImport
      parentRoute: typeof DevDashboardRoute
    }
    '/cards/app': {
      id: '/cards/app'
      path: '/cards/app'
      fullPath: '/cards/app'
      preLoaderRoute: typeof CardsAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/$module': {
      id: '/business/$module'
      path: '/$module'
      fullPath: '/business/$module'
      preLoaderRoute: typeof BusinessModuleRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business-dashboard/virtual-accounts': {
      id: '/business-dashboard/virtual-accounts'
      path: '/virtual-accounts'
      fullPath: '/business-dashboard/virtual-accounts'
      preLoaderRoute: typeof BusinessDashboardVirtualAccountsRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business-dashboard/treasury-cash': {
      id: '/business-dashboard/treasury-cash'
      path: '/treasury-cash'
      fullPath: '/business-dashboard/treasury-cash'
      preLoaderRoute: typeof BusinessDashboardTreasuryCashRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business-dashboard/support-disputes': {
      id: '/business-dashboard/support-disputes'
      path: '/support-disputes'
      fullPath: '/business-dashboard/support-disputes'
      preLoaderRoute: typeof BusinessDashboardSupportDisputesRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business-dashboard/settings-administration': {
      id: '/business-dashboard/settings-administration'
      path: '/settings-administration'
      fullPath: '/business-dashboard/settings-administration'
      preLoaderRoute: typeof BusinessDashboardSettingsAdministrationRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business-dashboard/payroll-hr': {
      id: '/business-dashboard/payroll-hr'
      path: '/payroll-hr'
      fullPath: '/business-dashboard/payroll-hr'
      preLoaderRoute: typeof BusinessDashboardPayrollHrRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business-dashboard/open-banking': {
      id: '/business-dashboard/open-banking'
      path: '/open-banking'
      fullPath: '/business-dashboard/open-banking'
      preLoaderRoute: typeof BusinessDashboardOpenBankingRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business-dashboard/multi-currency-treasury': {
      id: '/business-dashboard/multi-currency-treasury'
      path: '/multi-currency-treasury'
      fullPath: '/business-dashboard/multi-currency-treasury'
      preLoaderRoute: typeof BusinessDashboardMultiCurrencyTreasuryRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business-dashboard/invoicing-billing': {
      id: '/business-dashboard/invoicing-billing'
      path: '/invoicing-billing'
      fullPath: '/business-dashboard/invoicing-billing'
      preLoaderRoute: typeof BusinessDashboardInvoicingBillingRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business-dashboard/financial-reporting': {
      id: '/business-dashboard/financial-reporting'
      path: '/financial-reporting'
      fullPath: '/business-dashboard/financial-reporting'
      preLoaderRoute: typeof BusinessDashboardFinancialReportingRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business-dashboard/command-center': {
      id: '/business-dashboard/command-center'
      path: '/command-center'
      fullPath: '/business-dashboard/command-center'
      preLoaderRoute: typeof BusinessDashboardCommandCenterRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business-dashboard/collections-merchant': {
      id: '/business-dashboard/collections-merchant'
      path: '/collections-merchant'
      fullPath: '/business-dashboard/collections-merchant'
      preLoaderRoute: typeof BusinessDashboardCollectionsMerchantRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business-dashboard/business-onboarding': {
      id: '/business-dashboard/business-onboarding'
      path: '/business-onboarding'
      fullPath: '/business-dashboard/business-onboarding'
      preLoaderRoute: typeof BusinessDashboardBusinessOnboardingRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business-dashboard/bulk-disbursements': {
      id: '/business-dashboard/bulk-disbursements'
      path: '/bulk-disbursements'
      fullPath: '/business-dashboard/bulk-disbursements'
      preLoaderRoute: typeof BusinessDashboardBulkDisbursementsRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business-dashboard/accounts-payable': {
      id: '/business-dashboard/accounts-payable'
      path: '/accounts-payable'
      fullPath: '/business-dashboard/accounts-payable'
      preLoaderRoute: typeof BusinessDashboardAccountsPayableRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business-dashboard/$module': {
      id: '/business-dashboard/$module'
      path: '/$module'
      fullPath: '/business-dashboard/$module'
      preLoaderRoute: typeof BusinessDashboardModuleRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/auth/security': {
      id: '/auth/security'
      path: '/auth/security'
      fullPath: '/auth/security'
      preLoaderRoute: typeof AuthSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/recovery': {
      id: '/auth/recovery'
      path: '/auth/recovery'
      fullPath: '/auth/recovery'
      preLoaderRoute: typeof AuthRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/passkeys': {
      id: '/auth/passkeys'
      path: '/auth/passkeys'
      fullPath: '/auth/passkeys'
      preLoaderRoute: typeof AuthPasskeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/mfa': {
      id: '/auth/mfa'
      path: '/auth/mfa'
      fullPath: '/auth/mfa'
      preLoaderRoute: typeof AuthMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/identity': {
      id: '/auth/identity'
      path: '/auth/identity'
      fullPath: '/auth/identity'
      preLoaderRoute: typeof AuthIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/hub': {
      id: '/auth/hub'
      path: '/auth/hub'
      fullPath: '/auth/hub'
      preLoaderRoute: typeof AuthHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/account-status': {
      id: '/auth/account-status'
      path: '/auth/account-status'
      fullPath: '/auth/account-status'
      preLoaderRoute: typeof AuthAccountStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/business': {
      id: '/_home/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof HomeBusinessRouteImport
      parentRoute: typeof HomeRoute
    }
    '/transaction_dashboard/app/': {
      id: '/transaction_dashboard/app/'
      path: '/'
      fullPath: '/transaction_dashboard/app/'
      preLoaderRoute: typeof Transaction_dashboardAppIndexRouteImport
      parentRoute: typeof Transaction_dashboardAppRoute
    }
    '/transaction_dashboard/app/transfers': {
      id: '/transaction_dashboard/app/transfers'
      path: '/transfers'
      fullPath: '/transaction_dashboard/app/transfers'
      preLoaderRoute: typeof Transaction_dashboardAppTransfersRouteImport
      parentRoute: typeof Transaction_dashboardAppRoute
    }
    '/transaction_dashboard/app/transfer-overview': {
      id: '/transaction_dashboard/app/transfer-overview'
      path: '/transfer-overview'
      fullPath: '/transaction_dashboard/app/transfer-overview'
      preLoaderRoute: typeof Transaction_dashboardAppTransferOverviewRouteImport
      parentRoute: typeof Transaction_dashboardAppRoute
    }
    '/transaction_dashboard/app/transfer-management': {
      id: '/transaction_dashboard/app/transfer-management'
      path: '/transfer-management'
      fullPath: '/transaction_dashboard/app/transfer-management'
      preLoaderRoute: typeof Transaction_dashboardAppTransferManagementRouteImport
      parentRoute: typeof Transaction_dashboardAppRoute
    }
    '/transaction_dashboard/app/settlement': {
      id: '/transaction_dashboard/app/settlement'
      path: '/settlement'
      fullPath: '/transaction_dashboard/app/settlement'
      preLoaderRoute: typeof Transaction_dashboardAppSettlementRouteImport
      parentRoute: typeof Transaction_dashboardAppRoute
    }
    '/transaction_dashboard/app/settings': {
      id: '/transaction_dashboard/app/settings'
      path: '/settings'
      fullPath: '/transaction_dashboard/app/settings'
      preLoaderRoute: typeof Transaction_dashboardAppSettingsRouteImport
      parentRoute: typeof Transaction_dashboardAppRoute
    }
    '/transaction_dashboard/app/reconciliation': {
      id: '/transaction_dashboard/app/reconciliation'
      path: '/reconciliation'
      fullPath: '/transaction_dashboard/app/reconciliation'
      preLoaderRoute: typeof Transaction_dashboardAppReconciliationRouteImport
      parentRoute: typeof Transaction_dashboardAppRoute
    }
    '/transaction_dashboard/app/payment-rails': {
      id: '/transaction_dashboard/app/payment-rails'
      path: '/payment-rails'
      fullPath: '/transaction_dashboard/app/payment-rails'
      preLoaderRoute: typeof Transaction_dashboardAppPaymentRailsRouteImport
      parentRoute: typeof Transaction_dashboardAppRoute
    }
    '/transaction_dashboard/app/ops-health': {
      id: '/transaction_dashboard/app/ops-health'
      path: '/ops-health'
      fullPath: '/transaction_dashboard/app/ops-health'
      preLoaderRoute: typeof Transaction_dashboardAppOpsHealthRouteImport
      parentRoute: typeof Transaction_dashboardAppRoute
    }
    '/transaction_dashboard/app/mobile-money': {
      id: '/transaction_dashboard/app/mobile-money'
      path: '/mobile-money'
      fullPath: '/transaction_dashboard/app/mobile-money'
      preLoaderRoute: typeof Transaction_dashboardAppMobileMoneyRouteImport
      parentRoute: typeof Transaction_dashboardAppRoute
    }
    '/transaction_dashboard/app/liquidity': {
      id: '/transaction_dashboard/app/liquidity'
      path: '/liquidity'
      fullPath: '/transaction_dashboard/app/liquidity'
      preLoaderRoute: typeof Transaction_dashboardAppLiquidityRouteImport
      parentRoute: typeof Transaction_dashboardAppRoute
    }
    '/transaction_dashboard/app/kra-government': {
      id: '/transaction_dashboard/app/kra-government'
      path: '/kra-government'
      fullPath: '/transaction_dashboard/app/kra-government'
      preLoaderRoute: typeof Transaction_dashboardAppKraGovernmentRouteImport
      parentRoute: typeof Transaction_dashboardAppRoute
    }
    '/transaction_dashboard/app/initiate-transfer': {
      id: '/transaction_dashboard/app/initiate-transfer'
      path: '/initiate-transfer'
      fullPath: '/transaction_dashboard/app/initiate-transfer'
      preLoaderRoute: typeof Transaction_dashboardAppInitiateTransferRouteImport
      parentRoute: typeof Transaction_dashboardAppRoute
    }
    '/transaction_dashboard/app/fx': {
      id: '/transaction_dashboard/app/fx'
      path: '/fx'
      fullPath: '/transaction_dashboard/app/fx'
      preLoaderRoute: typeof Transaction_dashboardAppFxRouteImport
      parentRoute: typeof Transaction_dashboardAppRoute
    }
    '/transaction_dashboard/app/fees': {
      id: '/transaction_dashboard/app/fees'
      path: '/fees'
      fullPath: '/transaction_dashboard/app/fees'
      preLoaderRoute: typeof Transaction_dashboardAppFeesRouteImport
      parentRoute: typeof Transaction_dashboardAppRoute
    }
    '/transaction_dashboard/app/disputes': {
      id: '/transaction_dashboard/app/disputes'
      path: '/disputes'
      fullPath: '/transaction_dashboard/app/disputes'
      preLoaderRoute: typeof Transaction_dashboardAppDisputesRouteImport
      parentRoute: typeof Transaction_dashboardAppRoute
    }
    '/transaction_dashboard/app/customers': {
      id: '/transaction_dashboard/app/customers'
      path: '/customers'
      fullPath: '/transaction_dashboard/app/customers'
      preLoaderRoute: typeof Transaction_dashboardAppCustomersRouteImport
      parentRoute: typeof Transaction_dashboardAppRoute
    }
    '/transaction_dashboard/app/compliance': {
      id: '/transaction_dashboard/app/compliance'
      path: '/compliance'
      fullPath: '/transaction_dashboard/app/compliance'
      preLoaderRoute: typeof Transaction_dashboardAppComplianceRouteImport
      parentRoute: typeof Transaction_dashboardAppRoute
    }
    '/transaction_dashboard/app/analytics': {
      id: '/transaction_dashboard/app/analytics'
      path: '/analytics'
      fullPath: '/transaction_dashboard/app/analytics'
      preLoaderRoute: typeof Transaction_dashboardAppAnalyticsRouteImport
      parentRoute: typeof Transaction_dashboardAppRoute
    }
    '/transaction_dashboard/app/account': {
      id: '/transaction_dashboard/app/account'
      path: '/account'
      fullPath: '/transaction_dashboard/app/account'
      preLoaderRoute: typeof Transaction_dashboardAppAccountRouteImport
      parentRoute: typeof Transaction_dashboardAppRoute
    }
    '/transaction_dashboard/app/$section': {
      id: '/transaction_dashboard/app/$section'
      path: '/$section'
      fullPath: '/transaction_dashboard/app/$section'
      preLoaderRoute: typeof Transaction_dashboardAppSectionRouteImport
      parentRoute: typeof Transaction_dashboardAppRoute
    }
    '/cards/app/virtual-debit-cards': {
      id: '/cards/app/virtual-debit-cards'
      path: '/virtual-debit-cards'
      fullPath: '/cards/app/virtual-debit-cards'
      preLoaderRoute: typeof CardsAppVirtualDebitCardsRouteImport
      parentRoute: typeof CardsAppRoute
    }
    '/cards/app/virtual-credit-cards': {
      id: '/cards/app/virtual-credit-cards'
      path: '/virtual-credit-cards'
      fullPath: '/cards/app/virtual-credit-cards'
      preLoaderRoute: typeof CardsAppVirtualCreditCardsRouteImport
      parentRoute: typeof CardsAppRoute
    }
    '/cards/app/support': {
      id: '/cards/app/support'
      path: '/support'
      fullPath: '/cards/app/support'
      preLoaderRoute: typeof CardsAppSupportRouteImport
      parentRoute: typeof CardsAppRoute
    }
    '/cards/app/prepaid-card-management': {
      id: '/cards/app/prepaid-card-management'
      path: '/prepaid-card-management'
      fullPath: '/cards/app/prepaid-card-management'
      preLoaderRoute: typeof CardsAppPrepaidCardManagementRouteImport
      parentRoute: typeof CardsAppRoute
    }
    '/cards/app/physical-debit-cards': {
      id: '/cards/app/physical-debit-cards'
      path: '/physical-debit-cards'
      fullPath: '/cards/app/physical-debit-cards'
      preLoaderRoute: typeof CardsAppPhysicalDebitCardsRouteImport
      parentRoute: typeof CardsAppRoute
    }
    '/cards/app/corporate-business-cards': {
      id: '/cards/app/corporate-business-cards'
      path: '/corporate-business-cards'
      fullPath: '/cards/app/corporate-business-cards'
      preLoaderRoute: typeof CardsAppCorporateBusinessCardsRouteImport
      parentRoute: typeof CardsAppRoute
    }
    '/cards/app/card-settings-support': {
      id: '/cards/app/card-settings-support'
      path: '/card-settings-support'
      fullPath: '/cards/app/card-settings-support'
      preLoaderRoute: typeof CardsAppCardSettingsSupportRouteImport
      parentRoute: typeof CardsAppRoute
    }
    '/cards/app/card-security-fraud-prevention': {
      id: '/cards/app/card-security-fraud-prevention'
      path: '/card-security-fraud-prevention'
      fullPath: '/cards/app/card-security-fraud-prevention'
      preLoaderRoute: typeof CardsAppCardSecurityFraudPreventionRouteImport
      parentRoute: typeof CardsAppRoute
    }
    '/cards/app/card-program-administration': {
      id: '/cards/app/card-program-administration'
      path: '/card-program-administration'
      fullPath: '/cards/app/card-program-administration'
      preLoaderRoute: typeof CardsAppCardProgramAdministrationRouteImport
      parentRoute: typeof CardsAppRoute
    }
    '/cards/app/card-command-center': {
      id: '/cards/app/card-command-center'
      path: '/card-command-center'
      fullPath: '/cards/app/card-command-center'
      preLoaderRoute: typeof CardsAppCardCommandCenterRouteImport
      parentRoute: typeof CardsAppRoute
    }
    '/cards/app/card-analytics-reporting': {
      id: '/cards/app/card-analytics-reporting'
      path: '/card-analytics-reporting'
      fullPath: '/cards/app/card-analytics-reporting'
      preLoaderRoute: typeof CardsAppCardAnalyticsReportingRouteImport
      parentRoute: typeof CardsAppRoute
    }
    '/cards/app/account-settings': {
      id: '/cards/app/account-settings'
      path: '/account-settings'
      fullPath: '/cards/app/account-settings'
      preLoaderRoute: typeof CardsAppAccountSettingsRouteImport
      parentRoute: typeof CardsAppRoute
    }
  }
}

interface HomeRouteChildren {
  HomeBusinessRoute: typeof HomeBusinessRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeBusinessRoute: HomeBusinessRoute,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

interface BusinessRouteChildren {
  BusinessModuleRoute: typeof BusinessModuleRoute
  BusinessIndexRoute: typeof BusinessIndexRoute
}

const BusinessRouteChildren: BusinessRouteChildren = {
  BusinessModuleRoute: BusinessModuleRoute,
  BusinessIndexRoute: BusinessIndexRoute,
}

const BusinessRouteWithChildren = BusinessRoute._addFileChildren(
  BusinessRouteChildren,
)

interface BusinessDashboardRouteChildren {
  BusinessDashboardModuleRoute: typeof BusinessDashboardModuleRoute
  BusinessDashboardAccountsPayableRoute: typeof BusinessDashboardAccountsPayableRoute
  BusinessDashboardBulkDisbursementsRoute: typeof BusinessDashboardBulkDisbursementsRoute
  BusinessDashboardBusinessOnboardingRoute: typeof BusinessDashboardBusinessOnboardingRoute
  BusinessDashboardCollectionsMerchantRoute: typeof BusinessDashboardCollectionsMerchantRoute
  BusinessDashboardCommandCenterRoute: typeof BusinessDashboardCommandCenterRoute
  BusinessDashboardFinancialReportingRoute: typeof BusinessDashboardFinancialReportingRoute
  BusinessDashboardInvoicingBillingRoute: typeof BusinessDashboardInvoicingBillingRoute
  BusinessDashboardMultiCurrencyTreasuryRoute: typeof BusinessDashboardMultiCurrencyTreasuryRoute
  BusinessDashboardOpenBankingRoute: typeof BusinessDashboardOpenBankingRoute
  BusinessDashboardPayrollHrRoute: typeof BusinessDashboardPayrollHrRoute
  BusinessDashboardSettingsAdministrationRoute: typeof BusinessDashboardSettingsAdministrationRoute
  BusinessDashboardSupportDisputesRoute: typeof BusinessDashboardSupportDisputesRoute
  BusinessDashboardTreasuryCashRoute: typeof BusinessDashboardTreasuryCashRoute
  BusinessDashboardVirtualAccountsRoute: typeof BusinessDashboardVirtualAccountsRoute
  BusinessDashboardIndexRoute: typeof BusinessDashboardIndexRoute
}

const BusinessDashboardRouteChildren: BusinessDashboardRouteChildren = {
  BusinessDashboardModuleRoute: BusinessDashboardModuleRoute,
  BusinessDashboardAccountsPayableRoute: BusinessDashboardAccountsPayableRoute,
  BusinessDashboardBulkDisbursementsRoute:
    BusinessDashboardBulkDisbursementsRoute,
  BusinessDashboardBusinessOnboardingRoute:
    BusinessDashboardBusinessOnboardingRoute,
  BusinessDashboardCollectionsMerchantRoute:
    BusinessDashboardCollectionsMerchantRoute,
  BusinessDashboardCommandCenterRoute: BusinessDashboardCommandCenterRoute,
  BusinessDashboardFinancialReportingRoute:
    BusinessDashboardFinancialReportingRoute,
  BusinessDashboardInvoicingBillingRoute:
    BusinessDashboardInvoicingBillingRoute,
  BusinessDashboardMultiCurrencyTreasuryRoute:
    BusinessDashboardMultiCurrencyTreasuryRoute,
  BusinessDashboardOpenBankingRoute: BusinessDashboardOpenBankingRoute,
  BusinessDashboardPayrollHrRoute: BusinessDashboardPayrollHrRoute,
  BusinessDashboardSettingsAdministrationRoute:
    BusinessDashboardSettingsAdministrationRoute,
  BusinessDashboardSupportDisputesRoute: BusinessDashboardSupportDisputesRoute,
  BusinessDashboardTreasuryCashRoute: BusinessDashboardTreasuryCashRoute,
  BusinessDashboardVirtualAccountsRoute: BusinessDashboardVirtualAccountsRoute,
  BusinessDashboardIndexRoute: BusinessDashboardIndexRoute,
}

const BusinessDashboardRouteWithChildren =
  BusinessDashboardRoute._addFileChildren(BusinessDashboardRouteChildren)

interface DevRouteChildren {
  DevModuleRoute: typeof DevModuleRoute
  DevIndexRoute: typeof DevIndexRoute
}

const DevRouteChildren: DevRouteChildren = {
  DevModuleRoute: DevModuleRoute,
  DevIndexRoute: DevIndexRoute,
}

const DevRouteWithChildren = DevRoute._addFileChildren(DevRouteChildren)

interface DevDashboardRouteChildren {
  DevDashboardApiGovernanceRoute: typeof DevDashboardApiGovernanceRoute
  DevDashboardApiReferenceRoute: typeof DevDashboardApiReferenceRoute
  DevDashboardComplianceAuditRoute: typeof DevDashboardComplianceAuditRoute
  DevDashboardDeveloperDashboardRoute: typeof DevDashboardDeveloperDashboardRoute
  DevDashboardIntegrationArchitectureRoute: typeof DevDashboardIntegrationArchitectureRoute
  DevDashboardMonitoringIncidentsRoute: typeof DevDashboardMonitoringIncidentsRoute
  DevDashboardPartnerMarketplaceRoute: typeof DevDashboardPartnerMarketplaceRoute
  DevDashboardPlaygroundRoute: typeof DevDashboardPlaygroundRoute
  DevDashboardSdksRoute: typeof DevDashboardSdksRoute
  DevDashboardSecurityRoute: typeof DevDashboardSecurityRoute
  DevDashboardSupportSlasRoute: typeof DevDashboardSupportSlasRoute
  DevDashboardWebhooksEventsRoute: typeof DevDashboardWebhooksEventsRoute
  DevDashboardIndexRoute: typeof DevDashboardIndexRoute
}

const DevDashboardRouteChildren: DevDashboardRouteChildren = {
  DevDashboardApiGovernanceRoute: DevDashboardApiGovernanceRoute,
  DevDashboardApiReferenceRoute: DevDashboardApiReferenceRoute,
  DevDashboardComplianceAuditRoute: DevDashboardComplianceAuditRoute,
  DevDashboardDeveloperDashboardRoute: DevDashboardDeveloperDashboardRoute,
  DevDashboardIntegrationArchitectureRoute:
    DevDashboardIntegrationArchitectureRoute,
  DevDashboardMonitoringIncidentsRoute: DevDashboardMonitoringIncidentsRoute,
  DevDashboardPartnerMarketplaceRoute: DevDashboardPartnerMarketplaceRoute,
  DevDashboardPlaygroundRoute: DevDashboardPlaygroundRoute,
  DevDashboardSdksRoute: DevDashboardSdksRoute,
  DevDashboardSecurityRoute: DevDashboardSecurityRoute,
  DevDashboardSupportSlasRoute: DevDashboardSupportSlasRoute,
  DevDashboardWebhooksEventsRoute: DevDashboardWebhooksEventsRoute,
  DevDashboardIndexRoute: DevDashboardIndexRoute,
}

const DevDashboardRouteWithChildren = DevDashboardRoute._addFileChildren(
  DevDashboardRouteChildren,
)

interface UtilityRouteChildren {
  UtilityModuleRoute: typeof UtilityModuleRoute
  UtilityAirtimeRoute: typeof UtilityAirtimeRoute
  UtilityElectricityRoute: typeof UtilityElectricityRoute
  UtilityInternetRoute: typeof UtilityInternetRoute
  UtilitySettingsRoute: typeof UtilitySettingsRoute
  UtilityWaterRoute: typeof UtilityWaterRoute
  UtilityIndexRoute: typeof UtilityIndexRoute
}

const UtilityRouteChildren: UtilityRouteChildren = {
  UtilityModuleRoute: UtilityModuleRoute,
  UtilityAirtimeRoute: UtilityAirtimeRoute,
  UtilityElectricityRoute: UtilityElectricityRoute,
  UtilityInternetRoute: UtilityInternetRoute,
  UtilitySettingsRoute: UtilitySettingsRoute,
  UtilityWaterRoute: UtilityWaterRoute,
  UtilityIndexRoute: UtilityIndexRoute,
}

const UtilityRouteWithChildren =
  UtilityRoute._addFileChildren(UtilityRouteChildren)

interface CardsAppRouteChildren {
  CardsAppAccountSettingsRoute: typeof CardsAppAccountSettingsRoute
  CardsAppCardAnalyticsReportingRoute: typeof CardsAppCardAnalyticsReportingRoute
  CardsAppCardCommandCenterRoute: typeof CardsAppCardCommandCenterRoute
  CardsAppCardProgramAdministrationRoute: typeof CardsAppCardProgramAdministrationRoute
  CardsAppCardSecurityFraudPreventionRoute: typeof CardsAppCardSecurityFraudPreventionRoute
  CardsAppCardSettingsSupportRoute: typeof CardsAppCardSettingsSupportRoute
  CardsAppCorporateBusinessCardsRoute: typeof CardsAppCorporateBusinessCardsRoute
  CardsAppPhysicalDebitCardsRoute: typeof CardsAppPhysicalDebitCardsRoute
  CardsAppPrepaidCardManagementRoute: typeof CardsAppPrepaidCardManagementRoute
  CardsAppSupportRoute: typeof CardsAppSupportRoute
  CardsAppVirtualCreditCardsRoute: typeof CardsAppVirtualCreditCardsRoute
  CardsAppVirtualDebitCardsRoute: typeof CardsAppVirtualDebitCardsRoute
}

const CardsAppRouteChildren: CardsAppRouteChildren = {
  CardsAppAccountSettingsRoute: CardsAppAccountSettingsRoute,
  CardsAppCardAnalyticsReportingRoute: CardsAppCardAnalyticsReportingRoute,
  CardsAppCardCommandCenterRoute: CardsAppCardCommandCenterRoute,
  CardsAppCardProgramAdministrationRoute:
    CardsAppCardProgramAdministrationRoute,
  CardsAppCardSecurityFraudPreventionRoute:
    CardsAppCardSecurityFraudPreventionRoute,
  CardsAppCardSettingsSupportRoute: CardsAppCardSettingsSupportRoute,
  CardsAppCorporateBusinessCardsRoute: CardsAppCorporateBusinessCardsRoute,
  CardsAppPhysicalDebitCardsRoute: CardsAppPhysicalDebitCardsRoute,
  CardsAppPrepaidCardManagementRoute: CardsAppPrepaidCardManagementRoute,
  CardsAppSupportRoute: CardsAppSupportRoute,
  CardsAppVirtualCreditCardsRoute: CardsAppVirtualCreditCardsRoute,
  CardsAppVirtualDebitCardsRoute: CardsAppVirtualDebitCardsRoute,
}

const CardsAppRouteWithChildren = CardsAppRoute._addFileChildren(
  CardsAppRouteChildren,
)

interface Transaction_dashboardAppRouteChildren {
  Transaction_dashboardAppSectionRoute: typeof Transaction_dashboardAppSectionRoute
  Transaction_dashboardAppAccountRoute: typeof Transaction_dashboardAppAccountRoute
  Transaction_dashboardAppAnalyticsRoute: typeof Transaction_dashboardAppAnalyticsRoute
  Transaction_dashboardAppComplianceRoute: typeof Transaction_dashboardAppComplianceRoute
  Transaction_dashboardAppCustomersRoute: typeof Transaction_dashboardAppCustomersRoute
  Transaction_dashboardAppDisputesRoute: typeof Transaction_dashboardAppDisputesRoute
  Transaction_dashboardAppFeesRoute: typeof Transaction_dashboardAppFeesRoute
  Transaction_dashboardAppFxRoute: typeof Transaction_dashboardAppFxRoute
  Transaction_dashboardAppInitiateTransferRoute: typeof Transaction_dashboardAppInitiateTransferRoute
  Transaction_dashboardAppKraGovernmentRoute: typeof Transaction_dashboardAppKraGovernmentRoute
  Transaction_dashboardAppLiquidityRoute: typeof Transaction_dashboardAppLiquidityRoute
  Transaction_dashboardAppMobileMoneyRoute: typeof Transaction_dashboardAppMobileMoneyRoute
  Transaction_dashboardAppOpsHealthRoute: typeof Transaction_dashboardAppOpsHealthRoute
  Transaction_dashboardAppPaymentRailsRoute: typeof Transaction_dashboardAppPaymentRailsRoute
  Transaction_dashboardAppReconciliationRoute: typeof Transaction_dashboardAppReconciliationRoute
  Transaction_dashboardAppSettingsRoute: typeof Transaction_dashboardAppSettingsRoute
  Transaction_dashboardAppSettlementRoute: typeof Transaction_dashboardAppSettlementRoute
  Transaction_dashboardAppTransferManagementRoute: typeof Transaction_dashboardAppTransferManagementRoute
  Transaction_dashboardAppTransferOverviewRoute: typeof Transaction_dashboardAppTransferOverviewRoute
  Transaction_dashboardAppTransfersRoute: typeof Transaction_dashboardAppTransfersRoute
  Transaction_dashboardAppIndexRoute: typeof Transaction_dashboardAppIndexRoute
}

const Transaction_dashboardAppRouteChildren: Transaction_dashboardAppRouteChildren =
  {
    Transaction_dashboardAppSectionRoute: Transaction_dashboardAppSectionRoute,
    Transaction_dashboardAppAccountRoute: Transaction_dashboardAppAccountRoute,
    Transaction_dashboardAppAnalyticsRoute:
      Transaction_dashboardAppAnalyticsRoute,
    Transaction_dashboardAppComplianceRoute:
      Transaction_dashboardAppComplianceRoute,
    Transaction_dashboardAppCustomersRoute:
      Transaction_dashboardAppCustomersRoute,
    Transaction_dashboardAppDisputesRoute:
      Transaction_dashboardAppDisputesRoute,
    Transaction_dashboardAppFeesRoute: Transaction_dashboardAppFeesRoute,
    Transaction_dashboardAppFxRoute: Transaction_dashboardAppFxRoute,
    Transaction_dashboardAppInitiateTransferRoute:
      Transaction_dashboardAppInitiateTransferRoute,
    Transaction_dashboardAppKraGovernmentRoute:
      Transaction_dashboardAppKraGovernmentRoute,
    Transaction_dashboardAppLiquidityRoute:
      Transaction_dashboardAppLiquidityRoute,
    Transaction_dashboardAppMobileMoneyRoute:
      Transaction_dashboardAppMobileMoneyRoute,
    Transaction_dashboardAppOpsHealthRoute:
      Transaction_dashboardAppOpsHealthRoute,
    Transaction_dashboardAppPaymentRailsRoute:
      Transaction_dashboardAppPaymentRailsRoute,
    Transaction_dashboardAppReconciliationRoute:
      Transaction_dashboardAppReconciliationRoute,
    Transaction_dashboardAppSettingsRoute:
      Transaction_dashboardAppSettingsRoute,
    Transaction_dashboardAppSettlementRoute:
      Transaction_dashboardAppSettlementRoute,
    Transaction_dashboardAppTransferManagementRoute:
      Transaction_dashboardAppTransferManagementRoute,
    Transaction_dashboardAppTransferOverviewRoute:
      Transaction_dashboardAppTransferOverviewRoute,
    Transaction_dashboardAppTransfersRoute:
      Transaction_dashboardAppTransfersRoute,
    Transaction_dashboardAppIndexRoute: Transaction_dashboardAppIndexRoute,
  }

const Transaction_dashboardAppRouteWithChildren =
  Transaction_dashboardAppRoute._addFileChildren(
    Transaction_dashboardAppRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  HomeRoute: HomeRouteWithChildren,
  BusinessRoute: BusinessRouteWithChildren,
  BusinessDashboardRoute: BusinessDashboardRouteWithChildren,
  DevRoute: DevRouteWithChildren,
  DevDashboardRoute: DevDashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  UtilityRoute: UtilityRouteWithChildren,
  AuthAccountStatusRoute: AuthAccountStatusRoute,
  AuthHubRoute: AuthHubRoute,
  AuthIdentityRoute: AuthIdentityRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthMfaRoute: AuthMfaRoute,
  AuthPasskeysRoute: AuthPasskeysRoute,
  AuthRecoveryRoute: AuthRecoveryRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthSecurityRoute: AuthSecurityRoute,
  CardsAppRoute: CardsAppRouteWithChildren,
  Transaction_dashboardAppRoute: Transaction_dashboardAppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
