/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletActivationRouteImport } from './routes/wallet-activation'
import { Route as UtilityRouteImport } from './routes/utility'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DevDashboardRouteImport } from './routes/dev-dashboard'
import { Route as DevRouteImport } from './routes/dev'
import { Route as BusinessDashboardRouteImport } from './routes/business-dashboard'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as HomeRouteImport } from './routes/_home'
import { Route as UtilityIndexRouteImport } from './routes/utility/index'
import { Route as DevIndexRouteImport } from './routes/dev/index'
import { Route as DevDashboardIndexRouteImport } from './routes/dev-dashboard/index'
import { Route as BusinessIndexRouteImport } from './routes/business/index'
import { Route as BusinessDashboardIndexRouteImport } from './routes/business-dashboard/index'
import { Route as HomeIndexRouteImport } from './routes/_home/index'
import { Route as UtilityWaterRouteImport } from './routes/utility/water'
import { Route as UtilitySettingsRouteImport } from './routes/utility/settings'
import { Route as UtilityInternetRouteImport } from './routes/utility/internet'
import { Route as UtilityElectricityRouteImport } from './routes/utility/electricity'
import { Route as UtilityAirtimeRouteImport } from './routes/utility/airtime'
import { Route as UtilityModuleRouteImport } from './routes/utility/$module'
import { Route as PmAppRouteImport } from './routes/pm/app'
import { Route as DevModuleRouteImport } from './routes/dev/$module'
import { Route as DevDashboardWebhooksEventsRouteImport } from './routes/dev-dashboard/webhooks-events'
import { Route as DevDashboardSupportSlasRouteImport } from './routes/dev-dashboard/support-slas'
import { Route as DevDashboardSecurityRouteImport } from './routes/dev-dashboard/security'
import { Route as DevDashboardSdksRouteImport } from './routes/dev-dashboard/sdks'
import { Route as DevDashboardPlaygroundRouteImport } from './routes/dev-dashboard/playground'
import { Route as DevDashboardPartnerMarketplaceRouteImport } from './routes/dev-dashboard/partner-marketplace'
import { Route as DevDashboardMonitoringIncidentsRouteImport } from './routes/dev-dashboard/monitoring-incidents'
import { Route as DevDashboardIntegrationArchitectureRouteImport } from './routes/dev-dashboard/integration-architecture'
import { Route as DevDashboardDeveloperDashboardRouteImport } from './routes/dev-dashboard/developer-dashboard'
import { Route as DevDashboardComplianceAuditRouteImport } from './routes/dev-dashboard/compliance-audit'
import { Route as DevDashboardApiReferenceRouteImport } from './routes/dev-dashboard/api-reference'
import { Route as DevDashboardApiGovernanceRouteImport } from './routes/dev-dashboard/api-governance'
import { Route as CardsAppRouteImport } from './routes/cards/app'
import { Route as BusinessModuleRouteImport } from './routes/business/$module'
import { Route as BusinessDashboardVirtualAccountsRouteImport } from './routes/business-dashboard/virtual-accounts'
import { Route as BusinessDashboardTreasuryCashRouteImport } from './routes/business-dashboard/treasury-cash'
import { Route as BusinessDashboardSupportDisputesRouteImport } from './routes/business-dashboard/support-disputes'
import { Route as BusinessDashboardSettingsAdministrationRouteImport } from './routes/business-dashboard/settings-administration'
import { Route as BusinessDashboardPayrollHrRouteImport } from './routes/business-dashboard/payroll-hr'
import { Route as BusinessDashboardOpenBankingRouteImport } from './routes/business-dashboard/open-banking'
import { Route as BusinessDashboardMultiCurrencyTreasuryRouteImport } from './routes/business-dashboard/multi-currency-treasury'
import { Route as BusinessDashboardInvoicingBillingRouteImport } from './routes/business-dashboard/invoicing-billing'
import { Route as BusinessDashboardFinancialReportingRouteImport } from './routes/business-dashboard/financial-reporting'
import { Route as BusinessDashboardCommandCenterRouteImport } from './routes/business-dashboard/command-center'
import { Route as BusinessDashboardCollectionsMerchantRouteImport } from './routes/business-dashboard/collections-merchant'
import { Route as BusinessDashboardBusinessOnboardingRouteImport } from './routes/business-dashboard/business-onboarding'
import { Route as BusinessDashboardBulkDisbursementsRouteImport } from './routes/business-dashboard/bulk-disbursements'
import { Route as BusinessDashboardAccountsPayableRouteImport } from './routes/business-dashboard/accounts-payable'
import { Route as BusinessDashboardModuleRouteImport } from './routes/business-dashboard/$module'
import { Route as AuthSecurityRouteImport } from './routes/auth/security'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthRecoveryRouteImport } from './routes/auth/recovery'
import { Route as AuthPasskeysRouteImport } from './routes/auth/passkeys'
import { Route as AuthMfaRouteImport } from './routes/auth/mfa'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthIdentityRouteImport } from './routes/auth/identity'
import { Route as AuthHubRouteImport } from './routes/auth/hub'
import { Route as AuthAccountStatusRouteImport } from './routes/auth/account-status'
import { Route as HomeBusinessRouteImport } from './routes/_home/business'
import { Route as PmAppIndexRouteImport } from './routes/pm/app.index'
import { Route as PmAppTransfersRouteImport } from './routes/pm/app.transfers'
import { Route as PmAppTransferOverviewRouteImport } from './routes/pm/app.transfer-overview'
import { Route as PmAppTransferManagementRouteImport } from './routes/pm/app.transfer-management'
import { Route as PmAppSettlementRouteImport } from './routes/pm/app.settlement'
import { Route as PmAppSettingsRouteImport } from './routes/pm/app.settings'
import { Route as PmAppReconciliationRouteImport } from './routes/pm/app.reconciliation'
import { Route as PmAppPaymentRailsRouteImport } from './routes/pm/app.payment-rails'
import { Route as PmAppOpsHealthRouteImport } from './routes/pm/app.ops-health'
import { Route as PmAppMobileMoneyRouteImport } from './routes/pm/app.mobile-money'
import { Route as PmAppLiquidityRouteImport } from './routes/pm/app.liquidity'
import { Route as PmAppKraGovernmentRouteImport } from './routes/pm/app.kra-government'
import { Route as PmAppInitiateTransferRouteImport } from './routes/pm/app.initiate-transfer'
import { Route as PmAppFxRouteImport } from './routes/pm/app.fx'
import { Route as PmAppFeesRouteImport } from './routes/pm/app.fees'
import { Route as PmAppDisputesRouteImport } from './routes/pm/app.disputes'
import { Route as PmAppCustomersRouteImport } from './routes/pm/app.customers'
import { Route as PmAppComplianceRouteImport } from './routes/pm/app.compliance'
import { Route as PmAppAnalyticsRouteImport } from './routes/pm/app.analytics'
import { Route as PmAppAccountRouteImport } from './routes/pm/app.account'
import { Route as PmAppSectionRouteImport } from './routes/pm/app.$section'
import { Route as CardsAppVirtualDebitCardsRouteImport } from './routes/cards/app/virtual-debit-cards'
import { Route as CardsAppVirtualCreditCardsRouteImport } from './routes/cards/app/virtual-credit-cards'
import { Route as CardsAppSupportRouteImport } from './routes/cards/app/support'
import { Route as CardsAppPrepaidCardManagementRouteImport } from './routes/cards/app/prepaid-card-management'
import { Route as CardsAppPhysicalDebitCardsRouteImport } from './routes/cards/app/physical-debit-cards'
import { Route as CardsAppCorporateBusinessCardsRouteImport } from './routes/cards/app/corporate-business-cards'
import { Route as CardsAppCardSettingsSupportRouteImport } from './routes/cards/app/card-settings-support'
import { Route as CardsAppCardSecurityFraudPreventionRouteImport } from './routes/cards/app/card-security-fraud-prevention'
import { Route as CardsAppCardProgramAdministrationRouteImport } from './routes/cards/app/card-program-administration'
import { Route as CardsAppCardCommandCenterRouteImport } from './routes/cards/app/card-command-center'
import { Route as CardsAppCardAnalyticsReportingRouteImport } from './routes/cards/app/card-analytics-reporting'
import { Route as CardsAppAccountSettingsRouteImport } from './routes/cards/app/account-settings'

const WalletActivationRoute = WalletActivationRouteImport.update({
  id: '/wallet-activation',
  path: '/wallet-activation',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilityRoute = UtilityRouteImport.update({
  id: '/utility',
  path: '/utility',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DevDashboardRoute = DevDashboardRouteImport.update({
  id: '/dev-dashboard',
  path: '/dev-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessDashboardRoute = BusinessDashboardRouteImport.update({
  id: '/business-dashboard',
  path: '/business-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilityIndexRoute = UtilityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UtilityRoute,
} as any)
const DevIndexRoute = DevIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevRoute,
} as any)
const DevDashboardIndexRoute = DevDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevDashboardRoute,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessDashboardIndexRoute = BusinessDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BusinessDashboardRoute,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRoute,
} as any)
const UtilityWaterRoute = UtilityWaterRouteImport.update({
  id: '/water',
  path: '/water',
  getParentRoute: () => UtilityRoute,
} as any)
const UtilitySettingsRoute = UtilitySettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => UtilityRoute,
} as any)
const UtilityInternetRoute = UtilityInternetRouteImport.update({
  id: '/internet',
  path: '/internet',
  getParentRoute: () => UtilityRoute,
} as any)
const UtilityElectricityRoute = UtilityElectricityRouteImport.update({
  id: '/electricity',
  path: '/electricity',
  getParentRoute: () => UtilityRoute,
} as any)
const UtilityAirtimeRoute = UtilityAirtimeRouteImport.update({
  id: '/airtime',
  path: '/airtime',
  getParentRoute: () => UtilityRoute,
} as any)
const UtilityModuleRoute = UtilityModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => UtilityRoute,
} as any)
const PmAppRoute = PmAppRouteImport.update({
  id: '/pm/app',
  path: '/pm/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DevModuleRoute = DevModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => DevRoute,
} as any)
const DevDashboardWebhooksEventsRoute =
  DevDashboardWebhooksEventsRouteImport.update({
    id: '/webhooks-events',
    path: '/webhooks-events',
    getParentRoute: () => DevDashboardRoute,
  } as any)
const DevDashboardSupportSlasRoute = DevDashboardSupportSlasRouteImport.update({
  id: '/support-slas',
  path: '/support-slas',
  getParentRoute: () => DevDashboardRoute,
} as any)
const DevDashboardSecurityRoute = DevDashboardSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DevDashboardRoute,
} as any)
const DevDashboardSdksRoute = DevDashboardSdksRouteImport.update({
  id: '/sdks',
  path: '/sdks',
  getParentRoute: () => DevDashboardRoute,
} as any)
const DevDashboardPlaygroundRoute = DevDashboardPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => DevDashboardRoute,
} as any)
const DevDashboardPartnerMarketplaceRoute =
  DevDashboardPartnerMarketplaceRouteImport.update({
    id: '/partner-marketplace',
    path: '/partner-marketplace',
    getParentRoute: () => DevDashboardRoute,
  } as any)
const DevDashboardMonitoringIncidentsRoute =
  DevDashboardMonitoringIncidentsRouteImport.update({
    id: '/monitoring-incidents',
    path: '/monitoring-incidents',
    getParentRoute: () => DevDashboardRoute,
  } as any)
const DevDashboardIntegrationArchitectureRoute =
  DevDashboardIntegrationArchitectureRouteImport.update({
    id: '/integration-architecture',
    path: '/integration-architecture',
    getParentRoute: () => DevDashboardRoute,
  } as any)
const DevDashboardDeveloperDashboardRoute =
  DevDashboardDeveloperDashboardRouteImport.update({
    id: '/developer-dashboard',
    path: '/developer-dashboard',
    getParentRoute: () => DevDashboardRoute,
  } as any)
const DevDashboardComplianceAuditRoute =
  DevDashboardComplianceAuditRouteImport.update({
    id: '/compliance-audit',
    path: '/compliance-audit',
    getParentRoute: () => DevDashboardRoute,
  } as any)
const DevDashboardApiReferenceRoute =
  DevDashboardApiReferenceRouteImport.update({
    id: '/api-reference',
    path: '/api-reference',
    getParentRoute: () => DevDashboardRoute,
  } as any)
const DevDashboardApiGovernanceRoute =
  DevDashboardApiGovernanceRouteImport.update({
    id: '/api-governance',
    path: '/api-governance',
    getParentRoute: () => DevDashboardRoute,
  } as any)
const CardsAppRoute = CardsAppRouteImport.update({
  id: '/cards/app',
  path: '/cards/app',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessModuleRoute = BusinessModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessDashboardVirtualAccountsRoute =
  BusinessDashboardVirtualAccountsRouteImport.update({
    id: '/virtual-accounts',
    path: '/virtual-accounts',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardTreasuryCashRoute =
  BusinessDashboardTreasuryCashRouteImport.update({
    id: '/treasury-cash',
    path: '/treasury-cash',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardSupportDisputesRoute =
  BusinessDashboardSupportDisputesRouteImport.update({
    id: '/support-disputes',
    path: '/support-disputes',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardSettingsAdministrationRoute =
  BusinessDashboardSettingsAdministrationRouteImport.update({
    id: '/settings-administration',
    path: '/settings-administration',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardPayrollHrRoute =
  BusinessDashboardPayrollHrRouteImport.update({
    id: '/payroll-hr',
    path: '/payroll-hr',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardOpenBankingRoute =
  BusinessDashboardOpenBankingRouteImport.update({
    id: '/open-banking',
    path: '/open-banking',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardMultiCurrencyTreasuryRoute =
  BusinessDashboardMultiCurrencyTreasuryRouteImport.update({
    id: '/multi-currency-treasury',
    path: '/multi-currency-treasury',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardInvoicingBillingRoute =
  BusinessDashboardInvoicingBillingRouteImport.update({
    id: '/invoicing-billing',
    path: '/invoicing-billing',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardFinancialReportingRoute =
  BusinessDashboardFinancialReportingRouteImport.update({
    id: '/financial-reporting',
    path: '/financial-reporting',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardCommandCenterRoute =
  BusinessDashboardCommandCenterRouteImport.update({
    id: '/command-center',
    path: '/command-center',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardCollectionsMerchantRoute =
  BusinessDashboardCollectionsMerchantRouteImport.update({
    id: '/collections-merchant',
    path: '/collections-merchant',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardBusinessOnboardingRoute =
  BusinessDashboardBusinessOnboardingRouteImport.update({
    id: '/business-onboarding',
    path: '/business-onboarding',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardBulkDisbursementsRoute =
  BusinessDashboardBulkDisbursementsRouteImport.update({
    id: '/bulk-disbursements',
    path: '/bulk-disbursements',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardAccountsPayableRoute =
  BusinessDashboardAccountsPayableRouteImport.update({
    id: '/accounts-payable',
    path: '/accounts-payable',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardModuleRoute = BusinessDashboardModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => BusinessDashboardRoute,
} as any)
const AuthSecurityRoute = AuthSecurityRouteImport.update({
  id: '/auth/security',
  path: '/auth/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRecoveryRoute = AuthRecoveryRouteImport.update({
  id: '/auth/recovery',
  path: '/auth/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPasskeysRoute = AuthPasskeysRouteImport.update({
  id: '/auth/passkeys',
  path: '/auth/passkeys',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMfaRoute = AuthMfaRouteImport.update({
  id: '/auth/mfa',
  path: '/auth/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIdentityRoute = AuthIdentityRouteImport.update({
  id: '/auth/identity',
  path: '/auth/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthHubRoute = AuthHubRouteImport.update({
  id: '/auth/hub',
  path: '/auth/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAccountStatusRoute = AuthAccountStatusRouteImport.update({
  id: '/auth/account-status',
  path: '/auth/account-status',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeBusinessRoute = HomeBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => HomeRoute,
} as any)
const PmAppIndexRoute = PmAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PmAppRoute,
} as any)
const PmAppTransfersRoute = PmAppTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => PmAppRoute,
} as any)
const PmAppTransferOverviewRoute = PmAppTransferOverviewRouteImport.update({
  id: '/transfer-overview',
  path: '/transfer-overview',
  getParentRoute: () => PmAppRoute,
} as any)
const PmAppTransferManagementRoute = PmAppTransferManagementRouteImport.update({
  id: '/transfer-management',
  path: '/transfer-management',
  getParentRoute: () => PmAppRoute,
} as any)
const PmAppSettlementRoute = PmAppSettlementRouteImport.update({
  id: '/settlement',
  path: '/settlement',
  getParentRoute: () => PmAppRoute,
} as any)
const PmAppSettingsRoute = PmAppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PmAppRoute,
} as any)
const PmAppReconciliationRoute = PmAppReconciliationRouteImport.update({
  id: '/reconciliation',
  path: '/reconciliation',
  getParentRoute: () => PmAppRoute,
} as any)
const PmAppPaymentRailsRoute = PmAppPaymentRailsRouteImport.update({
  id: '/payment-rails',
  path: '/payment-rails',
  getParentRoute: () => PmAppRoute,
} as any)
const PmAppOpsHealthRoute = PmAppOpsHealthRouteImport.update({
  id: '/ops-health',
  path: '/ops-health',
  getParentRoute: () => PmAppRoute,
} as any)
const PmAppMobileMoneyRoute = PmAppMobileMoneyRouteImport.update({
  id: '/mobile-money',
  path: '/mobile-money',
  getParentRoute: () => PmAppRoute,
} as any)
const PmAppLiquidityRoute = PmAppLiquidityRouteImport.update({
  id: '/liquidity',
  path: '/liquidity',
  getParentRoute: () => PmAppRoute,
} as any)
const PmAppKraGovernmentRoute = PmAppKraGovernmentRouteImport.update({
  id: '/kra-government',
  path: '/kra-government',
  getParentRoute: () => PmAppRoute,
} as any)
const PmAppInitiateTransferRoute = PmAppInitiateTransferRouteImport.update({
  id: '/initiate-transfer',
  path: '/initiate-transfer',
  getParentRoute: () => PmAppRoute,
} as any)
const PmAppFxRoute = PmAppFxRouteImport.update({
  id: '/fx',
  path: '/fx',
  getParentRoute: () => PmAppRoute,
} as any)
const PmAppFeesRoute = PmAppFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => PmAppRoute,
} as any)
const PmAppDisputesRoute = PmAppDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => PmAppRoute,
} as any)
const PmAppCustomersRoute = PmAppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => PmAppRoute,
} as any)
const PmAppComplianceRoute = PmAppComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => PmAppRoute,
} as any)
const PmAppAnalyticsRoute = PmAppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => PmAppRoute,
} as any)
const PmAppAccountRoute = PmAppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => PmAppRoute,
} as any)
const PmAppSectionRoute = PmAppSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => PmAppRoute,
} as any)
const CardsAppVirtualDebitCardsRoute =
  CardsAppVirtualDebitCardsRouteImport.update({
    id: '/virtual-debit-cards',
    path: '/virtual-debit-cards',
    getParentRoute: () => CardsAppRoute,
  } as any)
const CardsAppVirtualCreditCardsRoute =
  CardsAppVirtualCreditCardsRouteImport.update({
    id: '/virtual-credit-cards',
    path: '/virtual-credit-cards',
    getParentRoute: () => CardsAppRoute,
  } as any)
const CardsAppSupportRoute = CardsAppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => CardsAppRoute,
} as any)
const CardsAppPrepaidCardManagementRoute =
  CardsAppPrepaidCardManagementRouteImport.update({
    id: '/prepaid-card-management',
    path: '/prepaid-card-management',
    getParentRoute: () => CardsAppRoute,
  } as any)
const CardsAppPhysicalDebitCardsRoute =
  CardsAppPhysicalDebitCardsRouteImport.update({
    id: '/physical-debit-cards',
    path: '/physical-debit-cards',
    getParentRoute: () => CardsAppRoute,
  } as any)
const CardsAppCorporateBusinessCardsRoute =
  CardsAppCorporateBusinessCardsRouteImport.update({
    id: '/corporate-business-cards',
    path: '/corporate-business-cards',
    getParentRoute: () => CardsAppRoute,
  } as any)
const CardsAppCardSettingsSupportRoute =
  CardsAppCardSettingsSupportRouteImport.update({
    id: '/card-settings-support',
    path: '/card-settings-support',
    getParentRoute: () => CardsAppRoute,
  } as any)
const CardsAppCardSecurityFraudPreventionRoute =
  CardsAppCardSecurityFraudPreventionRouteImport.update({
    id: '/card-security-fraud-prevention',
    path: '/card-security-fraud-prevention',
    getParentRoute: () => CardsAppRoute,
  } as any)
const CardsAppCardProgramAdministrationRoute =
  CardsAppCardProgramAdministrationRouteImport.update({
    id: '/card-program-administration',
    path: '/card-program-administration',
    getParentRoute: () => CardsAppRoute,
  } as any)
const CardsAppCardCommandCenterRoute =
  CardsAppCardCommandCenterRouteImport.update({
    id: '/card-command-center',
    path: '/card-command-center',
    getParentRoute: () => CardsAppRoute,
  } as any)
const CardsAppCardAnalyticsReportingRoute =
  CardsAppCardAnalyticsReportingRouteImport.update({
    id: '/card-analytics-reporting',
    path: '/card-analytics-reporting',
    getParentRoute: () => CardsAppRoute,
  } as any)
const CardsAppAccountSettingsRoute = CardsAppAccountSettingsRouteImport.update({
  id: '/account-settings',
  path: '/account-settings',
  getParentRoute: () => CardsAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof HomeIndexRoute
  '/business': typeof HomeBusinessRoute
  '/business-dashboard': typeof BusinessDashboardRouteWithChildren
  '/dev': typeof DevRouteWithChildren
  '/dev-dashboard': typeof DevDashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/utility': typeof UtilityRouteWithChildren
  '/wallet-activation': typeof WalletActivationRoute
  '/auth/account-status': typeof AuthAccountStatusRoute
  '/auth/hub': typeof AuthHubRoute
  '/auth/identity': typeof AuthIdentityRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/mfa': typeof AuthMfaRoute
  '/auth/passkeys': typeof AuthPasskeysRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/security': typeof AuthSecurityRoute
  '/business-dashboard/$module': typeof BusinessDashboardModuleRoute
  '/business-dashboard/accounts-payable': typeof BusinessDashboardAccountsPayableRoute
  '/business-dashboard/bulk-disbursements': typeof BusinessDashboardBulkDisbursementsRoute
  '/business-dashboard/business-onboarding': typeof BusinessDashboardBusinessOnboardingRoute
  '/business-dashboard/collections-merchant': typeof BusinessDashboardCollectionsMerchantRoute
  '/business-dashboard/command-center': typeof BusinessDashboardCommandCenterRoute
  '/business-dashboard/financial-reporting': typeof BusinessDashboardFinancialReportingRoute
  '/business-dashboard/invoicing-billing': typeof BusinessDashboardInvoicingBillingRoute
  '/business-dashboard/multi-currency-treasury': typeof BusinessDashboardMultiCurrencyTreasuryRoute
  '/business-dashboard/open-banking': typeof BusinessDashboardOpenBankingRoute
  '/business-dashboard/payroll-hr': typeof BusinessDashboardPayrollHrRoute
  '/business-dashboard/settings-administration': typeof BusinessDashboardSettingsAdministrationRoute
  '/business-dashboard/support-disputes': typeof BusinessDashboardSupportDisputesRoute
  '/business-dashboard/treasury-cash': typeof BusinessDashboardTreasuryCashRoute
  '/business-dashboard/virtual-accounts': typeof BusinessDashboardVirtualAccountsRoute
  '/business/$module': typeof BusinessModuleRoute
  '/cards/app': typeof CardsAppRouteWithChildren
  '/dev-dashboard/api-governance': typeof DevDashboardApiGovernanceRoute
  '/dev-dashboard/api-reference': typeof DevDashboardApiReferenceRoute
  '/dev-dashboard/compliance-audit': typeof DevDashboardComplianceAuditRoute
  '/dev-dashboard/developer-dashboard': typeof DevDashboardDeveloperDashboardRoute
  '/dev-dashboard/integration-architecture': typeof DevDashboardIntegrationArchitectureRoute
  '/dev-dashboard/monitoring-incidents': typeof DevDashboardMonitoringIncidentsRoute
  '/dev-dashboard/partner-marketplace': typeof DevDashboardPartnerMarketplaceRoute
  '/dev-dashboard/playground': typeof DevDashboardPlaygroundRoute
  '/dev-dashboard/sdks': typeof DevDashboardSdksRoute
  '/dev-dashboard/security': typeof DevDashboardSecurityRoute
  '/dev-dashboard/support-slas': typeof DevDashboardSupportSlasRoute
  '/dev-dashboard/webhooks-events': typeof DevDashboardWebhooksEventsRoute
  '/dev/$module': typeof DevModuleRoute
  '/pm/app': typeof PmAppRouteWithChildren
  '/utility/$module': typeof UtilityModuleRoute
  '/utility/airtime': typeof UtilityAirtimeRoute
  '/utility/electricity': typeof UtilityElectricityRoute
  '/utility/internet': typeof UtilityInternetRoute
  '/utility/settings': typeof UtilitySettingsRoute
  '/utility/water': typeof UtilityWaterRoute
  '/business-dashboard/': typeof BusinessDashboardIndexRoute
  '/business/': typeof BusinessIndexRoute
  '/dev-dashboard/': typeof DevDashboardIndexRoute
  '/dev/': typeof DevIndexRoute
  '/utility/': typeof UtilityIndexRoute
  '/cards/app/account-settings': typeof CardsAppAccountSettingsRoute
  '/cards/app/card-analytics-reporting': typeof CardsAppCardAnalyticsReportingRoute
  '/cards/app/card-command-center': typeof CardsAppCardCommandCenterRoute
  '/cards/app/card-program-administration': typeof CardsAppCardProgramAdministrationRoute
  '/cards/app/card-security-fraud-prevention': typeof CardsAppCardSecurityFraudPreventionRoute
  '/cards/app/card-settings-support': typeof CardsAppCardSettingsSupportRoute
  '/cards/app/corporate-business-cards': typeof CardsAppCorporateBusinessCardsRoute
  '/cards/app/physical-debit-cards': typeof CardsAppPhysicalDebitCardsRoute
  '/cards/app/prepaid-card-management': typeof CardsAppPrepaidCardManagementRoute
  '/cards/app/support': typeof CardsAppSupportRoute
  '/cards/app/virtual-credit-cards': typeof CardsAppVirtualCreditCardsRoute
  '/cards/app/virtual-debit-cards': typeof CardsAppVirtualDebitCardsRoute
  '/pm/app/$section': typeof PmAppSectionRoute
  '/pm/app/account': typeof PmAppAccountRoute
  '/pm/app/analytics': typeof PmAppAnalyticsRoute
  '/pm/app/compliance': typeof PmAppComplianceRoute
  '/pm/app/customers': typeof PmAppCustomersRoute
  '/pm/app/disputes': typeof PmAppDisputesRoute
  '/pm/app/fees': typeof PmAppFeesRoute
  '/pm/app/fx': typeof PmAppFxRoute
  '/pm/app/initiate-transfer': typeof PmAppInitiateTransferRoute
  '/pm/app/kra-government': typeof PmAppKraGovernmentRoute
  '/pm/app/liquidity': typeof PmAppLiquidityRoute
  '/pm/app/mobile-money': typeof PmAppMobileMoneyRoute
  '/pm/app/ops-health': typeof PmAppOpsHealthRoute
  '/pm/app/payment-rails': typeof PmAppPaymentRailsRoute
  '/pm/app/reconciliation': typeof PmAppReconciliationRoute
  '/pm/app/settings': typeof PmAppSettingsRoute
  '/pm/app/settlement': typeof PmAppSettlementRoute
  '/pm/app/transfer-management': typeof PmAppTransferManagementRoute
  '/pm/app/transfer-overview': typeof PmAppTransferOverviewRoute
  '/pm/app/transfers': typeof PmAppTransfersRoute
  '/pm/app/': typeof PmAppIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/wallet-activation': typeof WalletActivationRoute
  '/business': typeof BusinessIndexRoute
  '/auth/account-status': typeof AuthAccountStatusRoute
  '/auth/hub': typeof AuthHubRoute
  '/auth/identity': typeof AuthIdentityRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/mfa': typeof AuthMfaRoute
  '/auth/passkeys': typeof AuthPasskeysRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/security': typeof AuthSecurityRoute
  '/business-dashboard/$module': typeof BusinessDashboardModuleRoute
  '/business-dashboard/accounts-payable': typeof BusinessDashboardAccountsPayableRoute
  '/business-dashboard/bulk-disbursements': typeof BusinessDashboardBulkDisbursementsRoute
  '/business-dashboard/business-onboarding': typeof BusinessDashboardBusinessOnboardingRoute
  '/business-dashboard/collections-merchant': typeof BusinessDashboardCollectionsMerchantRoute
  '/business-dashboard/command-center': typeof BusinessDashboardCommandCenterRoute
  '/business-dashboard/financial-reporting': typeof BusinessDashboardFinancialReportingRoute
  '/business-dashboard/invoicing-billing': typeof BusinessDashboardInvoicingBillingRoute
  '/business-dashboard/multi-currency-treasury': typeof BusinessDashboardMultiCurrencyTreasuryRoute
  '/business-dashboard/open-banking': typeof BusinessDashboardOpenBankingRoute
  '/business-dashboard/payroll-hr': typeof BusinessDashboardPayrollHrRoute
  '/business-dashboard/settings-administration': typeof BusinessDashboardSettingsAdministrationRoute
  '/business-dashboard/support-disputes': typeof BusinessDashboardSupportDisputesRoute
  '/business-dashboard/treasury-cash': typeof BusinessDashboardTreasuryCashRoute
  '/business-dashboard/virtual-accounts': typeof BusinessDashboardVirtualAccountsRoute
  '/business/$module': typeof BusinessModuleRoute
  '/cards/app': typeof CardsAppRouteWithChildren
  '/dev-dashboard/api-governance': typeof DevDashboardApiGovernanceRoute
  '/dev-dashboard/api-reference': typeof DevDashboardApiReferenceRoute
  '/dev-dashboard/compliance-audit': typeof DevDashboardComplianceAuditRoute
  '/dev-dashboard/developer-dashboard': typeof DevDashboardDeveloperDashboardRoute
  '/dev-dashboard/integration-architecture': typeof DevDashboardIntegrationArchitectureRoute
  '/dev-dashboard/monitoring-incidents': typeof DevDashboardMonitoringIncidentsRoute
  '/dev-dashboard/partner-marketplace': typeof DevDashboardPartnerMarketplaceRoute
  '/dev-dashboard/playground': typeof DevDashboardPlaygroundRoute
  '/dev-dashboard/sdks': typeof DevDashboardSdksRoute
  '/dev-dashboard/security': typeof DevDashboardSecurityRoute
  '/dev-dashboard/support-slas': typeof DevDashboardSupportSlasRoute
  '/dev-dashboard/webhooks-events': typeof DevDashboardWebhooksEventsRoute
  '/dev/$module': typeof DevModuleRoute
  '/utility/$module': typeof UtilityModuleRoute
  '/utility/airtime': typeof UtilityAirtimeRoute
  '/utility/electricity': typeof UtilityElectricityRoute
  '/utility/internet': typeof UtilityInternetRoute
  '/utility/settings': typeof UtilitySettingsRoute
  '/utility/water': typeof UtilityWaterRoute
  '/': typeof HomeIndexRoute
  '/business-dashboard': typeof BusinessDashboardIndexRoute
  '/dev-dashboard': typeof DevDashboardIndexRoute
  '/dev': typeof DevIndexRoute
  '/utility': typeof UtilityIndexRoute
  '/cards/app/account-settings': typeof CardsAppAccountSettingsRoute
  '/cards/app/card-analytics-reporting': typeof CardsAppCardAnalyticsReportingRoute
  '/cards/app/card-command-center': typeof CardsAppCardCommandCenterRoute
  '/cards/app/card-program-administration': typeof CardsAppCardProgramAdministrationRoute
  '/cards/app/card-security-fraud-prevention': typeof CardsAppCardSecurityFraudPreventionRoute
  '/cards/app/card-settings-support': typeof CardsAppCardSettingsSupportRoute
  '/cards/app/corporate-business-cards': typeof CardsAppCorporateBusinessCardsRoute
  '/cards/app/physical-debit-cards': typeof CardsAppPhysicalDebitCardsRoute
  '/cards/app/prepaid-card-management': typeof CardsAppPrepaidCardManagementRoute
  '/cards/app/support': typeof CardsAppSupportRoute
  '/cards/app/virtual-credit-cards': typeof CardsAppVirtualCreditCardsRoute
  '/cards/app/virtual-debit-cards': typeof CardsAppVirtualDebitCardsRoute
  '/pm/app/$section': typeof PmAppSectionRoute
  '/pm/app/account': typeof PmAppAccountRoute
  '/pm/app/analytics': typeof PmAppAnalyticsRoute
  '/pm/app/compliance': typeof PmAppComplianceRoute
  '/pm/app/customers': typeof PmAppCustomersRoute
  '/pm/app/disputes': typeof PmAppDisputesRoute
  '/pm/app/fees': typeof PmAppFeesRoute
  '/pm/app/fx': typeof PmAppFxRoute
  '/pm/app/initiate-transfer': typeof PmAppInitiateTransferRoute
  '/pm/app/kra-government': typeof PmAppKraGovernmentRoute
  '/pm/app/liquidity': typeof PmAppLiquidityRoute
  '/pm/app/mobile-money': typeof PmAppMobileMoneyRoute
  '/pm/app/ops-health': typeof PmAppOpsHealthRoute
  '/pm/app/payment-rails': typeof PmAppPaymentRailsRoute
  '/pm/app/reconciliation': typeof PmAppReconciliationRoute
  '/pm/app/settings': typeof PmAppSettingsRoute
  '/pm/app/settlement': typeof PmAppSettlementRoute
  '/pm/app/transfer-management': typeof PmAppTransferManagementRoute
  '/pm/app/transfer-overview': typeof PmAppTransferOverviewRoute
  '/pm/app/transfers': typeof PmAppTransfersRoute
  '/pm/app': typeof PmAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_home': typeof HomeRouteWithChildren
  '/business': typeof BusinessRouteWithChildren
  '/business-dashboard': typeof BusinessDashboardRouteWithChildren
  '/dev': typeof DevRouteWithChildren
  '/dev-dashboard': typeof DevDashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/utility': typeof UtilityRouteWithChildren
  '/wallet-activation': typeof WalletActivationRoute
  '/_home/business': typeof HomeBusinessRoute
  '/auth/account-status': typeof AuthAccountStatusRoute
  '/auth/hub': typeof AuthHubRoute
  '/auth/identity': typeof AuthIdentityRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/mfa': typeof AuthMfaRoute
  '/auth/passkeys': typeof AuthPasskeysRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/security': typeof AuthSecurityRoute
  '/business-dashboard/$module': typeof BusinessDashboardModuleRoute
  '/business-dashboard/accounts-payable': typeof BusinessDashboardAccountsPayableRoute
  '/business-dashboard/bulk-disbursements': typeof BusinessDashboardBulkDisbursementsRoute
  '/business-dashboard/business-onboarding': typeof BusinessDashboardBusinessOnboardingRoute
  '/business-dashboard/collections-merchant': typeof BusinessDashboardCollectionsMerchantRoute
  '/business-dashboard/command-center': typeof BusinessDashboardCommandCenterRoute
  '/business-dashboard/financial-reporting': typeof BusinessDashboardFinancialReportingRoute
  '/business-dashboard/invoicing-billing': typeof BusinessDashboardInvoicingBillingRoute
  '/business-dashboard/multi-currency-treasury': typeof BusinessDashboardMultiCurrencyTreasuryRoute
  '/business-dashboard/open-banking': typeof BusinessDashboardOpenBankingRoute
  '/business-dashboard/payroll-hr': typeof BusinessDashboardPayrollHrRoute
  '/business-dashboard/settings-administration': typeof BusinessDashboardSettingsAdministrationRoute
  '/business-dashboard/support-disputes': typeof BusinessDashboardSupportDisputesRoute
  '/business-dashboard/treasury-cash': typeof BusinessDashboardTreasuryCashRoute
  '/business-dashboard/virtual-accounts': typeof BusinessDashboardVirtualAccountsRoute
  '/business/$module': typeof BusinessModuleRoute
  '/cards/app': typeof CardsAppRouteWithChildren
  '/dev-dashboard/api-governance': typeof DevDashboardApiGovernanceRoute
  '/dev-dashboard/api-reference': typeof DevDashboardApiReferenceRoute
  '/dev-dashboard/compliance-audit': typeof DevDashboardComplianceAuditRoute
  '/dev-dashboard/developer-dashboard': typeof DevDashboardDeveloperDashboardRoute
  '/dev-dashboard/integration-architecture': typeof DevDashboardIntegrationArchitectureRoute
  '/dev-dashboard/monitoring-incidents': typeof DevDashboardMonitoringIncidentsRoute
  '/dev-dashboard/partner-marketplace': typeof DevDashboardPartnerMarketplaceRoute
  '/dev-dashboard/playground': typeof DevDashboardPlaygroundRoute
  '/dev-dashboard/sdks': typeof DevDashboardSdksRoute
  '/dev-dashboard/security': typeof DevDashboardSecurityRoute
  '/dev-dashboard/support-slas': typeof DevDashboardSupportSlasRoute
  '/dev-dashboard/webhooks-events': typeof DevDashboardWebhooksEventsRoute
  '/dev/$module': typeof DevModuleRoute
  '/pm/app': typeof PmAppRouteWithChildren
  '/utility/$module': typeof UtilityModuleRoute
  '/utility/airtime': typeof UtilityAirtimeRoute
  '/utility/electricity': typeof UtilityElectricityRoute
  '/utility/internet': typeof UtilityInternetRoute
  '/utility/settings': typeof UtilitySettingsRoute
  '/utility/water': typeof UtilityWaterRoute
  '/_home/': typeof HomeIndexRoute
  '/business-dashboard/': typeof BusinessDashboardIndexRoute
  '/business/': typeof BusinessIndexRoute
  '/dev-dashboard/': typeof DevDashboardIndexRoute
  '/dev/': typeof DevIndexRoute
  '/utility/': typeof UtilityIndexRoute
  '/cards/app/account-settings': typeof CardsAppAccountSettingsRoute
  '/cards/app/card-analytics-reporting': typeof CardsAppCardAnalyticsReportingRoute
  '/cards/app/card-command-center': typeof CardsAppCardCommandCenterRoute
  '/cards/app/card-program-administration': typeof CardsAppCardProgramAdministrationRoute
  '/cards/app/card-security-fraud-prevention': typeof CardsAppCardSecurityFraudPreventionRoute
  '/cards/app/card-settings-support': typeof CardsAppCardSettingsSupportRoute
  '/cards/app/corporate-business-cards': typeof CardsAppCorporateBusinessCardsRoute
  '/cards/app/physical-debit-cards': typeof CardsAppPhysicalDebitCardsRoute
  '/cards/app/prepaid-card-management': typeof CardsAppPrepaidCardManagementRoute
  '/cards/app/support': typeof CardsAppSupportRoute
  '/cards/app/virtual-credit-cards': typeof CardsAppVirtualCreditCardsRoute
  '/cards/app/virtual-debit-cards': typeof CardsAppVirtualDebitCardsRoute
  '/pm/app/$section': typeof PmAppSectionRoute
  '/pm/app/account': typeof PmAppAccountRoute
  '/pm/app/analytics': typeof PmAppAnalyticsRoute
  '/pm/app/compliance': typeof PmAppComplianceRoute
  '/pm/app/customers': typeof PmAppCustomersRoute
  '/pm/app/disputes': typeof PmAppDisputesRoute
  '/pm/app/fees': typeof PmAppFeesRoute
  '/pm/app/fx': typeof PmAppFxRoute
  '/pm/app/initiate-transfer': typeof PmAppInitiateTransferRoute
  '/pm/app/kra-government': typeof PmAppKraGovernmentRoute
  '/pm/app/liquidity': typeof PmAppLiquidityRoute
  '/pm/app/mobile-money': typeof PmAppMobileMoneyRoute
  '/pm/app/ops-health': typeof PmAppOpsHealthRoute
  '/pm/app/payment-rails': typeof PmAppPaymentRailsRoute
  '/pm/app/reconciliation': typeof PmAppReconciliationRoute
  '/pm/app/settings': typeof PmAppSettingsRoute
  '/pm/app/settlement': typeof PmAppSettlementRoute
  '/pm/app/transfer-management': typeof PmAppTransferManagementRoute
  '/pm/app/transfer-overview': typeof PmAppTransferOverviewRoute
  '/pm/app/transfers': typeof PmAppTransfersRoute
  '/pm/app/': typeof PmAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/business'
    | '/business-dashboard'
    | '/dev'
    | '/dev-dashboard'
    | '/login'
    | '/utility'
    | '/wallet-activation'
    | '/auth/account-status'
    | '/auth/hub'
    | '/auth/identity'
    | '/auth/login'
    | '/auth/mfa'
    | '/auth/passkeys'
    | '/auth/recovery'
    | '/auth/register'
    | '/auth/security'
    | '/business-dashboard/$module'
    | '/business-dashboard/accounts-payable'
    | '/business-dashboard/bulk-disbursements'
    | '/business-dashboard/business-onboarding'
    | '/business-dashboard/collections-merchant'
    | '/business-dashboard/command-center'
    | '/business-dashboard/financial-reporting'
    | '/business-dashboard/invoicing-billing'
    | '/business-dashboard/multi-currency-treasury'
    | '/business-dashboard/open-banking'
    | '/business-dashboard/payroll-hr'
    | '/business-dashboard/settings-administration'
    | '/business-dashboard/support-disputes'
    | '/business-dashboard/treasury-cash'
    | '/business-dashboard/virtual-accounts'
    | '/business/$module'
    | '/cards/app'
    | '/dev-dashboard/api-governance'
    | '/dev-dashboard/api-reference'
    | '/dev-dashboard/compliance-audit'
    | '/dev-dashboard/developer-dashboard'
    | '/dev-dashboard/integration-architecture'
    | '/dev-dashboard/monitoring-incidents'
    | '/dev-dashboard/partner-marketplace'
    | '/dev-dashboard/playground'
    | '/dev-dashboard/sdks'
    | '/dev-dashboard/security'
    | '/dev-dashboard/support-slas'
    | '/dev-dashboard/webhooks-events'
    | '/dev/$module'
    | '/pm/app'
    | '/utility/$module'
    | '/utility/airtime'
    | '/utility/electricity'
    | '/utility/internet'
    | '/utility/settings'
    | '/utility/water'
    | '/business-dashboard/'
    | '/business/'
    | '/dev-dashboard/'
    | '/dev/'
    | '/utility/'
    | '/cards/app/account-settings'
    | '/cards/app/card-analytics-reporting'
    | '/cards/app/card-command-center'
    | '/cards/app/card-program-administration'
    | '/cards/app/card-security-fraud-prevention'
    | '/cards/app/card-settings-support'
    | '/cards/app/corporate-business-cards'
    | '/cards/app/physical-debit-cards'
    | '/cards/app/prepaid-card-management'
    | '/cards/app/support'
    | '/cards/app/virtual-credit-cards'
    | '/cards/app/virtual-debit-cards'
    | '/pm/app/$section'
    | '/pm/app/account'
    | '/pm/app/analytics'
    | '/pm/app/compliance'
    | '/pm/app/customers'
    | '/pm/app/disputes'
    | '/pm/app/fees'
    | '/pm/app/fx'
    | '/pm/app/initiate-transfer'
    | '/pm/app/kra-government'
    | '/pm/app/liquidity'
    | '/pm/app/mobile-money'
    | '/pm/app/ops-health'
    | '/pm/app/payment-rails'
    | '/pm/app/reconciliation'
    | '/pm/app/settings'
    | '/pm/app/settlement'
    | '/pm/app/transfer-management'
    | '/pm/app/transfer-overview'
    | '/pm/app/transfers'
    | '/pm/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/wallet-activation'
    | '/business'
    | '/auth/account-status'
    | '/auth/hub'
    | '/auth/identity'
    | '/auth/login'
    | '/auth/mfa'
    | '/auth/passkeys'
    | '/auth/recovery'
    | '/auth/register'
    | '/auth/security'
    | '/business-dashboard/$module'
    | '/business-dashboard/accounts-payable'
    | '/business-dashboard/bulk-disbursements'
    | '/business-dashboard/business-onboarding'
    | '/business-dashboard/collections-merchant'
    | '/business-dashboard/command-center'
    | '/business-dashboard/financial-reporting'
    | '/business-dashboard/invoicing-billing'
    | '/business-dashboard/multi-currency-treasury'
    | '/business-dashboard/open-banking'
    | '/business-dashboard/payroll-hr'
    | '/business-dashboard/settings-administration'
    | '/business-dashboard/support-disputes'
    | '/business-dashboard/treasury-cash'
    | '/business-dashboard/virtual-accounts'
    | '/business/$module'
    | '/cards/app'
    | '/dev-dashboard/api-governance'
    | '/dev-dashboard/api-reference'
    | '/dev-dashboard/compliance-audit'
    | '/dev-dashboard/developer-dashboard'
    | '/dev-dashboard/integration-architecture'
    | '/dev-dashboard/monitoring-incidents'
    | '/dev-dashboard/partner-marketplace'
    | '/dev-dashboard/playground'
    | '/dev-dashboard/sdks'
    | '/dev-dashboard/security'
    | '/dev-dashboard/support-slas'
    | '/dev-dashboard/webhooks-events'
    | '/dev/$module'
    | '/utility/$module'
    | '/utility/airtime'
    | '/utility/electricity'
    | '/utility/internet'
    | '/utility/settings'
    | '/utility/water'
    | '/'
    | '/business-dashboard'
    | '/dev-dashboard'
    | '/dev'
    | '/utility'
    | '/cards/app/account-settings'
    | '/cards/app/card-analytics-reporting'
    | '/cards/app/card-command-center'
    | '/cards/app/card-program-administration'
    | '/cards/app/card-security-fraud-prevention'
    | '/cards/app/card-settings-support'
    | '/cards/app/corporate-business-cards'
    | '/cards/app/physical-debit-cards'
    | '/cards/app/prepaid-card-management'
    | '/cards/app/support'
    | '/cards/app/virtual-credit-cards'
    | '/cards/app/virtual-debit-cards'
    | '/pm/app/$section'
    | '/pm/app/account'
    | '/pm/app/analytics'
    | '/pm/app/compliance'
    | '/pm/app/customers'
    | '/pm/app/disputes'
    | '/pm/app/fees'
    | '/pm/app/fx'
    | '/pm/app/initiate-transfer'
    | '/pm/app/kra-government'
    | '/pm/app/liquidity'
    | '/pm/app/mobile-money'
    | '/pm/app/ops-health'
    | '/pm/app/payment-rails'
    | '/pm/app/reconciliation'
    | '/pm/app/settings'
    | '/pm/app/settlement'
    | '/pm/app/transfer-management'
    | '/pm/app/transfer-overview'
    | '/pm/app/transfers'
    | '/pm/app'
  id:
    | '__root__'
    | '/_home'
    | '/business'
    | '/business-dashboard'
    | '/dev'
    | '/dev-dashboard'
    | '/login'
    | '/utility'
    | '/wallet-activation'
    | '/_home/business'
    | '/auth/account-status'
    | '/auth/hub'
    | '/auth/identity'
    | '/auth/login'
    | '/auth/mfa'
    | '/auth/passkeys'
    | '/auth/recovery'
    | '/auth/register'
    | '/auth/security'
    | '/business-dashboard/$module'
    | '/business-dashboard/accounts-payable'
    | '/business-dashboard/bulk-disbursements'
    | '/business-dashboard/business-onboarding'
    | '/business-dashboard/collections-merchant'
    | '/business-dashboard/command-center'
    | '/business-dashboard/financial-reporting'
    | '/business-dashboard/invoicing-billing'
    | '/business-dashboard/multi-currency-treasury'
    | '/business-dashboard/open-banking'
    | '/business-dashboard/payroll-hr'
    | '/business-dashboard/settings-administration'
    | '/business-dashboard/support-disputes'
    | '/business-dashboard/treasury-cash'
    | '/business-dashboard/virtual-accounts'
    | '/business/$module'
    | '/cards/app'
    | '/dev-dashboard/api-governance'
    | '/dev-dashboard/api-reference'
    | '/dev-dashboard/compliance-audit'
    | '/dev-dashboard/developer-dashboard'
    | '/dev-dashboard/integration-architecture'
    | '/dev-dashboard/monitoring-incidents'
    | '/dev-dashboard/partner-marketplace'
    | '/dev-dashboard/playground'
    | '/dev-dashboard/sdks'
    | '/dev-dashboard/security'
    | '/dev-dashboard/support-slas'
    | '/dev-dashboard/webhooks-events'
    | '/dev/$module'
    | '/pm/app'
    | '/utility/$module'
    | '/utility/airtime'
    | '/utility/electricity'
    | '/utility/internet'
    | '/utility/settings'
    | '/utility/water'
    | '/_home/'
    | '/business-dashboard/'
    | '/business/'
    | '/dev-dashboard/'
    | '/dev/'
    | '/utility/'
    | '/cards/app/account-settings'
    | '/cards/app/card-analytics-reporting'
    | '/cards/app/card-command-center'
    | '/cards/app/card-program-administration'
    | '/cards/app/card-security-fraud-prevention'
    | '/cards/app/card-settings-support'
    | '/cards/app/corporate-business-cards'
    | '/cards/app/physical-debit-cards'
    | '/cards/app/prepaid-card-management'
    | '/cards/app/support'
    | '/cards/app/virtual-credit-cards'
    | '/cards/app/virtual-debit-cards'
    | '/pm/app/$section'
    | '/pm/app/account'
    | '/pm/app/analytics'
    | '/pm/app/compliance'
    | '/pm/app/customers'
    | '/pm/app/disputes'
    | '/pm/app/fees'
    | '/pm/app/fx'
    | '/pm/app/initiate-transfer'
    | '/pm/app/kra-government'
    | '/pm/app/liquidity'
    | '/pm/app/mobile-money'
    | '/pm/app/ops-health'
    | '/pm/app/payment-rails'
    | '/pm/app/reconciliation'
    | '/pm/app/settings'
    | '/pm/app/settlement'
    | '/pm/app/transfer-management'
    | '/pm/app/transfer-overview'
    | '/pm/app/transfers'
    | '/pm/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeRoute: typeof HomeRouteWithChildren
  BusinessRoute: typeof BusinessRouteWithChildren
  BusinessDashboardRoute: typeof BusinessDashboardRouteWithChildren
  DevRoute: typeof DevRouteWithChildren
  DevDashboardRoute: typeof DevDashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  UtilityRoute: typeof UtilityRouteWithChildren
  WalletActivationRoute: typeof WalletActivationRoute
  AuthAccountStatusRoute: typeof AuthAccountStatusRoute
  AuthHubRoute: typeof AuthHubRoute
  AuthIdentityRoute: typeof AuthIdentityRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthMfaRoute: typeof AuthMfaRoute
  AuthPasskeysRoute: typeof AuthPasskeysRoute
  AuthRecoveryRoute: typeof AuthRecoveryRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthSecurityRoute: typeof AuthSecurityRoute
  CardsAppRoute: typeof CardsAppRouteWithChildren
  PmAppRoute: typeof PmAppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet-activation': {
      id: '/wallet-activation'
      path: '/wallet-activation'
      fullPath: '/wallet-activation'
      preLoaderRoute: typeof WalletActivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utility': {
      id: '/utility'
      path: '/utility'
      fullPath: '/utility'
      preLoaderRoute: typeof UtilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-dashboard': {
      id: '/dev-dashboard'
      path: '/dev-dashboard'
      fullPath: '/dev-dashboard'
      preLoaderRoute: typeof DevDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-dashboard': {
      id: '/business-dashboard'
      path: '/business-dashboard'
      fullPath: '/business-dashboard'
      preLoaderRoute: typeof BusinessDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utility/': {
      id: '/utility/'
      path: '/'
      fullPath: '/utility/'
      preLoaderRoute: typeof UtilityIndexRouteImport
      parentRoute: typeof UtilityRoute
    }
    '/dev/': {
      id: '/dev/'
      path: '/'
      fullPath: '/dev/'
      preLoaderRoute: typeof DevIndexRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev-dashboard/': {
      id: '/dev-dashboard/'
      path: '/'
      fullPath: '/dev-dashboard/'
      preLoaderRoute: typeof DevDashboardIndexRouteImport
      parentRoute: typeof DevDashboardRoute
    }
    '/business/': {
      id: '/business/'
      path: '/'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business-dashboard/': {
      id: '/business-dashboard/'
      path: '/'
      fullPath: '/business-dashboard/'
      preLoaderRoute: typeof BusinessDashboardIndexRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/utility/water': {
      id: '/utility/water'
      path: '/water'
      fullPath: '/utility/water'
      preLoaderRoute: typeof UtilityWaterRouteImport
      parentRoute: typeof UtilityRoute
    }
    '/utility/settings': {
      id: '/utility/settings'
      path: '/settings'
      fullPath: '/utility/settings'
      preLoaderRoute: typeof UtilitySettingsRouteImport
      parentRoute: typeof UtilityRoute
    }
    '/utility/internet': {
      id: '/utility/internet'
      path: '/internet'
      fullPath: '/utility/internet'
      preLoaderRoute: typeof UtilityInternetRouteImport
      parentRoute: typeof UtilityRoute
    }
    '/utility/electricity': {
      id: '/utility/electricity'
      path: '/electricity'
      fullPath: '/utility/electricity'
      preLoaderRoute: typeof UtilityElectricityRouteImport
      parentRoute: typeof UtilityRoute
    }
    '/utility/airtime': {
      id: '/utility/airtime'
      path: '/airtime'
      fullPath: '/utility/airtime'
      preLoaderRoute: typeof UtilityAirtimeRouteImport
      parentRoute: typeof UtilityRoute
    }
    '/utility/$module': {
      id: '/utility/$module'
      path: '/$module'
      fullPath: '/utility/$module'
      preLoaderRoute: typeof UtilityModuleRouteImport
      parentRoute: typeof UtilityRoute
    }
    '/pm/app': {
      id: '/pm/app'
      path: '/pm/app'
      fullPath: '/pm/app'
      preLoaderRoute: typeof PmAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/$module': {
      id: '/dev/$module'
      path: '/$module'
      fullPath: '/dev/$module'
      preLoaderRoute: typeof DevModuleRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev-dashboard/webhooks-events': {
      id: '/dev-dashboard/webhooks-events'
      path: '/webhooks-events'
      fullPath: '/dev-dashboard/webhooks-events'
      preLoaderRoute: typeof DevDashboardWebhooksEventsRouteImport
      parentRoute: typeof DevDashboardRoute
    }
    '/dev-dashboard/support-slas': {
      id: '/dev-dashboard/support-slas'
      path: '/support-slas'
      fullPath: '/dev-dashboard/support-slas'
      preLoaderRoute: typeof DevDashboardSupportSlasRouteImport
      parentRoute: typeof DevDashboardRoute
    }
    '/dev-dashboard/security': {
      id: '/dev-dashboard/security'
      path: '/security'
      fullPath: '/dev-dashboard/security'
      preLoaderRoute: typeof DevDashboardSecurityRouteImport
      parentRoute: typeof DevDashboardRoute
    }
    '/dev-dashboard/sdks': {
      id: '/dev-dashboard/sdks'
      path: '/sdks'
      fullPath: '/dev-dashboard/sdks'
      preLoaderRoute: typeof DevDashboardSdksRouteImport
      parentRoute: typeof DevDashboardRoute
    }
    '/dev-dashboard/playground': {
      id: '/dev-dashboard/playground'
      path: '/playground'
      fullPath: '/dev-dashboard/playground'
      preLoaderRoute: typeof DevDashboardPlaygroundRouteImport
      parentRoute: typeof DevDashboardRoute
    }
    '/dev-dashboard/partner-marketplace': {
      id: '/dev-dashboard/partner-marketplace'
      path: '/partner-marketplace'
      fullPath: '/dev-dashboard/partner-marketplace'
      preLoaderRoute: typeof DevDashboardPartnerMarketplaceRouteImport
      parentRoute: typeof DevDashboardRoute
    }
    '/dev-dashboard/monitoring-incidents': {
      id: '/dev-dashboard/monitoring-incidents'
      path: '/monitoring-incidents'
      fullPath: '/dev-dashboard/monitoring-incidents'
      preLoaderRoute: typeof DevDashboardMonitoringIncidentsRouteImport
      parentRoute: typeof DevDashboardRoute
    }
    '/dev-dashboard/integration-architecture': {
      id: '/dev-dashboard/integration-architecture'
      path: '/integration-architecture'
      fullPath: '/dev-dashboard/integration-architecture'
      preLoaderRoute: typeof DevDashboardIntegrationArchitectureRouteImport
      parentRoute: typeof DevDashboardRoute
    }
    '/dev-dashboard/developer-dashboard': {
      id: '/dev-dashboard/developer-dashboard'
      path: '/developer-dashboard'
      fullPath: '/dev-dashboard/developer-dashboard'
      preLoaderRoute: typeof DevDashboardDeveloperDashboardRouteImport
      parentRoute: typeof DevDashboardRoute
    }
    '/dev-dashboard/compliance-audit': {
      id: '/dev-dashboard/compliance-audit'
      path: '/compliance-audit'
      fullPath: '/dev-dashboard/compliance-audit'
      preLoaderRoute: typeof DevDashboardComplianceAuditRouteImport
      parentRoute: typeof DevDashboardRoute
    }
    '/dev-dashboard/api-reference': {
      id: '/dev-dashboard/api-reference'
      path: '/api-reference'
      fullPath: '/dev-dashboard/api-reference'
      preLoaderRoute: typeof DevDashboardApiReferenceRouteImport
      parentRoute: typeof DevDashboardRoute
    }
    '/dev-dashboard/api-governance': {
      id: '/dev-dashboard/api-governance'
      path: '/api-governance'
      fullPath: '/dev-dashboard/api-governance'
      preLoaderRoute: typeof DevDashboardApiGovernanceRouteImport
      parentRoute: typeof DevDashboardRoute
    }
    '/cards/app': {
      id: '/cards/app'
      path: '/cards/app'
      fullPath: '/cards/app'
      preLoaderRoute: typeof CardsAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/$module': {
      id: '/business/$module'
      path: '/$module'
      fullPath: '/business/$module'
      preLoaderRoute: typeof BusinessModuleRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business-dashboard/virtual-accounts': {
      id: '/business-dashboard/virtual-accounts'
      path: '/virtual-accounts'
      fullPath: '/business-dashboard/virtual-accounts'
      preLoaderRoute: typeof BusinessDashboardVirtualAccountsRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business-dashboard/treasury-cash': {
      id: '/business-dashboard/treasury-cash'
      path: '/treasury-cash'
      fullPath: '/business-dashboard/treasury-cash'
      preLoaderRoute: typeof BusinessDashboardTreasuryCashRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business-dashboard/support-disputes': {
      id: '/business-dashboard/support-disputes'
      path: '/support-disputes'
      fullPath: '/business-dashboard/support-disputes'
      preLoaderRoute: typeof BusinessDashboardSupportDisputesRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business-dashboard/settings-administration': {
      id: '/business-dashboard/settings-administration'
      path: '/settings-administration'
      fullPath: '/business-dashboard/settings-administration'
      preLoaderRoute: typeof BusinessDashboardSettingsAdministrationRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business-dashboard/payroll-hr': {
      id: '/business-dashboard/payroll-hr'
      path: '/payroll-hr'
      fullPath: '/business-dashboard/payroll-hr'
      preLoaderRoute: typeof BusinessDashboardPayrollHrRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business-dashboard/open-banking': {
      id: '/business-dashboard/open-banking'
      path: '/open-banking'
      fullPath: '/business-dashboard/open-banking'
      preLoaderRoute: typeof BusinessDashboardOpenBankingRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business-dashboard/multi-currency-treasury': {
      id: '/business-dashboard/multi-currency-treasury'
      path: '/multi-currency-treasury'
      fullPath: '/business-dashboard/multi-currency-treasury'
      preLoaderRoute: typeof BusinessDashboardMultiCurrencyTreasuryRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business-dashboard/invoicing-billing': {
      id: '/business-dashboard/invoicing-billing'
      path: '/invoicing-billing'
      fullPath: '/business-dashboard/invoicing-billing'
      preLoaderRoute: typeof BusinessDashboardInvoicingBillingRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business-dashboard/financial-reporting': {
      id: '/business-dashboard/financial-reporting'
      path: '/financial-reporting'
      fullPath: '/business-dashboard/financial-reporting'
      preLoaderRoute: typeof BusinessDashboardFinancialReportingRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business-dashboard/command-center': {
      id: '/business-dashboard/command-center'
      path: '/command-center'
      fullPath: '/business-dashboard/command-center'
      preLoaderRoute: typeof BusinessDashboardCommandCenterRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business-dashboard/collections-merchant': {
      id: '/business-dashboard/collections-merchant'
      path: '/collections-merchant'
      fullPath: '/business-dashboard/collections-merchant'
      preLoaderRoute: typeof BusinessDashboardCollectionsMerchantRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business-dashboard/business-onboarding': {
      id: '/business-dashboard/business-onboarding'
      path: '/business-onboarding'
      fullPath: '/business-dashboard/business-onboarding'
      preLoaderRoute: typeof BusinessDashboardBusinessOnboardingRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business-dashboard/bulk-disbursements': {
      id: '/business-dashboard/bulk-disbursements'
      path: '/bulk-disbursements'
      fullPath: '/business-dashboard/bulk-disbursements'
      preLoaderRoute: typeof BusinessDashboardBulkDisbursementsRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business-dashboard/accounts-payable': {
      id: '/business-dashboard/accounts-payable'
      path: '/accounts-payable'
      fullPath: '/business-dashboard/accounts-payable'
      preLoaderRoute: typeof BusinessDashboardAccountsPayableRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business-dashboard/$module': {
      id: '/business-dashboard/$module'
      path: '/$module'
      fullPath: '/business-dashboard/$module'
      preLoaderRoute: typeof BusinessDashboardModuleRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/auth/security': {
      id: '/auth/security'
      path: '/auth/security'
      fullPath: '/auth/security'
      preLoaderRoute: typeof AuthSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/recovery': {
      id: '/auth/recovery'
      path: '/auth/recovery'
      fullPath: '/auth/recovery'
      preLoaderRoute: typeof AuthRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/passkeys': {
      id: '/auth/passkeys'
      path: '/auth/passkeys'
      fullPath: '/auth/passkeys'
      preLoaderRoute: typeof AuthPasskeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/mfa': {
      id: '/auth/mfa'
      path: '/auth/mfa'
      fullPath: '/auth/mfa'
      preLoaderRoute: typeof AuthMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/identity': {
      id: '/auth/identity'
      path: '/auth/identity'
      fullPath: '/auth/identity'
      preLoaderRoute: typeof AuthIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/hub': {
      id: '/auth/hub'
      path: '/auth/hub'
      fullPath: '/auth/hub'
      preLoaderRoute: typeof AuthHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/account-status': {
      id: '/auth/account-status'
      path: '/auth/account-status'
      fullPath: '/auth/account-status'
      preLoaderRoute: typeof AuthAccountStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/business': {
      id: '/_home/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof HomeBusinessRouteImport
      parentRoute: typeof HomeRoute
    }
    '/pm/app/': {
      id: '/pm/app/'
      path: '/'
      fullPath: '/pm/app/'
      preLoaderRoute: typeof PmAppIndexRouteImport
      parentRoute: typeof PmAppRoute
    }
    '/pm/app/transfers': {
      id: '/pm/app/transfers'
      path: '/transfers'
      fullPath: '/pm/app/transfers'
      preLoaderRoute: typeof PmAppTransfersRouteImport
      parentRoute: typeof PmAppRoute
    }
    '/pm/app/transfer-overview': {
      id: '/pm/app/transfer-overview'
      path: '/transfer-overview'
      fullPath: '/pm/app/transfer-overview'
      preLoaderRoute: typeof PmAppTransferOverviewRouteImport
      parentRoute: typeof PmAppRoute
    }
    '/pm/app/transfer-management': {
      id: '/pm/app/transfer-management'
      path: '/transfer-management'
      fullPath: '/pm/app/transfer-management'
      preLoaderRoute: typeof PmAppTransferManagementRouteImport
      parentRoute: typeof PmAppRoute
    }
    '/pm/app/settlement': {
      id: '/pm/app/settlement'
      path: '/settlement'
      fullPath: '/pm/app/settlement'
      preLoaderRoute: typeof PmAppSettlementRouteImport
      parentRoute: typeof PmAppRoute
    }
    '/pm/app/settings': {
      id: '/pm/app/settings'
      path: '/settings'
      fullPath: '/pm/app/settings'
      preLoaderRoute: typeof PmAppSettingsRouteImport
      parentRoute: typeof PmAppRoute
    }
    '/pm/app/reconciliation': {
      id: '/pm/app/reconciliation'
      path: '/reconciliation'
      fullPath: '/pm/app/reconciliation'
      preLoaderRoute: typeof PmAppReconciliationRouteImport
      parentRoute: typeof PmAppRoute
    }
    '/pm/app/payment-rails': {
      id: '/pm/app/payment-rails'
      path: '/payment-rails'
      fullPath: '/pm/app/payment-rails'
      preLoaderRoute: typeof PmAppPaymentRailsRouteImport
      parentRoute: typeof PmAppRoute
    }
    '/pm/app/ops-health': {
      id: '/pm/app/ops-health'
      path: '/ops-health'
      fullPath: '/pm/app/ops-health'
      preLoaderRoute: typeof PmAppOpsHealthRouteImport
      parentRoute: typeof PmAppRoute
    }
    '/pm/app/mobile-money': {
      id: '/pm/app/mobile-money'
      path: '/mobile-money'
      fullPath: '/pm/app/mobile-money'
      preLoaderRoute: typeof PmAppMobileMoneyRouteImport
      parentRoute: typeof PmAppRoute
    }
    '/pm/app/liquidity': {
      id: '/pm/app/liquidity'
      path: '/liquidity'
      fullPath: '/pm/app/liquidity'
      preLoaderRoute: typeof PmAppLiquidityRouteImport
      parentRoute: typeof PmAppRoute
    }
    '/pm/app/kra-government': {
      id: '/pm/app/kra-government'
      path: '/kra-government'
      fullPath: '/pm/app/kra-government'
      preLoaderRoute: typeof PmAppKraGovernmentRouteImport
      parentRoute: typeof PmAppRoute
    }
    '/pm/app/initiate-transfer': {
      id: '/pm/app/initiate-transfer'
      path: '/initiate-transfer'
      fullPath: '/pm/app/initiate-transfer'
      preLoaderRoute: typeof PmAppInitiateTransferRouteImport
      parentRoute: typeof PmAppRoute
    }
    '/pm/app/fx': {
      id: '/pm/app/fx'
      path: '/fx'
      fullPath: '/pm/app/fx'
      preLoaderRoute: typeof PmAppFxRouteImport
      parentRoute: typeof PmAppRoute
    }
    '/pm/app/fees': {
      id: '/pm/app/fees'
      path: '/fees'
      fullPath: '/pm/app/fees'
      preLoaderRoute: typeof PmAppFeesRouteImport
      parentRoute: typeof PmAppRoute
    }
    '/pm/app/disputes': {
      id: '/pm/app/disputes'
      path: '/disputes'
      fullPath: '/pm/app/disputes'
      preLoaderRoute: typeof PmAppDisputesRouteImport
      parentRoute: typeof PmAppRoute
    }
    '/pm/app/customers': {
      id: '/pm/app/customers'
      path: '/customers'
      fullPath: '/pm/app/customers'
      preLoaderRoute: typeof PmAppCustomersRouteImport
      parentRoute: typeof PmAppRoute
    }
    '/pm/app/compliance': {
      id: '/pm/app/compliance'
      path: '/compliance'
      fullPath: '/pm/app/compliance'
      preLoaderRoute: typeof PmAppComplianceRouteImport
      parentRoute: typeof PmAppRoute
    }
    '/pm/app/analytics': {
      id: '/pm/app/analytics'
      path: '/analytics'
      fullPath: '/pm/app/analytics'
      preLoaderRoute: typeof PmAppAnalyticsRouteImport
      parentRoute: typeof PmAppRoute
    }
    '/pm/app/account': {
      id: '/pm/app/account'
      path: '/account'
      fullPath: '/pm/app/account'
      preLoaderRoute: typeof PmAppAccountRouteImport
      parentRoute: typeof PmAppRoute
    }
    '/pm/app/$section': {
      id: '/pm/app/$section'
      path: '/$section'
      fullPath: '/pm/app/$section'
      preLoaderRoute: typeof PmAppSectionRouteImport
      parentRoute: typeof PmAppRoute
    }
    '/cards/app/virtual-debit-cards': {
      id: '/cards/app/virtual-debit-cards'
      path: '/virtual-debit-cards'
      fullPath: '/cards/app/virtual-debit-cards'
      preLoaderRoute: typeof CardsAppVirtualDebitCardsRouteImport
      parentRoute: typeof CardsAppRoute
    }
    '/cards/app/virtual-credit-cards': {
      id: '/cards/app/virtual-credit-cards'
      path: '/virtual-credit-cards'
      fullPath: '/cards/app/virtual-credit-cards'
      preLoaderRoute: typeof CardsAppVirtualCreditCardsRouteImport
      parentRoute: typeof CardsAppRoute
    }
    '/cards/app/support': {
      id: '/cards/app/support'
      path: '/support'
      fullPath: '/cards/app/support'
      preLoaderRoute: typeof CardsAppSupportRouteImport
      parentRoute: typeof CardsAppRoute
    }
    '/cards/app/prepaid-card-management': {
      id: '/cards/app/prepaid-card-management'
      path: '/prepaid-card-management'
      fullPath: '/cards/app/prepaid-card-management'
      preLoaderRoute: typeof CardsAppPrepaidCardManagementRouteImport
      parentRoute: typeof CardsAppRoute
    }
    '/cards/app/physical-debit-cards': {
      id: '/cards/app/physical-debit-cards'
      path: '/physical-debit-cards'
      fullPath: '/cards/app/physical-debit-cards'
      preLoaderRoute: typeof CardsAppPhysicalDebitCardsRouteImport
      parentRoute: typeof CardsAppRoute
    }
    '/cards/app/corporate-business-cards': {
      id: '/cards/app/corporate-business-cards'
      path: '/corporate-business-cards'
      fullPath: '/cards/app/corporate-business-cards'
      preLoaderRoute: typeof CardsAppCorporateBusinessCardsRouteImport
      parentRoute: typeof CardsAppRoute
    }
    '/cards/app/card-settings-support': {
      id: '/cards/app/card-settings-support'
      path: '/card-settings-support'
      fullPath: '/cards/app/card-settings-support'
      preLoaderRoute: typeof CardsAppCardSettingsSupportRouteImport
      parentRoute: typeof CardsAppRoute
    }
    '/cards/app/card-security-fraud-prevention': {
      id: '/cards/app/card-security-fraud-prevention'
      path: '/card-security-fraud-prevention'
      fullPath: '/cards/app/card-security-fraud-prevention'
      preLoaderRoute: typeof CardsAppCardSecurityFraudPreventionRouteImport
      parentRoute: typeof CardsAppRoute
    }
    '/cards/app/card-program-administration': {
      id: '/cards/app/card-program-administration'
      path: '/card-program-administration'
      fullPath: '/cards/app/card-program-administration'
      preLoaderRoute: typeof CardsAppCardProgramAdministrationRouteImport
      parentRoute: typeof CardsAppRoute
    }
    '/cards/app/card-command-center': {
      id: '/cards/app/card-command-center'
      path: '/card-command-center'
      fullPath: '/cards/app/card-command-center'
      preLoaderRoute: typeof CardsAppCardCommandCenterRouteImport
      parentRoute: typeof CardsAppRoute
    }
    '/cards/app/card-analytics-reporting': {
      id: '/cards/app/card-analytics-reporting'
      path: '/card-analytics-reporting'
      fullPath: '/cards/app/card-analytics-reporting'
      preLoaderRoute: typeof CardsAppCardAnalyticsReportingRouteImport
      parentRoute: typeof CardsAppRoute
    }
    '/cards/app/account-settings': {
      id: '/cards/app/account-settings'
      path: '/account-settings'
      fullPath: '/cards/app/account-settings'
      preLoaderRoute: typeof CardsAppAccountSettingsRouteImport
      parentRoute: typeof CardsAppRoute
    }
  }
}

interface HomeRouteChildren {
  HomeBusinessRoute: typeof HomeBusinessRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeBusinessRoute: HomeBusinessRoute,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

interface BusinessRouteChildren {
  BusinessModuleRoute: typeof BusinessModuleRoute
  BusinessIndexRoute: typeof BusinessIndexRoute
}

const BusinessRouteChildren: BusinessRouteChildren = {
  BusinessModuleRoute: BusinessModuleRoute,
  BusinessIndexRoute: BusinessIndexRoute,
}

const BusinessRouteWithChildren = BusinessRoute._addFileChildren(
  BusinessRouteChildren,
)

interface BusinessDashboardRouteChildren {
  BusinessDashboardModuleRoute: typeof BusinessDashboardModuleRoute
  BusinessDashboardAccountsPayableRoute: typeof BusinessDashboardAccountsPayableRoute
  BusinessDashboardBulkDisbursementsRoute: typeof BusinessDashboardBulkDisbursementsRoute
  BusinessDashboardBusinessOnboardingRoute: typeof BusinessDashboardBusinessOnboardingRoute
  BusinessDashboardCollectionsMerchantRoute: typeof BusinessDashboardCollectionsMerchantRoute
  BusinessDashboardCommandCenterRoute: typeof BusinessDashboardCommandCenterRoute
  BusinessDashboardFinancialReportingRoute: typeof BusinessDashboardFinancialReportingRoute
  BusinessDashboardInvoicingBillingRoute: typeof BusinessDashboardInvoicingBillingRoute
  BusinessDashboardMultiCurrencyTreasuryRoute: typeof BusinessDashboardMultiCurrencyTreasuryRoute
  BusinessDashboardOpenBankingRoute: typeof BusinessDashboardOpenBankingRoute
  BusinessDashboardPayrollHrRoute: typeof BusinessDashboardPayrollHrRoute
  BusinessDashboardSettingsAdministrationRoute: typeof BusinessDashboardSettingsAdministrationRoute
  BusinessDashboardSupportDisputesRoute: typeof BusinessDashboardSupportDisputesRoute
  BusinessDashboardTreasuryCashRoute: typeof BusinessDashboardTreasuryCashRoute
  BusinessDashboardVirtualAccountsRoute: typeof BusinessDashboardVirtualAccountsRoute
  BusinessDashboardIndexRoute: typeof BusinessDashboardIndexRoute
}

const BusinessDashboardRouteChildren: BusinessDashboardRouteChildren = {
  BusinessDashboardModuleRoute: BusinessDashboardModuleRoute,
  BusinessDashboardAccountsPayableRoute: BusinessDashboardAccountsPayableRoute,
  BusinessDashboardBulkDisbursementsRoute:
    BusinessDashboardBulkDisbursementsRoute,
  BusinessDashboardBusinessOnboardingRoute:
    BusinessDashboardBusinessOnboardingRoute,
  BusinessDashboardCollectionsMerchantRoute:
    BusinessDashboardCollectionsMerchantRoute,
  BusinessDashboardCommandCenterRoute: BusinessDashboardCommandCenterRoute,
  BusinessDashboardFinancialReportingRoute:
    BusinessDashboardFinancialReportingRoute,
  BusinessDashboardInvoicingBillingRoute:
    BusinessDashboardInvoicingBillingRoute,
  BusinessDashboardMultiCurrencyTreasuryRoute:
    BusinessDashboardMultiCurrencyTreasuryRoute,
  BusinessDashboardOpenBankingRoute: BusinessDashboardOpenBankingRoute,
  BusinessDashboardPayrollHrRoute: BusinessDashboardPayrollHrRoute,
  BusinessDashboardSettingsAdministrationRoute:
    BusinessDashboardSettingsAdministrationRoute,
  BusinessDashboardSupportDisputesRoute: BusinessDashboardSupportDisputesRoute,
  BusinessDashboardTreasuryCashRoute: BusinessDashboardTreasuryCashRoute,
  BusinessDashboardVirtualAccountsRoute: BusinessDashboardVirtualAccountsRoute,
  BusinessDashboardIndexRoute: BusinessDashboardIndexRoute,
}

const BusinessDashboardRouteWithChildren =
  BusinessDashboardRoute._addFileChildren(BusinessDashboardRouteChildren)

interface DevRouteChildren {
  DevModuleRoute: typeof DevModuleRoute
  DevIndexRoute: typeof DevIndexRoute
}

const DevRouteChildren: DevRouteChildren = {
  DevModuleRoute: DevModuleRoute,
  DevIndexRoute: DevIndexRoute,
}

const DevRouteWithChildren = DevRoute._addFileChildren(DevRouteChildren)

interface DevDashboardRouteChildren {
  DevDashboardApiGovernanceRoute: typeof DevDashboardApiGovernanceRoute
  DevDashboardApiReferenceRoute: typeof DevDashboardApiReferenceRoute
  DevDashboardComplianceAuditRoute: typeof DevDashboardComplianceAuditRoute
  DevDashboardDeveloperDashboardRoute: typeof DevDashboardDeveloperDashboardRoute
  DevDashboardIntegrationArchitectureRoute: typeof DevDashboardIntegrationArchitectureRoute
  DevDashboardMonitoringIncidentsRoute: typeof DevDashboardMonitoringIncidentsRoute
  DevDashboardPartnerMarketplaceRoute: typeof DevDashboardPartnerMarketplaceRoute
  DevDashboardPlaygroundRoute: typeof DevDashboardPlaygroundRoute
  DevDashboardSdksRoute: typeof DevDashboardSdksRoute
  DevDashboardSecurityRoute: typeof DevDashboardSecurityRoute
  DevDashboardSupportSlasRoute: typeof DevDashboardSupportSlasRoute
  DevDashboardWebhooksEventsRoute: typeof DevDashboardWebhooksEventsRoute
  DevDashboardIndexRoute: typeof DevDashboardIndexRoute
}

const DevDashboardRouteChildren: DevDashboardRouteChildren = {
  DevDashboardApiGovernanceRoute: DevDashboardApiGovernanceRoute,
  DevDashboardApiReferenceRoute: DevDashboardApiReferenceRoute,
  DevDashboardComplianceAuditRoute: DevDashboardComplianceAuditRoute,
  DevDashboardDeveloperDashboardRoute: DevDashboardDeveloperDashboardRoute,
  DevDashboardIntegrationArchitectureRoute:
    DevDashboardIntegrationArchitectureRoute,
  DevDashboardMonitoringIncidentsRoute: DevDashboardMonitoringIncidentsRoute,
  DevDashboardPartnerMarketplaceRoute: DevDashboardPartnerMarketplaceRoute,
  DevDashboardPlaygroundRoute: DevDashboardPlaygroundRoute,
  DevDashboardSdksRoute: DevDashboardSdksRoute,
  DevDashboardSecurityRoute: DevDashboardSecurityRoute,
  DevDashboardSupportSlasRoute: DevDashboardSupportSlasRoute,
  DevDashboardWebhooksEventsRoute: DevDashboardWebhooksEventsRoute,
  DevDashboardIndexRoute: DevDashboardIndexRoute,
}

const DevDashboardRouteWithChildren = DevDashboardRoute._addFileChildren(
  DevDashboardRouteChildren,
)

interface UtilityRouteChildren {
  UtilityModuleRoute: typeof UtilityModuleRoute
  UtilityAirtimeRoute: typeof UtilityAirtimeRoute
  UtilityElectricityRoute: typeof UtilityElectricityRoute
  UtilityInternetRoute: typeof UtilityInternetRoute
  UtilitySettingsRoute: typeof UtilitySettingsRoute
  UtilityWaterRoute: typeof UtilityWaterRoute
  UtilityIndexRoute: typeof UtilityIndexRoute
}

const UtilityRouteChildren: UtilityRouteChildren = {
  UtilityModuleRoute: UtilityModuleRoute,
  UtilityAirtimeRoute: UtilityAirtimeRoute,
  UtilityElectricityRoute: UtilityElectricityRoute,
  UtilityInternetRoute: UtilityInternetRoute,
  UtilitySettingsRoute: UtilitySettingsRoute,
  UtilityWaterRoute: UtilityWaterRoute,
  UtilityIndexRoute: UtilityIndexRoute,
}

const UtilityRouteWithChildren =
  UtilityRoute._addFileChildren(UtilityRouteChildren)

interface CardsAppRouteChildren {
  CardsAppAccountSettingsRoute: typeof CardsAppAccountSettingsRoute
  CardsAppCardAnalyticsReportingRoute: typeof CardsAppCardAnalyticsReportingRoute
  CardsAppCardCommandCenterRoute: typeof CardsAppCardCommandCenterRoute
  CardsAppCardProgramAdministrationRoute: typeof CardsAppCardProgramAdministrationRoute
  CardsAppCardSecurityFraudPreventionRoute: typeof CardsAppCardSecurityFraudPreventionRoute
  CardsAppCardSettingsSupportRoute: typeof CardsAppCardSettingsSupportRoute
  CardsAppCorporateBusinessCardsRoute: typeof CardsAppCorporateBusinessCardsRoute
  CardsAppPhysicalDebitCardsRoute: typeof CardsAppPhysicalDebitCardsRoute
  CardsAppPrepaidCardManagementRoute: typeof CardsAppPrepaidCardManagementRoute
  CardsAppSupportRoute: typeof CardsAppSupportRoute
  CardsAppVirtualCreditCardsRoute: typeof CardsAppVirtualCreditCardsRoute
  CardsAppVirtualDebitCardsRoute: typeof CardsAppVirtualDebitCardsRoute
}

const CardsAppRouteChildren: CardsAppRouteChildren = {
  CardsAppAccountSettingsRoute: CardsAppAccountSettingsRoute,
  CardsAppCardAnalyticsReportingRoute: CardsAppCardAnalyticsReportingRoute,
  CardsAppCardCommandCenterRoute: CardsAppCardCommandCenterRoute,
  CardsAppCardProgramAdministrationRoute:
    CardsAppCardProgramAdministrationRoute,
  CardsAppCardSecurityFraudPreventionRoute:
    CardsAppCardSecurityFraudPreventionRoute,
  CardsAppCardSettingsSupportRoute: CardsAppCardSettingsSupportRoute,
  CardsAppCorporateBusinessCardsRoute: CardsAppCorporateBusinessCardsRoute,
  CardsAppPhysicalDebitCardsRoute: CardsAppPhysicalDebitCardsRoute,
  CardsAppPrepaidCardManagementRoute: CardsAppPrepaidCardManagementRoute,
  CardsAppSupportRoute: CardsAppSupportRoute,
  CardsAppVirtualCreditCardsRoute: CardsAppVirtualCreditCardsRoute,
  CardsAppVirtualDebitCardsRoute: CardsAppVirtualDebitCardsRoute,
}

const CardsAppRouteWithChildren = CardsAppRoute._addFileChildren(
  CardsAppRouteChildren,
)

interface PmAppRouteChildren {
  PmAppSectionRoute: typeof PmAppSectionRoute
  PmAppAccountRoute: typeof PmAppAccountRoute
  PmAppAnalyticsRoute: typeof PmAppAnalyticsRoute
  PmAppComplianceRoute: typeof PmAppComplianceRoute
  PmAppCustomersRoute: typeof PmAppCustomersRoute
  PmAppDisputesRoute: typeof PmAppDisputesRoute
  PmAppFeesRoute: typeof PmAppFeesRoute
  PmAppFxRoute: typeof PmAppFxRoute
  PmAppInitiateTransferRoute: typeof PmAppInitiateTransferRoute
  PmAppKraGovernmentRoute: typeof PmAppKraGovernmentRoute
  PmAppLiquidityRoute: typeof PmAppLiquidityRoute
  PmAppMobileMoneyRoute: typeof PmAppMobileMoneyRoute
  PmAppOpsHealthRoute: typeof PmAppOpsHealthRoute
  PmAppPaymentRailsRoute: typeof PmAppPaymentRailsRoute
  PmAppReconciliationRoute: typeof PmAppReconciliationRoute
  PmAppSettingsRoute: typeof PmAppSettingsRoute
  PmAppSettlementRoute: typeof PmAppSettlementRoute
  PmAppTransferManagementRoute: typeof PmAppTransferManagementRoute
  PmAppTransferOverviewRoute: typeof PmAppTransferOverviewRoute
  PmAppTransfersRoute: typeof PmAppTransfersRoute
  PmAppIndexRoute: typeof PmAppIndexRoute
}

const PmAppRouteChildren: PmAppRouteChildren = {
  PmAppSectionRoute: PmAppSectionRoute,
  PmAppAccountRoute: PmAppAccountRoute,
  PmAppAnalyticsRoute: PmAppAnalyticsRoute,
  PmAppComplianceRoute: PmAppComplianceRoute,
  PmAppCustomersRoute: PmAppCustomersRoute,
  PmAppDisputesRoute: PmAppDisputesRoute,
  PmAppFeesRoute: PmAppFeesRoute,
  PmAppFxRoute: PmAppFxRoute,
  PmAppInitiateTransferRoute: PmAppInitiateTransferRoute,
  PmAppKraGovernmentRoute: PmAppKraGovernmentRoute,
  PmAppLiquidityRoute: PmAppLiquidityRoute,
  PmAppMobileMoneyRoute: PmAppMobileMoneyRoute,
  PmAppOpsHealthRoute: PmAppOpsHealthRoute,
  PmAppPaymentRailsRoute: PmAppPaymentRailsRoute,
  PmAppReconciliationRoute: PmAppReconciliationRoute,
  PmAppSettingsRoute: PmAppSettingsRoute,
  PmAppSettlementRoute: PmAppSettlementRoute,
  PmAppTransferManagementRoute: PmAppTransferManagementRoute,
  PmAppTransferOverviewRoute: PmAppTransferOverviewRoute,
  PmAppTransfersRoute: PmAppTransfersRoute,
  PmAppIndexRoute: PmAppIndexRoute,
}

const PmAppRouteWithChildren = PmAppRoute._addFileChildren(PmAppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  HomeRoute: HomeRouteWithChildren,
  BusinessRoute: BusinessRouteWithChildren,
  BusinessDashboardRoute: BusinessDashboardRouteWithChildren,
  DevRoute: DevRouteWithChildren,
  DevDashboardRoute: DevDashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  UtilityRoute: UtilityRouteWithChildren,
  WalletActivationRoute: WalletActivationRoute,
  AuthAccountStatusRoute: AuthAccountStatusRoute,
  AuthHubRoute: AuthHubRoute,
  AuthIdentityRoute: AuthIdentityRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthMfaRoute: AuthMfaRoute,
  AuthPasskeysRoute: AuthPasskeysRoute,
  AuthRecoveryRoute: AuthRecoveryRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthSecurityRoute: AuthSecurityRoute,
  CardsAppRoute: CardsAppRouteWithChildren,
  PmAppRoute: PmAppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
