import { useEffect, useState } from "react";
import {
  FileText, Download, Printer, Send, Scale, TrendingUp, Layers, BookOpen, Calendar, CheckCircle2,
} from "lucide-react";
import type { ReportRow } from "../../dataBooks";
import { bsReport, cfReport, plReport, trialBalance } from "../../dataBooks";
import { cls, downloadCSV, fmt, fmtDate, todayISO, type QAction } from "../../lib";
import { Badge, Field, Kpi, Modal, PillTabs, Section, Toggle } from "../Getpaid/ui";

type Notify = (t: { tone: "success" | "warning" | "danger" | "info"; title: string; body?: string }) => void;

const REPORTS = [
  { id: "pl", name: "Profit & Loss", desc: "Income statement for the period", icon: <TrendingUp size={16} /> },
  { id: "bs", name: "Balance Sheet", desc: "Assets, liabilities & equity", icon: <Scale size={16} /> },
  { id: "cf", name: "Cash Flow", desc: "Operating, investing & financing", icon: <Layers size={16} /> },
  { id: "tb", name: "Trial Balance", desc: "Every account, debits vs credits", icon: <BookOpen size={16} /> },
];

export default function Reports({ notify, qa, onConsume }: {
  notify: Notify;
  emit?: (q: QAction) => void;
  qa: QAction;
  onConsume: () => void;
}) {
  const [tab, setTab] = useState("pl");
  const [period, setPeriod] = useState("March 2026");
  const [compare, setCompare] = useState(false);
  const [exportOpen, setExportOpen] = useState(false);
  const [sendOpen, setSendOpen] = useState(false);
  const [packOpen, setPackOpen] = useState(false);

  useEffect(() => {
    if (!qa) return;
    if (qa.a === "report") {
      if (typeof qa.p === "string") setTab(qa.p);
      document.getElementById("sec-reports")?.scrollIntoView({ behavior: "smooth" });
    }
    if (qa.a === "reportPack") setPackOpen(true);
    onConsume();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [qa]);

  const rows: ReportRow[] = tab === "pl" ? plReport : tab === "bs" ? bsReport : tab === "cf" ? cfReport : [];
  const tbDr = trialBalance.reduce((s, r) => s + r.debit, 0);
  const tbCr = trialBalance.reduce((s, r) => s + r.credit, 0);

  const doExport = () => {
    if (tab === "tb") {
      downloadCSV(`trial-balance-${todayISO()}.csv`, [["Code", "Account", "Debit", "Credit"], ...trialBalance.map((r) => [r.code, r.name, r.debit, r.credit]), ["", "TOTALS", tbDr, tbCr]]);
    } else {
      downloadCSV(`${tab}-${todayISO()}.csv`, [["Line", "Amount (KES)"], ...rows.map((r) => [r.label, r.amount || ""])]);
    }
    notify({ tone: "success", title: "Report downloaded", body: `${REPORTS.find((r) => r.id === tab)?.name} · ${period} exported as CSV.` });
    setExportOpen(false);
  };

  const printReport = () => {
    const w = window.open("", "_blank", "width=880,height=1000");
    if (!w) { notify({ tone: "warning", title: "Pop-up blocked", body: "Allow pop-ups to print the report." }); return; }
    const body = tab === "tb"
      ? `<table><tr><th>Code</th><th>Account</th><th class="r">Debit</th><th class="r">Credit</th></tr>${trialBalance.map((r) => `<tr><td>${r.code}</td><td>${r.name}</td><td class="r">${r.debit ? r.debit.toLocaleString() : "—"}</td><td class="r">${r.credit ? r.credit.toLocaleString() : "—"}</td></tr>`).join("")}<tr class="tot"><td colspan="2">TOTALS</td><td class="r">${tbDr.toLocaleString()}</td><td class="r">${tbCr.toLocaleString()}</td></tr></table>`
      : `<table>${rows.map((r) => `<tr class="${r.bold ? "tot" : ""}"><td style="padding-left:${r.indent ? 24 : 0}px">${r.label}</td><td class="r">${r.amount ? (r.amount < 0 ? "(" + Math.abs(r.amount).toLocaleString() + ")" : r.amount.toLocaleString()) : ""}</td></tr>`).join("")}</table>`;
    w.document.write(`<html><head><title>${REPORTS.find((r) => r.id === tab)?.name}</title><style>body{font-family:Arial;padding:40px;color:#111}h1{font-size:20px;margin-bottom:2px}h2{font-size:13px;color:#666;font-weight:normal;margin-top:0}table{width:100%;border-collapse:collapse;margin-top:20px}td,th{padding:7px 8px;font-size:13px;border-bottom:1px solid #eee;text-align:left}.r{text-align:right}.tot{font-weight:bold;border-top:2px solid #333}.foot{margin-top:30px;font-size:11px;color:#888;border-top:1px solid #ddd;padding-top:12px}</style></head><body>
      <h1>TechSol Ltd — ${REPORTS.find((r) => r.id === tab)?.name}</h1>
      <h2>${period} · KRA PIN P0512345678V · prepared ${fmtDate(todayISO())}</h2>
      ${body}
      <div class="foot">Generated by PayMo Business from the general ledger. Unaudited management accounts.</div>
      <script>window.onload=()=>window.print()</script></body></html>`);
    w.document.close();
  };

  return (
    <>
      <Section
        no="4.4" sub="Your Business · Statements" id="sec-reports"
        title="Financial Reports"
        right={
          <>
            <button className="btn pm-btn-soft" onClick={() => setPackOpen(true)}><Layers size={15} /> Build Report Pack</button>
            <button className="btn pm-btn-soft" onClick={() => setSendOpen(true)}><Send size={15} /> Send to Accountant</button>
            <button className="btn pm-btn-violet" onClick={() => setExportOpen(true)}><Download size={15} /> Export</button>
          </>
        }
      >
        <div className="row g-3 mb-3">
          <div className="col-6 col-lg-3"><Kpi icon={<TrendingUp size={16} />} label="Revenue (YTD)" value={fmt(2947000)} delta="▲ 12.4%" sub="vs same period last year" /></div>
          <div className="col-6 col-lg-3"><Kpi icon={<Scale size={16} />} label="Gross margin" value="83.5%" delta="▲ 1.8 pts" sub="services-heavy mix" /></div>
          <div className="col-6 col-lg-3"><Kpi icon={<Layers size={16} />} label="Total assets" value={fmt(4872300)} delta="balanced ✓" sub="= liabilities + equity" /></div>
          <div className="col-6 col-lg-3"><Kpi icon={<BookOpen size={16} />} label="Trial balance" value={tbDr === tbCr ? "In balance" : "Out"} delta={fmt(tbDr)} sub="debits = credits" /></div>
        </div>

        <div className="pm-card">
          <div className="d-flex flex-wrap gap-2 align-items-center justify-content-between mb-3">
            <PillTabs tabs={REPORTS.map((r) => ({ id: r.id, label: r.name }))} active={tab} onChange={setTab} />
            <div className="d-flex gap-2 align-items-center flex-wrap">
              <select className="form-select form-select-sm pm-input pm-w-150" value={period} onChange={(e) => setPeriod(e.target.value)}>
                <option>March 2026</option><option>Q1 2026</option><option>Financial year 2026</option><option>February 2026</option>
              </select>
              <Toggle on={compare} onChange={setCompare} label="Compare period" />
              <button className="btn pm-btn-ghost btn-sm" onClick={printReport}><Printer size={14} /> Print</button>
            </div>
          </div>

          <div className="pm-report-paper">
            <div className="pm-report-head">
              <div>
                <div className="fw-bold pm-fs-15">TechSol Ltd — {REPORTS.find((r) => r.id === tab)?.name}</div>
                <div className="pm-muted pm-fs-12">{period} · unaudited management accounts · prepared {fmtDate(todayISO())}</div>
              </div>
              <Badge tone="success" dot>Live from ledger</Badge>
            </div>

            {tab !== "tb" ? (
              <table className="table pm-report-table mb-0">
                <thead>
                  <tr><th>Line item</th><th className="text-end">{period}</th>{compare && <th className="text-end">Prior period</th>}{compare && <th className="text-end">Change</th>}</tr>
                </thead>
                <tbody>
                  {rows.map((r, i) => (
                    <tr key={i} className={cls(r.bold && "pm-report-bold", r.divider && "pm-report-divider")}>
                      <td style={{ paddingLeft: r.indent ? 28 : 12 }}>{r.label}</td>
                      <td className={cls("text-end", r.amount < 0 && "t-danger")}>{r.amount ? (r.amount < 0 ? `(${fmt(Math.abs(r.amount))})` : fmt(r.amount)) : ""}</td>
                      {compare && <td className="text-end pm-muted">{r.amount ? fmt(Math.round(Math.abs(r.amount) * 0.93)) : ""}</td>}
                      {compare && <td className="text-end">{r.amount ? <span className={r.amount > 0 ? "t-success" : "t-danger"}>{r.amount > 0 ? "▲" : "▼"} 7%</span> : ""}</td>}
                    </tr>
                  ))}
                </tbody>
              </table>
            ) : (
              <table className="table pm-report-table mb-0">
                <thead><tr><th>Code</th><th>Account</th><th className="text-end">Debit</th><th className="text-end">Credit</th></tr></thead>
                <tbody>
                  {trialBalance.map((r) => (
                    <tr key={r.code}>
                      <td className="pm-mono">{r.code}</td>
                      <td>{r.name}</td>
                      <td className="text-end">{r.debit ? fmt(r.debit) : "—"}</td>
                      <td className="text-end">{r.credit ? fmt(r.credit) : "—"}</td>
                    </tr>
                  ))}
                </tbody>
                <tfoot>
                  <tr className="pm-report-bold pm-report-divider">
                    <td colSpan={2}>TOTALS</td>
                    <td className="text-end">{fmt(tbDr)}</td>
                    <td className="text-end">{fmt(tbCr)}</td>
                  </tr>
                </tfoot>
              </table>
            )}
            <div className="pm-report-foot">
              Generated by PayMo Business from the general ledger · figures in KES · {tab === "tb" && tbDr === tbCr ? "debits equal credits ✓" : "unaudited"}
            </div>
          </div>
        </div>
      </Section>

      {/* ── export ── */}
      <Modal open={exportOpen} onClose={() => setExportOpen(false)} kicker="Export" title="Export report"
        footer={<><button className="btn pm-btn-ghost" onClick={() => setExportOpen(false)}>Cancel</button>
          <button className="btn pm-btn-soft" onClick={printReport}><Printer size={15} /> Print / PDF</button>
          <button className="btn pm-btn-violet" onClick={doExport}><Download size={15} /> Download CSV</button></>}
      >
        <Field label="Report"><input className="form-control pm-input" value={REPORTS.find((r) => r.id === tab)?.name} disabled /></Field>
        <Field label="Period"><input className="form-control pm-input" value={period} disabled /></Field>
        <div className="pm-note">CSV opens in Excel/Sheets. Print produces a clean PDF your bank or accountant will accept.</div>
      </Modal>

      {/* ── send to accountant ── */}
      <Modal open={sendOpen} onClose={() => setSendOpen(false)} kicker="Collaboration" title="Send reports to your accountant"
        footer={<><button className="btn pm-btn-ghost" onClick={() => setSendOpen(false)}>Cancel</button>
          <button className="btn pm-btn-violet" onClick={() => { notify({ tone: "success", title: "Reports sent", body: "P&L, Balance Sheet and Trial Balance emailed to grace@mwendecpa.co.ke." }); setSendOpen(false); }}><Send size={15} /> Send now</button></>}
      >
        <Field label="Recipient"><select className="form-select pm-input"><option>Grace Mwende, CPA(K) — grace@mwendecpa.co.ke</option><option>PKF Kenya (audit) — audit@pkf.co.ke</option><option>Daniel Kiprop — daniel@techsol.co.ke</option></select></Field>
        <Field label="Include">
          <div className="pm-check-grid">
            {REPORTS.map((r) => <button key={r.id} className="pm-check-chip pm-check-on">✓ {r.name}</button>)}
          </div>
        </Field>
        <Field label="Message"><textarea className="form-control pm-input" rows={2} defaultValue={`Hi Grace, here are the ${period} management accounts for review. Let me know if you need anything else.`} /></Field>
      </Modal>

      {/* ── report pack builder ── */}
      <Modal open={packOpen} onClose={() => setPackOpen(false)} kicker="Report Pack" title="Build a lender-ready pack" subtitle="Bundle the statements banks ask for into one PDF." size="lg"
        footer={<><button className="btn pm-btn-ghost" onClick={() => setPackOpen(false)}>Cancel</button>
          <button className="btn pm-btn-violet" onClick={() => { downloadCSV(`report-pack-${todayISO()}.csv`, [["Report", "Period", "Included"], ...REPORTS.map((r) => [r.name, period, "yes"]), ["Aged receivables", period, "yes"], ["Bank statements", period, "yes"]]); notify({ tone: "success", title: "Report pack generated", body: "6 statements bundled — index CSV downloaded, PDF emailed to you." }); setPackOpen(false); }}><Download size={15} /> Generate pack</button></>}
      >
        <div className="pm-preset-grid">
          {[...REPORTS, { id: "ar", name: "Aged receivables", desc: "Who owes you, by bucket", icon: <Calendar size={16} /> }, { id: "bank", name: "Bank statements", desc: "Certified 6-month history", icon: <FileText size={16} /> }].map((r) => (
            <div className="pm-preset-card pm-preset-on" key={r.id}>
              <span className="pm-acc-ic pm-acc-ic-virtual">{r.icon}</span>
              <b>{r.name} <CheckCircle2 size={13} className="t-primary" /></b>
              <span>{r.desc}</span>
            </div>
          ))}
        </div>
        <div className="pm-cyan-note mt-3">This is exactly the bundle KCB, Equity and most SACCOs request for a working-capital facility.</div>
      </Modal>
    </>
  );
}
