/* ============================================================================
 * CollectionsMerchantTables.tsx — table rows the legacy page injected with JavaScript.
 * ----------------------------------------------------------------------------
 * AUTO-GENERATED by hydrate_js_tables.py — regenerate rather than hand-edit.
 *
 * In 3.2.html these tables ship as an empty `<tbody id="…"></tbody>` and are
 * filled at runtime by vanilla JS (`tbody.innerHTML = data.map(…)`). A literal
 * markup conversion therefore reproduced an EMPTY table. Here the backing data
 * is lifted into `initialMockData` and the row template becomes JSX rendered
 * with `.map()`, so the rows are real React output and the table is
 * backend-ready: swap `initialMockData` for a query result and nothing else
 * changes.
 * ========================================================================== */
import styles from "../styles/collections-merchant.module.css";

const s = styles as Record<string, string>;
const cx = (...c: (string | false | undefined)[]) =>
	c.filter(Boolean).join(" ");

interface Props {
	onOpen: (id: string) => void;
	onAction?: () => void;
}

/** Rows extracted from the page's inline <script>. */
export const initialMockData = {
	customers: [
		{
			name: "Alice Wanjiku",
			phone: "0722 *** 112",
			seg: "VIP",
			ltv: "KES 142,500",
			last: "Today",
		},
		{
			name: "John Mark",
			phone: "0711 *** 443",
			seg: "Regular",
			ltv: "KES 12,400",
			last: "Today",
		},
		{
			name: "Sarah K.",
			phone: "0733 *** 991",
			seg: "VIP",
			ltv: "KES 85,000",
			last: "Yesterday",
		},
		{
			name: "David O.",
			phone: "0721 *** 220",
			seg: "Churn Risk",
			ltv: "KES 8,000",
			last: "45 days ago",
		},
		{
			name: "Mary J.",
			phone: "0755 *** 881",
			seg: "New",
			ltv: "KES 550",
			last: "Today",
		},
	],
	txns: [
		{
			time: "14:32",
			cust: "Alice W.",
			ref: "TXN-892110",
			method: "PayBill",
			amount: "KES 4,500",
			status: "Success",
		},
		{
			time: "14:15",
			cust: "John M.",
			ref: "TXN-892109",
			method: "Till",
			amount: "KES 1,200",
			status: "Success",
		},
		{
			time: "13:40",
			cust: "Sarah K.",
			ref: "TXN-892108",
			method: "Visa",
			amount: "KES 8,500",
			status: "Success",
		},
		{
			time: "13:12",
			cust: "David O.",
			ref: "TXN-892107",
			method: "PayBill",
			amount: "KES 2,000",
			status: "Failed",
		},
		{
			time: "12:55",
			cust: "Mary J.",
			ref: "TXN-892106",
			method: "Till",
			amount: "KES 550",
			status: "Success",
		},
	],
} as const;

/** Rows for `#customerTableBody`. */
export function CustomerTableBody({ onOpen, onAction }: Props) {
	const act = onAction ?? (() => undefined);
	void act;
	return (
		<>
			{initialMockData.customers.map((c, i) => (
				<RowCustomerTableBody key={i} c={c} onOpen={onOpen} onAction={act} />
			))}
		</>
	);
}

function RowCustomerTableBody({
	c,
	onOpen,
	onAction,
}: Props & { c: (typeof initialMockData.customers)[number] }) {
	const act = onAction ?? (() => undefined);
	void act;
	return (
		<>
			<tr>
				<td data-label="Customer Name">
					<strong>{c.name}</strong>
				</td>
				<td data-label="Contact">{c.phone}</td>
				<td data-label="Segment">
					<span
						className={cx(
							s.badge,
							c.seg === "VIP"
								? s.badgeP
								: c.seg === "Churn Risk"
									? s.badgeD
									: c.seg === "New"
										? s.badgeI
										: s.badgeS,
						)}
					>
						{c.seg}
					</span>
				</td>
				<td data-label="LTV (Total Spend)">{c.ltv}</td>
				<td data-label="Last Payment">{c.last}</td>
				<td data-label="Action">
					<button
						type="button"
						className={cx(s.btnPm, s.btnSm)}
						onClick={() => onOpen("sendReminderModal")}
					>
						Msg
					</button>
				</td>
			</tr>
		</>
	);
}

/** Rows for `#transactionFeedBody`. */
export function TransactionFeedBody({ onOpen, onAction }: Props) {
	const act = onAction ?? (() => undefined);
	void act;
	return (
		<>
			{initialMockData.txns.map((t, i) => (
				<RowTransactionFeedBody key={i} t={t} onOpen={onOpen} onAction={act} />
			))}
		</>
	);
}

function RowTransactionFeedBody({
	t,
	onOpen,
	onAction,
}: Props & { t: (typeof initialMockData.txns)[number] }) {
	const act = onAction ?? (() => undefined);
	void act;
	return (
		<>
			<tr>
				<td data-label="Time">{t.time}</td>
				<td data-label="Customer">{t.cust}</td>
				<td data-label="Ref / ID">
					<code>{t.ref}</code>
				</td>
				<td data-label="Method">{t.method}</td>
				<td data-label="Amount">
					<strong>{t.amount}</strong>
				</td>
				<td data-label="Status">
					<span
						className={cx(
							s.badge,
							t.status === "Success" ? s.badgeS : s.badgeD,
						)}
					>
						{t.status}
					</span>
				</td>
				<td data-label="Action">
					<button
						type="button"
						className={cx(s.btnPm, s.btnSm)}
						onClick={() => onOpen("txnDetailModal")}
					>
						View
					</button>
				</td>
			</tr>
		</>
	);
}
