/* ============================================================================
 * VirtualAccountsExtraModals.tsx — modals ported from the original page 3.9.html.
 * ----------------------------------------------------------------------------
 * AUTO-GENERATED by port_missing_modals.py — regenerate rather than hand-edit.
 *
 * These dialogs exist in the legacy HTML and were reachable there via
 * onclick="openModal('…')", but were never carried into the React port, so the
 * buttons that target them did nothing. Markup, titles, sizes, tables and
 * footer actions are ported from the source.
 *
 * Legacy bridges applied:
 *   openModal('x')        -> onOpen('x')
 *   data-bs-dismiss       -> onClose
 *   processAction(...)    -> doAction(...)  (spinner -> receipt)
 * ========================================================================== */
import type { ReactNode } from "react";
import { useEffect, useRef, useState } from "react";
import styles from "../styles/virtual-accounts.module.css";

const s = styles as Record<string, string>;
const cx = (...c: (string | false | undefined)[]) =>
	c.filter(Boolean).join(" ");

interface Props {
	active: string | null;
	onClose: () => void;
	onOpen: (id: string) => void;
}

interface Result {
	msg: string;
	ref?: string;
}

/* Modal shell — mirrors the shared kit used by the hand-written modals so
 * these dialogs look and behave identically. */
function MBox({
	id,
	active,
	title,
	size = "md",
	onClose,
	children,
	footer,
}: {
	id: string;
	active: string | null;
	title: ReactNode;
	size?: "md" | "lg" | "xl";
	onClose: () => void;
	children: ReactNode;
	footer?: ReactNode;
}) {
	if (active !== id) return null;
	return (
		<>
			<div className={s.backdrop} onClick={onClose} />
			<div className={s.modalWrap} role="dialog" aria-modal="true">
				<div
					className={cx(
						s.modalBox,
						size === "lg" && s.modalBoxLg,
						size === "xl" && s.modalBoxXl,
					)}
				>
					<div className={s.modalHeader}>
						<h5 className={s.modalTitle}>{title}</h5>
						<button
							type="button"
							className="btn-close"
							aria-label="Close"
							onClick={onClose}
						/>
					</div>
					<div className={s.modalBody}>{children}</div>
					{footer && <div className={s.modalFooter}>{footer}</div>}
				</div>
			</div>
		</>
	);
}

function Busy() {
	return (
		<div className={s.loadingOv}>
			<div className={s.spinner} />
			<p className={s.loadingLabel}>Processing...</p>
		</div>
	);
}

export default function VirtualAccountsExtraModals({
	active,
	onClose,
	onOpen,
}: Props) {
	const [results, setResults] = useState<Record<string, Result>>({});
	const [busy, setBusy] = useState<string | null>(null);
	const [flows, setFlows] = useState<Record<string, number>>({});
	const timer = useRef<number | undefined>(undefined);

	/* LEGACY BRIDGE: cacheResettable() — clear state when the modal closes. */
	useEffect(() => {
		if (active === null) {
			setResults({});
			setBusy(null);
			setFlows({});
		}
	}, [active]);
	useEffect(() => () => window.clearTimeout(timer.current), []);

	/* LEGACY BRIDGE: processAction() — 1.2s spinner, then a receipt. */
	const doAction = (id: string, msg: string, ref?: string) => {
		setBusy(id);
		timer.current = window.setTimeout(() => {
			setResults((p) => ({ ...p, [id]: { msg, ref } }));
			setBusy(null);
		}, 1200);
	};

	const nextFlow = (key: string, total: number) => {
		const cur = flows[key] ?? 1;
		if (cur >= total) {
			onClose();
			return;
		}
		setFlows((p) => ({ ...p, [key]: cur + 1 }));
	};
	void nextFlow;

	const bodyFor = (id: string, content: ReactNode) => {
		if (busy === id) return <Busy />;
		const r = results[id];
		if (r)
			return (
				<div className={s.receipt}>
					<div className={s.receiptIcon}>
						<i className="bi bi-check-lg" />
					</div>
					<h5 style={{ fontWeight: 700, color: "var(--pm-accent)" }}>
						{r.msg}
					</h5>
					{r.ref && (
						<p style={{ fontSize: 12, color: "var(--pm-muted)" }}>
							Ref: {r.ref}
						</p>
					)}
				</div>
			);
		return content;
	};

	return (
		<>
			<MBox
				id="activityModal"
				active={active}
				size="xl"
				onClose={onClose}
				title={
					<>
						<i className="bi bi-clock-history me-2" /> Full Activity Log
					</>
				}
				footer={
					<>
						<button type="button" className="btn-pm" onClick={onClose}>
							Close
						</button>
						<button type="button" className="btn-pm btn-pm-p" onClick={onClose}>
							Export Log
						</button>
					</>
				}
			>
				{bodyFor(
					"activityModal",
					<>
						<div className="d-flex gap-2 mb-3 flex-wrap">
							<select className="FC" style={{ width: "auto" }}>
								<option>All Accounts</option>
								<option>VA-003</option>
								<option>VA-007</option>
							</select>
							<select className="FC" style={{ width: "auto" }}>
								<option>Last 7 days</option>
								<option>Last 30 days</option>
								<option>Last 90 days</option>
							</select>
							<input
								className="FC"
								style={{ width: 200 }}
								placeholder="Search reference..."
							/>
						</div>
						<div
							className="table-responsive"
							style={{ maxHeight: 400, overflowY: "auto" }}
						>
							<table className="T">
								<thead>
									<tr>
										<th>Date</th>
										<th>Account</th>
										<th>Type</th>
										<th>Description</th>
										<th>Amount</th>
										<th>Status</th>
										<th>Ref</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>27 Jun 09:14</td>
										<td>VA-003</td>
										<td>Credit</td>
										<td>Client payment INV-4421</td>
										<td>KES 2,450,000</td>
										<td>
											<span className="B B-s">Success</span>
										</td>
										<td>VA-003-4421</td>
									</tr>
									<tr>
										<td>27 Jun 08:45</td>
										<td>VA-007</td>
										<td>Debit</td>
										<td>Salary batch June</td>
										<td>KES 8,920,000</td>
										<td>
											<span className="B B-s">Success</span>
										</td>
										<td>SUB-007-8812</td>
									</tr>
									<tr>
										<td>26 Jun 16:22</td>
										<td>VA-001</td>
										<td>Debit</td>
										<td>Supplier payment</td>
										<td>KES 1,875,500</td>
										<td>
											<span className="B B-i">Pending</span>
										</td>
										<td>VA-001-3390</td>
									</tr>
									<tr>
										<td>26 Jun 14:10</td>
										<td>VA-003</td>
										<td>Debit</td>
										<td>Auto-sweep to Treasury</td>
										<td>KES 5,200,000</td>
										<td>
											<span className="B B-s">Success</span>
										</td>
										<td>VA-003-3389</td>
									</tr>
									<tr>
										<td>25 Jun 11:05</td>
										<td>SUB-012</td>
										<td>Credit</td>
										<td>Campaign budget top-up</td>
										<td>KES 450,000</td>
										<td>
											<span className="B B-s">Success</span>
										</td>
										<td>SUB-012-2291</td>
									</tr>
								</tbody>
							</table>
						</div>
					</>,
				)}
			</MBox>
			<MBox
				id="hierarchyModal"
				active={active}
				size="lg"
				onClose={onClose}
				title={
					<>
						<i className="bi bi-diagram-3 me-2" /> Virtual Account Hierarchy
					</>
				}
				footer={
					<>
						<button type="button" className="btn-pm" onClick={onClose}>
							Close
						</button>
						<button type="button" className="btn-pm btn-pm-p" onClick={onClose}>
							Add Sub-Account
						</button>
					</>
				}
			>
				{bodyFor(
					"hierarchyModal",
					<>
						<div
							className="p-3 rounded mb-3"
							style={{ background: "var(--pm-surface-2)" }}
						>
							<div style={{ fontWeight: 700 }}>VA-003 — Client Collections</div>
							<div style={{ fontSize: 12, color: "var(--pm-muted)" }}>
								Balance: KES 12.4M | 8 sub-accounts
							</div>
						</div>
						<div className="ps-4">
							<div className="p-2 border-start border-2 mb-2">
								<strong>SUB-0142 — Project Alpha</strong>
								<span className="B B-s">KES 2.1M</span>
							</div>
							<div className="p-2 border-start border-2 mb-2">
								<strong>SUB-0143 — Project Beta</strong>
								<span className="B B-s">KES 1.8M</span>
							</div>
							<div className="p-2 border-start border-2 mb-2">
								<strong>SUB-0144 — Project Gamma</strong>
								<span className="B B-w">KES 450K (over limit)</span>
							</div>
						</div>
					</>,
				)}
			</MBox>
			<MBox
				id="txnDetailModal"
				active={active}
				onClose={onClose}
				title={
					<>
						<i className="bi bi-receipt me-2" /> Transaction Details
					</>
				}
				footer={
					<>
						<button type="button" className="btn-pm" onClick={onClose}>
							Close
						</button>
						<button type="button" className="btn-pm btn-pm-p" onClick={onClose}>
							Match / Unmatch
						</button>
					</>
				}
			>
				{bodyFor(
					"txnDetailModal",
					<>
						<div
							className="p-3 rounded mb-3"
							style={{ background: "var(--pm-surface-2)" }}
						>
							<div className="d-flex justify-content-between mb-2">
								<span className="text-muted">Reference</span>
								<strong>VA-003-4421</strong>
							</div>
							<div className="d-flex justify-content-between mb-2">
								<span className="text-muted">Date&Time</span>
								<strong>27 Jun 2025, 09:14</strong>
							</div>
							<div className="d-flex justify-content-between mb-2">
								<span className="text-muted">From</span>
								<strong>MPESA Till 882910</strong>
							</div>
							<div className="d-flex justify-content-between mb-2">
								<span className="text-muted">To</span>
								<strong>VA-003 — Client Collections</strong>
							</div>
							<div className="d-flex justify-content-between">
								<span className="text-muted">Amount</span>
								<strong>KES 2,450,000</strong>
							</div>
						</div>
						<div className="mb-3">
							<label className="FL">Status</label>
							<div>
								<span className="B B-s">Completed • Bank confirmed</span>
							</div>
						</div>
						<div className="mb-3">
							<label className="FL">Notes</label>
							<div style={{ fontSize: 13 }}>
								Client payment for Invoice INV-4421. Matched automatically via
								reference.
							</div>
						</div>
					</>,
				)}
			</MBox>
			<MBox
				id="vaHealthModal"
				active={active}
				size="lg"
				onClose={onClose}
				title={
					<>
						<i className="bi bi-heart-pulse text-danger me-2" /> Virtual Account
						Health Check
					</>
				}
				footer={
					<>
						<button type="button" className="btn-pm" onClick={onClose}>
							Close
						</button>
						<button type="button" className="btn-pm btn-pm-p" onClick={onClose}>
							Fix Issues
						</button>
					</>
				}
			>
				{bodyFor(
					"vaHealthModal",
					<>
						<div className="row g-3 mb-3">
							<div className="col-md-3 col-6">
								<div
									className="p-3 rounded text-center"
									style={{ background: "var(--pm-accent-soft)" }}
								>
									<div
										style={{
											fontSize: 28,
											fontWeight: 800,
											color: "var(--pm-accent)",
											fontFamily: "var(--pm-font-display)",
										}}
									>
										94
									</div>
									<div
										style={{ fontSize: 10, fontWeight: 700, color: "#047857" }}
									>
										HEALTH SCORE
									</div>
								</div>
							</div>
							<div className="col-md-3 col-6">
								<div
									className="p-3 rounded text-center"
									style={{ background: "var(--pm-info-soft)" }}
								>
									<div
										style={{
											fontSize: 24,
											fontWeight: 700,
											color: "var(--pm-info)",
										}}
									>
										18/18
									</div>
									<div
										style={{ fontSize: 10, fontWeight: 700, color: "#1D4ED8" }}
									>
										ACTIVE
									</div>
								</div>
							</div>
							<div className="col-md-3 col-6">
								<div
									className="p-3 rounded text-center"
									style={{ background: "var(--pm-warning-soft)" }}
								>
									<div
										style={{
											fontSize: 24,
											fontWeight: 700,
											color: "var(--pm-warning)",
										}}
									>
										4
									</div>
									<div
										style={{ fontSize: 10, fontWeight: 700, color: "#B45309" }}
									>
										ISSUES
									</div>
								</div>
							</div>
							<div className="col-md-3 col-6">
								<div
									className="p-3 rounded text-center"
									style={{ background: "var(--pm-purple-soft)" }}
								>
									<div
										style={{
											fontSize: 24,
											fontWeight: 700,
											color: "var(--pm-purple)",
										}}
									>
										6
									</div>
									<div
										style={{ fontSize: 10, fontWeight: 700, color: "#6D28D9" }}
									>
										RULES
									</div>
								</div>
							</div>
						</div>
						<div className="table-responsive">
							<table className="T">
								<thead>
									<tr>
										<th>Account</th>
										<th>Score</th>
										<th>Issues</th>
										<th>Status</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>VA-003</td>
										<td>
											<strong>98</strong>
										</td>
										<td>None</td>
										<td>
											<span className="B B-s">Healthy</span>
										</td>
									</tr>
									<tr>
										<td>VA-007</td>
										<td>
											<strong>91</strong>
										</td>
										<td>1 limit breach</td>
										<td>
											<span className="B B-w">Warning</span>
										</td>
									</tr>
									<tr>
										<td>SUB-0144</td>
										<td>
											<strong>72</strong>
										</td>
										<td>Over limit, no rule</td>
										<td>
											<span className="B B-d">Critical</span>
										</td>
									</tr>
								</tbody>
							</table>
						</div>
					</>,
				)}
			</MBox>
		</>
	);
}
